### ISSUE TITLE
Settings menu loading too long

### ISSUE THREAD

**Issue by macsunmood** [pbek/QOwnNotes#2574] opened 2022-08-10 10:32 UTC
On my SSD it takes a couple of seconds for the settings to load/save. I guess it's normal behaviour, but what's the reason behind and can something be done about it?

**Comment by pbek** [comment] 2022-08-10 10:45
I dunno. It takes a couple of 100ms for me. Do you have any slow network requests to a possible Nextcloud/ownCloud server?

**Comment by macsunmood** [comment] 2022-08-10 10:55
> I dunno. It takes a couple of 100ms for me. Do you have any slow network requests to a possible Nextcloud/ownCloud server?

no nextcloud server configured/connected.

**Comment by pbek** [comment] 2022-08-10 11:02
Then I don't know what takes long for you for the dialog to open.... 😬 You'd need to step through `SettingsDialog::SettingsDialog` to see what's happening on your box.

**Comment by macsunmood** [comment] 2022-08-10 13:10
> Then I don't know what takes long for you for the dialog to open.... 😬 You'd need to step through `SettingsDialog::SettingsDialog` to see what's happening on your box.

can it be logged? should something be turned on see settings loading/saving details?

**Comment by pbek** [comment] 2022-08-10 13:23
It would be a bit overkill to write a debug message after every line... `SettingsDialog::SettingsDialog` is huge.

**Comment by macsunmood** [comment] 2022-08-13 23:20
> It would be a bit overkill to write a debug message after every line... `SettingsDialog::SettingsDialog` is huge.

Has this issue been never mentioned before by noone?

**Comment by pbek** [comment] 2022-08-14 03:52
Not that I remember...

**Comment by Carterpersall** [comment] 2022-08-17 22:10
Takes about 1 second for me which isn't unbearable but is definitely noticeable and might get annoying if I open it enough

**Comment by macsunmood** [comment] 2022-08-18 11:31
> Takes about 1 second for me which isn't unbearable but is definitely noticeable and might get annoying if I open it enough

Indeed, the issue exists, could possibly be not what a fast c++ app is expected to behave

**Comment by macsunmood** [comment] 2022-08-18 12:17
> Takes about 1 second for me which isn't unbearable but is definitely noticeable and might get annoying if I open it enough

@Carterpersall , please, can you check if you normally can trigger custom actions from the CLI?
![image](https://user-images.githubusercontent.com/45285672/185392570-9141ffa5-1058-4f41-98ed-887b7a04f6a7.png)

the issue, which may be somehow related to long settings loading, is described here: 
https://github.com/pbek/QOwnNotes/issues/2576

**Comment by Carterpersall** [comment] 2022-08-22 19:25
@macsunmood when I run `QOwnNotes.exe --portable --action action_Settings` in Powershell using Windows Terminal
 while QOwnNotes is open, the QOwnNotes window becomes active and this shows up in logs but no settings window:
 ```
[Aug 22 14:11:01] [warning]: "A second instance of QOwnNotes was attempted to be started!"
[Aug 22 14:11:01] [debug]: operator()  - 'message':  "ction:action_Settings"
 ```

When the command is run without QOwnNotes currently running, QOwnNotes opens and opens the settings window just fine, but it takes significantly longer to do with taking ~4 seconds without `--action action_Settings` in the launch options and ~9 seconds with it. Here's the log for both options:

Without option
```
[Aug 22 14:15:52] [Debug]: Translation  "/usr/share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "qt_en" in "C:/Users/carte/Downloads/QOwnNotes/translations" isLoaded: true , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "qt_en" in "C:/Users/carte/Downloads/QOwnNotes/translations" isLoaded: true , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Aug 22 14:15:52] [Debug]: Translation  "../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "../share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:15:52] [Debug]: Translation  "QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Aug 22 14:15:52] [Debug]: getDiskDatabasePath  - 'databaseFileName':  "C:/Users/carte/Downloads/QOwnNotes/Data/QOwnNotes.sqlite"
[Aug 22 14:15:52] [Debug]: setupTables  - 'database_version':  41
[Aug 22 14:15:52] [Debug]:  HunspellClient::HunspellClient
[Aug 22 14:15:52] [Debug]:  SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_US"
[Aug 22 14:15:52] [Debug]: Loading dictionary for "en_US" from "C:/Users/carte/Downloads/QOwnNotes/Data/dicts"
[Aug 22 14:15:52] [Debug]: Load a user dictionary "C:/Users/carte/Downloads/QOwnNotes/Data/.hunspell_en_US"
[Aug 22 14:15:52] [Debug]: Created  0x452f3b0
[Aug 22 14:15:53] [debug]: Set proxy configuration to use NO proxy
[Aug 22 14:15:53] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Aug 22 14:15:53] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[Aug 22 14:15:53] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Aug 22 14:15:53] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:15:54] [scripting]: loading script file: C:/Users/carte/Downloads/QOwnNotes/Data/scripts/latex-math/latex-math.qml
[Aug 22 14:15:54] [scripting]: [LaTex] init
[Aug 22 14:15:54] [scripting]: [LaTex] C:/Users/carte/AppData/Local/PBE/QOwnNotes/cache/scripts/latex-math
[Aug 22 14:15:54] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Aug 22 14:15:54] [debug]: setupNoteFolderTables  - 'database version':  15
[Aug 22 14:15:54] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[Aug 22 14:15:54] [debug]: loadNoteDirectoryList
[Aug 22 14:15:54] [debug]: reloadTagTree
[Aug 22 14:15:54] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Aug 22 14:15:54] [debug]: loadNoteDirectoryList
[Aug 22 14:15:54] [debug]: reloadTagTree
[Aug 22 14:15:54] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Aug 22 14:15:54] [debug]: reloadNoteSubFolderTree
[Aug 22 14:15:54] [debug]: reload
[Aug 22 14:15:54] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:15:54] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:15:54] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:15:55] [debug]: on_noteTreeWidget_itemSelectionChanged
[Aug 22 14:15:55] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"Chemistry" <fileName>"Chemistry.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Aug 22 14:15:55] [debug]:  added to history:  NoteHistoryItem: <noteName>"Chemistry" <noteSubFolderPathData>"" <cursorPosition>3117 <relativeScrollBarPosition>0.738318
[Aug 22 14:15:56] [debug]: Reply from  "/qownnotes/scripts/master/latex-math/info.json"
[Aug 22 14:15:56] [debug]: Reply from info.qml request
```

With option
```
[Aug 22 14:17:45] [Debug]: Translation  "/usr/share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "qt_en" in "C:/Users/carte/Downloads/QOwnNotes/translations" isLoaded: true , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "qt_en" in "C:/Users/carte/Downloads/QOwnNotes/translations" isLoaded: true , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Aug 22 14:17:45] [Debug]: Translation  "../src/languages/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "../share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "C:/Users/carte/Downloads/QOwnNotes/../share/qt5/translations/QOwnNotes_en" in "" isLoaded: false , isInstalled: false
[Aug 22 14:17:45] [Debug]: Translation  "QOwnNotes_en" in "" isLoaded: true , isInstalled: true
[Aug 22 14:17:45] [Debug]: getDiskDatabasePath  - 'databaseFileName':  "C:/Users/carte/Downloads/QOwnNotes/Data/QOwnNotes.sqlite"
[Aug 22 14:17:45] [Debug]: setupTables  - 'database_version':  41
[Aug 22 14:17:46] [Debug]:  HunspellClient::HunspellClient
[Aug 22 14:17:46] [Debug]:  SpellerPlugin *HunspellClient::createSpeller(const QString &language) ; "en_US"
[Aug 22 14:17:46] [Debug]: Loading dictionary for "en_US" from "C:/Users/carte/Downloads/QOwnNotes/Data/dicts"
[Aug 22 14:17:46] [Debug]: Load a user dictionary "C:/Users/carte/Downloads/QOwnNotes/Data/.hunspell_en_US"
[Aug 22 14:17:46] [Debug]: Created  0x44cfab0
[Aug 22 14:17:46] [debug]: Set proxy configuration to use NO proxy
[Aug 22 14:17:46] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Aug 22 14:17:46] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[Aug 22 14:17:46] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Aug 22 14:17:47] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:17:47] [scripting]: loading script file: C:/Users/carte/Downloads/QOwnNotes/Data/scripts/latex-math/latex-math.qml
[Aug 22 14:17:47] [scripting]: [LaTex] init
[Aug 22 14:17:47] [scripting]: [LaTex] C:/Users/carte/AppData/Local/PBE/QOwnNotes/cache/scripts/latex-math
[Aug 22 14:17:47] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Aug 22 14:17:47] [debug]: setupNoteFolderTables  - 'database version':  15
[Aug 22 14:17:47] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <accountId>"" <priority>1
[Aug 22 14:17:47] [debug]: loadNoteDirectoryList
[Aug 22 14:17:47] [debug]: reloadTagTree
[Aug 22 14:17:47] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Aug 22 14:17:47] [debug]: loadNoteDirectoryList
[Aug 22 14:17:47] [debug]: reloadTagTree
[Aug 22 14:17:47] [debug]: reloadTagTree  - 'noteSubFolderIds':  QVector()
[Aug 22 14:17:47] [debug]: reloadNoteSubFolderTree
[Aug 22 14:17:47] [debug]: reload
[Aug 22 14:17:48] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:17:48] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:17:48] [debug]: updatePanelMenu  - 'updatePanelMenu'
[Aug 22 14:17:49] [debug]: Running menu action:  "action_Settings"
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 12
[Aug 22 14:17:49] [warning]:   OpenType support missing for "Arial", script 12
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS UI Gothic", script 12
[Aug 22 14:17:49] [warning]:   OpenType support missing for "SimSun", script 12
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 11
[Aug 22 14:17:49] [warning]:   OpenType support missing for "Arial", script 11
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS UI Gothic", script 11
[Aug 22 14:17:49] [warning]:   OpenType support missing for "SimSun", script 11
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 32
[Aug 22 14:17:49] [warning]:   OpenType support missing for "Arial", script 32
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS UI Gothic", script 32
[Aug 22 14:17:49] [warning]:   OpenType support missing for "SimSun", script 32
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 13
[Aug 22 14:17:49] [warning]:   OpenType support missing for "Arial", script 13
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS UI Gothic", script 13
[Aug 22 14:17:49] [warning]:   OpenType support missing for "SimSun", script 13
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 20
[Aug 22 14:17:49] [warning]:   OpenType support missing for "Arial", script 20
[Aug 22 14:17:49] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[Aug 22 14:17:49] [warning]:   OpenType support missing for "SimSun", script 20
[Aug 22 14:17:52] [warning]:   OpenType support missing for "Segoe UI", script 20
[Aug 22 14:17:52] [warning]:   OpenType support missing for "MS Shell Dlg 2", script 20
[Aug 22 14:17:52] [warning]:   OpenType support missing for "Arial", script 20
[Aug 22 14:17:52] [warning]:   OpenType support missing for "MS UI Gothic", script 20
[Aug 22 14:17:52] [warning]:   OpenType support missing for "SimSun", script 20
[Aug 22 14:17:54] [debug]: on_noteTreeWidget_itemSelectionChanged
[Aug 22 14:17:54] [debug]: setCurrentNote  - 'note':  Note: <id>1 <name>"Chemistry" <fileName>"Chemistry.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false  - 'updateNoteText':  true  - 'updateSelectedNote':  false
[Aug 22 14:17:54] [debug]:  added to history:  NoteHistoryItem: <noteName>"Chemistry" <noteSubFolderPathData>"" <cursorPosition>3117 <relativeScrollBarPosition>0.738318
[Aug 22 14:17:55] [debug]: Reply from  "/qownnotes/scripts/master/latex-math/info.json"
[Aug 22 14:17:55] [debug]: Reply from info.qml request
```

It might be useful to look at the lines where there is a suspicious difference in time. For example, 3 seconds passed between lines 61 and 62 seemingly randomly, and that difference seems to be consistent when reopening the app with the same command.

**Comment by Carterpersall** [comment] 2022-09-02 16:24
@macsunmood @pbek Any updates on this issue?

**Comment by pbek** [comment] 2022-09-02 16:55
It's really hard to debug anything without actually tracing through the code on your end.
So far @Waqar144 was my benchmark for slow computers and he doesn't seem to have any issues.

**Comment by Waqar144** [comment] 2022-09-02 18:48
https://github.com/pbek/QOwnNotes/pull/2601 should help things a bit.

Besides that, SettingsDialog doesn't really get any attention perf wise as one doesn't need interact with it every 10 seconds. If we try a bit harder, we can make it start instantly by lazy loading widget etc, but I don't see a lot of point in going towards that direction.

**Comment by pbek** [comment] 2022-09-03 07:16
I hope not reading the settings when the dialog opens will not cause any regressions... 😬

**Comment by pbek** [comment] 2022-09-03 07:20
Ah, never mind, that was redundant since a new instance of the dialog is used every time.

**Comment by Waqar144** [comment] 2022-09-03 08:33
To clarify, it should be ~2x faster now.

**Comment by pbek** [comment] 2022-09-10 08:00
## 22.9.0
- the settings dialog opening time was improved a lot (for [#2574](https://github.com/pbek/QOwnNotes/issues/2574), thank you, @Waqar144)

There now is a new release, could you please test it and report if it works for you?

**Comment by hervyqa** [comment] 2022-09-10 09:22
nice.. thank youu..

**Comment by pbek** [comment] 2022-09-27 12:47
I will close this issue until there is more information.

**Closed by pbek** 2022-09-27 12:47 UTC
Labels: Importance: Low, Type: Improvement
