### ISSUE TITLE
Alt + s should type special character 

### ISSUE THREAD

**Issue by npodbielski** [pbek/QOwnNotes#1282] opened 2019-09-04 19:11 UTC
#### Expected behaviour
Pressing Left Alt + s should type special "ś" character. 

#### Actual behaviour
It shows "Share your note" message. It should be under Right Alt + s I think.

#### Steps to reproduce
I think it only be tested in Windows with Polish keyboard layout.

**Comment by npodbielski** [comment] 2019-09-04 19:12
I tried to add issue via your app but it seems to be broken too - it did not anything.

**Comment by pbek** [comment] 2019-09-04 20:27
> It shows "Share your note" message. It should be under Right Alt + s I think.

You can set an other shortcut in the *Shortcut settings*.

> I tried to add issue via your app but it seems to be broken too - it did not anything.

Please see #1260, you will need to download the latest version manually.

**Comment by pbek** [comment] 2019-09-05 07:32
Usually the left <kbd>Alt</kbd> is reserved for accessing menus. Here on my German keyboard I use the right <kbd>Alt</kbd> (<kbd>Alt Gr</kbd>) key for accessing characters like `€`.

**Comment by npodbielski** [comment] 2019-09-05 07:53
>You can set another shortcut in the Shortcut settings.
I checked and it is Ctrl + Alt +S. Seems like QON checks for those incorrectly somehow then. 
>Usually the left Alt is reserved for accessing menus. 
You are right. It was late and I was tired and I messed this up. 
Right Alt + S -> should be "ś" 
Ctrl + Left Alt + s -> should invoke "Share note" command

**Comment by pbek** [comment] 2019-09-05 08:24
> I checked and it is Ctrl + Alt +S. Seems like QON checks for those incorrectly somehow then.

I cannot reproduce this, <kbd>Ctrl + Alt +S</kbd> works for me on the German keyboard. Maybe Qt confuses those modifier keys on your layout. Can you set another shortcut for the share dialog?

**Comment by npodbielski** [comment] 2019-09-05 08:32
There is something funky here. I tried to set Ctrl + Alt + A and instead I got Ctrl + Alt + Ą where Ą is typed with Right Alt + A. So I got impossible to type shortcut and working ą and ś character :)

**Comment by pbek** [comment] 2019-09-05 08:56
Ok, great :laughing:. Feel free to close the issue then.

**Comment by npodbielski** [comment] 2019-09-05 09:46
So you think it is not the problem with QON? :)

**Comment by pbek** [comment] 2019-09-05 10:02
QON uses QShortcut from Qt, the modifier key detection is handled directly by Qt. If you want you can file a bug at https://bugreports.qt.io/secure/Dashboard.jspa.

**Comment by npodbielski** [comment] 2019-09-08 18:57
Ok. Thanks. I guess you can close it.

**Closed** 2019-09-08 20:17 UTC
Labels: question, upstream-problem
