### ISSUE TITLE
String length limit with "ctrl-shift-v"

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#645] opened 2017-07-27 15:07 UTC
When I paste html with shortcut  "ctrl-shift-v", I find a string length limit which may break the correct paste text formatting.
For an example, I write a simple html file (utf-8 encode)
```
<html>
<head>
</head>

<body>
<h1 id="toc_0">Note 2017-07-24</h1>
<p><strong>123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789</strong></p>

</body>
</html>
```

I open this html page with browser. I select the different length of content and paste (ctrl-shift-v) into QON, then I find it will not format correctly if the length of selected text exceed 128 characters.

![snap627](https://user-images.githubusercontent.com/12027772/28677454-1811080c-7320-11e7-99cd-73acb75c5a59.jpg)

**Comment by bepolymathe** [comment] 2017-07-27 15:48
Hi,

I confirm the same for me with Ctrl-shift-v but no problem with simple Ctrl-v

**Comment by pbek** [comment] 2017-07-27 19:17
That's interesting, maybe it's a limitation of Qt regular expression parser. I will take a look at it.

**Comment by vanleo2001** [comment] 2017-07-27 23:40
I find a talk about this **undocumented**  maximum string length limitation.
https://stackoverflow.com/questions/33614500/qml-regexpvalidator-maximum-string-length-for-validation

**Comment by vanleo2001** [comment] 2017-07-28 09:47
There is the 1024 characters length limitation in QRegExp module, but not in QRegularExpression module. Also I write a demo to test, it works correctly and shows none length limitation.
```
QString text.replace(QRegularExpression(
            "<strong.*?>(.+?)<\\/strong>",
            QRegularExpression::CaseInsensitiveOption), "**\\1**");
```

**Comment by vanleo2001** [comment] 2017-07-29 14:19
I know the why. When copying html, if copy content exceed a length limit, Win OS will insert some linebreaks  `\r\n` in clipboard content. You can confirm this with "Free Clipboard Viewer" software.  Then Qt regular expression parser can not match.

**Comment by vanleo2001** [comment] 2017-07-29 14:49
So add "remove \r\n in clipboard text"  first before html tag converting  https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L5888  ?

**Comment by pbek** [comment] 2017-07-30 05:12
Strange, I cannot reproduce that problem under mac OS, regardless of how many characters there are in the strong-tag, I always was able to paste them correctly.

**Comment by pbek** [comment] 2017-07-30 06:42
> So add "remove \r\n in clipboard text" first before html tag converting
That would influence the interpretation of `<pre>` and `<code>` tags.

I neither can reproduce this issue under Windows 8.1. I was able to copy and paste html of any length. :/

**Comment by vanleo2001** [comment] 2017-07-30 09:12
Would you like to test the html file in zip attach?
[Test.zip](https://github.com/pbek/QOwnNotes/files/1185559/Test.zip)

I make this special html page with some CR LF add. You can open it with browser and try "paste html or media" function in QON.  Is it same as shown in browser?

**Comment by vanleo2001** [comment] 2017-07-30 10:24
I google and test again. It seems the problem of browser. In windows 7, When copy (ctrl-c) some content in Firefox, it will auto insert some \r\n into copy data. So it will cause line breaks in QON when paste html (ctrl-shift-v}. While I do same in IE, it will not insert \r\n, even it will auto remove unnecessary \r\n. 
You can test Test.zip above either in IE or Firefox to distinguish the difference. Someone says Chrome has the same act as Firefox, though I don't test it.

**Comment by vanleo2001** [comment] 2017-07-31 05:28
Now I test QON in MAC OS virtual machine. `<pre> `and `<code>` tags are not replaced. 
1. In MAC OS, I open the html in below zip file with safari browser. 
[Note 2017-07-24.zip](https://github.com/pbek/QOwnNotes/files/1186460/Note.2017-07-24.zip)

2. I select some content which use `<pre>` tags in source.
![snap747](https://user-images.githubusercontent.com/12027772/28763629-19de9f3a-75f2-11e7-8eff-005af740a83d.png)

3. Then ctrl-shift-v in QON. You can see the pasted text doesn't format as it in browser. The markdown "code block" tags are missing. 
![snap748](https://user-images.githubusercontent.com/12027772/28763632-1fb673a6-75f2-11e7-8169-81d2a9e220a5.png)

4. The problem is QRegularExpression will match in one line. If you want match in multilines, you need use param `globalMatch` .

**Comment by pbek** [comment] 2017-07-31 05:33
I tested your `Test.html` in Windows under Chrome and IE, where I didn't had any problems, but it didn't work with pasting from FF.

**Comment by pbek** [comment] 2017-07-31 05:36
> The problem is QRegularExpression will match in one line. If you want match in multilines, you need use param globalMatch .

@vanleo2001, where did you find that problem? `QString::replace` replaces all occurrences (<http://doc.qt.io/qt-5/qstring.html#replace-12>)

**Comment by vanleo2001** [comment] 2017-07-31 05:58
I review the QT source. You are right.  But it seems QON exactly doesn't match in multilines. Strange!
```
QString &QString::replace(const QRegularExpression &re, const QString &after)
{
......
    QRegularExpressionMatchIterator iterator = re.globalMatch(copy);
```

**Comment by pbek** [comment] 2017-07-31 06:03
Strange, but the other replaces in `Utils::Misc::htmlToMarkdown` definitely work multiple times...

**Comment by vanleo2001** [comment] 2017-07-31 06:07
I don't think so. All above what I said copy function in FF is also caused by mismatch in multilines.

**Comment by pbek** [comment] 2017-07-31 06:12
I have not reverse engineered yet what FF does to the html code in the clipboard, but transforming multiple hits of all kind of tags with `QString::replace` seems to work with code from other browsers.

**Comment by vanleo2001** [comment] 2017-07-31 06:17
Would you like to read https://github.com/pbek/QOwnNotes/issues/645#issuecomment-318971429. The copy problem in Chrome, IE or Safari  is they will auto remove the line breaks. So `QString::replace ` is in single line.

**Comment by pbek** [comment] 2017-07-31 06:23
If `QString::replace` is the cause of this we have to file a bug for Qt, because <http://doc.qt.io/qt-5/qstring.html#replace-12> states `Replaces every occurrence of the regular expression re in the string with after. Returns a reference to the string.` ;)

**Comment by vanleo2001** [comment] 2017-07-31 07:32
I get it. Please add param in  `Utils::Misc::htmlToMarkdown`
` QRegularExpression::DotMatchesEverythingOption`  


For example:
```
text.replace(QRegularExpression(
            "<pre.*?>(.+?)<\\/pre>",
            QRegularExpression::CaseInsensitiveOption | QRegularExpression::DotMatchesEverythingOption), "\n```\n\\1\n```\n");
```

**Comment by pbek** [comment] 2017-07-31 07:38
Yes, that is the equivalent of the multiline-regexp-modifier. That definitely is needed for `<pre>` and surely for other tags too... Thank you. (It also came into my mind right before you were writing your comment)

**Comment by vanleo2001** [comment] 2017-07-31 07:40
:+1:

**Comment by pbek** [comment] 2017-07-31 16:24
It was more complex than I though...


## 17.08.0
- when pasting html from the clipboard as markdown null characters and Windows
  line breaks will now be removed as well as all tags will be interpreted over
  multiple lines

**Comment by pbek** [comment] 2017-08-02 04:38
I will close this issue until there is more information.

**Closed by pbek** 2017-08-02 04:38 UTC
