### ISSUE TITLE
[I] Typing " \;' " in a codeblock freezes the app.

### ISSUE THREAD

**Issue by Gremious** [pbek/QOwnNotes#1523] opened 2019-12-30 02:45 UTC
#### Expected behaviour

You can type whatever you want, wherever you want, and the app won't freeze/crash.

#### Actual behaviour

Typing (or, I suspect rendering the output of) \\;'in a codeblock will cause the app to become unresponcive and need to be terminated.

#### Steps to reproduce

1. Create a new note
2. Create a new code block. The one I used which for me reproduces said bug is:
\```java
for (int i : <List>){
    new String = "Cool"
}
\```
3. After the "Cool", make a space and type the three symbols: \\;' from the keyboard . This will usually cause the app to hang up.
4. If it does not, continue mashing a combination of the ; ' and \ and it should freeze up fairly quickly.

#### Relevant log output in the Log panel (Log from file after freeze.)

<details><summary>Expand</summary>

```
[Dec 30 02:40:41] [debug]: Set proxy configuration to use NO proxy
[Dec 30 02:40:45] [debug]: initShortcuts  - 'menuBarIsVisible':  true
[Dec 30 02:40:46] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 30 02:40:46] [debug]: buildNotesIndex  - 'noteSubFolderId':  0
[Dec 30 02:40:46] [debug]: setupNoteFolderTables  - 'database version':  14
[Dec 30 02:40:46] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 30 02:40:46] [debug]: loadNoteDirectoryList
[Dec 30 02:40:46] [debug]: reloadTagTree
[Dec 30 02:40:46] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 30 02:40:46] [debug]: reloadNoteSubFolderTree
[Dec 30 02:40:46] [debug]: reloadNoteSubFolderTree
[Dec 30 02:40:46] [debug]: reloadTagTree
[Dec 30 02:40:46] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Dec 30 02:40:46] [debug]: loadNoteDirectoryList
[Dec 30 02:40:46] [debug]: reloadTagTree
[Dec 30 02:40:46] [debug]: reloadTagTree  - 'noteSubFolderIds':  (0)
[Dec 30 02:40:46] [debug]: reloadNoteSubFolderTree
[Dec 30 02:40:46] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 30 02:40:46] [debug]: reloadTagTree
[Dec 30 02:40:46] [debug]: reloadTagTree  - 'noteSubFolderIds':  ()
[Dec 30 02:41:08] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
[Dec 30 02:41:14] [debug]: cloudConnection:  CloudConnection: <id>1 <name>"Default" <serverUrl>"" <username>"" <priority>1
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

(Cleared.)

**Comment by Waqar144** [comment] 2019-12-30 05:12
I can't reproduce this with the latest code.

I made some fixes and improvements to the escape sequence highlighting so this should be fixed in the next release.

**Comment by Gremious** [comment] 2019-12-30 05:36
I have a small question regarding the highlighting, my appologies that it doesn't directly relate to the issue: Are there plans to implement it in the preview/output screen as well? I love it, but admitedly It's odd to see the edit view looking prettier than the actual note output.

**Comment by Waqar144** [comment] 2019-12-30 05:46
> I have a small question regarding the highlighting, my appologies that it doesn't directly relate to the issue: Are there plans to implement it in the preview/output screen as well? I love it, but admitedly It's odd to see the edit view looking prettier than the actual note output.

Yes, I am working on it (A lot of people want it :smile: ) but its a bit tricky and the progress is slow. (It's a pretty big wheel to invent)

Unlike usual markdown editors, we don't use a browser based preview (for various reasons like supporting debian 8 + cross platform issues) otherwise it would be very easy with highlight.js and similar libraries. [Details here](https://github.com/pbek/QOwnNotes/issues/1421) 
[pics here](https://github.com/pbek/QOwnNotes/pull/1474)

**Comment by Gremious** [comment] 2019-12-30 05:51
I'm really glad to hear it! Can't say the thought "why don't they just implement highlight.js?" didn't cross my mind, but you were one step ahead! Really looking forward to that update, keep up the great work!

**Comment by pbek** [comment] 2019-12-30 06:43
I was able to reproduce it on 19.12.16 but not with the current develop branch, so yes, will be fixed with the next release. 😁

**Comment by Waqar144** [comment] 2019-12-30 10:52
> I'm really glad to hear it! Can't say the thought "why don't they just implement highlight.js?" didn't cross my mind, but you were one step ahead! Really looking forward to that update, keep up the great work!

It's done. You will get it in the next release hopefully :)

**Comment by pbek** [comment] 2019-12-30 15:58
## 19.12.17
- did some highlighting fixes and improvements (for [#1523](https://github.com/pbek/QOwnNotes/issues/1523),
  [#64](https://github.com/pbek/qmarkdowntextedit/pull/64) and
  [#65](https://github.com/pbek/qmarkdowntextedit/pull/65), thank you @Waqar144)

**Comment by pbek** [comment] 2019-12-30 16:25
> It's done. You will get it in the next release hopefully :)

see #1526

**Comment by pbek** [comment] 2019-12-30 16:38
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment] 2020-01-06 13:47
This should be closed

**Closed** 2020-01-06 13:59 UTC
Labels: Importance: Medium, Type: Bug - Regression
