### ISSUE TITLE
[I] Incompatibility bewtween Windows/Linux and Mac OS

### ISSUE THREAD

**Issue by bkomanet** [pbek/QOwnNotes#1605] opened 2020-01-23 18:15 UTC
#### Expected behaviour

Notes created on Linux and Windows should also be availble on Mac OS

#### Actual behaviour

I have put my QOwnNotes folder on my Dropbox drive.  I then installed QOwnNotes o Windows and on multiple liux computers (Ubuntu). Everything works great (after each computer sync's its dropbox)!  But when I got to work, I installed it on one of my mac's and waited for my dropbox to finish sync'ing.  I then started QOwnNotes on the Mac, pointed to the EXACT same folder as my windows and linux installs did, and I would have expected it to display the notes correctly, but it does not.  None of my tags are available and any note I click on I cannot see its contents.  I see the note titles, but no note content.  I am lookig for a cross-platofrm note taking app and am willing to donte, but it needs to work before I do.  Thank you.

#### Steps to reproduce

See Actual behaviour section as to how I found this problem

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```

```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Thu Jan 23 10:13:37 2020`
**Version**: `20.1.15`
**Build date**: `Jan 23 2020`
**Build number**: `5279`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/bkomanet/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/bkomanet/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1200`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `13`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/bkomanet/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `2`

### Note folder `default`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `/Users/bkomanet/Dropbox/Apps/QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/bkomanet/Dropbox/Apps/QOwnNotes/notes.sqlite`

### Note folder `default`

**id**: `2`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/bkomanet/Dropbox/Apps/QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/bkomanet/Dropbox/Apps/QOwnNotes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

** Patriot Memory** (QString): `1`
** USB DISK 2/0** (QString): `1`
**1D19B11E9063328B9BD6ACBAA52F6CF9E8EBCDA1** (QByteArray): `<binary data>`
**646F6E7A_00000000_00000001_6E7A6361_696D6963** (qlonglong): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2019-10-07T14:27:31.673`
**AKLastCheckInSuccessDate** (QDateTime): `2019-10-07T14:27:36.287`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-01-23T09:22:46.932`
**AKLastIDMSEnvironment** (qlonglong): `0`
**ASIX Elec/ AX88179** (QString): `1`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Akai MPK225** (QString): `1`
**BILLBOARD CLASS ANALOGIXSEMI COM** (QString): `1`
**Brother ADS-1700W** (QString): `1`
**Brother MFC-J995DW** (QString): `1`
**ContextMenuGesture** (qlonglong): `1`
**Country** (QString): `US`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**FUJITSU ScanSnap S300M** (QString): `1`
**Fujitsu ScanSnap iX500** (QString): `1`
**HP ENVY 5540 series** (QString): `1`
**HP ENVY 7640 series** (QString): `1`
**HP OfficeJet Pro 8740** (QString): `1`
**HP Photosmart 5510d series** (QString): `1`
**Hewlett Packard MFP M277c6** (QString): `1`
**Hitachi-LG Data Storage Inc Portable Super Multi Drive** (QString): `1`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**Kingston DT 101 G2** (QString): `1`
**Kingston DataTraveler 2/0** (QString): `1`
**Kingston Multi-Reader** (QString): `1`
**LastUpdateCheck** (QDateTime): `2020-01-23T10:10:20.685`
**Lexar USB Flash Drive** (QString): `1`
**LogWidget/criticalLog** (bool): `true`
**LogWidget/debugLog** (bool): `true`
**LogWidget/fatalLog** (bool): `true`
**LogWidget/infoLog** (bool): `true`
**LogWidget/scriptingLog** (bool): `true`
**LogWidget/statusLog** (bool): `true`
**LogWidget/warningLog** (bool): `true`
**Logitech Cordless RumblePad 2** (QString): `1`
**Logitech Wireless Gamepad F710** (QString): `1`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `.SF NS Mono,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.AppleSystemUIFont,13,-1,5,50,0,0,0,0,0`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**Memorex Mini** (QString): `1`
**NoteHistory-2** (QVariantList): `<variant list with 4 item(s)>`
**NoteHistoryCurrentIndex-2** (qlonglong): `3`
**OLYMPUS CORPORATION DIGITAL VOICE RECORDER** (QString): `1`
**OWC Elite Pro FWU3 eSATA** (QString): `1`
**OWC Envoy Pro** (QString): `1`
**PKSecureElementAvailableFlags** (qlonglong): `3`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `3`
**PNY Technologies USB 2/0 FD** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**Realtek USB 10·100·1000 LAN** (QString): `1`
**SAMSUNG SAMSUNG_Android** (QString): `1`
**Samsung Flash Drive** (QString): `1`
**SanDisk Cruzer Blade** (QString): `1`
**SanDisk Cruzer Facet** (QString): `1`
**SanDisk Cruzer Glide 3/0** (QString): `1`
**SanDisk Ultra** (QString): `1`
**SanDisk Ultra USB 3/0** (QString): `1`
**Seagate BUP BK** (QString): `1`
**Seagate BUP BL** (QString): `1`
**Seagate BUP Fast HDD** (QString): `1`
**Seagate BUP Slim BK** (QString): `1`
**Seagate BUP Slim Mac SL** (QString): `1`
**Seagate BUP Slim SL** (QString): `1`
**Seagate FreeAgent GoFlex** (QString): `1`
**Sony MRW-E90** (QString): `1`
**Sunplus Innovation Technology/ USB to Serial-ATA bridge** (QString): `1`
**SyncServicesServerWasActive** (bool): `true`
**VIA Technologies Inc/ USB 2/0 BILLBOARD** (QString): `1`
**VLI Manufacture String VLI Product String** (QString): `1`
**Wacom Co/,Ltd/ Intuos PTM** (QString): `1`
**Wacom Co/,Ltd/ Wacom Intuos Pro M** (QString): `1`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**Western Digital My Passport 259F** (QString): `1`
**allowNoteEditing** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**checkSpelling** (bool): `false`
**com/barebones/bbedit~54CB6434051D7649405DCC9F47620EF86E29A8A9** (QByteArray): `<binary data>`
**com/omnigroup/OmniFocus2:2:25** (QByteArray): `<binary data>`
**com/omnigroup/OmniFocus3:40** (QByteArray): `<binary data>`
**com/omnigroup/OmniGraffle7:7:4** (QByteArray): `<binary data>`
**com/omnigroup/OmniOutliner4:4:4** (QByteArray): `<binary data>`
**com/omnigroup/OmniOutliner5:5:10** (QByteArray): `<binary data>`
**com/omnigroup/OmniPlan3:3:9** (QByteArray): `<binary data>`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `2`
**currentWorkspace** (QString): `initial`
**darkMode** (bool): `false`
**disableAutomaticUpdateDialog** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `full`
**itemHeight** (qlonglong): `18`
**markdownHighlightingEnabled** (bool): `true`
**noteEditIsCentralWidget** (QString): `true`
**notesPath** (QString): `/Users/bkomanet/Dropbox/Apps/QOwnNotes`
**ownCloud/supportEnabled** (bool): `false`
**restoreCursorPosition** (bool): `false`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**USER**: `bkomanet`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `bkomanet`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.eXJ4mY6NEu/Listeners`
**HOME**: `/Users/bkomanet`
**SHELL**: `/bin/bash`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x0`
**TMPDIR**: `/var/folders/46/2df_t7nn57l98kyqqxg5hmq40000gn/T/`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.29860`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
</details>

**Comment by pbek** [comment] 2020-01-23 20:34
I cannot reproduce your problem. Can you please post a list of files of your note folder with filesize from every system.

**Comment by bkomanet** [comment] 2020-01-23 21:21
I could zip up my data directory if you like.  Nothing private there, just trying it out.

**Comment by pbek** [comment] 2020-01-23 21:22
I just want to see what is different in your note folders on your different systems.

**Comment by bkomanet** [comment] 2020-01-23 21:35
Ok, but I don't have different folders.  I have my note folder on my dropbox drive which syncs locally to all of my other drives.    I have attached the listing I see on my Mac, and another I see on one of my Linux(s) which works (Mac does not, or as I spelled the file - Mak.  hee hee)

![MakListing](https://user-images.githubusercontent.com/32656258/73025756-02ae3d80-3de5-11ea-9e52-42c72db544ad.png)

![TP51Listing](https://user-images.githubusercontent.com/32656258/73025895-4608ac00-3de5-11ea-8445-9f6798bcc9d3.png)

**Comment by pbek** [comment] 2020-01-24 05:34
> Ok, but I don't have different folders.

they are different folders, Dropbox just syncs them ;)
files are looking ok.

and what does QOwnNotes show, in what way is the content "not shown"? do you have screenshots? I use the same notes in QON on more than 10 devices on all platforms.

**Comment by bkomanet** [comment] 2020-01-24 19:25
Ha Ha.  Yes, I understand they are different folders....  :-)

Here is a URL of a video with me installing it, and what I'm seeing.
https://www.dropbox.com/s/gjqmhyzi2wrunz2/QOwnNotesMacProblem.mp4?dl=0

**Comment by pbek** [comment] 2020-01-24 19:44
> empty screen, nothing clickable

I've never in my life seen QON behave on macOS (or anywhere else) like on your system. I can't believe it's caused by QON directly.

> removing settings

There are cli parameters for that: http://docs.qownnotes.org/en/develop/cli-parameters.html

can you please try to start a new session of qownnotes (see cli parameters) with a new and empty note folder

And is there any useful log output after startup and when clicking note if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by bkomanet** [comment] 2020-01-24 23:36
Ok, I just installed it on another Mac, and about to try on a third.  The second Mac it worked fine on...

**Comment by pbek** [comment] 2020-01-25 05:39
Just to make sure I just started a new session on my macBook with `/Applications/QOwnNotes.app/Contents/MacOS/QOwnNotes --session test` to get the setup dialog again and everything worked fine. So did you get any log output on your first mac? And what about your 3rd one?

**Comment by bkomanet** [comment] 2020-01-25 16:32
OK, I just tried it on another Mac and it worked OK.  I have attached the log from the Mac which is not working OK.  
[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/4112241/QOwnNotes.log)

**Comment by pbek** [comment] 2020-01-25 21:52
> [Jan 25 08:22:04] [warning]: countAllOfNote :  QSqlError("", "Parameter count mismatch", "")

it looks like your `notes.sqlite` is damaged on this mac (or your sqlite library is broken), you could try to move the file it away and try again to see if it works when the file is regenerated (empty of course).

**Comment by bkomanet** [comment] 2020-01-25 22:27
Won't deleting this (on my Dropbox folder) cause the database to be regenerated for ALL of my computers using QOwnNotes since they all use the same dropbox folder?
And if so, then why would it be fine for my other Mac's and my Linux/Windows computers?

**Comment by pbek** [comment] 2020-01-25 22:38
>you could try to move the file it away and try again to see if it works when the file is regenerated (empty of course)

after the test you can move it back of course

> And if so, then why would it be fine for my other Mac's and my Linux/Windows computers?

ask Dropbox or or mac OS installation, I've no idea 😸 

> can you please try to start a new session of qownnotes (see cli parameters) with a new and empty note folder

you still also can try that to get a better picture what is going to on your system

**Comment by bkomanet** [comment] 2020-01-26 00:11
OK, so here is what I did to make it finally work:
1) I issued QOwnNotes --session test
2) Created a folder on the desktop with the basic notes created during session initialization
3) I closed QOwnNotes
4) Copied all of the files, including the notes.sqlite file to the new folder created by the test session
5) I restarted QOwnNotes --session test and everything worked!
6) I then deleted all of the files in the Dropbox QOwnNotes folder (after backing them up), then copied all of the files from the test session back to the Dropbox folder
7) I then ran QOwnNotes (not the test session) and everything looked good.
8) I then tested two linux and three Mac's and everything looked good.

I did NOT reinstall anything on the Mac in question....  Very strange..

**Comment by pbek** [comment] 2020-01-26 06:52
Maybe you damaged something by removing QON settings files manually. Don't do that manually, there is a cli parameter and a button in the settings to wipe all settings. But on the other hand now your main sessions also works so I still don't know. 😆 

My best guess is that Dropbox or macOS somehow locked access to `notes.sqlite` in your dropbox folder.

If that that answers your question feel free to close the issue.

**Comment by bkomanet** [comment] 2020-01-26 17:39
FYI, I never removed the settings the first time I installed it.  The ONLY reason I removed the settings was to reset everything to try again since the program was messed up (locked up notes as you saw in the video).  It does make sense that the notes.sqlite file may have had permission problems, so QOwnNotes couldn't use it.  That makes sense.  Thanks for your quick help.  I'll be donating today.

**Closed** 2020-01-26 17:39 UTC
Labels: Type: Question

**Comment by pbek** [comment] 2020-01-26 19:15
Great it works now and thank you. :grin:
