### ISSUE TITLE
Request: a browser add-in that lets you highlight any text and lets you send it to QOwnNotes

### ISSUE THREAD

**Issue by Weej1** [pbek/QOwnNotes#330] opened 2016-09-18 23:13 UTC
Hi, 
I've been hunting around for quite sometime for a notetaking app that could work both on my windows work PC and Ubuntu personal one. I finally settled on QOwnNotes, so thank you for the amazing app! 
As the title says I'm requesting a feature that currently has me using 2 separate systems and I'd much rather port ALL of it into QOwnNotes and just run one note taking system. 

The other 2 systems I use are the Firefox addons on QuickFox and Gkeep Panel. The reasons for keeping them around are:
- Browser integration. Both QuickFox and  Gkeep Panel connects to Firefox so you can grab text. Gkeep Panel's plus point is that a "window-within-a-window" pops up instantly whenever I click on it Here's what that looks like:
  ![screenshot from 2016-09-19 04-20-32](https://cloud.githubusercontent.com/assets/6381159/18619794/eb5fabbc-7e22-11e6-8657-5b5e414bf9ac.png)
- QuickFox Notes takes a little time to load itself and opens up as a separate window however functionally it beats GKeep Panel (really the only plus point of Gkeep panel _is_ it's instantly appearing panel!) The biggest feature I use of QuickFox Notes is its right click context "send to" option. I just need to highlight text from the browser, right click, and I get an option to either create a new note from the selection or append the selected text to a list of already existing notes. Here's what that looks like: 
  ![screenshot from 2016-09-19 04-33-20](https://cloud.githubusercontent.com/assets/6381159/18619784/d09c169e-7e22-11e6-9825-d1b76fcf9a90.png)

I know it looks like I'm making demands, but really it's just an idea. If any of these options could be implemented in any way, shape or form I'd be getting rid of the other 2 options in a heartbeat! As it stands Im loving qOwnNotes right now, here's to it being the only app that gets my love instead of sharing it with 2 others! Thanks for reading! :bowtie:

**Comment by pbek** [comment] 2016-09-19 04:44
Thank you for your kind words and your suggestion.
QuickFox and Gkeep are both web-services, aren't they? I don't think there is a unified way to "talk" to a desktop app on Linux, Mac and Windows, plus I don't know if the browser is allowed to use them if there would be a way. And then there also would be integration for other browsers...

**Comment by Maboroshy** [comment] 2016-09-19 14:33
I've added  this feature for QOwnNotes with my [Bash-note](https://github.com/Maboroshy/Bash-note) shell script. Looks like you're running Linux so you can give it a try.

**Comment by Maboroshy** [comment] 2016-09-19 16:39
I called it so. Set inbox note in the script, bind `bash-note -c` to some key, KDE easily do this, and it pastes any selected web page part including images as markdown.

**Comment by pbek** [comment] 2016-09-19 16:49
You really are crafty! :tada:

**Comment by Maboroshy** [comment] 2016-09-19 18:00
I'm still to implement pasting to current note instead of predefined one though.

**Comment by pbek** [comment] 2016-09-21 18:19
I will close this issue until there is more information.

**Comment by Weej1** [comment] 2016-09-22 10:55
Hi Patrizio and Maboroshy

My apologies for the late reply. I'm currently out of country and my personal Linux laptop is back home. I intend to try this solution out when I return. @pbek To answer your question yes Google Keep is a web service however However QuickFox is not, it saves notes either in Firefox's Bookmarks *OR* in an sqlite file. As for the rest of your post I'm guessing you're probably right on all counts!   

The issue is primarily my work laptop which is windows 7 based. It has many IT policies governing it so installing software isn't easy (Thankfully QON has a portable version option). 

Currently to get around this "clipnotes" issue on the work laptop I use the right click context menu option called "Save To Keep" which saves a highlighted clip of text to Google Keep, then I copy each one by one into QOwnNotes when I have the free time. 

@Maboroshy Thanks for the scripts! I'm not very Bash savvy but I'm sure I'll get through them and find out exactly what I need from them. Thanks again for sharing them!

**Comment by pbek** [comment] 2016-09-22 13:17
@Weej1 as you was suggesting I guess the extension doesn't "talk" to QuickFox directly.
I guess your safest call is with the solution of @Maboroshy.

> portable mode

Yes, the portable mode came into existence recently. ;)

> clipnotes

if you find an extension that stores text files to disk you could use that too...

**Comment by Maboroshy** [comment] 2016-09-22 18:37
@Weej1 feel free to ask me anything and open any issues.

**Comment by Weej1** [comment] 2016-09-27 14:09
Alright, this is an update for those who have this issue and are searching for a "fix" with Windows+Chrome. 

My solution isn't great but it was the easiest I could think of. 

**__Context__**

Firefox has plenty of addons that lets you select text in your browser and save it as a plain text file. Many even give options such as "Append to existing text file" etc.  This is all great since it means QOwnNotes can access those files direct. 

Yet Chrome is a different beast altogether. I've found many "note clipper" extensions for it but they all didn't have the option to save to a plain text file! (except for [this one](https://chrome.google.com/webstore/detail/simple-notepad/kfjclcfpbfhdmikhohhjacgdmndneckj?utm_source=gmail) but I'll explain why I skipped it). 

At best the extensions saved to a format like XML or some Database. At worst they saved to a proprietary format that could be read by some "reader" extension or website by the same author/company. 

* _**The Solution**_ *

The "fix" I came up with is down to the latest version of QOwnNotes. * **It now can parse and save Evernote files!** * This is why I skipped the extension I linked above.  While I could "export all to text" with ease I was running into issues like: "How well updated is this extension?" " Will it break with the next version of chrome?"etc  

Since I was installing an extension to parse the text later on and put in someplace QOwnNotes could use it. I thought it better to just install the Evernote extension (and the portable app too!) and just save my notes in Evernote's Format (.enex ). From that point  I  direct QOwnNotes to its notes folder and have it auto-import! It does a pretty good job so for now Im sorted I guess! I have a few more suggestions but I'll open up those as other tickets.   

For Linux users just use Maboroshy's stuff it's very modular and you can set it up any way you want.

**Comment by pbek** [comment] 2018-12-26 08:32
## 18.12.6
- start of QOwnNotes websocket server integration for implementing a
  **Web Scraper** browser extension
    - you should already be able to "talk" to your QOwnNotes application by
      connecting to `ws://127.0.0.1:22222`, for example with [Echo Test](https://www.websocket.org/echo.html?location=ws://127.0.0.1:22222)

**Comment by pbek** [comment] 2018-12-27 11:34
## 18.12.7
- added support for the new [QOwnNotes Chrome Web Companion extension](https://github.com/qownnotes/chrome-web-companion/) to add selected text as new note
    - you can download the current release of the extension at [QOwnNotes Chrome Web Companion 18.12.0](https://github.com/qownnotes/chrome-web-companion/releases/tag/18.12.0), just drop the file into Chrome to install the extension

**Comment by pbek** [comment] 2018-12-27 11:57
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2018-12-27 13:19
@woodworker thank you for testing!

> set the port to 2222

it should be 22222

> marked some text and created a new note via the extension but the note seem to behave like read only, no cursor, no input

are you in *read only mode*? you would see a "read-only" text on the bottom right of the app

**Comment by woodworker** [comment] 2018-12-27 14:36
Yes port is correct, forgett the last 2, but when i install it i needed to set a port, when i set it the value in the confirm is set to NaN

so teh readonly thing appears only to happen on this page
http://www.davidhaillant.com/mini-dual-power-supply-update-to-2-1/

maybe its because of the | symbol in the header.

PS: maybe add teh URL from the current page at the bottom of the note

**Comment by pbek** [comment] 2018-12-27 14:49
> when i set it the value in the confirm is set to NaN

Thank you, I just noticed that myself, the default should also be `22222`.

> so teh readonly thing appears only to happen on this page
http://www.davidhaillant.com/mini-dual-power-supply-update-to-2-1/

it works for me on that page...

> PS: maybe add teh URL from the current page at the bottom of the note

or on the beginning...
yes, good idea. I already wanted to do that.

**Comment by pbek** [comment] 2018-12-27 14:51
I also want to use the the selected HTML (and convert it to markdown) instead of plain text, but getting the HTML from the browser proofed yet to be impossible...

**Comment by woodworker** [comment] 2018-12-27 15:05
I made some screenshots:

the initial state after note creation (se teh difference between the markdown and the rendered version)
![after-creation](https://user-images.githubusercontent.com/85796/50484391-a1087d80-09f0-11e9-8dca-3b2e97639d5c.png)

the note name in the browser
![in-notes-browser](https://user-images.githubusercontent.com/85796/50484392-a1087d80-09f0-11e9-90fd-b1feaf9e693d.png)

Then after switchign to another note and switching back to this note, because i thought this would fix the read only thing only the headline is there
![after-switching-to-another-note](https://user-images.githubusercontent.com/85796/50484393-a1087d80-09f0-11e9-9020-d438e4a2b818.png)

mote details:
* the notes are created in a subfolder (always the one i have selected right now)
* windows 10 pro system
* i use the chrome-web-companion-18.12.0 release tar.gz from github (installed it via dev mode + load unpacked)

**Comment by pbek** [comment] 2018-12-27 15:21
> Then after switchign to another note and switching back to this note, because i thought this would fix the read only thing only the headline is there

strange, I could not reproduce that under Linux, will take a look under Windows
did you have this issue on other webpages too?

> the notes are created in a subfolder (always the one i have selected right now)

yes, notes are currently created as if you would create it manually

**Comment by pbek** [comment] 2018-12-27 17:33
## 18.12.8
- improved note name filtering to prevent troubles on Windows for the
  [QOwnNotes Web Companion Chrome extension](https://github.com/qownnotes/chrome-web-companion/)

plus for the **QOwnNotes Web Companion**

## 18.12.1
- fixed the default port
- restructured the context menu
- added an context menu entry to reset the settings

the changes in the QOwnNotes Web Companion you should be already able to test

**Comment by pbek** [comment] 2018-12-27 17:40
plus: the url of the page will now also be written to the note

**Comment by pbek** [comment] 2018-12-27 18:10
## 18.12.8
- improved note name filtering to prevent troubles on Windows for the [QOwnNotes Web Companion Chrome extension](https://github.com/qownnotes/chrome-web-companion/)
    - the name and note text will be trimmed to prevent wrong newlines
    - the QOwnNotes Web Companion Chrome extension was updated to version 18.12.1
        - fixed the default port
        - the url of the page will now also be written to the note
        - restructured the context menu
        - added an context menu entry to reset the settings
        - download the latest version on [QOwnNotes Chrome Web Companion releases](https://github.com/qownnotes/chrome-web-companion/releases)
- the amount of `=` characters added for the headlines of new notes are now
  limited to 40 to prevent too long headline lines
    - the name will be trimmed to prevent wrong newlines in the headline

**Comment by pbek** [comment] 2018-12-27 18:43
There now is a new release, could you please test it and report if it works for you?

**Comment by woodworker** [comment] 2018-12-27 19:01
Works now, but the Headline is a bit strange when there are 2 pipes in the Title

![image](https://user-images.githubusercontent.com/85796/50491335-12a4f380-0a12-11e9-991d-5a5e532aa83a.png)

**Comment by pbek** [comment] 2018-12-28 12:02
## 18.12.9
- "dangerous" characters will now be converted to whitespaces instead of `_` in
  filenames and headlines to prevent underline formatting in headlines if two `_`
  characters are present (for [#330](https://github.com/pbek/QOwnNotes/issues/330))
- added support for converting html to markdown when a page is created as new
  note for the [QOwnNotes Web Companion Chrome extension](https://github.com/qownnotes/chrome-web-companion/)
  (for [#330](https://github.com/pbek/QOwnNotes/issues/330))
- inline images will now be automatically transformed to real images if html is
  converted to markdown (for [#330](https://github.com/pbek/QOwnNotes/issues/330))
- the [QOwnNotes Web Companion Chrome extension](https://github.com/qownnotes/chrome-web-companion/)
  was updated to version 18.12.2
    - added support to import pages as new note
        - the html will be converted to markdown and images of the page will be
          downloaded (might take a while)
    - added support to add a screenshot of the visible area as new note
    - selected text will now be created as new note with newlines if possible
    - download the latest version on [QOwnNotes Chrome Web Companion releases](https://github.com/qownnotes/chrome-web-companion/releases)

**Comment by pbek** [comment] 2018-12-28 12:05
Still no luck with capturing the selection as html... Tried finding something several hours again.

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2018-12-31 10:42
I now also added the extension to the [Chrome Web Store](https://chrome.google.com/webstore/detail/qownnotes-web-companion/pkgkfnampapjbopomdpnkckbjdnpkbkp).

**Comment by pbek** [comment] 2019-01-01 12:10
## 19.1.0
- you can now change the socket server port for connecting with the
  [QOwnNotes Web Companion Chrome extension](https://github.com/qownnotes/chrome-web-companion) in the new *Chrome extension settings* 
    - the Chrome extension is now also available in the [Chrome Web Store](https://chrome.google.com/webstore/detail/qownnotes-web-companion/pkgkfnampapjbopomdpnkckbjdnpkbkp)
- fixed some possible crashes if a socket client disconnects from the socket server

**Comment by pbek** [comment] 2019-01-01 12:11
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2019-01-08 19:22
## 19.1.1
- the *Chrome extension settings* got renamed to *Browser extension*
- added [Firefox Add-ons page](https://addons.mozilla.org/firefox/addon/qownnotes-web-companion)
  to the *Browser extension* settings page (for [#330](https://github.com/pbek/QOwnNotes/issues/330))
- the [QOwnNotes Web Companion browser extension](https://github.com/qownnotes/web-companion)
  was updated to version 19.1.1
    - the extension now also works with Firefox (for [#1](https://github.com/qownnotes/web-companion/issues/1),
      thank you @Offerel for your Firefox changes)
    - reimplementation of extension with webextension-toolbox, webpack and VueJS
      for Google Chrome and Mozilla Firefox
        - creating notes from the current selection, the whole page and as
          screenshot now works with Firefox and Chrome 
    - there now is a browser option page to set and reset the server socket port
    - the text of the extension can now be translated
        - visit [QOwnNotes translations](https://crowdin.com/project/qownnotes)
          if you want to help to translate the interface to your language
    - download the latest version on [QOwnNotes Web Companion releases](https://github.com/qownnotes/web-companion/releases)

**Comment by pbek** [comment] 2019-01-08 19:23
There now is a new release, could you please test it and report if it works for you?

**Closed** 2019-07-07 04:23 UTC
Labels: enhancement
