### ISSUE TITLE
Define standard folders for attachments and images according to the name of the md-file

### ISSUE THREAD

**Issue by tragtragtrag** [pbek/QOwnNotes#1645] opened 2020-02-28 13:33 UTC
I am about ot use Qownnotes for more and more notes. I like it a lot and I really appreciate the work you do for that, thanks a lot!

One feature I have not found and/or which might be missing in my opinion is this:

My notes have following structures (folders in capital letters, files in lower case):  
- FOLDER A
- FOLDER B
  - file1.md
  - file2.md
  - FILE1.ATT
    - attachment1forfile1.pdf
    - attachment2forfile1.jpg
  - FILE2.ATT
    - attachment1forfile2.doc
- FOLDER C
- etc.

Is or could there be an option that automatically attaches a file/image when being inserted via the inserting option directly in a folder named "filename.ATT"?

There exist the feature with the checkbox "insert to Media-folder". But I do not like the system with the media-folder since everything gets very messy if there are many attachments. I prefer to have for every single md-file an attachment-folder.

**Comment by pbek** [comment] 2020-02-28 13:52
I don't think that would work easily, a lot of the mechanic (like renaming notes, moving notes between sub-folders and note-folders, the orphaned attachment/media file dialogs, media file / attachment detection, ...) is tailored to one central media and attachment folder per note folder. Those mechanics would work and people would start arguing about that.

**Comment by pbek** [comment] 2020-02-28 13:54
You can always just create those folders as you like (you would need to ignore them in the *Panel settings* because otherwise that would be note sub-folders), copy your media files to them and insert the media files into notes without inserting them into the media library.

**Comment by tragtragtrag** [comment] 2020-02-28 21:08
Thank you for the explanation. I see, it would be quite a complex task. I will keep on doing it as you described. Thanks for the hint to ignore these attachment folder, I didn't realize that this is possible.

**Comment by pbek** [comment] 2020-02-28 21:22
QON is automating quite a lot. People rely on this now. :sweat_smile:

**Comment by tragtragtrag** [comment] 2020-11-05 11:18
> You can always just create those folders as you like (you would need to ignore them in the _Panel settings_ because otherwise they would be note sub-folders), copy your media files to them and insert the media files into notes without inserting them into the media library.

I'm still a big fan of having for each note a separate folder. So, a follow up question:  
To insert a file (e.g. pdf or jpg) an easy approach is just to click on that file in the (Windows) Explorer and move it directly into the note in QON. Unfortunately, this file will then be copied to the attachment or media folder in QON. Is there a way how I can easily move the file from the Explorer by mouse to the note without having it copied to the attachment/media folder but getting the exact (relative) file path?

An example, I have following setup:
- NOTES (folder)
  - Projectlist.md
  - PROJECTLIST (folder)

Instead of [Manual.pdf](../attachments/Manual-857942123.pdf) I want to get [Manual.pdf](/PROJECTLIST/Manual.pdf), i.e. Manual.pdf is already saved in the folder PROJECTLIST which is in the same folder (NOTES) as the md-file.

Alternatively, if this is too complicated what about this proposal: Put all the added pictures and attachments to the attachment/media folders but (in addition to the original file-name as this is the case now) also adding the path-data of the md-file in the relevant note-folder.

As an example: Instead of [Manual.pdf](../attachments/Manual-857942123.pdf) I would get [Manual.pdf](../attachments/Projectlist_Manual-857942123.pdf)

Like this it would still easily be possible for me to be able to assign easy attached file to the corresponding md-file, e.g. in Windows Explorer.

**Comment by pbek** [comment] 2020-11-05 11:23
> Instead of [Manual.pdf](../attachments/Manual-857942123.pdf) I want to get [Manual.pdf](/PROJECTLIST/Manual.pdf), i.e. Manual.pdf is already saved in the folder PROJECTLIST which is in the same folder (NOTES) as the md-file.

You can do that with https://www.qownnotes.org/scripting/hooks.html#insertmediahook

**Comment by tragtragtrag** [comment] 2020-11-05 11:37
Thank you! Actually I found this before, but unfortunately I have no idea how to include this script (even with this help: https://www.qownnotes.org/scripting/) in QON :). So far I only used the script-repository but never managed to use a script that is not in there. I guess I don't have to mention that I'm not that programming freak ;)

**Comment by pbek** [comment] 2020-11-05 11:39
There is an **Add script** button in the *Script settings*.

**Comment by pbek** [comment] 2020-11-05 11:43
> You can place those QML files anywhere you like and add use them in QOwnNotes by adding them in the Scripting settings.

That's what https://www.qownnotes.org/scripting/ is currently saying. 😁  I'll add a note for the `Add script` button if that was unclear. 😀

**Comment by tragtragtrag** [comment] 2020-11-05 11:49
I have seen this too, but my problem is different, more fundamental, it starts when I see the text of the script in https://www.qownnotes.org/scripting/hooks.html#insertmediahook. What do I do with that text? (I said, I have no idea about scripting etc.... :)) Copy it, paste it in an editor, add some text (see below) and save it as qml-file and insert this then? If I do this, then I always get this error: `file:///C:/Users/XXXX/Downloads/dateiname.qml:14 Expected token `{' `

I have followin qml-file:

```
import QtQml 2.0
import QOwnNotesTypes 1.0

Script {

/**
 * This function is called when media file is inserted into the note
 * If this function is defined in multiple scripts, then the first script that returns a non-empty string wins
 *
 * @param fileName string the file path of the source media file before it was copied to the media folder
 * @param mediaMarkdownText string the markdown text of the media file, e.g. ![my-image](file://media/505671508.jpg)
 * @return string the new markdown text of the media file
 */
function insertMediaHook(fileName, mediaMarkdownText);
}
```

**Comment by pbek** [comment] 2020-11-05 11:53
> You may want to take a look at the example example.qml.

There is an example script you can use.

**Comment by pbek** [comment] 2020-11-05 11:54
> PS: Just stop helping me if this is too annoying, I absolutely understand this :) !!!

If you are not able to get started with scripting we need more documentation! So please just keep telling me what wasn't clear.

**Comment by tragtragtrag** [comment] 2020-11-05 12:48
I finally managed to make the script working (I guess I missed a few lines from the example script)! Thank you! I don't think the documentation is bad, it's just me who has no idea about programming/scripting :)

But I realize this script only applies to media files, and it also only works when using the insert-button. So, I guess I will have to keep on using my old, very uncomfortable approach: copy the file in the explorer, paste it (the path) in md-file, shorten the path and make it relative, and finally add the file-description.
Or alternatively, copy the file in the explorer, paste it with STRG+SHIFT+V, edit the path (and delete the newly attached number-string in the file name), and from time to time clean up the non-used files in the media/attachment directory.
Both ways are not very comfortable, but I don't know any other way. Maybe with time there will be more user facing this problem and a solution can be found, I hope! But anyway: THANKS A LOT FOR THIS GREAT WORK!

**Comment by pbek** [comment] 2020-11-05 12:58
> But I realize this script only applies to media files

I could create a similar hook for `MainWindow::insertAttachment`, like in `MainWindow::insertMedia`, if that would be of any help.

> and it also only works when using the insert-button.

It should also work with drag&drop and pasting.
Can you please try again dropping an image and confirm if the hook is executed.

**Comment by pbek** [comment] 2020-11-05 14:17
I tested it myself. `insertMediaHook` is called when file is dropped into QOwnNotes.
And you will get your `insertAttachmentHook` today!

**Comment by tragtragtrag** [comment] 2020-11-05 16:09
Oh, wow! I really really do not expect you to make that effort! :) So, don't do too much work for that!!
 
I tested it again with insertMediaHook. It behaves differently depending the way how I do it:

Button: Inserting a picture with the 'inserting a picture'-button (and the option do not copy into the media folder) it works perfectly the way I want it, i.e. I get the relativ path to the picture (e.g. `![img](Test_File2/Camel2 sdf - Kopie.jpg)`).

Drag and Drop: If I do the drag and drop and pasting option then the picture is still copied to the media folder and I get the media-folder path (e.g. `![Camel2 sdf](../media/Camel2-sdf-11172544.jpeg)`).

Side note: If I use the button method but with the option 'do not copy into the media folder' deactivated then nothing happens at all.

**Comment by pbek** [comment] 2020-11-05 17:00
The copying is done before the hook in all methods where media / attachments are inserted, you can only affect the text for the markdown link that gets into the note.

> Side note: If I use the button method but with the option 'do not copy into the media folder' deactivated then nothing happens at all.

As it should 😁

**Comment by pbek** [comment] 2020-11-05 17:22
## 20.11.2
- a new scripting hook `insertAttachmentHook` was added that is executed when an attachment file is inserted into the current note
    - please take a look at the [handleNoteNameHook documentation](https://www.qownnotes.org/scripting/hooks.html#insertattachmenthook) for more information

**Comment by pbek** [comment] 2020-11-05 17:58
There now is a new release, could you please test it and report if it works for you?

**Comment by tragtragtrag** [comment] 2020-11-05 18:38
I've tried it with the new version and the new attachment script.

Unfortunately, in both cases (inserting it by the use of the button or by drag and drop) the file is always copied to the attachment file.

The other script (insertMediaHook) still only works with the button option.

Just to be sure that I used the right script (insertAttachmentHook): I made a qml-file with this code/text inside:

```
import QtQml 2.0
import QOwnNotesTypes 1.0

/**
 * This script is a generic example of some functions that will be called by QOwnNotes
 */
QtObject {
    /**
     * This is called when the script is loaded by QOwnNotes
     */
    function init() {
        script.log("Script init");
    }       
    /**
     * This function is called when an attachment file is inserted into the current note
     * If this function is defined in multiple scripts, then the first script that returns a non-empty string wins
     *
     * @param fileName string the file path of the source attachment file before it was copied to the attachment folder
     * @param markdownText string the markdown text of the attachment file, e.g. [my-file.txt](attachments/my-file-4245650967.txt)
     * @return string the new markdown text of the attachment file
     */
    function insertAttachmentHook(fileName, markdownText) {
        script.log("attachment was inserted: " + fileName);
        return "";
    }
    

}
```

**Comment by tragtragtrag** [comment] 2020-11-05 18:43
But I realized: It's possible to insert any kind of file with the 'insert picture' option. Like this e.g. a pdf will be inserted (without being copied to the 'media'-folder). The only drawback then is that in markdown it just has the 'picture'-format (with the '!'), but this is no real problem for me.

**Comment by pbek** [comment] 2020-11-05 19:17
> Unfortunately, in both cases (inserting it by the use of the button or by drag and drop) the file is always copied to the attachment file.

And that will not change in the future most likely.

> The other script (insertMediaHook) still only works with the button option.

I cannot reproduce that.
Btw. you can put multiple hooks in the same script.

> The only drawback then is that in markdown it just has the 'picture'-format (with the '!'), but this is no real problem for me.

You could write a script that reads the selected text (you select your markdown link) and transforms that text to your liking and putting the new text in your note again (overwriting the old text).

**Comment by tragtragtrag** [comment] 2020-11-06 07:19
> And that will not change in the future most likely.

So, then I don't see any reason for the use of insertAttachmentHook (I always thought that it should be good exactly that for)

> I cannot reproduce that.

Drag and Drop doesn't work, only the button option.

> You could write a script that reads the selected text (you select your markdown link) and transforms that text to your liking and putting the new text in your note again (overwriting the old text).

Thanks for the hint, but this would be definitely beyond my knowledge :)

**Comment by pbek** [comment] 2020-11-06 12:28
> > And that will not change in the future most likely.
> 
> So, then I don't see any reason for the use of insertAttachmentHook (I always thought that it should be good exactly that for)

It was meant to help you with:

```
Alternatively, if this is too complicated what about this proposal: Put all the added pictures and attachments to the attachment/media folders but (in addition to the original file-name as this is the case now) also adding the path-data of the md-file in the relevant note-folder.
```

> 
> > I cannot reproduce that.
> 
> Drag and Drop doesn't work, only the button option.
> 
> > You could write a script that reads the selected text (you select your markdown link) and transforms that text to your liking and putting the new text in your note again (overwriting the old text).
> 
> Thanks for the hint, but this would be definitely beyond my knowledge :)

just two commands. one to get the text of the selection, one to write it to the note again...

**Comment by pbek** [comment] 2020-11-06 16:53
> So, then I don't see any reason for the use of insertAttachmentHook (I always thought that it should be good exactly that for)

And there is another thing you can do... Moving the file to another location!

**Comment by tragtragtrag** [comment] 2020-11-07 04:47
> > > And that will not change in the future most likely.
> > 
> > 
> > So, then I don't see any reason for the use of insertAttachmentHook (I always thought that it should be good exactly that for)
> 
> It was meant to help you with:
> 
> ```
> Alternatively, if this is too complicated what about this proposal: Put all the added pictures and attachments to the attachment/media folders but (in addition to the original file-name as this is the case now) also adding the path-data of the md-file in the relevant note-folder.
> ```

But this doesn't work. The path will not show up in the filename when the file is inserted in the QON attachment folder.

> just two commands. one to get the text of the selection, one to write it to the note again...

I really have no idea about programming, so with my knowledge (and I'm not willing to make the effort to aquire this knowledge ;)) this is no option for me.

> And there is another thing you can do... Moving the file to another location!

The whole reason why I originally asked the question on top of this issue is that I do not want to change my structure of setup. I want to keep it as I'm used to be and as I think it's a good structure for my purpose. And I keep it even if there will be no comfortable solution in QON because I'm very much used to it. 

I think maybe there were also quite a bit of misunderstandings in this thread :) But I repeat again: I'm very thankful for you help and support, I didn't expect that!! And above all, I'm thankful for QON! Even as somebody who has no idea about scripting/programming (no idea at all!) it is very useful for my purpose. I appreciate that much!

**Comment by tragtragtrag** [comment] 2020-11-07 05:45
Just to repeat my original problem with an example (I can't get rid of the fact that we might misunderstand each other):

I have a md-file saved here: C:\Users\XXX\Notes\Work\projects.md
All pictures and attachments I do save here: C:\Users\XXX\Notes\Work\Projects

I have my attachment already saved here C:\Users\XXX\Notes\Work\Projects\attachment.pdf.

What I'm looking for is an easy way to make the link to the file attachment.pdf in my md-file.

If the file is a picture then the script insertMediaHook works: I can copy the picture in the file explorer, then in QON I can use the button 'insert picture' and I get the exact file path (and the picture correctly also is not copied to the media folder).
If the file is not a picture (any other type of file) then the script insertAttachmentHook does not work: When copying e.g. the pdf-file in the file explorer and then in QON use the option 'insert attachment' then the attachment file with the path shows up in the popup-field, but when finally clicking on OK then it just copies the file to the attachment-folder (in QON) (maybe also because other than in the 'insert picture' option, in the 'insert attachment' the option 'do not copy into the attachment folder' does not exist!) and the link in the md-file will be to the newly created file in the attachment folder.

And as mentioned earlier, when using the drag&drop option (that would be the most comfortable way to do it!) then, in both cases, i.e. picture and non-picture, QON just copies the file to the media or attachment folder as normal.

So, finally, for me only the picture option with the 'insert picture' button works, the 'insert attachment' button as well as the drag&drop option (for both pictures and non-pictures) does not work.

So, my solution for now (and I can live with that!): For pictures AND other files (non-picture/media type) use only the 'insert picture' button and the insertMediaHook (maybe insertAttachmentHook is necessary too, I haven't tested without that script). I do not use the 'insert attachment' button! By only using the 'insert picture' button, both kind of files will not be copied to the media/attachment folder and for both I get the wanted file path in the link. In the case of attachment I then just have to delete the '!' manually in front of the description text of the attachment.
And in addition, if I want the file name in the description, I just write it manually since the file name is not automatically proposed in the description (but this is another problem).

**Comment by pbek** [comment] 2020-11-07 21:24
It's hard to help you because you never filled out the issue template to see what platform you are using, but I tested linux and windows and for both the two hooks worked with dropping files into QON. And you can parse the current destination from the generated markdown, so you would be able to move the file in the hook and rewrite the markdown code for the new destination.

**Comment by pbek** [comment] 2020-11-17 17:18
I will close this issue until there is more information.

**Closed by pbek** 2020-11-17 17:18 UTC
Labels: Effort: Significant, Importance: Low, Scripting, Type: Feature
