### ISSUE TITLE
How can I rename a media attachment easily?

### ISSUE THREAD

**Issue by jg55** [pbek/QOwnNotes#2073] opened 2021-03-19 00:19 UTC
Still learning the ropes, but I can't find an answer to this -- I need to be able to easily rename a file -- for example an image file -- that I cut and paste directly into QOwnNotes. 

For example, when I copy and paste an image from a web browser right into the editor, it generates a filename for me -- such as media-mkpqWq-3633790604.jpeg -- or when I drag and drop an image from a folder into the editor, it appends a unique string to it such as "2246093183" in somefile-2246093183.jpeg. 

So I need to easily rename these files and not break anything. I can obviously do this manually, but that's very time consuming, and with hundreds or thousands of photos in the media folder, it becomes a nightmare to find things and not mess things up. 

Is there a way to easily do this? I know I can manually link to an external file in any path I want, and it preserves the filename as it should. However, dragging and dropping, and copying and pasting are very user friendly, but they create naming issues, so I need to rename the files.

I suppose this goes for attachments too! When I drag in a .WAV file, for example, it appends a 10-digit unique value as well. I need a bit more control over those filenames too.

**Comment by pbek** [comment] 2021-03-19 08:13
How would this "more control" look like that you want to have? Renaming files also means that links (one could also link to a media file) and image "tags" in other notes need to be updated (and those notes could live in other folders too, so the relative links are different).

If you want to have more control about what happens when you insert media files or attachments, there are:

- https://www.qownnotes.org/scripting/hooks.html#insertmediahook
- https://www.qownnotes.org/scripting/hooks.html#insertattachmenthook

**Comment by pbek** [comment] 2021-03-19 08:13
And there are dialogs for orphaned images and attachments to remove them or put them into the current note.

**Comment by jg55** [comment] 2021-03-19 12:28
1. First, thank you for being so responsive to user questions and feedback!
2. How would this "more control" look? TBH, whatever is the simplest, easiest, fastest way for you to make it possible to rename media/attachment assets and have any references/links to those assets be optionally renamed/relinked inside the notes, just like when you currently rename a note, QOwnNotes asks: **"A change of the note path was detected. Would you like to replace all occurrences of note://AAAA links with note://BBBB and links with filename AAAA with BBBB in X note file(s)?"** -- but this feature would work for media and attachments too.
3. The renaming option could theoretically be available in one or more of several places -- in context of the note editor, or the note preview, or a dialog box similar to the orphaned images and attachment dialogs, or maybe even a new panel to manage media/attachments like the note list panel, or perhaps even inside the note panel itself, but you'd add an option to "show media/attachments" folders? Whatever is the easiest/fastest way to implement asset renaming. The main thing is that when renaming a media or attachment asset that optionally all the references/links are updated in all the notes, just like note renaming works now. 
4. I'm *guessing* (I'm very rusty with programming, and haven't looked at the source code), that however you are currently handling note renaming could hopefully be implemented in a new "rename media and attachment" dialog or in a panel, or perhaps modeled on the orphaned images/attachment dialog, or existing note list panel, as long as there is a way to filter the list of images/attachments, since there could be thousands and thousands of images/attachments. If you implement it in the note list panel, then the search box should then filter images/attachments list below it, like it currently does for notes.
5. In fact, in the current notes list panel, you already have options to "switch to a different note folder" -- so maybe this can be adapted to add a "media" button and "attachments" button that filters right to the respective media and attachment folders, then allowing us to find/rename assets?
6. It might also be nice, but not necessary and maybe inadvisable, to be able to rename *external* media/attachments and have them updated in notes too, but that causes other issues I think, so maybe is the wrong scope for this project, and is probably not a good idea. I think just *internal* assets should be able to be renamed inside the media/attachments folders only. The core issue is that QOwnNotes is touching/creating the filenames of all dragged/dropped and copy/pasted media/attachments... and those need to be able to be renamed, especially for anyone who manages large numbers of items -- I already have 100's of images, will easily get into thousands and thousands, and it will be impossible to know what is what TBH. So I think external media/attachments should probably remain manual renames, and just focus on the internal auto-generated stuff in the media and attachments folders. Hope that makes sense.
7. Yes, very cool about the hooks for insert media files or attachment, but again that happens at the beginning when the asset is inserted, which is great, but we need a way to rename an asset after the fact down the road, weeks/months/years later, just like we need to be able to rename notes themselves down the road.
8. Repeating #1, thanks again for being so responsive to the community!
9. I'm not an active programmer anymore, so how can I help make this happen? I can see this is going to be a big one for me and will save me lots of time if we can have this feature. I think many users will benefit from having this kind of filename flexibility with assets too. I'd be happy to send a small donation to help start to make this happen, if that matters or is useful.

**Comment by pbek** [comment] 2021-03-19 12:42
The effort to make this happen certainly is high.

We would need:
- Refactoring of the orphaned images dialog to allow to also show non-orphaned images and to allow renaming them in all notes
- Refactoring of the orphaned attachment dialog to allow to also show non-orphaned attachments
- A way to allow renaming them media and attachment files in all notes in all kind of tags, taking into account the relative path from note to image/attachment file

Could you please summarize good reasons to rename files in the attachment and media folder? Most people who want to control the file names also want to control where those files are put, which is not possible with the current system.

**Comment by jg55** [comment] 2021-03-19 13:48
Instead of using the orphaned images/attachment dialogs, how about using a modified notes list panel as I mentioned? Would that help make it easier?

> Could you please summarize good reasons to rename files in the attachment and media folder? Most people who want to control the file names also want to control where those files are put, which is not possible with the current system.

Great question. I have thousands and thousands of assets (photos and attachments) that I'll be adding to my various notebooks, and they are all context-filename-keyword-tag-sensitive and can change over time for various reasons. I believe anyone who uses a lot of assets would benefit from a renaming feature. In fact, everyone will be able to benefit -- some more thoughts:

1. Currently, when you drag/drop/copy/paste images/attachments into QOwnNotes, then the app generates a unique name or it appends a unique code to the filename so there is no duplication. This is a logical and user friendly workflow (thank you!), and a perfectly decent workflow for *small* numbers of images/attachments.
2. However, if someone has a lot of media/attachments, this becomes a problem in several scenarios, especially if users also use external apps to view/edit those images/attachments. I am often editing attachments (PDF files, photos, videos, WAV files, etc.) directly from the media/attachment folders. The filenames sometimes are impossible to track, figure out and remember; they need to be renamable simply for this reason. With a larger and larger number of assets in there, it will become a huge headache if I can't rename them easily.
3. One could argue, why don't I just use external links instead of using the internal media/attachment folders? Well I do that already for many assets that are already organized and have more fixed filenames. But a) that defeats the nice and easy drag/drop/copy/paste workflow of 1.... and b) I need to change filenames quite often on some assets, so why not have a complete workflow inside QOwnNotes? We're already halfway there...
4. Consider this scenario: I am browsing a website and take a screen capture or copy an image from a page, a google map, a diagram, etc., then easily "paste" it into QOwnNotes. QOwnNotes then gives it a unique filename that is altered or cryptic. At first this is fine since I'm just "capturing" information, but later on I might want to edit the image in Photoshop or Gimp and annotate it with overlays, give it more context, then save it again. So finding that file inside the media/attachment folders outside of QOwnNotes is very difficult with hundreds or thousands of files, since the filenames are essentially randomly generated. I need to be able to rename inside QOwnNotes so I can find them easily outside of QOwnNotes.
5. Additionally, over time, the filename may need to change -- i.e. let's say I take a screen capture of google maps and annotate it in Gimp with my favorite restaurants. I want to rename the asset to something like "map210319 favorite restaurants.jpg" which is easy to find inside QOwnNotes and *outside* QOwnNotes! But then later, I edit the JPG again in Gimp and maybe change the filename in QOwnNotes to "map210319 favorite restaurants and pubs.jpg" -- the advantages should be clear -- this has big advantages inside and outside QOwnNotes, and frankly it makes the search feature in QOwnNotes effectively more powerful too due to the improved relevancy of the image/attachment filename.
6.  One of the benefits of QOwnNotes is how flexible it is and there's no proprietary file/db or vendor lock-in. So there should be no *filename* lock-in either. 
7. Since QOwnNotes is totally open and compatible with any other tool, I use other tools to browse/view/edit the media and attachment folders. I might edit these on a synced machine or mobile device that does NOT have QOwnNotes installed. Outside of QOwnNotes, the filenames in the media and attachment folders therefore lose all meaning, who knows what is what, when you have hundreds or thousands of assets!
8. Additionally, I use tags on assets -- but I put tags in the filenames so they can be searched inside and *outside* of QOwnNotes. Similar to my maps example above, these tags can change over time. For example, if I am adding photos of clients in my client database, it might change over time, such as starting out with copy/paste from an email (so then QOwnNotes gives it a random unique filename) and then I need to rename the first time to "photo210319 clientSmithJohn firmIBM.jpg" but then he moves to Apple, so I want to rename it to "photo210319 clientSmithJohn firmApple.jpg" or maybe it's a really old photo and I need to remember that, so I add the tag "old" to the filename -- and so on. I might have 5+ tags on a filename sometimes, and they change over time.
9. People who use a Zettelkasten method, for example, and include image/attachment assets inside their notebooks are likely going to be sensitive to long-term file naming and Zettelkasten IDs or GUIDs, so having the flexibility to rename all assets with those IDs is very important and useful for a whole range of research, mindmap, and knowledgebase workflows!
10. This applies to many situations where people might drag/drop/copy/paste file into QOwnNotes and need to change filenames later on. And since QOwnNotes auto-generates the filenames when you drag/drop/copy/paste, you are stuck with what it gives you unless you manually deal with it.
11. Again, these kinds of filename changes make finding/sorting/editing/tracking files super useful **inside and outside** of QOwnNotes. So it benefits every QOwnNotes user since search results will be even more relevant.
12. Of course all this can be handled manually, but it is a very slow workflow to do it that way. 

I hope that helps! Now in the past I've done this manually with other apps, or using a bulk renamer or other tools to search and replace filenames/links. It's very tedious of course and prone to mistakes. I'm hoping we can add this renaming feature to QOwnNotes and make for an even better workflow.

Thanks again for listening!

**Comment by pbek** [comment] 2021-03-19 19:24
Phew, that's far to much for me to comprehend.
So I have to go back to my initial question. Could you please **summarize** good reasons to rename files in the attachment and media folder (and not being able to put them into other folders)?

**Comment by jg55** [comment] 2021-03-19 20:33
Haha! Yes, that was a bit long. Okay, a summary would be:

Good reasons to rename files in the attachment and media folder (and not being able to put them into other folders) include:

1. Significantly improve the overall drag/drop/copy/paste images/attachments workflow for all users who use media/attachments, especially when there are a lot of files in the media/attachments folders.
2. Using external folders defeats the existing advantages of the smooth drag/drop/copy/paste workflow.
3. When there are many files in the media/attachment folders, and you can't rename the files, they are easy to lose context when using *external* programs, especially when syncing to other devices, which may not have QOwnNotes to provide context (i.e. mobile devices too)!
4. Renaming media/attachments with optional auto-link-renaming inside the notes potentially improves all user experiences, improves organization, improves speed compared to manually renaming, and improves contextual search results inside QOwnNotes since the filenames themselves can be changed to be much more specific and context-tag-keyword oriented! 
5. One of the mantras of QOwnNotes is how flexible it is and there's no proprietary lock-in. So there should be no *filename* lock-in either.
6. Allows for various workflows where tagging and using GUIDs in the media/attachment filenames such as with many Zettelkasten, research, mindmap, and knowledgebase workflows where changing GUIDs or filename tags are very useful *inside* QOwnNotes with optional auto-updates of internal links. 
7. Because it's cool, it makes sense, and improves drag/drop/copy/paste media/attachments for all, and brings joy and happiness to the world.

Still long, but at least it's a little easier to read! 😄

**Comment by pbek** [comment] 2021-03-19 20:42
Thank you, but I am still not sure that being able to easily rename media files in the media folder will satisfy those who want to customize the place where the files are put... I wouldn't want to spend a large amount of time to satisfy only one user (you). 😄

**Comment by jg55** [comment] 2021-03-19 21:40
> will satisfy those who want to customize the place where the files are put...

If this is the larger question, then ideally, yes, the feature would allow for creation and management of custom folders inside the notes folder too, all managed by QOwnNotes. 

And to that I say, **absolutely awesome**. That would take my suggestion to the next level, and yes, that would indeed be even better. Way better. Fantastic. You will make a lot more people happy, and if you go for it, I'll be more than happy to send a humble donation to help kick off your programming sprint.

**Comment by pbek** [comment] 2021-03-21 10:02
First batch of work...

## 21.3.3
- if you now insert an image or attachment directly from a file the original
  file name will be used if the file doesn't exist in the media/attachments
  folder (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - previously a random string was added to the basename to make it unique
    - if the file already exists a number will be added to the basename of the
      file (like `my-image-1.jpg`) and increased until a filename is available
- instead of the *Orphaned images dialog* there now is the new *Stored images dialog*
  which also allows managing non-orphaned images (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - you are now also able to search for images by name
    - the file size of the images will now also be shown in the tooltip of the file list
    - if notes are using the current image a list of those notes will be shown

**Comment by pbek** [comment] 2021-03-21 10:10
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-21 11:59
Thank you! Yes, testing today asap and will report back!

**Comment by jg55** [comment] 2021-03-21 13:05
Just ran some tests on Windows (don't have access to my Linux machines right now):
1. Tested on about 150 images so far. I assume this will handle thousands and thousands of images, but want to check if you have imposed any limits on it?
2. Confirmed new features work as intended (I love the "Used in notes" box inside the Stored images dialog!)
3. Minor issue: Tested .jpg, .jpeg, .gif, .png files. All are added and incremented as expected, except .jpeg images are added as attachments instead of images. However, .jpeg should be considered an image.
4. How possible would it be to add a "refresh" or "rescan" button to the Stored images dialog since if it stays open, it does not auto refresh, and any further edits to notes files do not update inside the dialog until I close and re-open the dialog?
5. How possible would it be to add a double-click feature to the "Used in notes" box to open the respective note?
6. Thank you! I can see where you are going with this, and I think once we can manage the filenames themselves, this will be a great solution. Expect a humble thank you donation shortly. Hopefully the first of several in the months to come! I really appreciate the great work!

**Comment by jg55** [comment] 2021-03-21 13:55
Quick additional observation:
7. Image filenames are truncated to 32 characters -- most common filesystems allow up to 255 (EXT4, BTRFS, exFAT, APFS, HFS Plus, NTFS, etc.). Can you please extend this length? If you need to set a hard limit, please set it to at least 240 characters which will cover most situations and still add room for added numbers+extension. In theory, truncating should only happen when/if a number needs to be added in the sequence to make it unique.

**Example:** 

Original 81-character filename is **"Long filename test to see how long of a filename will be allowed in QOwnNotes.png"** but is truncated to **"Long filename test to see how lo.png"**:

![Long filename test to see how long of a filename will be allowed in QOwnNotes](media/Long filename test to see how lo.png)
![Long filename test to see how long of a filename will be allowed in QOwnNotes](media/Long filename test to see how lo-1.png)

**Comment by siran** [comment] 2021-03-21 16:26
>     2\. Confirmed new features work as intended (I love the "Used in notes" box inside the Stored images dialog!)

This might be an independent feature request. But in the "Used in notes" feature it is so cool you want to double click on a note to open it and automatically close the "Stored images" dialog.

**Comment by pbek** [comment] 2021-03-21 18:22
Thank you for testing.

3) An image is only what Qt can detect as an image.
4) Yes, can add a button. Currently you could click the checkbox twice.
5) Makes sense
6) Haha, thank you very much! Not humble at all. 😁 
7) I want to prevent spamming of long image-filenames e.g. when importing webpages. I'm not sure how great it would be to have 240 character (plus iterator and file extension) filenames in the note markdown... Pre-Previously we only had auto-generated 8 character basename to keep imagenames short in notes.

> But in the "Used in notes" feature it is so cool you want to double click on a note to open it and automatically close the "Stored images" dialog.

Can be a bit tricky with sub-folders and so on, but I had such a thing in mind, but without closing the dialog. Is there something a user could do in the dialog after the note is opened in the background?

**Comment by jg55** [comment] 2021-03-21 19:33
Thank you @pbek!

3. Perhaps something changed in the detection since I have .jpeg files in my media folder from a prior version, I think 21.2.5 handled .jpeg files differently. Or what do you think might have changed? In any case, the behavior is different now than before when it comes to drag/drop/copy/paste of .jpeg files. The others (.gif, .jpg, .png) go into the correct folder as before. If needed, I can experiment to try to find a reproducible example for you between the two versions if that helps.
4.  Awesome
5. 👍 However you want to do this. As long as there's some way to open a note from the "Used in notes" box that would be great. It gives the full round-trip workflow of searching for information in either context of the note OR the image, and you can get to the note you want. Very powerful feature.
6. 😁
7. Understand your reasons, but maybe this can be user-defined setting in the preferences? In any case, 32 char baseName is definitely too short! My filenames are often 80-100 chars when it comes to my knowledgebase. I put tags and IDs in the filenames so they are application agnostic.

**Comment by siran** [comment] 2021-03-22 01:41
> > But in the "Used in notes" feature it is so cool you want to double click on a note to open it and automatically close the "Stored images" dialog.
> 
> Can be a bit tricky with sub-folders and so on, but I had such a thing in mind, but without closing the dialog. Is there something a user could do in the dialog after the note is opened in the background?

You are right, @pbek, better not to close the dialog. A user might want to open a couple of notes from there...
Maybe a right-click->[Open, Open in tab] ?

**Comment by jg55** [comment] 2021-03-22 01:48
> Maybe a right-click->[Open, Open in tab] ?

I like this +1 👍

**Comment by pbek** [comment] 2021-03-22 08:43
>  I think 21.2.5 handled .jpeg files differently. Or what do you think might have changed?

Nothing changed there for ages and I didn't have any issues dropping a "jpeg" file into QON. Can you share that file?

**Comment by jg55** [comment] 2021-03-22 13:42
> Nothing changed there for ages and I didn't have any issues dropping a "jpeg" file into QON. Can you share that file?

Attached. BTW, I just tested this in 21.2.5 and 21.3.3 and the behavior is the same! On further experimentation, when I drag and drop this .jpeg from the desktop into QOwnNotes, it gets copied into the attachments folder. But for some reason, when I originally copied and pasted it from the web, it was originally put into the media folder correctly! Strange. What's even more strange is that when I RENAME the file to a .jpg extension, then drag and drop, it gets put into the media folder. I've attached both files. Unzip and then drag and drop and see what happens. They are identical files.

Anyway, I am not worried about this mystery. It's very minor, and seems like it can be solved by renaming the file from .jpeg to .jpg. I've been reading up on Qt and finding a variety of interesting minor issues with image handling, so it's not likely something in your code. Honestly, for now I don't know if it merits much more attention, I think it's a rabbit hole of Qt, separate from this thread from what I can tell as I read up on Qt image issues out of curiosity.

BTW, I found a lag issue in the editor with QOwnNotes related to another Qt issue -- **"[warning] fromIccProfile: failed minimal tag size sanity"** -- which I'll post about in another thread when I get a chance. Another issue with Qt apparently that is throwing a warning that then causes QOwnNotes to briefly pause as it re-renders the preview panel. It's a colorspace issue if what I've read is correct. More in another thread when I get a chance. Didn't want to take this thread off topic!

[media-goes-to-attachment.zip](https://github.com/pbek/QOwnNotes/files/6182537/media-goes-to-attachment.zip)
[media-goes-to-attachment-renamed-to-JPG.zip](https://github.com/pbek/QOwnNotes/files/6182552/media-goes-to-attachment-renamed-to-JPG.zip)

**Comment by pbek** [comment] 2021-03-22 17:40
I can confirm `media-goes-to-attachment.jpeg` goes into attachments. I've no clue why. You can open a new issue, but I can't promise anything. 😀

**Comment by pbek** [comment] 2021-03-22 17:51
## 21.3.4
- the filename-clipping of the basename of inserted images was increased to
  200 characters (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
- more improvements to the new *Stored images dialog* have been made
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - there now is a *Refresh* button to reload the image file list
    - you can now also double-click on an item in the image list to insert it
      into the current note
    - you can now double-click on an item in the note list to open the note
    - a context menu was added for the image file list
    - you are now able to rename image files with the context menu or by pressing <kbd>F2</kbd>

**Comment by pbek** [comment] 2021-03-22 17:57
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-22 17:59
Excellent, thank you! Testing shortly! 😁

**Comment by siran** [comment] 2021-03-22 19:21
It's working fine for me!

Some comments:
- When double clicking on a note I think each different note should open in a different tab, currently all notes open in the same active tab and replace the current note being edited.
- For example, if the user is editing a certain note in a tab and decides to use the `stored images` dialog and then double-clicks on a note in the `used in notes` list, then the current note is replaced. This might be intended or not. So, I still favor a context menu to allow either Open in current tab or Open in new tab. Then it would be fine if double-click always opens the note in current tab (since if user wants a new tab he could right-click->Open in new tab).
- Also, when testing the feature I noticed that I had a duplicate note (both notes were referencing the same image). So I decided to delete one of the duplicates. It would be great if the context menu has the Delete note and even a Duplicate this note options as well. However, when I double-clicked the note to open it and then delete it the note list didn't refresh automatically and then I noticed there is a rerfesh button. Auto-refresh in this case would feel magical.

These comments are not by any means crucial. Just would-likes that if you agree could be implemented in the future.

**Comment by jg55** [comment] 2021-03-22 19:38
Just tested, great features! Everything works as expected, some quick observations/questions:

1. When you rename an item it does not yet give you a dialog to confirm: **Would you like to replace all occurrences of AAAA with BBBB in X documents?**  I assume this is coming soon, but so far so good!
2. Curious what the default sort order is in the stored images list? It's alphabetical when I do a search, but without a search term, it's a little mysterious what sort order is going on. I've got 200+ images in my test notebook, sorry if I am missing something obvious! 
3. Is the plan to finish this stored images dialog and then apply the same concept to a stored attachments dialog?
4. Re: @siran's comments, I agree that double-clicking a note should open in a different tab if possible. Happy with his context menu current tab/new tab idea too. Either way... but at least the default double click would be better as a new tab IMO.
5. Re: @siran's suggestion of auto-refresh, I'm torn, I kind of like it with manual refresh, but I can see his point.

**Comment by pbek** [comment] 2021-03-23 08:10
> Also, when testing the feature I noticed that I had a duplicate note (both notes were referencing the same image). So I decided to delete one of the duplicates. It would be great if the context menu has the Delete note and even a Duplicate this note options as well. However, when I double-clicked the note to open it and then delete it the note list didn't refresh automatically and then I noticed there is a rerfesh button. Auto-refresh in this case would feel magical.

Note manipulation is far out of scope for this dialog and would introduce lots of troubles.

**Comment by pbek** [comment] 2021-03-23 16:28
> Is the plan to finish this stored images dialog and then apply the same concept to a stored attachments dialog?

Yes

**Comment by pbek** [comment] 2021-03-23 17:22
## 21.3.5
- more improvements to the new *Stored images dialog* have been made
    - you are now able to to decide to also update the image file names in
      all notes after renaming an image
    - the image file list is now sorted alphabetically
    - there now is an informative tooltip for each note in the note list
    - when double-clicking on an item in the note list the note will now be
      opened in a new tab
    - various issues with duplicate notes and refreshing were fixed

**Comment by pbek** [comment] 2021-03-23 17:24
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-23 22:38
> There now is a new release, could you please test it and report if it works for you?

It works! Fantastic! Love it! Thank you! Great features!

**Comment by pbek** [comment] 2021-03-26 11:12
## 21.3.6
- more improvements to the new *Stored images dialog* have been made
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - there now is a context menu in the note list
    - fixed a typo in the file list context menu
    - small margin adaptions were made in the UI
- instead of the *Orphaned attachments dialog* there now is the new
  *Stored attachments dialog* which also allows managing non-orphaned attachments
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - you are now also able to search for attachments by name
    - you are now able to rename attachment files with the context menu or by
      pressing <kbd>F2</kbd>
    - there now is a context menu for the attachment file list
    - the file size of the attachments will now also be shown in the tooltip of
      the file list
    - you can now also double-click on an item in the attachment list to insert
      it into the current note
    - there now is a *Refresh* button to reload the attachment file list
    - the filepath of the attachment file is now truncated if there is not enough
      space in the dialog, but you are still able to select and copy the full path
    - if notes are using the current attachment a list of those notes will be shown
    - you can double-click on an item in the note list or use the context menu
      to open the note in a new tab
- the new *Stored images dialog* and *Stored attachments dialog* were moved one
  level up in the *Edit menu* because of their added functionality
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))

**Comment by pbek** [comment] 2021-03-26 11:13
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-26 13:09
Excellent! Could only test it briefly (have to deal with client meetings today), but so far it works great! Thank you so much for working on this and delivering such a great set of new useful features! 😁 Glad you moved up the the menu items one level too!

BTW I really love the **Open attachment** and **Open folder** buttons in the **stored attachments** dialog. This really enhances the workflow, thank you! Can you please add these buttons to the **stored images** dialog too? That way we can configure something like Photoshop or Gimp as default editors, for example, and edit the images right from the dialog!

Super minor text inconsistency: Also noticed that the button text in **stored attachments** is "+ Add to note", but the same button text in **stored images** is "+ Add to current note". 

Thanks again, QON is fantastic!

**Comment by pbek** [comment] 2021-03-27 09:52
>  I really love the Open attachment and Open folder buttons in the stored attachments dialog. This really enhances the workflow, thank you! Can you please add these buttons to the stored images dialog too?


I can do that.

> That way we can configure something like Photoshop or Gimp as default editors, for example, and edit the images right from the dialog!

Your settings in the operating system is deciding what to open.

> Super minor text inconsistency: Also noticed that the button text in stored attachments is "+ Add to note", but the same button text in stored images is "+ Add to current note".

Thank you for mentioning.

**Comment by pbek** [comment] 2021-03-27 10:11
## 21.3.7
- some button text in more new *Stored attachments dialog* was updated to match
  the text in the *Stored images dialog* (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
- more improvements to the new *Stored images dialog* have been made
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - there now is an *Open image* button to open the current image externally
    - there now is an *Open folder* button to open the folder of the current image

**Comment by pbek** [comment] 2021-03-27 10:13
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-27 13:13
Tested on Windows and it seems to work great! 🎉 (Will test on Linux later!) Thank you @pbek for working on this, it's a fantastic workflow boost! Now I just have to decide what shortcut keys to bind to the two new dialogs... decisions decisions.

Couple of thoughts/questions:

1. Minor inconsistency: **Stored attachments** has both right-click context "open attachment" AND "open attachment" button. **Stored images** only has the button. Not a big deal at all, but in case you wanted them to have identical behavior.
2. I'm wondering what (if any) your plans are regarding renaming or fully controlling the folders where the images and attachments are located? Right now with 21.3.7 you've accomplished what I was hoping for (and more!), but you seemed to imply earlier in this thread (or at least ask a question about it) that you might add full control over image/attachment folders. I'm very excited about 21.3.7, but if you decide to add folder renaming too at some point in the future, that would obviously be the **next level**.
3. One more thought about image/attachment folders -- Not complaining about the way you have the two folders named, however, keep in mind that the images folder is currently named "media" but the word "media" also implies any other kind of media, such as WAV, MP3, MP4, etc., etc.. I work in media so I have tons of audio and video attachments in my notes. Currently, all those other kinds of media files get put into the **attachments** folder. Again, not complaining, I'm already used to this, but the "media" folder is more accurately purely an "images" folder, and even the dialog to manage them is called "Stored **images**". For future consideration, being able to rename at least that folder ("media" -> "images") might be logical.
4. Thank you again for your great work, this feature really stands out and gives a lot of extra flexibility to QON! Expect another donation of thanks next month! 😁

**Comment by siran** [comment] 2021-03-27 20:32
My two cents: I don't know why is there a difference between images (media)
and attachments. Like an email, they are all attachments to the note.
Probably the attachments could be later filtered by "type".

**Comment by jg55** [comment] 2021-03-27 22:23
> My two cents: I don't know why is there a difference between images (media) and attachments.

I think the separation of images from other types of media and attachments currently makes sense due to the way that the preview panel works by only displaying the images, and all the other kinds of attachments are links only, and/or other kinds of media do not currently display or do not have native players available in the preview panel. But I think you bring up a great point.

Eventually I think it would probably make sense to merge the stored images dialog and stored attachments dialog into one super dialog that covers everything, including creating/renaming any media/attachment folders. So in that sense I agree with you that an attachment is an attachment, no matter what filetype. But for now images are different than other kinds of attachments.

However, ideally at some future time, it would also be great for QON to have embedded players/viewers for audio, video, PDF, etc... but again hopefully in the nearer future we'll have total control over all the folders where any media/attachments can go.

Joplin, for example, currently has embedded viewers in their preview panel that cover various filetypes like video, audio, PDF, and of course images too. Joplin's preview is pretty well done in that regard. But for now, QON only displays images in the preview panel, which is fine IMO. 

What's more important (again IMO) is that you can actually easily rename (and find and replace and display orphans, etc.) media/attachments, which QON can now do really well (yay!), but surprisingly, Joplin can't yet rename media/attachments at all... and in fact Joplin uses a cryptic GUID for their imported attachments making it _very_ hard to deal with attachments compared to QON... so QON now really shines in this regard. 

It's all a matter of priorities of course, who knows what the next round of features will bring either app. Just very happy that QON now has renaming.

**Comment by pbek** [comment] 2021-03-29 06:31
> 2. I'm wondering what (if any) your plans are regarding renaming or fully controlling the folders where the images and attachments are located?

I looked through the code... It would be very painful and possibly introduce lots of regressions... Especially all those special handling with renaming things in the background and portable mode. So currently no plans.

> 3. One more thought about image/attachment folders 

There is no handling for videos in markdown nor is there any in QON. So those files can only be linked to and thus currently only are attachments...

> My two cents: I don't know why is there a difference between images (media)
and attachments.

Currently not much of a difference any more (beside how they are used in notes, need to be moved when notes are moved or files are renamed, shown in dialogs, ...) But bringing them together would mean a huge amount of work and regressions (and also migration work for users).

**Comment by pbek** [comment] 2021-03-29 06:33
> 1. Minor inconsistency: Stored attachments has both right-click context "open attachment" AND "open attachment" button. Stored images only has the button. Not a big deal at all, but in case you wanted them to have identical behavior.

Thank you for mentioning!

**Comment by pbek** [comment] 2021-03-29 16:55
## 21.3.8
- a leading html comment block in a note will now be ignored in the automatic note
  filename generation (for [#2084](https://github.com/pbek/QOwnNotes/issues/2084))
- more improvements to the new *Stored images dialog* have been made
  (for [#2073](https://github.com/pbek/QOwnNotes/issues/2073))
    - added a an *Open image* context menu entry
    - added some tooltip texts

**Comment by pbek** [comment] 2021-03-29 16:58
There now is a new release, could you please test it and report if it works for you?

**Comment by jg55** [comment] 2021-03-29 18:09
Just tested 21.3.8 and found a crash in both stored images dialog and stored attachments dialog when adding multiple images or attachments to a note. Adding one note is fine, but adding multiple causes QON to go poof. I went back to 21.3.7 and 21.3.6 and they also crash, sorry I missed that in my testing! 😬 I also went back to 21.3.5 when stored images dialog was still part of the Extra menu, and adding multiple images worked fine.

**Comment by jg55** [comment] 2021-03-29 18:19
On further testing, when I add 1 image from the dialog, it works fine as I mentioned before. But when I add 2 or more images, it may or may not crash, depending on prior actions and what images are already in the note (from what I can tell), but the best I get is:

![qownnotes-media-bvdGqr](media/qownnotes-media-bvdGqr.png)
![](media/)

But then, if I do the exact same action of adding the same two images again, it will crash. So it's as if it crashes when the filename (or part of the filename) is duplicated and/or already exists in the note. Not sure about the pattern of crashing, though, it's not entire clear yet. 

Hopefully that's a little clue to help find the culprit.

**Comment by pbek** [comment] 2021-03-30 05:34
I can't reproduce that.
Can you please describe step by step what you did do get a crash.

**Comment by pbek** [comment] 2021-03-30 05:36
Can you please post the output from the debug settings (see issue template).
And can you please turn on logging into a file in the *Debug options* in the *Settings dialog*.
Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`) if you enable the log panel (see Window / Panels).

**Comment by pbek** [comment] 2021-03-30 05:38
Best open a new issue with it. This went on far too long already. 😁

**Closed by pbek** 2021-03-30 05:38 UTC
Labels: Effort: High, Importance: Low, Type: Feature
