### ISSUE TITLE
QOwnNotes crashes when text is pasted in a a certain point and continues to crash on startup

### ISSUE THREAD

**Issue by Amourspirit** [pbek/QOwnNotes#471] opened 2017-01-09 04:29 UTC
Seems like a strange bug. 
When my note is [this ](http://pastebin.com/vCk15vKk) everything is fine. however when I ammend the end of the file to look like [this](http://pastebin.com/YSkQDRLb) See Example 10 at the end of the files.

The only difference between the two files is this text pasted near the end

> **Example 10:**
>```
>	varA := 0.0000000000003
>	varA += 0.0000000000003
>	wasformat := A_FormatFloat
>	fmt := "0.15"
>	SetFormat, FloatFast, %fmt%
>	MsgBox %varA% ; 0.000000000000600
>	SetFormat, FloatFast, %wasformat%
>```

When I pasted in the text QOwnNotes crashes. When I try and reopen QOwnNotes with the text still there it crashes again and will not allow me to open QOwnNotes until the text is removed.

I am using QOwnNotes 17.01.3 portable on windows 10 x64.
This is the first time I have had this error in QownNotes.

**Comment by pbek** [comment] 2017-01-09 05:45
Thank you for reporting. I can't reproduce that under macOS, I will try Windows later.
Can you please post the output from the debug settings.

**Comment by pbek** [comment] 2017-01-09 17:18
I can only reproduce it under Windows, Linux works as well.
Unfortunately I couldn't make the QtCreator debugger work under Windows, I tried to get it working for an hour now, it just gets stuck at various places (even without the prepared note)... :(

Do you have a QtCreator installed by chance?

**Comment by pbek** [comment] 2017-01-09 17:21
same problem as #461

**Comment by philiptruax** [comment] 2017-01-09 17:21
I've got a similar reproducible bug on Windows. I'm pasting in content from a github page. If I paste in as html directly the issue does not happen. If I paste as text the program will not open. Clearing the text file resolves the issue. I also get a warning regarding ANSI characters when attempting to post in plain markdown directly into the text file from outside QOwnNotes. 

The debug log does not have an information regarding the crash written to it. I tested by having the log opened while I repeated the crash.

I'm on Win 7 x64.

I'll see if I can get QT Creator installed on my box and update.

**Comment by pbek** [comment] 2017-01-09 17:23
Thank you @philiptruax!

**Comment by philiptruax** [comment] 2017-01-09 18:23
Sorry took me a bit to figure out how to get it working properly. I'm not a developer by trade, though I've dabbled a bit. So when pasting the text in while running with the debugger attached I get the error message 
`The inferior stopped because it received a signal from the operating system`
`Signal Name: SIGSEGV`
`Signal Meaning: Segmentation Fault`

At which point QT Creator itself crashed.

**Comment by philiptruax** [comment] 2017-01-09 18:37
I believe I got the debug log you're looking for. Let me know if it is or isn't and I can adjust from there. 
[dis2.txt](https://github.com/pbek/QOwnNotes/files/694355/dis2.txt)

**Comment by pbek** [comment] 2017-01-09 19:08
Thank you for your effort, but assembler commands are not very suitable to debug a Qt application. :)

> At which point QT Creator itself crashed.

wow!

**Comment by philiptruax** [comment] 2017-01-09 19:12
I'm more than open to doing something different if you can tell me specifically what will be useful.

**Comment by pbek** [comment] 2017-01-09 19:17
Does your Qt Creator still crash when the QON crash occurs? Ideally we would have a stack trace where we can see which commands were called last. I almost fear it could be some weird Qt bug...

**Comment by philiptruax** [comment] 2017-01-09 19:18
Yes it crashes every time. I'll see if I can get a stack trace for you.

**Comment by pbek** [comment] 2017-01-09 19:18
Thanks a lot!

**Comment by philiptruax** [comment] 2017-01-10 02:47
I think I've got something useful now. i.e. Not machine language. I've got the output of some of the backtraces. These two are the last two before QON crashes. I've actually gotten QTCreator stable now when debugging by being gentle. 
[backtrace4.txt](https://github.com/pbek/QOwnNotes/files/695125/backtrace4.txt)
[backtrace5.txt](https://github.com/pbek/QOwnNotes/files/695126/backtrace5.txt)

The software appears to break on a call to ZN16QEventTransition11qt_metacallEN11QMetaObject4CallEiPPv if I'm reading this right when trying to access Qt5Core.dll

If I can add a little bit more information, it look as though everything renders to a specific point in the text and once it reaches that point is where it crashes. 

I've also got some better information from Windows. 

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	QOwnNotes.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5871faba
  Fault Module Name:	Qt5Core.dll
  Fault Module Version:	5.7.1.0
  Fault Module Timestamp:	583ffb95
  Exception Code:	c00000fd
  Exception Offset:	0021c2de
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	45d5
  Additional Information 2:	45d509d9d5056c5082a5120d16d1c8c9
  Additional Information 3:	3caa
  Additional Information 4:	3caa9f0048dd0f5b0cafcdf33c9b1035

```

Let me know if I'm completely giving you useless info. There's nothing I can get from the QML Stack. Nothing appears in Local and Expressions.

**Comment by pbek** [comment] 2017-01-10 04:23
Thank you for your crash reports! Unfortunately they only consist of windows system calls and once or twice a call to the QtCore library, no actual QON calls... :( 

I'll try to test the following:

- test in a plain QTextEdit
- test in a plain QMarkdownTextEdit
- test in QON without markdown highlighting
- test in QON without preview html code generation

**Comment by pbek** [comment] 2017-01-10 06:44
The regular expression

```
QRegularExpressionMatchIterator i =
            QRegularExpression("<(((?!\\w+:\\/\\/)[^<>])+)>").globalMatch(str);
```

is crashing under Windows if there is a `<` with enough text after it.

**Comment by pbek** [comment] 2017-01-10 07:20
and I think the solution is using `<(((?!\\w+:\\/\\/)[^<>\n])+)>` as regular expression (added an `\n`)

**Comment by pbek** [comment] 2017-01-10 16:38
## 17.01.4
- fixed a crash under Windows when entering an opening `<` with a lot of text
  after it, but no closing `>`

**Comment by pbek** [comment] 2017-01-10 17:56
There now is a new release, could you please test it now works for you?

**Comment by philiptruax** [comment] 2017-01-10 21:38
I can confirm that the issue is no longer present. You will still need to clear or move the file initially to update through the application. Once updated the file can be placed back in or pasted back in through the application.

**Comment by pbek** [comment] 2017-01-11 05:46
Great, thank you for testing!

**Closed by pbek** 2017-01-11 05:46 UTC
Labels: duplicate
