### ISSUE TITLE
QOwnNotes resets all settings when notes folder is unavailable

### ISSUE THREAD

**Issue by toxpal** [pbek/QOwnNotes#1140] opened 2019-02-03 12:26 UTC
Using QOwnNotes on antergos KDE for some time, and noticed that every single time QOwnNotes resets all settings to default when notes folder is unavailable. I really mean all - theme, toolbars, layout, every single option is reset.

I run antergos on SSD, and store notes on Luks RAID (2 x HDD in mirror mode, encrypted with Luks and auto-mounted during boot). Sometimes, after system update (like 1 out of 50 times), antergos fails to automount encrypted RAID during first boot. If I launch QOwnNotes then, it displays default startup window, and all settings are lost.

I then reboot OS, try to run QOwnNotes again, but default startup window is still here, and it doesn't allow me to start using app unless I choose default folder for notes, specify theme, etc. In other words, I must do everything from scratch.

I did some tests and noticed the same happens if I manually delete/rename default notes folder and run QOwnNotes then - all settings are reset again. Restoring original folder doesn't help - I still need to go through default startup wizard. It really drives me crazy...

I found a similar issue here - https://github.com/pbek/QOwnNotes/issues/370 - but it's not exactly the same.

`QOwnNotes Debug Information
===========================

## General Info

**Version**: `19.2.0`
**Build date**: `Feb  1 2019`
**Build number**: `517`
**Platform**: `linux`
**Operating System**: `Antergos Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.12.0`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/home/myusername/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/myusername/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `3`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `0`

### Note folder `QOwnNotes`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `-2`
**localPath**: `/mnt/data/Archives/QOwnNotes`
**remotePath**: `QOwnNotes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/mnt/data/Archives/QOwnNotes/notes.sqlite`

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**LastUpdateCheck** (QDateTime): `2019-02-03T14:12:09.764`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**NoteHistory-0** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-0** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**appMetrics/notificationShown** (QString): `true`
**cryptoKey** (QString): `<hidden>`
**currentWorkspace** (QString): `initial`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (QString): `24`
**noteEditIsCentralWidget** (QString): `true`
**notesPath** (QString): `/mnt/data/Archives/QOwnNotes`
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**showMenuBar** (bool): `true`
**showNoteSubFolders** (QString): `true`
**showStatusBar** (bool): `true`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QString): `initial`

## System environment

**SHELL**: `/bin/bash`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**LANGUAGE**: `en_US`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**LC_MONETARY**: `lt_LT.UTF-8`
**XCURSOR_SIZE**: `0`
**EDITOR**: `/usr/bin/nano`
**GTK_MODULES**: `canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/myusername`
**LOGNAME**: `myusername`
**XDG_SESSION_DESKTOP**: `KDE`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/myusername/.Xauthority`
**LD_PRELOAD**: `/usr/${LIB}/libgtk3-nocsd.so.0`
**HOME**: `/home/myusername`
**LANG**: `en_US.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**GTK_CSD**: `0`
**KDE_SESSION_UID**: `1000`
**XDG_SESSION_CLASS**: `user`
**USER**: `myusername`
**KDE_SESSION_VERSION**: `5`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**DISPLAY**: `:0`
**SHLVL**: `1`
**LC_MEASUREMENT**: `lt_LT.UTF-8`
**XDG_VTNR**: `1`
**XDG_SESSION_ID**: `1`
**GS_LIB**: `/home/myusername/.fonts`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `lt_LT.UTF-8`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**LC_COLLATE**: `lt_LT.UTF-8`
**XCURSOR_THEME**: `Breeze_Snow`
**XDG_DATA_DIRS**: `/usr/share:/usr/share:/usr/local/share`
**KDE_FULL_SESSION**: `true`
**BROWSER**: `/usr/bin/chromium`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/myusername`
**COGL_ATLAS_DEFAULT_BLIT_MODE**: `framebuffer`
**LC_NUMERIC**: `lt_LT.UTF-8`
**_**: `/usr/bin/kwrapper5`
**SESSION_MANAGER**: `local/desktop:@/tmp/.ICE-unix/989,unix/desktop:/tmp/.ICE-unix/989`
`

**Comment by pbek** [comment] 2019-02-03 20:03
Thank you for your finding. It sounds correct, because QOwnNotes needs its note folder. I guess not being able to access it will trigger the welcome dialog that sets some settings. What in your eyes would be the right thing to do?

**Comment by pbek** [comment] 2019-02-03 20:05
Also interesting is that you don't have a current note folder set in `currentNoteFolderId`...

**Comment by toxpal** [comment] 2019-02-04 07:48
Hm, all the note/password/todo apps I ever used, worked this way: if folder/file is not accessible, app offers to create new one (or open some other) folder/file. Just like QOwnNotes does. The only difference is that they did not reset software settings, so once user creates/opens some file, software settings are the same, and user doesn't need to re-configure every single option again.

Is there some reason why QOwnNotes destroy every single user-defined option?

**Comment by pbek** [comment] 2019-02-04 07:55
> Is there some reason why QOwnNotes destroy every single user-defined option?

I guess not being able to access the note folder will trigger the welcome dialog that sets some settings. This issue was never reported yet. I'll investigate that.

**Comment by toxpal** [comment] 2019-02-04 08:01
Yes, my guess was the same. I realize it's perfectly normal QOwnNotes offers to set a new folder for notes in this situation, but I just don't think it should reset user-defined GUI settings too.

And thank you for your fast and prompt reply.

**Comment by pbek** [comment] 2019-02-07 07:15
@liulex, It could be that QOwnNotes resets some or all settings when the note folder is unavailable, this also seem to occur in the portable mode the first time QOwnNotes is started, do you want something to chew on? :smile:

**Comment by liulex** [comment] 2019-02-08 10:10
I think it's not clear what "some or all settings when the note folder is unavailable" means, since I don't see all settings are gone. If only **some** of the settings get wrong, maybe pointing out which settings would help to clarify the problem. @toxpal 

@pbek  As for me, the weird thing is that the welcome dialog does not set the note folder correctly. Steps to reproduce:
1. Fresh new install QON and launch it in portable mode.
2. In the welcome dialog, set the note folder to `Notes` and finish the welcome dialog.
3. Quit QON.
4. Rename folder `Notes` to `Notes_` manually.
5. Launch QON in portable mode.
6. The welcome dialog shows up as expected.
7. Specify `Notes_` to be the note folder and finish the welcome dialog.
8. Error:
![default](https://user-images.githubusercontent.com/2010459/52471279-7b63bc00-2bcb-11e9-9e09-bc1e420d76fc.png)

---

**After step 7, we expect all the settings and notes becomes exactly the same as in step 3.** However, we get an error dialog instead. After skipping the error dialog, open the settings, we can see that the note folder is still `Notes`:
![default](https://user-images.githubusercontent.com/2010459/52471510-080e7a00-2bcc-11e9-8ce6-864a0120a425.png)
... which means the setup in step 7 fails to work as expected.

**Comment by pbek** [comment] 2019-02-08 10:13
> the weird thing is that the welcome dialog does not set the note folder correctly

I already suspected such a thing

**Comment by toxpal** [comment] 2019-02-08 10:51
> If only **some** of the settings get wrong, maybe pointing out which settings would help to clarify the problem

@liulex - in my situation, QOwnNotes looses all the custom settings which I define in Note > Settings menu. To be more specific, I loose these settings every time notes folder is unavailable:

Interface > Enable dark mode
Interface > Enable dark mode icon
Interface > Show system tray icon
Interface > Interface style (selected theme)
Interface > Editor > Editor Fonts & Colors (all settings)
Interface > Editor > Panels (all settings)
Interface > Editor >Toolbars (all settings)
General (all settings)

In addition, I loose layout of all toolbars/buttons/panels, whole GUI is reverted back to default.

**Comment by liulex** [comment] 2019-02-08 12:14
@toxpal Thanks for the info. I tried the following steps:
1. Fresh new install QON and launch it in portable mode.
2. In the welcome dialog, set the note folder to `Notes` and finish the welcome dialog.
3. **Enable dark mode and dark mode icon in the settings.**
4. Quit QON.
4. Remove `Notes` folder.
5. Launch QON in portable mode.
6. Follow instructions in the welcome dialog and finish it.
7. **The dark mode is still enabled.**

So I dont' see anything wrong... Could you please provide steps for us to reproduce your situation?

**Comment by toxpal** [comment] 2019-02-08 13:29
I use "normal" (not portable) version on antergos KDE (package is downloaded from Arch User Repository) here, and I'm willing to debug it for you. I can re-produce this issue super easily; just by deleting/renaming Notes folder. But I guess that won't help you much...

Maybe you want to do so some extra steps before/after deleting notes folder? Like capturing debug inform from QOWnNotes before/after, and so on? Just tell me what to do exactly :)

**Comment by liulex** [comment] 2019-02-08 14:59
>     1. Fresh new install QON and launch it.
>     2. In the welcome dialog, set the note folder to `Notes` and finish the welcome dialog.
>     3. **Enable dark mode and dark mode icon in the settings.**
>     4. Quit QON.
>     5. Remove `Notes` folder.
>     6. Launch QON
>     7. Follow instructions in the welcome dialog and finish it.
>     8. **The dark mode is still enabled.**

@toxpal Could you follow the above steps on antergos KDE and report whether the dark theme is enabled at last?
Being in portable mode should be an irrelevant condition, since I cannot reproduce it in non-portable mode either (on Windows).

**Comment by toxpal** [comment] 2019-02-08 15:25
Sure, will do. Just give me some time to backup everything (since I'll be uninstalling/re-installing QOwnNotes fully), and I'll let you know how it works...

**Comment by toxpal** [comment] 2019-02-08 17:09
So I uninstalled app and installed it again. 

1. Created default folder and added some notes - https://i.postimg.cc/020T1KYy/1.png
2. Closed app, deleted folder from 1st step, launched app again and got default Welcome window - https://i.postimg.cc/vTVGvYk6/2.png
3. Completed dialog window (so QOwnNotes created a new folder with some default files), all GUI settings are gone (notice how default toolbars were also restored, even if they don't exist in 1st screenshot) - https://i.postimg.cc/x1tq8C20/3.png

Did the same stuff 4 times... The strange thing is that 2 times out of 4 (after deleting folder), QOwnNotes displayed a warning popup it can't find sqlite file. For some reason, it did **not** set notes folder to new one. Instead, it was trying to access old folder (which was deleted) during every launch, and I had to set new folder location manually in Settings window (because even if I specified new folder location in Welcome dialog, Settings section still displayed old location). But like I said, it only happened 2 times out of 4, other 2 times Welcome dialog set new location properly.

**Comment by liulex** [comment] 2019-02-09 11:35
@toxpal Thank you so much for the tests.

The warning popup is what I mentioned in https://github.com/pbek/QOwnNotes/issues/1140#issuecomment-461753634 and can be fixed by #1144.

I can confirm that the toolbars and the layout will be reset to default right before the welcome dialog shows up. I will try to make a PR to fix this behavior.

But I still cannot reproduce `text editor became white`. Maybe it's platform dependent? Could you try it on Linux? @pbek

**Comment by pbek** [comment] 2019-02-10 06:06
> But I still cannot reproduce `text editor became white`. Maybe it's platform dependent? Could you try it on Linux?

I could not reproduce that, the editor theme wasn't touched under Linux (at least after your patch)

There now is a new release, could you please test it and report if it works for you?

**Comment by liulex** [comment] 2019-02-10 06:55
The new release allows the user to finish the welcome dialog at the first step if old settings are found, in which way all the settings except for the note folder location should be kept untouched. Could you please test it (fresh installation is not required)? @toxpal

**Comment by toxpal** [comment] 2019-02-10 10:11
Everything works perfectly now. All settings are in place (including color of text editor). Tested 3 times, everything is good.

Devs, thank you very much for your super-fast and prompt response.

**Comment by pbek** [comment] 2019-02-10 10:23
Awesome, thank you for testing! @liulex did all the heavy lifting! Again a big thank you to you, @liulex!

**Closed** 2019-02-10 10:23 UTC

**Comment by toxpal** [comment] 2019-02-14 08:48
A quick update... The issue seems to be resolved only partially.

Yesterday, tons of updates came to antergos, and after reboot, encrypted partition with my notes wasn't auto-mounted. Didn't notice it and started QOwnNotes. As usually, got Welcome screen. Since I knew what the problem was (partition not mounted), I closed app (Welcome dialog) and rebooted PC. Launched QOwnNotes again, specified my old directory in Welcome dialog, and... completely all settings lost again.

So I did some more tests, and found that user must complete Welcome wizard in order to keep his settings when notes folder is unavailable. If user just closes this dialog and restarts app later, all settings are lost.

**Comment by liulex** [comment] 2019-02-15 17:34
@toxpal Confirmed and fixed in #1140. Please wait for a release.

**Comment by pbek** [comment] 2019-02-16 05:39
There now is a new release, could you please test it and report if it works for you?

**Comment by toxpal** [comment] 2019-02-17 08:33
Thanks, seems OK now :)
