### ISSUE TITLE
Add 'navigate to sub-dir' to note-contextmenu

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1432] opened 2019-11-20 08:53 UTC
#### Expected behaviour

When searching and opening a search-result-note it would be cool to have a right-mouse-click option on the search result to be able to move to the subdirectory where the note lives. A bit like sublime's 'reveal in sidebar'.

**Comment by pbek** [comment] 2019-11-20 09:00
Thank you for your suggestion.

**Comment by pbek** [comment] 2019-11-24 15:36
## 19.11.21
- added a note list context menu item to jump to the note sub-folder of the
  selected note (for [#1432](https://github.com/pbek/QOwnNotes/issues/1432), thank you @Waqar144)

**Comment by sanderboom** [comment] 2019-11-24 15:47
Nice!

**Comment by pbek** [comment] 2019-11-25 17:53
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment] 2019-11-25 20:31
The subfolder jump works for me.

But after the jump, i can't select the root folder. I have to select another subfolder before to go to the root.

**Comment by pbek** [comment] 2019-11-25 20:38
I'll look at that (if @Waqar144 isn't before me)

**Comment by Waqar144** [comment] 2019-11-26 05:21
> I'll look at that (if @Waqar144 isn't before me)

Was very hard to reproduce this issue as it wasn't happening to me under my default setup. I will send in the PR in a moment for review.

**Comment by pbek** [comment] 2019-11-26 08:11
Will be fixed in the next release.

**Comment by pbek** [comment] 2019-11-26 08:12
Also affected the scripting function to jump to a sub-folder. Happens only if you want to switch back to the last subfolder by clicking on it.

**Comment by pbek** [comment] 2019-11-26 16:05
## 19.11.22
- fixed unable to switch back to last note subfolder after jumping to a subfolder
  with the `Jump to the note's sub-folder` note list context menu item
  (for [#1432](https://github.com/pbek/QOwnNotes/issues/1432))

**Comment by pbek** [comment] 2019-11-26 16:07
There now is a new release, could you please test it and report if it works for you?

**Comment by iolivier87** [comment] 2019-11-26 19:02
Yes, It works now ! 👍

**Comment by pbek** [comment] 2019-11-26 20:13
Great, thank you for testing!

**Closed by pbek** 2019-11-26 20:13 UTC
Labels: enhancement, importance-low
