### ISSUE TITLE
Custom colours not saving on macOS

### ISSUE THREAD

**Issue by dtougas** [pbek/QOwnNotes#503] opened 2017-01-31 14:31 UTC
I am using QOwnNotes version 17.01.13 (build 2759) on Mac OS X 10.12.2 and am unable to save colours in my custom font themes. If I copy an existing font theme, everything is black and any colour changes I make are not saved and revert back to black. Font size changes work properly.

**Comment by pbek** [comment] 2017-01-31 16:03
Thank you for reporting, it's very strange. It works on Linux, but doesn't on macOS.

**Comment by pbek** [comment] 2017-01-31 17:43
Unfortunately it's a QColor serialization bug in Qt.
<https://bugreports.qt.io/browse/QTBUG-56565>
I can reproduce the same issue...

under macOS:

```
Debug: set value:  QVariant(QColor, QColor(ARGB 1, 0.639216, 0, 0.482353))
Debug: get value:  QVariant(QString, "@Variant(")
```

under Linux:

```
Debug: set value:  QVariant(QColor, QColor(ARGB 1, 0.858824, 0.976471, 0.898039))
Debug: get value:  QVariant(QColor, QColor(ARGB 1, 0.858824, 0.976471, 0.898039))
```

We are currently stuck with Qt 5.5.1 on macOS because I didn't manage to get later versions to work on TravisCI (the build system) so far...

**Comment by pbek** [comment] 2017-01-31 17:53
The only thing you can currently try is creating a color schema on an other operating system and import it on macOS.

**Comment by pbek** [comment] 2017-01-31 17:54
I will close this issue until there is more information.

**Closed by pbek** 2017-01-31 17:54 UTC

**Comment by pbek** [comment] 2017-02-01 16:40
## 17.02.0
- disabled the `Copy` button in the Note editor font schema settings under macOS because of a Qt bug for Qt versions lower than 5.8

**Comment by pbek** [comment] 2017-02-02 16:10
I finally did it today! Copying works now!

## 17.02.1
- QOwnNotes for macOS is finally deployed with Qt 5.8, solving some pesky Qt bugs

**Comment by pbek** [comment] 2017-02-02 16:31
There now is a new release, could you please test it and report if it works for you?

**Comment by dtougas** [comment] 2017-02-02 17:56
The new release appears to have fixed the problem. I can now properly save colours on MacOS X. Thank you!

**Comment by pbek** [comment] 2017-02-02 21:27
Great, thank you for testing!
