### ISSUE TITLE
Lag experienced when editing note with preview panel open when it includes large images, especially with different ICC profiles

### ISSUE THREAD

**Issue by jg55** [pbek/QOwnNotes#2078] opened 2021-03-22 20:27 UTC
When editing a large note with large image files and the note preview window is open, I've noticed a lag as you are editing text or typing quickly. This is on a very fast machine, SSD, tons or RAM, etc., with large notes and lots of images. It seems that the preview panel refreshes every second, so the larger and more complex the note, the more the lag is noticed as the preview panel refreshes. 

The lag increases much more when there are images that have ICC profile differences from whatever Qt is expecting as default. And in those cases, the log panel indicates **"[warning] fromIccProfile: failed minimal tag size sanity"** which is thrown every time the preview panel refreshes. The images still display just fine, but this warning seems to increase the lag on each preview panel refresh.

I've been able to test different ICC profiles of .jpg images to help exacerbate the issue. I've attached two images so you can test -- they are the same image, but one has an ICC profile that is different than whatever Qt wants (at least on my machine), which increases lag. To reproduce the problem, create a large note with lots of stuff, including tables, and copy in some instances of these images... open the log panel and make sure you are getting the **"[warning] fromIccProfile: failed minimal tag size sanity"** message. Then type very fast in the editor and you will see what I'm talking about as you will get a lag each time the preview panel refreshes, especially with the image that throws the ICC warning.

My current workarounds are to manually resave images with a different ICC profile in Photoshop (which is not always ideal or possible in the moment), which helps to remove a lot of the refresh lag. OR, the other workaround is to simply close the preview panel (which is also not ideal if I need to see the images as I'm working on a note). 

But I'm wondering if:

1. Can the preview panel actually do its refresh on a different thread, which might potentially solve all lag issues? The lag is obviously related to the refresh.
2. Or can the Qt ICC warning be suppressed so that it doesn't steal so much time during the refresh? That might help.

This is not urgent, obviously, but perhaps there's an easier solution than my workarounds?

[galaxy.zip](https://github.com/pbek/QOwnNotes/files/6185105/galaxy.zip)

[galaxy-different-ICC-profile.zip](https://github.com/pbek/QOwnNotes/files/6185106/galaxy-different-ICC-profile.zip)

**Comment by pbek** [comment] 2021-03-23 06:39
Yes, I also got the warning with the jpg from galaxy.zip. Newer versions of Qt always seem to have more such warnings, we can ignore them...

I tried the jpg in a very large note and had no lag whatsoever on my 2014 Core i7 Linux PC...

**Version**: `21.3.4`
**Build date**: `Mar 23 2021`
**Build number**: `820`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.21`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Self-build`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`

@Waqar144, could you try the jpg in galaxy.zip?

**Comment by pbek** [comment] 2021-03-23 06:46
> Can the preview panel actually do its refresh on a different thread, which might potentially solve all lag issues? The lag is obviously related to the refresh.

@Waqar144, any thought on that?

**Comment by Waqar144** [comment] 2021-03-23 13:06
> Can the preview panel actually do its refresh on a different thread, which might potentially solve all lag issues? The lag is obviously related to the refresh.

No.

Images are not handled by QON, nor is any of the rendering. We just hand html and expect Qt to do the right thing.

If we override this behavior, i.e., do the rendering ourselves, one can think about using some alternative / faster solution or even doing the non ui work on a separate thread.

---

That said, maybe there's some diff algorithm we can use to actually reduce the amount of work being done, i.e., only do appends/inserts in existing text. Currently, afaik, we replace the whole text every single time

**Comment by Waqar144** [comment] 2021-03-23 13:08
I will try this myself to see if I get any lags.

> This is on a very fast machine, SSD, tons or RAM

Can you share what processor you are using?

**Comment by jg55** [comment] 2021-03-23 13:36
> Can you share what processor you are using?

Thanks for looking into this guys! I'm using an i9-9900K w/ Windows 10, lots of RAM, SSD, etc... so it's a very nice fast current system. I will try on Linux later on a different system too. Definitely lag in typing with very large notes (put more instances of the ICC image and add some tables, etc... to see this).

Yeah, I noticed the whole page refreshes in the preview panel, so that makes sense that the larger and more complex the note, especially with several images throwing ICC warnings, increases the lag -- again, this lag is while typing quickly. If no refreshing is happening (i.e. no editing happening), there is no lag... but you'll see the lag -- it will hesitate every second -- as you start typing quickly as it then refreshes the preview panel every second.

**Comment by jg55** [comment] 2021-03-23 13:42
BTW, I first noticed this problem with a much larger image... I didn't post that one since it had sensitive info in it. However, I can create a larger image that will trigger the ICC warning if it helps.

**Comment by pbek** [comment] 2021-03-23 16:30
## 21.3.5
- the warning `fromIccProfile: failed minimal tag size sanity` is now ignored in
  the *Log panel*

**Comment by pbek** [comment] 2021-03-23 17:24
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2021-03-23 20:10
No lag on Windows 10 with 2015 Core i5...

**Comment by jg55** [comment] 2021-03-23 22:53
> No lag on Windows 10 with 2015 Core i5...

I'm still getting lag on an i9-9900K, so I'm guessing maybe my note is a lot bigger than yours! 😉 My note has 29 large images (some VERY large), several of the ICC images that triggered the warning before, various sections, tables, ordered lists, etc...

However, I can confirm that with 21.3.5 the ICC warning doesn't show up. But the lag is still there. I can't tell if the lag is a little bit better though... might be. 

I'll create better example files -- I'll include a note file that is large with plenty of images that will trigger the lag and upload asap later today or tomorrow! Thanks again for looking into this!

**Comment by jg55** [comment] 2021-03-24 15:36
Attached is an MD file and attached media folder that should demonstrate the lag I'm talking about. I also tested this same content in Joplin, Zettlr, Zim Wiki, and other similar editors, and there was no lag.

[QON test folder 2.zip](https://github.com/pbek/QOwnNotes/files/6198434/QON.test.folder.2.zip)

**Comment by pbek** [comment] 2021-03-26 07:30
Thank you for the example!

I can confirm that there is lag when typing in that note on my 2014 i7 system under KDE Neon **with preview turned on**.
There is no lag if I turn off the the preview (e.g. by switching to a workspace without preview with the shortcut to toggle between the last two workspaces).

There even is a little lag when I remove the `media` folder. When I also remove the big table there is no lag.
There also is lesser lag with intact images, but no table.

The table alone even lags a bit in an empty note. Seems like drawing of tables takes some time in QTextBrowser.

Any thoughts, @Waqar144?

**Comment by pbek** [comment] 2021-03-26 07:32
## To summarize

Large images or large tables in the preview can cause lag.

**Comment by Waqar144** [comment] 2021-03-26 15:22
I guess we have hit a wall with QTextBrowser this time....

**Comment by Waqar144** [comment] 2021-03-26 15:27
We have two ways to fix this imo:
1. Use qwebkit instead of qtextbrowser
2. Remove full refresh every second, and instead, only update the changed part of the document. This is kind of a bit hard to get right. We can calculate a diff and then update the changed parts.

QWebEngine is not a solution. It is hard to maintain across platforms and doesn't compile with mingw at all.

**Comment by Waqar144** [comment] 2021-08-22 10:17
Just did some profiling, this is all our own fault. The code for markdown -> html is just really slow

**Comment by pbek** [comment] 2021-08-22 11:21
Can we do anything about it?

**Comment by Waqar144** [comment] 2021-08-22 12:28
Yeah created #2216

**Comment by Waqar144** [comment] 2021-08-22 12:29
Also, note that the slow down due to large tables is in Qt. Notes with large tables will still be slow.

**Comment by pbek** [comment] 2021-08-22 19:34
Yes, even with just one (local) 2MB image it's a lot faster (on my 12 Core Ryzen).
You don't cache remote images, right? Like `![img](https://picsum.photos/2000/3000)`

![img](https://picsum.photos/2000/3000)

**Comment by pbek** [comment] 2021-08-22 19:50
## 21.8.10
- the performance of notes with (especially large) images was improved massively
  (for [#2078](https://github.com/pbek/QOwnNotes/issues/2078), thank you @Waqar144)
    - the general load time of notes was improved as well

**Comment by pbek** [comment] 2021-08-22 19:51
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2021-08-22 19:53
> Also, note that the slow down due to large tables is in Qt. Notes with large tables will still be slow.

@Waqar144, I guess we can't fix that, can't we?

**Comment by Waqar144** [comment] 2021-08-23 04:24
> > Also, note that the slow down due to large tables is in Qt. Notes with large tables will still be slow.
> 
> @Waqar144, I guess we can't fix that, can't we?

Not in QOwnNotes, but it can be fixed in Qt. I have a patch which if accepted will improve things for Qt 5.15 and above.

For remote images, I think we can cache them too just as we cache the local ones. It will involve a little more work I guess (fetch image to disk, load it in QON and then cache it for further requests).

**Comment by pbek** [comment] 2021-08-23 06:17
> Not in QOwnNotes, but it can be fixed in Qt. I have a patch which if accepted will improve things for Qt 5.15 and above.

Cool. Accepted by whom? Qt or KDE? 😁 

> For remote images, I think we can cache them too just as we cache the local ones. It will involve a little more work I guess (fetch image to disk, load it in QON and then cache it for further requests).

Sounds like a plan 😀

**Comment by pbek** [comment] 2021-09-13 04:33
I will close this issue until there is more information.

**Closed by pbek** 2021-09-13 04:33 UTC
Labels: Help wanted, Type: Improvement

**Comment by exelotl** [comment] 2024-04-09 12:14
Hi! I recently encountered this while working on a note containing dozens of photos. Every time the preview panel refreshes, the editor freezes for about 3 seconds.

Can confirm it happens on both Windows and Linux, using QOwnNotes 24.4.0. It's not limited to huge photos (though I'd guess they cause it sooner), adding lots of screenshots will do it too.

Is there any chance this issue could be reopened?

**Comment by pbek** [comment] 2024-04-09 12:57
It really depends on the size of the images... Everything is drawn again every time the preview is refreshed... QOwnNotes doesn't use a real browser engine with caching and so on...

**Comment by exelotl** [comment] 2024-04-10 16:49
I naively had a go at the diff approach using `diff_match_patch.h` which is already in the repo. It didn't go well, because the position of the QTextCursor is entirely disconnected from the position of the chars in the HTML. Unless there's an efficient way to go from one to the other, I guess this is a dead end?

Looking into it a bit more I guess what's needed is something like [QTextImporter](https://github.com/qt/qtbase/blob/80bfeb4e793c673d540bd7641fc159338f64af1b/src/gui/text/qtextdocumentfragment.cpp#L432) but modified to skip nodes if they already exist in the document. Seems like quite a lot of work to get right :(

**Comment by pbek** [comment] 2024-04-11 11:05
I am not sure if I understand the context of your last post.

**Comment by pbek** [comment] 2024-04-11 14:27
Yes, it would be a lot of work 😁
