### ISSUE TITLE
Leaving "Typewriter mode" leaves a horizontal and a vertical line on my note edit panel

### ISSUE THREAD

**Issue by Fabijenna** [pbek/QOwnNotes#1655] opened 2020-03-10 10:48 UTC
#### Expected behaviour

(1) Checking "Typewriter mode" should produce a keyboard on the screen...
(2) Leaving "Typewriter mode" should have the note edit panel return to original appearance

#### Actual behaviour

(1) Selecting "Typewriter mode" produces two lines
(2) Upon leaving "Typewriter mode" the horizontal and the vertical line still appear on my note edit panel

![Bildschirmfoto 2020-03-10 um 12 00 03](https://user-images.githubusercontent.com/17498644/76306177-b6e92200-62c6-11ea-9a8b-39a2efb42039.png)

#### Steps to reproduce

(1), (2) Check "Typewriter mode" and uncheck it again.

#### Output from the debug section in the settings dialog

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Di. März 10 12:37:00 2020`
**Version**: `20.3.2`
**Build date**: `Mar  6 2020`
**Build number**: `5396`
**Platform**: `macosx`
**Operating System**: `macOS High Sierra (10.13)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/amyfabijennalang/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Users/amyfabijennalang/Desktop/QOwnNotes.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_AT`
**Locale (interface)**: `en`
**Primary screen resolution**: `2560x1440`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `254`
**Calendar items**: `0`
**Enabled scripts**: `7`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/Users/amyfabijennalang/ownCloud/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users/amyfabijennalang/ownCloud/Notes/notes.sqlite`

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: `Fabijenna`

### Script `Weather stats`

**id**: `1`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/weather-stats/weather-stats.qml`
**variablesJson**: 
```
{
    "city": "Graz"
}
```
**identifier**: `weather-stats`
**version**: `0.0.3`
**minAppVersion**: `17.06.4`

### Script `Text Highlights`

**id**: `2`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/text-highlights/text-highlights.qml`
**variablesJson**: *empty*
**identifier**: `text-highlights`
**version**: `0.0.3`
**minAppVersion**: `17.06.2`

### Script `Paste text from Skype history`

**id**: `3`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/paste-from-skype-history/paste-from-skype-history.qml`
**variablesJson**: *empty*
**identifier**: `paste-from-skype-history`
**version**: `0.0.1`
**minAppVersion**: `17.05.6`

### Script `Note stats`

**id**: `4`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/note-stats/note-stats.qml`
**variablesJson**: *empty*
**identifier**: `note-stats`
**version**: `0.0.2`
**minAppVersion**: `17.06.3`

### Script `Journal entry`

**id**: `5`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/journal-entry/journal-entry.qml`
**variablesJson**: 
```
{
    "defaultTags": "journal",
    "noteBodyTemplate": "",
    "singleJournalPerDay": true
}
```
**identifier**: `journal-entry`
**version**: `1.4.0`
**minAppVersion**: `17.11.6`

### Script `Insert text button`

**id**: `6`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/insert-text/insert-text.qml`
**variablesJson**: *empty*
**identifier**: `insert-text`
**version**: `0.0.1`
**minAppVersion**: `17.05.8`

### Script `Crowdin changelog translation contributions text`

**id**: `7`
**path**: `/Users/amyfabijennalang/Library/Application Support/PBE/QOwnNotes/scripts/crowdin-translation-contributions/crowdin-translation-contributions.qml`
**variablesJson**: *empty*
**identifier**: `crowdin-translation-contributions`
**version**: `1.1.0`
**minAppVersion**: `17.05.6`

## Settings

**AKAI professional LLC LPK25** (QString): `1`
**AKLastCheckInAttemptDate** (QDateTime): `2020-02-25T14:11:29.770`
**AKLastCheckInSuccessDate** (QDateTime): `2020-02-25T14:11:31.775`
**AKLastEmailListRequestDateKey** (QDateTime): `2020-01-19T19:30:12.196`
**AKLastIDMSEnvironment** (qlonglong): `0`
**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Compx 2/4G Receiver** (QString): `1`
**Country** (QString): `AT`
**Debug/fakeOldVersionNumber** (bool): `false`
**Debug/fileLogging** (bool): `true`
**DistractionFreeMode/editorWidthMode** (qlonglong): `1`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (qlonglong): `0`
**DistractionFreeMode/menuBarVisible** (bool): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-650b75f1-ad37-4129-a0a9-7918a7a0eb24`
**Editor/autoBracketClosing** (bool): `true`
**Editor/autoBracketRemoval** (bool): `true`
**Editor/centerCursor** (bool): `false`
**Editor/disableCursorBlinking** (bool): `false`
**Editor/editorWidthInDFMOnly** (bool): `true`
**Editor/highlightCurrentLine** (bool): `true`
**Editor/indentSize** (qlonglong): `4`
**Editor/useTabIndent** (bool): `false`
**Editor/vimMode** (bool): `false`
**EvernoteImportDialog/geometry** (QByteArray): `<binary data>`
**FileDialog/LastPath** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-InsertImage** (QString): `/Users/amyfabijennalang/Desktop`
**FileDialog/LastPath-NoteHTMLExport** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-NoteMarkdownExport** (QString): `/Users/amyfabijennalang/Desktop`
**FileDialog/LastPath-NotePDFExport** (QString): `/Users/amyfabijennalang/Documents`
**FileDialog/LastPath-PreviewHTMLFileExport** (QString): `/Users/amyfabijennalang/Desktop`
**HP ENVY 4520 series** (QString): `1`
**ImageDialog/disableCopying** (bool): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**InitialKeyRepeat** (qlonglong): `25`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**KeyRepeat** (qlonglong): `2`
**LastUpdateCheck** (QDateTime): `2020-03-10T11:53:28.200`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (qlonglong): `32`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): ...
**MainWindow/noteTextEdit.code.font** (QString): `Monaco,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Arial,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Monaco,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `.SF NS Text,13,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (bool): `true`
**MainWindow/noteTextView.rtl** (bool): `false`
**MainWindow/noteTextView.underline** (bool): `true`
**MainWindow/noteTextView.useEditorStyles** (bool): `true`
**MainWindow/noteTextView.useInternalExportStyling** (bool): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `true`
**MessageBoxOverride/move-notes** (qlonglong): `16384`
**MessageBoxOverride/remove-folders** (qlonglong): `16384`
**MessageBoxOverride/remove-note-folder** (qlonglong): `16384`
**MessageBoxOverride/remove-notes** (qlonglong): `16384`
**MessageBoxOverride/update-and-restart** (qlonglong): `16384`
**MultipleSessionEnabled** (bool): `true`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDiffDialog/geometry** (QByteArray): `<binary data>`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistoryCurrentIndex-1** (qlonglong): `28`
**PKSecureElementAvailableFlags** (qlonglong): `1`
**PKSecureElementAvailableFlagsByHost** (qlonglong): `1`
**PasswordDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**Printer/NotePDFExportOrientation** (qlonglong): `1`
**Printer/NotePDFExportPageSize** (qlonglong): `4`
**SanDisk Cruzer Edge** (QString): `1`
**SanDisk Cruzer Fit** (QString): `1`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (qlonglong): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (bool): `true`
**StartHidden** (bool): `false`
**SyncServicesServerWasActive** (bool): `true`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WebAutomaticSpellingCorrectionEnabled** (bool): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (bool): `false`
**allowDifferentNoteFileName** (bool): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `false`
**appMetrics/disableAppHeartbeat** (bool): `false`
**appMetrics/disableTracking** (bool): `false`
**appMetrics/notificationShown** (bool): `true`
**automaticNoteFolderDatabaseClosing** (bool): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (bool): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (qlonglong): `1`
**currentWorkspace** (QString): `aa4da425-54cd-4949-8149-15c005190fe7`
**cursorWidth** (qlonglong): `1`
**customNoteFileExtensionList** (QStringList): *empty*
**darkMode** (bool): `true`
**darkModeColors** (bool): `true`
**darkModeIconTheme** (bool): `true`
**darkModeTrayIcon** (bool): `true`
**defaultNoteFileExtension** (QString): `txt`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `true`
**disableSavedSearchesAutoCompletion** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**enableNoteTree** (bool): `false`
**enableSocketServer** (bool): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (bool): `false`
**gitCommitInterval** (qlonglong): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (bool): `true`
**ignoreAllExternalNoteFolderChanges** (bool): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (bool): `false`
**imageScaleDownMaximumHeight** (qlonglong): `1024`
**imageScaleDownMaximumWidth** (qlonglong): `1024`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (qlonglong): `11`
**interfaceLanguage** (QString): `en`
**interfaceStyle** (QString): `macintosh`
**internalIconTheme** (bool): `true`
**itemHeight** (qlonglong): `18`
**legacyLinking** (bool): `false`
**localTrash/autoCleanupDays** (qlonglong): `30`
**localTrash/autoCleanupEnabled** (bool): `true`
**localTrash/supportEnabled** (bool): `true`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (bool): `true`
**navigationPanelHideSearch** (bool): `false`
**networking/ignoreSSLErrors** (bool): `true`
**networking/proxyType** (qlonglong): `2`
**newNoteAskHeadline** (bool): `false`
**noteEditIsCentralWidget** (bool): `false`
**noteListPreview** (bool): `false`
**noteSaveIntervalTime** (qlonglong): `10`
**noteSubfoldersPanelDisplayAsFullTree** (bool): `true`
**noteSubfoldersPanelHideSearch** (bool): `false`
**noteSubfoldersPanelOrder** (qlonglong): `0`
**noteSubfoldersPanelShowFullPath** (bool): `false`
**noteSubfoldersPanelShowNotesRecursively** (bool): `false`
**noteSubfoldersPanelShowRootFolderName** (bool): `true`
**noteSubfoldersPanelSort** (qlonglong): `0`
**notesPanelOrder** (qlonglong): `0`
**notesPanelSort** (qlonglong): `1`
**notesPath** (QString): `/Users/amyfabijennalang/ownCloud/Notes`
**notifyAllExternalModifications** (bool): `false`
**overrideInterfaceFontSize** (bool): `false`
**ownCloud/ignoreNonTodoCalendars** (bool): `true`
**ownCloud/supportEnabled** (bool): `true`
**ownCloud/todoCalendarBackend** (qlonglong): `2`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (qlonglong): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (bool): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `c86b98c2-92f4-48aa-a6a4-679aed46fc3e`
**restoreCursorPosition** (bool): `false`
**restoreLastNoteAtStartup** (bool): `true`
**savedSearches/noteFolder-1** (QStringList): ...
**showMatches** (bool): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**skipVersion** (QString): `18.09.4`
**systemIconTheme** (bool): `false`
**tagWasAddedToNote** (bool): `true`
**taggingShowNotesRecursively** (bool): `false`
**tagsPanelHideSearch** (bool): `false`
**tagsPanelOrder** (qlonglong): `0`
**tagsPanelSort** (qlonglong): `0`
**todoCalendarSupport** (bool): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/3/name** (QString): `encryptionToolbar`
**toolbar/3/title** (QString): `encryption toolbar`
**toolbar/4/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/4/name** (QString): `windowToolbar`
**toolbar/4/title** (QString): `window toolbar`
**toolbar/5/items** (QStringList): `action_Quit`
**toolbar/5/name** (QString): `quitToolbar`
**toolbar/5/title** (QString): `quit toolbar`
**toolbar/6/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/6/name** (QString): `insertingToolbar`
**toolbar/6/title** (QString): `inserting toolbar`
**toolbar/size** (qlonglong): `6`
**useSoftWrapInNoteEditor** (bool): `false`
**useUNIXNewline** (bool): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (qlonglong): `22222`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/name** (QString): `Minimal`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-aa4da425-54cd-4949-8149-15c005190fe7/windowState** (QByteArray): `<binary data>`
**workspace-b51dba04-d3e5-4d63-a499-8bf9064074f4/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-b51dba04-d3e5-4d63-a499-8bf9064074f4/windowState** (QByteArray): `<binary data>`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/name** (QString): `Dissertation`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-c86b98c2-92f4-48aa-a6a4-679aed46fc3e/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `aa4da425-54cd-4949-8149-15c005190fe7, c86b98c2-92f4-48aa-a6a4-679aed46fc3e`

## System environment

**TMPDIR**: `/var/folders/m6/hp8h5xxn4z738r441_r9tbww0000gn/T/`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x5C`
**SHELL**: `/bin/bash`
**HOME**: `/Users/amyfabijennalang`
**Apple_PubSub_Socket_Render**: `/private/tmp/com.apple.launchd.80mYkGPs2f/Render`
**SSH_AUTH_SOCK**: `/private/tmp/com.apple.launchd.ZjrTk2PgFN/Listeners`
**PATH**: `/usr/bin:/bin:/usr/sbin:/sbin`
**LOGNAME**: `amyfabijennalang`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.14712`
**USER**: `amyfabijennalang`
**XPC_FLAGS**: `0x0`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`

<details><summary>Expand</summary>

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

![image](https://user-images.githubusercontent.com/17498644/76305197-fca4eb00-62c4-11ea-920d-ce0246fe2ad8.png)

</details>

**Comment by pbek** [comment] 2020-03-10 11:56
I can't reproduce that on KDE Neon, no lines appear. Seems like a drawing/redrawing error... Maybe a Qt or macOS thing...

**Comment by pbek** [comment] 2020-03-11 03:35
I neither can reproduce that under macOS. 😞 

## General Info

**Version**: `20.3.3`
**Build date**: `Mar 10 2020`
**Build number**: `5422`
**Platform**: `macosx`
**Operating System**: `macOS 10.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`

**Comment by pbek** [comment] 2020-05-12 05:41
Do you still have those lines?

**Comment by Fabijenna** [comment] 2020-05-12 11:48
No lines but also no typewriter.

**Comment by pbek** [comment] 2020-05-12 12:08
Ok, I will close this until there is more information.

**Closed by pbek** 2020-05-12 12:08 UTC
Labels: Type: Support, Type: Upstream-problem
