### ISSUE TITLE
[I] MacOS Mojave: Bold formatting impossible

### ISSUE THREAD

**Issue by dgirke** [pbek/QOwnNotes#1037] opened 2018-10-01 17:44 UTC
#### Expected behaviour

Going into preferences to change the editor font allows it to be displayed bold, when for example headings are selected.

#### Actual behaviour

In the Editor Font dialogue, it is possible to check the checkbox f0r bold formatting on individual fonts like Arial etc., but it will not be displayed bold. Also when changing the preview font, there is no chance display or print or export it with bold headings etc.

#### Steps to reproduce

In Settings - Editor Font, change the font to Arial or whatever you like and see what happens with the different formattings below.

#### Relevant log output in the Log panel

```
No debug information availiable
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mo. Okt. 1 19:35:30 2018`
**Version**: `18.09.5`
**Build date**: `Sep 29 2018`
**Build number**: `3847`
**Platform**: `macosx`
**Operating System**: `macOS 10.14`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Travis CI`
**Qt Version (build)**: `5.11.2`
**Qt Version (runtime)**: `5.11.2`
**Portable mode**: `no`
**Settings path / key**: `/Users/x/Library/Preferences/com.pbe.QOwnNotes.plist`
**Application database path**: `/Users/x/Library/Application Support/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/Applications/xZ.app/Contents/MacOS/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `136`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: x
**appIsValid**: `yes`
**notesPathExists**: `not found`
**serverVersion**: `10.0.8.5`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/Users/x
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/Users

## Settings

**646F6E7A_00000000_00000001_6E7A6361_696D6963**: `1`
**ADATA USB Flash Drive**: `1`
**AKLastCheckInAttemptDate**: `2018-09-29T10:55:56.080`
**AKLastCheckInSuccessDate**: `2018-09-29T10:55:58.477`
**AKLastEmailListRequestDateKey**: `2018-09-25T14:25:38.353`
**AKLastIDMSEnvironment**: `0`
**ASIX Elec/ Corp/ AX88179**: `1`
**ActiveNoteHistoryItem**: *empty*
**Country**: `DE`
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/ColorSchemes**: `EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c`
**Editor/CurrentSchemaKey**: `EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_-1**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_0**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_1**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_11**: `false`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_12**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_13**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_14**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_15**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_16**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_17**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_18**: `false`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_19**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_2**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_21**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_22**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_23**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_25**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_3**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_4**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_7**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColorEnabled_8**: `false`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_-1**: `#ffffff`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_0**: `#fff8ef`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_1**: `#fff2e4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_11**: `#aaf7ff`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_12**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_13**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_14**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_15**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_16**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_17**: `#f1f1f4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_18**: `#f5f9d8`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_19**: `#e2e7e2`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_2**: `#fff2e4`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_21**: `#ebebeb`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_22**: `#f7f6ff`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_23**: `#eaebea`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_25**: `#fffae2`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_3**: `#edffed`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_4**: `#eaebea`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/BackgroundColor_8**: `#dbf9e5`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_12**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_13**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_14**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_15**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_16**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_17**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_7**: `false`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Bold_8**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_12**: `150`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_13**: `140`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_14**: `130`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_15**: `120`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_16**: `110`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_17**: `100`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/FontSizeAdaption_8**: `100`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_-1**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_0**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_1**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_10**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_11**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_12**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_13**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_14**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_15**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_16**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_17**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_18**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_19**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_2**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_20**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_21**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_22**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_23**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_24**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_26**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_3**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_4**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_5**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_6**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_7**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_8**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColorEnabled_9**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_-1**: `#000000`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_0**: `#fc7e00`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_1**: `#fc7e00`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_10**: `#a3007b`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_11**: `#ababab`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_12**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_13**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_14**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_15**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_16**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_17**: `#00316e`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_18**: `#aa0000`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_19**: `#008000`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_2**: `#fc7e00`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_20**: `#3d3d3d`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_21**: `#393939`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_22**: `#4e18b9`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_23**: `#008000`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_24**: `#cccccc`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_26**: `#ff5500`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_3**: `#00bf00`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_4**: `#008000`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_5**: `#3d3d3d`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_6**: `#3d3d3d`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_7**: `#0057ae`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_8**: `#00428a`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/ForegroundColor_9**: `#a3007b`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Italic_7**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Name**: `user`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Underline_26**: `true`
**EditorColorSchema-ffb91a36-e8c5-4712-99e5-7b9ca27fb87c/Underline_8**: `false`
**FileDialog/LastPath**: `/Users`
**FileDialog/LastPath-NotePDFExport**: `
**Generic External**: `1`
**Generic Mass Storage**: `1`
**InitialKeyRepeat**: `35`
**IssueAssistantDialog/geometry**: `<binary data>`
**KeyRepeat**: `2`
**LastUpdateCheck**: `2018-10-01T19:23:31.048`
**Linux 4/1/28-zero-gravitas-01897-g7f82abb869aa-dirty with 2184000/usb RNDIS·Ethernet Gadget**: `1`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `32`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Lucida Console,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font**: `Arial,13,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font**: `Lucida Console,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font**: `Noto Sans,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl**: `false`
**PKSecureElementAvailableFlags**: `1`
**PKSecureElementAvailableFlagsByHost**: `1`
**PiwikClientId**: `<hidden>`
**Printer/NotePDFExportOrientation**: `0`
**Printer/NotePDFExportPageSize**: `4`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**StartHidden**: `false`
**SyncServicesServerWasActive**: `true`
**UpdateDialog/geometry**: `<binary data>`
**VLI Manufacture String VLI Product String**: `1`
**WebAutomaticSpellingCorrectionEnabled**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `ec6adaf8-605c-4481-8f9c-6bab001e3ef9`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `18`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `true`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: 
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: 
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: ``
**ownCloud/todoCalendarEnabledList**: ``
**ownCloud/todoCalendarEnabledUrlList**: 
**ownCloud/todoCalendarUrlList**: `
**ownCloudInfo/appIsValid**: `true`
**ownCloudInfo/connectionErrorMessage**: `Unknown error`
**ownCloudInfo/notesPathExistsText**: `not found`
**ownCloudInfo/serverVersion**: `10.0.8.5`
**previousWorkspace**: `c1e6bcb5-153f-4a8c-941d-068980911e03`
**restoreCursorPosition**: `false`
**showMenuBar**: `false`
**showStatusBar**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Hauptsymbolleiste`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `Formatierungs-Werkzeugleiste`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `Einfügen-Werkzeugleiste`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `Werkzeugleiste Verschlüsselung`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `Fenster-Werkzeugleiste`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Beenden - Symbolleiste`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-/noteSubFolderDockWidgetVisible**: `true`
**workspace-/windowState**: `<binary data>`
**workspace-c1e6bcb5-153f-4a8c-941d-068980911e03/name**: `Vollständig`
**workspace-c1e6bcb5-153f-4a8c-941d-068980911e03/noteSubFolderDockWidgetVisible**: `true`
**workspace-c1e6bcb5-153f-4a8c-941d-068980911e03/windowState**: `<binary data>`
**workspace-ec6adaf8-605c-4481-8f9c-6bab001e3ef9/name**: `Minimal`
**workspace-ec6adaf8-605c-4481-8f9c-6bab001e3ef9/noteSubFolderDockWidgetVisible**: `true`
**workspace-ec6adaf8-605c-4481-8f9c-6bab001e3ef9/windowState**: `<binary data>`
**workspaces**: `c1e6bcb5-153f-4a8c-941d-068980911e03, ec6adaf8-605c-4481-8f9c-6bab001e3ef9`

## System environment

**TERM_PROGRAM**: `Apple_Terminal`
**TMPDIR**: `/var/folders/nm/x4vmp2496mj939l1d1n82d840000gn/T/`
**__CF_USER_TEXT_ENCODING**: `0x1F5:0x0:0x3`
**OLDPWD**: `/Users/detlef`
**SHELL**: `/bin/bash`
**QT_LOGGING_RULES**: `qt.network.ssl.warning=false`
**_**: `/usr/bin/open`
**HOME**: `/Users/detlef`
**TERM_SESSION_ID**: `2763268C-5F70-4CA8-9E8E-2DBC13DBDCDF`
**SSH_AUTH_SOCK**: `/
**Apple_PubSub_Socket_Render**: `/
**TERM_PROGRAM_VERSION**: `421`
**SHLVL**: `2`
**PATH**: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
**TERM**: `xterm-256color`
**LOGNAME**: `detlef`
**XPC_SERVICE_NAME**: `com.PBE.QOwnNotes.4016`
**LANG**: `de_DE.UTF-8`
**USER**: `detlef`
**XPC_FLAGS**: `0x0`
**PWD**: `/

**Comment by pbek** [comment] 2018-10-02 05:05
And here goes an other Qt issue. This works in Sierra for me... (and I still don't have Mojave) I hope they are ironing it out in the near future...

If you want to check if there is already a filed bug for Qt: https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by dgirke** [comment] 2018-10-02 06:45
No, unfortunately not.

**Comment by dgirke** [comment] 2018-10-02 06:47
What I missed to mention: The default font type (.SF NS Text) _is_ displayed bold.

**Comment by pbek** [comment] 2019-07-07 04:21
Seems to be fixed by now, can't reproduce it any more.

**Closed by pbek** 2019-07-07 04:21 UTC
Labels: upstream-problem
