### ISSUE TITLE
[Q] Creating A New Note In A Specific Note Subfolder

### ISSUE THREAD

**Issue by dyllan-rafail** [pbek/QOwnNotes#3108] opened 2024-09-13 18:31 UTC
#### General question

Hello, 
I have a quick "how to" question that ive been struggling with for months.
I can't seem to figure out how to create a new note within a specific note subfolder. 

Currently when I create a new note, by any method, it's stored in a seemingly random subfolder.

I know I can just move the newly created note, but this requires me to search through the side navigation panel in QOwnNotes for increasingly long periods of time just to find where it was placed by default.

Is there something obvious I'm doing wrong? Is there a special way of selecting the designated parent subfolder in the navigation pane when creating a new note?

**Comment by pbek** [comment] 2024-09-13 18:34
> Currently when I create a new note, by any method, it's stored in a seemingly random subfolder.

Which note subfolder have you selected?
You need to select one and then notes will be created in that subfolder. Or you can right-click the subfolder and click `New note` there...

**Comment by pbek** [comment] 2024-09-13 18:35
Can you please post the output from the debug settings that you can copy when you get to the settings dialog in QOwnNotes and head over to the *Debug* section of it?

And can you please make a screenshot of your QOwnNotes window?

**Comment by dyllan-rafail** [comment] 2024-09-13 19:35
Selecting a subfolder from the navigation pane doesnt seem to change where the notes appear for me. Same thing when I create a new note using the context menu option that appears when clicking on a subfolder.  It really does feel like the location is being assigned by a randomizer.

![qownnotes_ss_2](https://github.com/user-attachments/assets/8440e7e0-cee8-41fe-80ce-066dd7a393cc)

Ive provided a screenshot and the debug info below.
Note that I did obfuscate certain information by replacing it with the text "REMOVED".

![image](https://github.com/user-attachments/assets/e4719255-cfe6-4238-9d38-034f2944c428)

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Sep 13 15:06:19 2024`
**Version**: `24.9.5`
**Build date**: `Sep 11 2024`
**Build number**: `1127`
**Platform**: `windows (windows)`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\REMOVED\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\REMOVED\Desktop\QOwnNotes\QOwnNotes.exe`, `--after-update`, `C:\Users\REMOVED\AppData\Local\Temp\QOwnNotes-sYCcfS-updater.bat`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `5120x1440`
**Screen resolution(s)**: `5120x1440, 1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `48`
**Calendar items**: `0`
**Enabled scripts**: `0`
**Database drivers**: `QSQLITE, QODBC, QODBC3, QPSQL, QPSQL7`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\REMOVED\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `\\REMOVED\QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: `Projects`
**database file**: `\\REMOVED\QOwnNotes\notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/editorWidthMode** (int): `1`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (int): `5`
**Editor/removeTrailingSpaces** (QString): `true`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `true`
**Editor/vimMode** (QString): `false`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2024-09-13T14:57:13.230`
**LinkDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `40`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `REMOVED`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,15,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,15,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,14,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (int): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**MessageBoxOverride/windows-light-mode** (int): `65536`
**NoteFolder-1/NoteTabNameList** (QStringList): `Substance, new note`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): `Journal, Electronics`
**NoteHistory-1** (QVariantList): `<variant list with 124 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `123`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (int): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**StoredImagesDialog/geometry** (QByteArray): `<binary data>`
**TableDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WebSocketTokenDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**ai/enabled** (QString): `false`
**ai/groq/apiKey** (QString): `<hidden>`
**ai/openai/apiKey** (QString): `<hidden>`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**autoReadOnlyMode** (QString): `false`
**autoReadOnlyModeTimeout** (int): `30`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**cursorWidth** (int): `3`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `true`
**enableSocketServer** (QString): `true`
**enableWebAppSupport** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (int): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (QString): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `true`
**imageScaleDownMaximumHeight** (int): `400`
**imageScaleDownMaximumWidth** (int): `900`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): `ddd MMMM d yyyy, h:m:s ap`
**interfaceFontSize** (int): `22`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (int): `30`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (int): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (int): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (int): `12`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (int): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (int): `0`
**noteSubfoldersPanelTabsUnsetAllNotesSelection** (QString): `false`
**notesPanelOrder** (int): `0`
**notesPanelSort** (int): `1`
**notesPath** (QString): `//REMOVED/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `true`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (int): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (int): `1`
**ownCloud/todoCalendarDisplayNameList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledList** (QStringList): *empty*
**ownCloud/todoCalendarEnabledUrlList** (QStringList): *empty*
**ownCloud/todoCalendarUrlList** (QStringList): *empty*
**ownCloudInfo/appIsValid** (QString): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `REMOVED`
**showMatches** (QString): `true`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**showStatusBarNotePath** (QString): `true`
**showStatusBarRelativeNotePath** (QString): `false`
**startInReadOnlyMode** (QString): `false`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideNoteCount** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (int): `0`
**tagsPanelSort** (int): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionShow_Todo_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_text_link, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionEnable_AI, actionAiBackendComboBox, actionAiModelComboBox`
**toolbar/5/name** (QString): `aiToolbar`
**toolbar/5/title** (QString): `AI toolbar`
**toolbar/6/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/6/name** (QString): `windowToolbar`
**toolbar/6/title** (QString): `window toolbar`
**toolbar/7/items** (QStringList): `action_Quit`
**toolbar/7/name** (QString): `quitToolbar`
**toolbar/7/title** (QString): `quit toolbar`
**toolbar/size** (int): `7`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (int): `REMOVED`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\REMOVED\AppData\Roaming`
**AV_APPDATA**: `C:\Users\REMOVED\AppData\Roaming`
**BESIEGE_GAME_ASSEMBLIES**: `D:/SteamLibrary/steamapps/common/Besiege/Besiege_Data\Managed/`
**BESIEGE_UNITY_ASSEMBLIES**: `D:/SteamLibrary/steamapps/common/Besiege/Besiege_Data\Managed/`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `REMOVED`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**destination**: `C:\Users\REMOVED\Desktop\QOwnNotes`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\REMOVED`
**IntelliJ IDEA Community Edition**: `C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.1\bin;`
**JAVA_HOME**: `C:\Program Files\Java\jdk-17.0.5`
**LOCALAPPDATA**: `C:\Users\REMOVED\AppData\Local`
**LOGONSERVER**: `\\REMOVED`
**NUMBER_OF_PROCESSORS**: `24`
**OneDrive**: `C:\Users\REMOVED\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\VMware\VMware Player\bin\;C:\Program Files (x86)\Common Files\ArcSoft\Bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\WinSCP\;C:\Program Files\dotnet\;C:\Program Files\VSCodium\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PuTTY\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\REMOVED\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\REMOVED\AppData\Local\Programs\Python\Python311\;C:\Users\REMOVED\AppData\Local\Microsoft\WindowsApps;C:\Users\REMOVED\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\REMOVED\AppData\Local\GitHubDesktop\bin;C:\Program Files\Docker\Docker\resources\bin;;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.1\bin;;C:\Users\REMOVED\AppData\Local\Pandoc\;C:\Users\REMOVED\.dotnet\tools`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD`
**PROCESSOR_LEVEL**: `25`
**PROCESSOR_REVISION**: `6102`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PROMPT**: `$P$G`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**qownnotesCommand**: `C:\Users\REMOVED\Desktop\QOwnNotes\QOwnNotes.exe --after-update C:\Users\REMOVED\AppData\Local\Temp\QOwnNotes-sYCcfS-updater.bat `
**SESSIONNAME**: `Console`
**source**: `C:\Users\REMOVED\AppData\Local\Temp\QOwnNotes-sYCcfS.zip`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\REMOVED\AppData\Local\Temp`
**TMP**: `C:\Users\REMOVED\AppData\Local\Temp`
**unzipCommand**: `C:\Users\REMOVED\AppData\Local\Temp\QOwnNotes-sYCcfS-unzip.exe -o C:\Users\REMOVED\AppData\Local\Temp\QOwnNotes-sYCcfS.zip -d C:\Users\REMOVED\Desktop\QOwnNotes`
**unzipExecutable**: `C:\Users\REMOVED'
**USERDOMAIN**: `REMOVED`
**USERDOMAIN_ROAMINGPROFILE**: `REMOVED`
**USERNAME**: `REMOVED`
**USERPROFILE**: `C:\Users\REMOVED`
**VBOX_MSI_INSTALL_PATH**: `C:\Program Files\Oracle\VirtualBox\`
**windir**: `C:\Windows`

**Comment by pbek** [comment] 2024-09-13 19:52
Looks like you are talking about the work in progress feature #790, right?
If yes, then it would be the best to deposit your request there... 😉

**Comment by dyllan-rafail** [comment] 2024-09-13 20:10
I guess I'm not sure, or am confused. 
Is there currently a way to control the location of newly created notes?
Earlier you seemed to indicate that selecting a subfolder and then selecting "new note" was suposed to create the new note in that subfolder.

**Comment by dyllan-rafail** [comment] 2024-09-13 20:12
> You need to select one and then notes will be created in that subfolder. Or you can right-click the subfolder and click `New note`

This is the expected behavior for the current release of QOwnNotes right? Not something in the works?

**Comment by pbek** [comment] 2024-09-13 20:36
Your screenshot tells me you turned on that one experimental feature in the *Experimental* settings. If you turn it off, it should work as intended.

**Comment by dyllan-rafail** [comment] 2024-09-13 21:26
Thanks! I see now. 
Could you delete this thread entirely? I'm a bit of a private person and would prefer the comments associated with my name here be removed.

**Comment by pbek** [comment] 2024-09-14 04:44
Hm, good question. My policy so far was that I don't give private support in my spare time. Those issues are documentation. And this one I want to keep even harder, because I want to see if it's fixable easily. It's already on my to-do list. Then I need it for referencing in the git commits.

Is there no settings to hide your details?

**Comment by pbek** [comment] 2024-09-14 05:23
I'm closing this for #3072, and there might be a fix.

**Closed by pbek** 2024-09-14 05:23 UTC
Labels: Duplicate, Type: Support

**Comment by pbek** [comment] 2024-09-14 10:57
## 24.9.6
- The note selection when selecting a note subfolder in the experimental
  [note tree mode](https://github.com/pbek/QOwnNotes/issues/790) was fixed
  (for [#3072](https://github.com/pbek/QOwnNotes/issues/3072))

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2024-09-17 19:44
Thank you for confirming.

> Is it possible for you to make a one time exception in this instance?

Deleting issues destroys all the cross-references between commits and other issues and is not advised.
You have other options, for example asking GitHub for anonymization of your data, see https://github.com/pbek/QOwnNotes/blob/main/PRIVACY.md#3-privacy-requests.
