### ISSUE TITLE
Text is slightly truncated when cursor is not on current line

### ISSUE THREAD

**Issue by raelb** [pbek/QOwnNotes#1434] opened 2019-11-21 06:12 UTC
Windows 10, Scaling 150%. v 19.11.18

See how `some` and `jumping` are slightly truncated. Also, the `is` before jumping is slightly truncated.

![image](https://user-images.githubusercontent.com/13108198/69311943-44c8d080-0c36-11ea-93ef-96dd7e4499c2.png)

If the cursor is on the current line then notice how these defects do not occur:

![image](https://user-images.githubusercontent.com/13108198/69311968-5c07be00-0c36-11ea-9447-71404c83200d.png)

![image](https://user-images.githubusercontent.com/13108198/69311985-6924ad00-0c36-11ea-95cb-8eb3b4373bc6.png)

**Comment by pbek** [comment] 2019-11-21 06:35
I cannot reproduce that on KDE Neon, do you also have this issue with:

1) other editor fonts and font sizes
2) interface font size override turned off
3) Windows Scaling set to 100%

**Comment by raelb** [comment] 2019-11-21 07:14
1. What do you mean?
2. It does not make a difference..

**Comment by pbek** [comment] 2019-11-21 07:15
1) to set an other *Default font* in the *Edit fonts & colors*

**Comment by raelb** [comment] 2019-11-21 07:22
Yes, same issue in all cases (1,2,3)

**Comment by pbek** [comment] 2019-11-21 07:39
Thank you for testing. I don't know if that is fixable easily, seems to be a Windows Qt problem in the `QPlainTextEdit`.

**Comment by Waqar144** [comment] 2019-11-21 08:48
Happens to me too.

I think it's because the background color of the asterisk overlaps the last letter before asterisk so it seems a bit cut off.

**Comment by pbek** [comment] 2019-11-21 09:13
> I think it's because the background color of the asterisk overlaps the last letter before asterisk so it seems a bit cut off.

That's correct, will be fixed in the next release. (it's a problem with setting the background color even if there shouldn't be one)

**Comment by pbek** [comment] 2019-11-21 16:14
## 19.11.19
- fixed a problem where the background of masked characters (for example `*` in italic text)
  is overwriting parts of the neighboring characters even if the masked characters
  have no background configured

**Comment by pbek** [comment] 2019-11-21 16:44
There now is a new release, could you please test it and report if it works for you?

**Comment by raelb** [comment] 2019-11-22 04:55
Hi,
Yes, it works correctly now. Thanks.

There is still a small issue:
![image](https://user-images.githubusercontent.com/13108198/69398773-596b9e00-0cf4-11ea-9e3b-9b1696d64de2.png)

You can see the trailing  asterisk (*) overlaps/touches the `g` in `jumping`. Also, the first asterisk is a drop too far to the left from the first letter. Perhaps this is something that can be fixed?

**Comment by pbek** [comment] 2019-11-22 05:32
Thank you for testing.

> You can see the trailing asterisk (*) overlaps/touches the g in jumping. Also, the first asterisk is a drop too far to the left from the first letter. Perhaps this is something that can be fixed?

I don't know if that can be fixed, that's the way italic text is rendered in a QPlainTextEdit. If you want you can create another issue.

**Closed by pbek** 2019-11-22 05:32 UTC
Labels: bug, importance-low
