### ISSUE TITLE
Navigation in preview pane incorrect when images are used

### ISSUE THREAD

**Issue by CTrauma** [pbek/QOwnNotes#458] opened 2017-01-05 01:58 UTC
When I have images rendered in my preview pane, clicking on a header in the navigation pane scrolls to the proper location in the markdown editor but not in preview. This actually effects synchronized scrolling of the two panes in general. More of a problem for navigation since I'm not sure how scrolling sync could work with inline images.

**Comment by pbek** [comment] 2017-01-05 06:11
I'm not sure how you tested that, I couldn't reproduce your problem...
Generally the position in the scrollbars are attempted to be synced... So if something takes only one line in the note edit and a page in the preview the sync is not very accurate...

Can you please make an example what you tried.

**Comment by CTrauma** [comment] 2017-01-05 15:33
What I'm saying is that specifically for navigation, wouldn't it make more sense to scroll the preview window to the anchor, rather than scroll the edit window to the anchor and have the preview window render because the single line image markdown in the edit window can expand to almost any height in the preview window throwing off the navigation. For instance in this note example:

![snap01-2017-01-05-10-25-51](https://cloud.githubusercontent.com/assets/943437/21686026/cae537bc-d331-11e6-8fb7-e337d979753c.png)

Where I wanted to navigate the document to heading02 but in the preview pane it doesn't show because the image is expanded.

Is the idea of the navigation pane to navigate through the markdown or the rendered doc? I was using it as a table of contents for the rendered document, but maybe that is not it's purpose.

**Comment by pbek** [comment] 2017-01-05 22:08
I'm sorry, as I were saying and as you demonstrated in your screen shot, the scrollbars are "linked". The Navigation is for jumping to a position the highlighter marked as headline in the editor. The editor knows nothing of the content of the preview.

**Closed by pbek** 2017-01-05 22:08 UTC
