### ISSUE TITLE
Theme colors broken in v22.6

### ISSUE THREAD

**Issue by toxpal** [pbek/QOwnNotes#2554] opened 2022-06-09 16:18 UTC
Upgraded from v22.5.3 to 22.6.1 on Manjaro Linux (KDE). Right after starting app, I got a popup asking if I want to use dark theme (which I always used anyways). That was strange, but I clicked YES and app started. However, theme was changed to "Material Dark" while I used custom dark theme in the past.

Now, no matter which theme I choose, colors are changed properly **except**  color of menu hover. I mean the color which is displayed after menu is selected/button is clicked. It's always bright orange, and such color doesn't even exist in theme. Where does it come from?

Screenshot - https://i.postimg.cc/8518p86N/notes.png

P.S. v22.6 also has 2 seconds delay before Notes -> Settings window is opened.

**Comment by toxpal** [comment] 2022-06-09 16:21
QOwnNotes Debug Information
===========================

## General Info

**Version**: `22.6.1`
**Build date**: `Jun  9 2022`
**Build number**: `968`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.15.4`
**Qt Version (runtime)**: `5.15.4`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark`
**Notes in current note folder**: `62`
**Calendar items**: `0`
**Enabled scripts**: `0`

**Comment by toxpal** [comment] 2022-06-09 20:34
Thanks for quick reply. Like I mentioned in the 1st post, I talk about orange color. (visible in screenshot) It doesn't even exist in QOwnNotes theme, and it surely doesn't exist in system (Linux) theme. It was green for years, but after update it was changed to orange and this orange still remains no matter which theme I apply.

**UPDATE**: While posting this message, I was playing with app settings for 10 minutes and I solved it. This is what I did:

1. Unchecked "Enable dark mode" in Settings > Interface.

And this is it! After restarting, QOwnNotes still uses dark mode (even if this box is not checked anymore) and all colors are back to normal.

Here's full debug info in case you still need it - https://pastebin.com/iamERGhh

**Comment by pbek** [comment] 2022-06-10 07:46
The Dark Mode Interface that you enabled uses their own interface styles, by disabling them the system styles (I guess dark mode in KDE or your desktop environment) are used again. I guess that caused your confusion.

I will close this issue then. 😉

**Closed by pbek** 2022-06-10 07:46 UTC
Labels: Type: Support

**Comment by joenepraat** [comment] 2022-12-21 00:50
I can confirm this. See screenshot. Using QOwnNotes under Ubuntu 22.04 with Gnome 42.5.

For me it doesn't work to disable dark mode, because after the mandatory restart nothing changed and in the settings the dark mode is re-enabled for some unknown reason.

![afbeelding](https://user-images.githubusercontent.com/41594439/208794656-2f1b1954-9d07-4255-aea1-c731ff9f6f3f.png)

**Comment by pbek** [comment] 2022-12-21 07:44
Maybe your dark mode will be re-applied on restart automatically because you told QOwnNotes once to do so. You could try resetting the message boxes in the *General Settings*.
