### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by HardCoreXXL** [pbek/QOwnNotes#1259] opened 2019-08-09 16:28 UTC
Hello,

the last version working for me is 19.7.11
All following versions start with a Runtime Error:

![runtime-error](https://user-images.githubusercontent.com/53942450/62793656-585e8a00-bad2-11e9-8d8f-2d13b0e4ed48.png)!

It also does not matter, whether via update or fresh-install - always the same runtime error.
It would be great if someone could take care of the problem.

**Info:**
**OS: Windows 10 1903 x64**
QOwnNotes is used in Portable Mode

Best regards
HardcoreXXL

**Comment by pbek** [comment] 2019-08-09 18:50
Thank you for reporting, unfortunately I cannot reproduce this issue on Win 10 nor on Win 8.1. Everything works fine for me. Does it work without portable mode? Can you post the output of your Debug settings of v19.7.11 by any chance?

**Comment by pbek** [comment] 2019-08-09 19:25
Maybe Qt 5.13 is causing your issue, I'm trying a Qt 5.12 build. Could you please try the version from https://ci.appveyor.com/project/pbek/qownnotes/builds/26596919/job/r7pijdphvn9apaw6/artifacts (will need some minutes to build).

**Comment by teamayu** [comment] 2019-08-09 23:53
Just upgraded to the latest version and I also get the runtime error.

**Comment by pbek** [comment] 2019-08-10 05:02
> Just upgraded to the latest version and I also now get the runtime error.

1) Do you mean this version by "latest version"?
https://ci.appveyor.com/project/pbek/qownnotes/builds/26596919/job/r7pijdphvn9apaw6/artifacts

2) Does it work without portable mode?

3) Can you please try to remove those 3 DLLs for testing:

libeay32.dll
libssl32.dll
ssleay32.dll

**Comment by pbek** [comment] 2019-08-10 05:03
4) what happens if you run `QOwnNotes.exe –dump-settings`?

**Comment by HardCoreXXL** [comment] 2019-08-10 08:16
Hello pbek,

great, version 19.8.3:
https://ci.appveyor.com/project/pbek/qownnotes/builds/26596919/job/r7pijdphvn9apaw6/artifacts
works well.
No runtime error.

Thank you for your quick help - absolutely great.
Do you still need the debug information from the working version 19.7.11 & not working version 19.8.3?

Best regards
HardcoreXXL

**Comment by pbek** [comment] 2019-08-10 10:20
I need you to test the original Qt 5.13 release (https://github.com/pbek/QOwnNotes/releases/download/windows-b4458/QOwnNotes.zip) with removing those three DLLs:

libeay32.dll
libssl32.dll
ssleay32.dll

Because the next release will be with Qt 5.13 again.

**Comment by pbek** [comment] 2019-08-10 10:44
Meanwhile you can test this. This build is with Qt 5.13 and OpenSSL v1.1.1c: https://ci.appveyor.com/project/pbek/qownnotes/builds/26606177/job/82f92y9w8859w0et/artifacts

There will be a release soon.

**Comment by pbek** [comment] 2019-08-10 11:23
There now is a new release (should be on https://www.qownnotes.org/installation#Windows soon), could you please test it and report if it works for you?

**Comment by HardCoreXXL** [comment] 2019-08-10 11:43
> I need you to test the original Qt 5.13 release (https://github.com/pbek/QOwnNotes/releases/download/windows-b4458/QOwnNotes.zip) with removing those three DLLs:
> 
> libeay32.dll
> libssl32.dll
> ssleay32.dll

**Did I test:
Runtime Error** despite removing the 3 .dll's

> There now is a new release (should be on https://www.qownnotes.org/installation#Windows soon), could you please test it and report if it works for you?

**Did I test:
Runtime Error**

**Comment by pbek** [comment] 2019-08-10 12:16
> Runtime Error despite removing the 3 .dll's

that's strange, but I'll ignore that now

> 19.8.4 works fine

that's all that counts (would be bad otherwise because I haven't found anyone else with your issue :laughing: thank you for testing!

so I will close this issue now

**Closed by pbek** 2019-08-10 12:16 UTC
Labels: question

**Comment by teamayu** [comment] 2019-08-10 14:00
Sorry for the delay. I can also confirm 19.8.4 works fine, thank you.

**Comment by pbek** [comment] 2019-08-11 04:48
Great, thank you for testing!
