### ISSUE TITLE
imported notes from joplin have yaml in front that is displayed in the preview

### ISSUE THREAD

**Issue by pcause** [pbek/QOwnNotes#2343] opened 2021-12-31 14:32 UTC
started using the app.  exported joplin notes and imported/  all of the notes have the yaml header but is displays in the preview window.  see below.

![image](https://user-images.githubusercontent.com/1071479/147828341-609ee06f-fbcb-4f9a-962c-6754a82bab40.png)

**Comment by pbek** [comment] 2021-12-31 22:03
I cannot reproduce that. Do you have an example Joplin export directory to import?

**Comment by pcause** [comment] 2022-01-01 14:49
I made a mistake and exported to a jex and then unzipped and imported.  here is a zip file of the exported raw directory

[joplintestraw.zip](https://github.com/pbek/QOwnNotes/files/7797786/joplintestraw.zip)
y

**Comment by pcause** [comment] 2022-01-01 19:28
just found that if i edit the yaml front matter it is no longer displayed in the preview.  i cna add a space and delete it and save and all is fine

**Comment by pbek** [comment] 2022-01-02 05:38
I imported above notes and didn't see the frontmatter in the preview...

**Comment by pbek** [comment] 2022-01-02 08:38
I only found a similar issue when using the script https://github.com/qownnotes/scripts/blob/master/mermaid/mermaid.qml (by @dohliam and @cyclops1982). The script was directly using the markdown text from the note, instead of the one provided by the script method (and I found out why they did that, because the code highlighting was converting the `>` and `<` to html tags, this is now fixed in 22.1.1).

@pcause, but it's hard to tell if that was your issue, since you never filled out the issue template...

**Comment by pbek** [comment] 2022-01-02 08:50
## 22.1.1
- an issue with scripts getting Markdown code, that was already modified too much
  by code block highlighting was fixed

**Comment by pbek** [comment] 2022-01-02 09:15
@dohliam and @cyclops1982 (and maybe @pcause)

There now is a new release, could you please test it and report if it works for you? (Don't forget to update your mermaid script from the script repository, it needs 22.1.1 now.)

**Comment by pcause** [comment] 2022-01-02 14:41
i di a clean install with the new release.  imported the covid directory.   Same issue:

![image](https://user-images.githubusercontent.com/1071479/147878337-d4e7ee37-f6a2-48ef-b550-f27781fb5746.png)

i put a space in front of the first item in the yam and then deleted and now it is not showing, as I indicated above:

![image](https://user-images.githubusercontent.com/1071479/147879309-5dab9aae-18c5-4f81-bd53-79091cdb20fb.png)


here is the debug information but not a log:

[debufinto.txt](https://github.com/pbek/QOwnNotes/files/7799212/debufinto.txt)

**Comment by pbek** [comment] 2022-01-02 15:55
If it wasn't a script then I really can imagine (nor reproduce) how that happens. Can you please do a "export raw html" (right click on the preview) on a note preview and post it here when you see it happen...

**Comment by pcause** [comment] 2022-01-02 16:07
[rawhtm.zip](https://github.com/pbek/QOwnNotes/files/7799382/rawhtm.zip)

**Comment by pbek** [comment] 2022-01-02 16:21
Thank you. It seems it was detected as one, large heading 2... But in fact the whole frontmatter should be cut out before the markdown even makes it to the markdown2html converter.

It's done by:

https://github.com/pbek/QOwnNotes/blob/8895c86cccc9ddd397c028dc058dd5c0d2b0e26c/src/entities/note.cpp#L2476-L2480

Something seems to be hindering that removal process, but I don't know why I don't have the issue.

**Comment by cyclops1982** [comment] 2022-01-02 18:55
@pbek Just updated. The mermaid script still works fine for me!

**Comment by pcause** [comment] 2022-01-02 19:02
just installed the latest on linux(fedora35) and imported the same content and the yaml isn't displayed in preview.  haven't yet tried on windows.  will a bit later.

**Comment by pbek** [comment] 2022-01-02 19:29
thank you, @cyclops1982.

**Comment by pcause** [comment] 2022-01-02 19:52
a thought.  i don't have "use linux line endings" on windows.  could that effect the regex

**Comment by pbek** [comment] 2022-01-03 07:20
Possibly... maybe try with Linux line endings...

**Comment by pcause** [comment] 2022-01-03 14:43
Did a completely new install with 22.1.2 but enabled use Unix line endings.  imported the test file.  When I open one of the notes no YAML header displayed.

**Comment by pbek** [comment] 2022-01-04 19:25
## 22.1.3
- some issues with Windows line breaks for frontmatter and comment detection
  have been fixed

**Comment by pbek** [comment] 2022-01-04 19:36
There now is a new release, could you please test it and report if it works for you?

**Comment by pcause** [comment] 2022-01-04 21:23
fixed in 22.1.3

**Closed** 2022-01-04 21:23 UTC
Labels: Importance: Low, Type: Improvement
