### ISSUE TITLE
Error with refreshing folders

### ISSUE THREAD

**Issue by lmjst** [pbek/QOwnNotes#489] opened 2017-01-21 18:12 UTC
Hi,
Sync between my distant owncloud and QOwnotes works since I can create note and it's sync

But when I want to refresh the folders in QOwnotes I got the error message : 
Erreur du serveur ownCloud : Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:
Veuillez vérifier votre configuration ownCloud.

In the server setup parameters it's OK :
Connection success !
Version du serveur : 8.2.9.4
Version de QOwnNotesAPI : 16.09.0

Next step : I'm looking to import a notes.nnex files which comes from Nixnotes (need this to sync from Evernote since I'm on Linux and Evernote doesn't have a Linux apps.)

Apparently it's not similar to .enex format and thus I'm stucked with the import.

Hope you can help
thanks

**Comment by pbek** [comment] 2017-01-21 22:25
> But when I want to refresh the folders in QOwnotes I got the error message :

Can you please explain in more detail and step by step what you did, what happened and what you expected.

> Apparently it's not similar to .enex format and thus I'm stucked with the import.

I'm not sure I understand what your question is.

**Comment by lmjst** [comment] 2017-01-22 14:06
Hi,
Here is a capture of the error message when opening qowncloud. And one with the server config
 And the top lines of the parameters info if it helps.
Is qowncloud capable of importing .nnex notes files ?
Thanks

QOwnNotes Debug Information
===========================
![selection_001](https://cloud.githubusercontent.com/assets/12174676/22183024/11886c22-e0b4-11e6-85ba-b26ac6c7da68.jpg)
![selection_002](https://cloud.githubusercontent.com/assets/12174676/22183025/118ac10c-e0b4-11e6-8722-c373ef1c5a9c.jpg)

## General Info

**Current Date**: `dim. janv. 22 15:00:47 2017`
**Version**: `17.01.8`
**Build date**: `Jan 22 2017`
**Build number**: `301`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/dd/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dd/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Humanity`
**Notes in current note folder**: `2`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://dd.org/owncloud`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `8.2.9.4`
**appVersion**: `16.09.0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/dd/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dd/Documents/Notes/notes.sqlite`

**Comment by pbek** [comment] 2017-01-22 19:56
When do you get this error message?
Can you please post the whole output from the debug settings...

Yes, you can import enex files. Note > Import > Evernote

**Comment by lmjst** [comment] 2017-01-22 20:23
I get the error when opening qowncloud and when reloading notes folders
(even when changing  to English)

Here is the whole debug file :

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `dim. janv. 22 21:15:51 2017`
**Version**: `17.01.8`
**Build date**: `Jan 22 2017`
**Build number**: `301`
**Platform**: `linux`
**Operating System**: `Ubuntu 16.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.5.1`
**Portable mode**: `no`
**Settings path / key**: `/home/dd/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/dd/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: *empty*
**Icon theme**: `Humanity`
**Notes in current note folder**: `2`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://dd.org/owncloud`
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Notes`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/dd/Documents/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/dd/Documents/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `true`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**EvernoteImportDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2017-01-22T21:15:27`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Sans,9,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**UpdateDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `true`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `be24a6b5-843c-4511-a689-e3b467471f17`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `16`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `/home/dd/Documents/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://dd.org/owncloud`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloud/userName**: `dd`
**previousWorkspace**: `95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1`
**recentNoteFolders**: `/home/dd/ownCloud/Notes`
**savedSearches/noteFolder-1**: `Note 2017-01-21T19.01.32, Note 2017-01-21T17.43.01`
**showMenuBar**: `true`
**showStatusBar**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `barre d'outils principale`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `barre d'outils de formatage`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `barre d'outils d'insertion`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `barre d'outils de chiffrement`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `barre d'outils de fenêtre`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quitter la barre d’outils`
**toolbar/size**: `0`
**useUNIXNewline**: `false`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/name**: `complet`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/noteSubFolderDockWidgetVisible**: `true`
**workspace-95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1/windowState**: `<binary data>`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/name**: `minimal`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/noteSubFolderDockWidgetVisible**: `true`
**workspace-be24a6b5-843c-4511-a689-e3b467471f17/windowState**: `<binary data>`
**workspaces**: `95d2fcdd-1ddc-4b7f-98a3-02eee5b418b1, be24a6b5-843c-4511-a689-e3b467471f17`

## System environment

**USER**: `dd`
**LANGUAGE**: `fr_FR`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `1777`
**SHLVL**: `0`
**HOME**: `/home/dd`
**DESKTOP_SESSION**: `cinnamon`
**QT_LINUX_ACCESSIBILITY_ALWAYS_ON**: `1`
**GTK_MODULES**: `gail:atk-bridge`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**DBUS_SESSION_BUS_ADDRESS**: `unix:abstract=/tmp/dbus-4ab1jwuHX5,guid=3750ffffa418cc9d753d50c331`
**QT_QPA_PLATFORMTHEME**: `appmenu-qt5`
**MANDATORY_PATH**: `/usr/share/gconf/cinnamon.mandatory.path`
**LOGNAME**: `dd`
**DEFAULTS_PATH**: `/usr/share/gconf/cinnamon.default.path`
**XDG_SESSION_ID**: `c2`
**GTK2_MODULES**: `overlay-scrollbar`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
**GDM_LANG**: `fr_FR`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**DISPLAY**: `:0`
**LANG**: `fr_FR.UTF-8`
**XDG_SESSION_DESKTOP**: `cinnamon`
**XAUTHORITY**: `/home/dd/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/dd`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GDMSESSION**: `cinnamon`
**XDG_VTNR**: `7`
**PWD**: `/home/dd`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-cinnamon:/etc/xdg`
**XDG_DATA_DIRS**: `/usr/share/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**QT_STYLE_OVERRIDE**: `gtk`
**GTK_OVERLAY_SCROLLING**: `1`
**SESSION_MANAGER**: `local/dd:@/tmp/.ICE-unix/1720,unix/dd:/tmp/.ICE-unix/1720`
**XDG_CURRENT_DESKTOP**: `X-Cinnamon`
**GJS_DEBUG_OUTPUT**: `stderr`
**GJS_DEBUG_TOPICS**: `JS ERROR;JS LOG`
**CINNAMON_VERSION**: `3.0.7`
**GIO_LAUNCHED_DESKTOP_FILE**: `/usr/share/applications/QOwnNotes.desktop`
**GIO_LAUNCHED_DESKTOP_FILE_PID**: `4375`
**QT_IM_MODULE**: `compose`

**Comment by pbek** [comment] 2017-01-22 20:48
Maybe it's an error message from your ownCloud calendar. Can you please try to select the ownCloud legacy backend in the Todo - settings...

**Comment by pbek** [comment] 2017-01-25 12:13
I will close this issue until there is more information.

**Closed** 2017-02-01 12:00 UTC
Labels: question

**Comment by X-dark** [comment] 2017-02-04 12:01
Same error (on Windows), with latest Nextcloud and QownNotes version. Changing the calendar settings does not fix the error.

**Comment by X-dark** [comment] 2017-02-04 12:05
And here my debug file: 

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `sam. févr. 4 13:02:55 2017`
**Version**: `17.02.1`
**Build date**: `Feb  2 2017`
**Build number**: `2787`
**Platform**: `windows`
**Operating System**: `Windows 10`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.7.1`
**Qt Version (runtime)**: `5.7.1`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\cedric\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `fr_FR`
**Locale (interface)**: `en`
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `114`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://foo`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `11.0.1.2`
**appVersion**: `16.12.0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `par défaut`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-2`
**localPath**: `C:\Users\cedric\Nextcloud\Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\cedric\Nextcloud\Notes\notes.sqlite`

## Settings

**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**EvernoteImportDialog/geometry**: `<binary data>`
**FileDialog/LastPath**: `J:/cedric/Dropbox/Evernote`
**FileDialog/LastPath-EvernoteImport**: `J:/cedric/Dropbox/Evernote`
**LastUpdateCheck**: `2017-02-04T12:50:13`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `24`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteTextEdit.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `MS Shell Dlg 2,8.25,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**NoteSortOrder**: `0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `false`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `0a27a008-ff7e-4d8a-aa6d-088dafc71ce7`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**demoNotesCreated**: `true`
**disableAutomaticUpdateDialog**: `false`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: `en`
**internalIconTheme**: `false`
**itemHeight**: `15`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `C:/Users/cedric/Nextcloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://foo`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `0`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: `https://foo/remote.php/caldav/calendars/admin/personal/`
**ownCloud/userName**: `bar`
**previousWorkspace**: `ea4194c3-d356-484d-b36a-db17e5155dae`
**recentNoteFolders**: `C:/Users/cedric/Documents/QOwnNotes`
**restoreCursorPosition**: `true`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-0a27a008-ff7e-4d8a-aa6d-088dafc71ce7/name**: `complet`
**workspace-0a27a008-ff7e-4d8a-aa6d-088dafc71ce7/noteSubFolderDockWidgetVisible**: `true`
**workspace-0a27a008-ff7e-4d8a-aa6d-088dafc71ce7/windowState**: `<binary data>`
**workspace-ea4194c3-d356-484d-b36a-db17e5155dae/name**: `minimal`
**workspace-ea4194c3-d356-484d-b36a-db17e5155dae/noteSubFolderDockWidgetVisible**: `true`
**workspace-ea4194c3-d356-484d-b36a-db17e5155dae/windowState**: `<binary data>`
**workspaces**: `0a27a008-ff7e-4d8a-aa6d-088dafc71ce7, ea4194c3-d356-484d-b36a-db17e5155dae`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\cedric\AppData\Roaming`
**asl.log**: `Destination=file`
**CommonProgramFiles**: `C:\Program Files (x86)\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-XXXXXXXX`
**ComSpec**: `C:\WINDOWS\system32\cmd.exe`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\cedric`
**LOCALAPPDATA**: `C:\Users\cedric\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-XXXXXXXX`
**NUMBER_OF_PROCESSORS**: `4`
**OneDrive**: `C:\Users\cedric\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Program Files (x86)\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Calibre2\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Users\cedric\AppData\Local\Microsoft\WindowsApps;`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `x86`
**PROCESSOR_ARCHITEW6432**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 94 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `5e03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files (x86)`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\`
**PUBLIC**: `C:\Users\Public`
**SESSIONNAME**: `Console`
**SystemDrive**: `C:`
**SystemRoot**: `C:\WINDOWS`
**TEMP**: `C:\Users\cedric\AppData\Local\Temp`
**TMP**: `C:\Users\cedric\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-XXXXXXXX`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-8IJHXXXXXXXXFMG`
**USERNAME**: `cedric`
**USERPROFILE**: `C:\Users\cedric`
**windir**: `C:\WINDOWS`

**Comment by X-dark** [comment] 2017-02-04 13:00
And here is the Calendar reply from the log file when testing the connection in the settings.

```XML
<?xml version=\"1.0\"?>
<d:multistatus xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\" xmlns:cal=\"urn:ietf:params:xml:ns:caldav\" xmlns:cs=\"http://calendarserver.org/ns/\" xmlns:card=\"urn:ietf:params:xml:ns:carddav\" xmlns:oc=\"http://owncloud.org/ns\" xmlns:nc=\"http://nextcloud.org/ns\">
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:displayname/>
    <s:getctag/>
    <cal:supported-calendar-component-set/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/personal/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <cal:calendar/>
    </d:resourcetype>
    <d:displayname>Personal</d:displayname>
    <cal:supported-calendar-component-set>
     <cal:comp name=\"VEVENT\"/>
     <cal:comp name=\"VTODO\"/>
    </cal:supported-calendar-component-set>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <s:getctag/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/contact_birthdays/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <cal:calendar/>
    </d:resourcetype>
    <d:displayname>Contact birthdays</d:displayname>
    <cal:supported-calendar-component-set>
     <cal:comp name=\"VEVENT\"/>
    </cal:supported-calendar-component-set>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <s:getctag/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/inbox/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <cal:schedule-inbox/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:displayname/>
    <s:getctag/>
    <cal:supported-calendar-component-set/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/calendars/admin/outbox/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <cal:schedule-outbox/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
  <d:propstat>
   <d:prop>
    <d:displayname/>
    <s:getctag/>
    <cal:supported-calendar-component-set/>
   </d:prop>
   <d:status>HTTP/1.1 404 Not Found</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

**Comment by pbek** [comment] 2017-02-04 13:59
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by X-dark** [comment] 2017-02-04 16:21
Same as above, when I launch or sync QOwnNotes, I get an Owncloud Server connection error. In settings, everything is green on the OC/NC checks.

**Comment by pbek** [comment] 2017-02-04 21:36
You mean you get an error from the Caldav Server? If you create a test account I maybe could take a look...

**Comment by teslazap** [comment] 2017-02-06 17:14
Same problem as X-dark, everything green OK in the related settings page.
QOwnNotes 17.02.2 on Windows 7 x64 connecting to OwnCloud 9.1.4
Is there a way to completely disable calendar connections if that's the problem?

**Comment by pbek** [comment] 2017-02-06 17:41
You can switch to "Other CalDAV server" and don't enter anything there. Can you then please report if it was CalDAV related?

**Comment by X-dark** [comment] 2017-02-07 15:28
Just tested (under Linux) with "Other CalDAV server" and I still get the error.

**Comment by X-dark** [comment] 2017-02-07 16:02
@pbek I just sent you the login information of a test account.

**Comment by pbek** [comment] 2017-02-07 16:34
Thank you, I've tested it and didn't get any error on Linux. I'll try with Windows...

**Comment by pbek** [comment] 2017-02-07 16:36
I didn't get any errors on Windows neither... I could create todo entries both times.

**Comment by X-dark** [comment] 2017-02-07 16:48
Indeed I cannot reproduce either with your account :/

**Comment by 9Mad-Max5** [comment] 2020-08-19 19:44
Did you find any solution?
I'm now running in the same issue but im not sure why.
