### ISSUE TITLE
Misbehaviour of show tag panel button/menu item 

### ISSUE THREAD

**Issue by L-R-S** [pbek/QOwnNotes#301] opened 2016-08-22 13:14 UTC
When clicking this button (or clicking appropriate menu item) wrong panels are showed or hided.

**Comment by pbek** [comment] 2016-08-22 13:25
I can't reproduce that. Can you please be more specific on how to reproduce that problem and can you please post the output of the debug tab in the settings.

**Comment by pbek** [comment] 2016-08-22 13:26
And please define what "wrong" is in your eyes.

**Comment by pbek** [comment] 2016-08-24 11:19
I will close this issue until there is more information.

**Closed by pbek** 2016-08-24 11:19 UTC
