### ISSUE TITLE
Notes.sqlite tag sync

### ISSUE THREAD

**Issue by joeydc** [pbek/QOwnNotes#926] opened 2018-06-01 19:20 UTC
Let say I have QON opened on 2 PC at the same time.
If I add a tag for one of my note with PC1, Nextcloud on PC2 can't download the new notes.sqlite. It says " Access is denied". 
It cause issue because on PC2, I'm not getting the new tag.

Here's a screenshot of Nextcloud on PC2.
![image 043](https://user-images.githubusercontent.com/8237849/40859191-eef8edcc-65ae-11e8-8fe8-7028de0123fe.png)

**Comment by pbek** [comment] 2018-06-01 19:43
Maybe your Nextcloud client is syncing the file and that's why it's locked... I've never seen that issue. My notes.sqlite constantly gets downloaded while QOwnNotes is running...

**Comment by joeydc** [comment] 2018-06-01 22:03
If I close QON on PC2 and force Nextcloud to sync, everything is fine.. but that's so inconvenient.
That means QON is locking the file and Nextcloud is not able to overwrite the existing notes.sqlite

**Comment by pbek** [comment] 2018-06-02 04:43
What are the operating systems of your PC? (you didn't post your debug output)

**Comment by joeydc** [comment] 2018-06-02 16:11
I'm sorry about that.
Windows 10 for both PC and Ubuntu inside an LXC container for Nextcloud server.
I have a Laptop running Arch, I'll test tonight if it's doing the same thing.

**Comment by joeydc** [comment] 2018-06-04 19:14
QON for linux is not affected by this. I can change a TAG on any PC and I'll sync correctly even if I have QON opened.
If I change any TAG on my Linux/Win QON, it will not sync correctly on Win PCs if QON is opened, Nextcloud says: Access is denied.

**Comment by pbek** [comment] 2018-06-04 19:41
Strange. Sounds like an implementation detail of Qt on Windows or some special thing on your Windows PC... I wonder if someone else can reproduce this issue.

**Comment by stobbsm** [comment] 2018-06-04 22:03
I have a Windows VM I'm setting up tomorrow. I can try it then.

**Comment by pbek** [comment] 2018-06-05 04:13
Great, @stobbsm! Thanks a lot!

**Comment by stobbsm** [comment] 2018-06-11 03:19
I can confirm this is an issue in my Windows 10 vm.
Sorry for being so late in getting back. Was a hell of a week.

**Comment by pbek** [comment] 2018-06-11 03:40
Thank you for testing. But I'm not sure how to deal with that, since database handling is done by Qt directly (if that is the reason and not the Nextcloud server or client)... I haven't found anything to this topic on the internet...

**Comment by thornpw** [comment] 2018-06-13 18:19
I also have the problem, that a tag I added on a Windows System is not synced to another Linux PC, and wisewerse.

**Comment by joeydc** [comment] 2018-06-13 18:30
@thornpw are you sure it doesn't work both way? Because I've tested adding a TAG on Windows 10 and my Linux QON+Nextcloud get sync perfectly fine. However, the other way around cause an issue.

**Comment by thornpw** [comment] 2018-06-13 18:37
I add on Windows a Note. This was synced. Then I added a tag, this was not synced from Windows to Linux. I use latest QON versions and the ownCloud Client und arch Linux (Manjaro). Also from Linux to Windows it does not work. Maybe a generell Problem with my database?

**Comment by thornpw** [comment] 2018-06-13 19:23
Found out, that on Linux I had a 18.06.1 instead of 18.06.2 on Windows. Also got an update on Windows. Now It works from Window (create note) to Linux. But still not from Linux to Windows. Also adding a tag in windows on a node that was synced without tags from linux to windows does not work

**Comment by joeydc** [comment] 2018-06-13 19:27
Do you get any sync error with your ownCloud client?

**Comment by thornpw** [comment] 2018-06-13 19:30
No no error messages on both clients

**Comment by pbek** [comment] 2018-06-17 08:53
## 18.06.3
- the note folder database will now be explicitly closed for Windows after each
  operation to prevent synchronization problems

**Comment by pbek** [comment] 2018-06-17 08:53
I tested this with Linux, macOS and Windows at the same time.

**Comment by pbek** [comment] 2018-06-17 08:59
There now is a new release, could you please test it and report if it works for you?

**Comment by thornpw** [comment] 2018-06-17 18:19
Tested the new release and it works, thanks for your efforts.

**Comment by joeydc** [comment] 2018-06-17 18:50
Yes, I confirm. Problem fixed.
Thank you !

**Comment by pbek** [comment] 2018-06-20 20:44
## 18.06.5
- disabled note folder database closing feature temporarily, since it breaks 
  the application under Windows for new note folders

see #945

**Comment by pbek** [comment] 2018-07-06 09:33
## 18.07.2
- on Windows there now is a new experimental settings in the *General settings*
  to automatically close the note folder database to prevent problems with sync 
  tools

**Comment by pbek** [comment] 2018-07-06 09:40
There now is a new release, could you please test it and report if it works for you?

**Comment by joeydc** [comment] 2018-07-06 14:42
Yes, working as expected. Checking the new option in the General tab fix the sync issue.
Thanks !

**Comment by pbek** [comment] 2018-07-06 18:21
Thank you for testing. Let's hope there are no other regressions, it was a lot of work.

**Closed by pbek** 2018-07-06 18:21 UTC
Labels: enhancement, upstream-problem
