### ISSUE TITLE
why table has no border in preview?

### ISSUE THREAD

**Issue by todatamining** [pbek/QOwnNotes#1018] opened 2018-09-09 16:05 UTC
My environment is :
ubuntu 16.4
qownnotes 18.09

I follow the instructions here :https://github.com/pbek/QOwnNotes/blob/develop/src/demonotes/Markdown%20Cheatsheet.md

```
 | Tables        | Are           | Cool  |
 | ------------- |:-------------:| -----:|
 | col 3 is      | right-aligned | $1600 |
 | col 2 is      | centered      |   $12 |
 | zebra stripes | are neat      |    $1 |
```

But there is no border in the preview.

snapshot:

https://ibb.co/jxz8h9

#### Expected behaviour
      table has border

#### Actual behaviour
      no border

#### Steps to reproduce
```
 | Tables        | Are           | Cool  |
 | ------------- |:-------------:| -----:|
 | col 3 is      | right-aligned | $1600 |
 | col 2 is      | centered      |   $12 |
 | zebra stripes | are neat      |    $1 |
```
then click preview

**Comment by pbek** [comment] 2018-09-09 18:34
I'm sorry, tables does not support borders in a QTextBrowser, see: http://doc.qt.io/qt-5/richtext-html-subset.html

**Comment by pbek** [comment] 2018-11-11 09:31
> Your own markdown cheatsheet page shows it

what does it show and where are you looking at it?

**Comment by pbek** [comment] 2018-11-11 09:32
> And the table was definitely rendered like that.

when and where?

**Comment by DutchPete** [comment] 2018-11-11 16:00
> 
> 
> > Your own markdown cheatsheet page shows it
> 
> what does it show and where are you looking at it?

If you open the page that I provided the link for, scroll down to the "Tables" header, there you will 1st see a table as per the editor pane, then below that a sentence "Colons can be used to align columns.", then below that a table with borders. I am not making up things.

**Comment by DutchPete** [comment] 2018-11-11 16:03
> 
> 
> > And the table was definitely rendered like that.
> 
> when and where?

When I 1st started using QON in July in a test note I made. If I load that test note now it does not show those borders anymore, of course.

**Comment by DutchPete** [comment] 2018-11-11 16:04
> 
> 
> I'm sorry, tables does not support borders in a QTextBrowser, see: http://doc.qt.io/qt-5/richtext-html-subset.html

With all due respect, a table without borders is not a table.

**Comment by pbek** [comment] 2018-11-11 21:03
> If you open the page that I provided the link for, scroll down to the "Tables" header, there you will 1st see a table as per the editor pane, then below that a sentence "Colons can be used to align columns.", then below that a table with borders. 

I guess you are viewing the markdown file on Github (with their markdown renderer) in your webbrowser, I' not sure what that has to do with the preview of QOwnNotes...

**Comment by DutchPete** [comment] 2018-11-12 05:35
> 
> 
>  
> I guess you are viewing the markdown file on Github (with their markdown renderer) in your webbrowser, I' not sure what that has to do with the preview of QOwnNotes...

If QOwnNotes has a webpage that is meant to show people how certain things are done and what the results are, then anybody who uses that page may reasonably assume that what is shown on the page is what can be expected from QON. If that is not the right assumption, then there should be a clear, unequivocal comment at the top top of the page that "what you see is NOT what you get", so there are no misunderstandings.

**Comment by pbek** [comment] 2018-11-12 07:16
I'm sorry, GitHub is not owned by me, it is owned by Microsoft. :)

**Comment by pbek** [comment] 2018-11-12 16:32
It took quite some effort to make this work, I had to hack both the Hoedown library (for converting markdown to html) and the markdown-it library (because it's installed by many users of QOwnNotes).

## 18.11.2
- the **preview** will now view **table borders**
    - the script `Markdown-it markdown parser` now also supports table borders
    - to disable this feature you can use `table {border-width: 0;}` in the
      `Custom note preview styling` script

@sanderboom, @codito, this might also be of interest to you

**Comment by DutchPete** [comment] 2018-11-12 16:59
> 
> Thanks Patrizio. I'll wait for the update to come through so we can see the results of your hard work.

**Comment by pbek** [comment] 2018-11-12 19:51
There now is a new release, could you please test it and report if it works for you?

**Comment by DutchPete** [comment] 2018-11-13 05:55
> 
> 
> There now is a new release, could you please test it and report if it works for you?

Thanks Patrizio, that's some good work. I have some remarks:
* the table in the editor pane consists of pipes and dashes. Normally, even if in the editor the pipes and dashes are not aligned properly because words or values are of differing lengths, the table in preview is rendered properly. In QON it is not - the table in the editor needs to be aligned properly for the table in preview to be rendered properly too.

* I have the following in the editor:
Table 1 title = text
Table 1

Table 2 title = text
Table 2

Table 3 title = text
Table 3

There is no gap between the Table title and the table in the editor for all 3 tables, nor in the preview, which is fine. However, in the editor there is a gap between Table 1 and Table 2 title, but in preview there is NO gap. There IS a gap between Table 2 and Table 3 title in the preview, even though in the editor all empty spaces are the same.
I can send you a screenshot if you like. If you do, you'll have to tell me where to send it to.

**Comment by pbek** [comment] 2018-11-13 07:38
@DutchPete I'm sorry, I quite don't grasp what you are talking about, maybe some screenshots would help.

**Comment by pbek** [comment] 2018-11-13 07:39
> I can send you a screenshot if you like. If you do, you'll have to tell me where to send it to.

Just post them here.

**Comment by DutchPete** [comment] 2018-11-13 07:58
I have made a screenshot, saved it as a jpg file, but the webpage "can't process that file".
Please advise.

**Comment by pbek** [comment] 2018-11-13 08:06
Are you sure you created a jpg image? What operating system are you working on?

**Comment by DutchPete** [comment] 2018-11-13 08:43
> 
> 
> Are you sure you created a jpg image? What operating system are you working on? And how did you create the screenshot?

Yes it is a jpg image and I am on Windows.

**Comment by pbek** [comment] 2018-11-13 08:45
If it were a JPG image the GitHub would accept it if you drag and drop it to the comment edit. So how did you create the jpg image?

**Comment by DutchPete** [comment] 2018-11-13 09:29
I created it by making a screenshot and saving it as a jpg file, an option offered by the screenshot program. Now, a jpg is a jpg, AFAIK there are no different types of jpg formats.

I tried both the drag & drop and copy from clipboard, and that's when I got that message in each case. Isn't there an email address I can send the image to?

**Comment by pbek** [comment] 2018-11-13 09:53
Try https://imgur.com/upload, I would prefer the screenshot publicly available to discuss.

**Comment by pbek** [comment] 2018-11-13 10:01
You need to share the link with us. :smiley:

**Comment by DutchPete** [comment] 2018-11-13 10:15
Here is a link;
https://imgur.com/ceJ7pdJ

**Comment by pbek** [comment] 2018-11-13 10:17
![cej7pdj](https://user-images.githubusercontent.com/1798101/48406810-b0c84d00-e735-11e8-8d6f-288cec739064.png)

**Comment by pbek** [comment] 2018-11-13 10:17
Ok, great. So what's the issue?

**Comment by DutchPete** [comment] 2018-11-13 11:31
The issue is as described earlier this morning. To repeat:
in the preview there should be a gap between Table 1 and the text "2. Markets", just like there is a gap between Table 2 and the text "3. Weather conditions in Nicosia @ 12:00h".

As you can see from the editor in the upper half, there is no reason for that gap not to be there. In other words, what do I need to do to create or delete a gap between a table and the text below it?

**Comment by pbek** [comment] 2018-11-13 11:56
thank you for your feedback

ad 1: The `QTextBrowser` (http://doc.qt.io/qt-5/qtextbrowser.html) has a lot of glitches with margins, this seems to be one of it. I'm sorry, you could only try to file a Qt bug at https://bugreports.qt.io/secure/Dashboard.jspa

ad 2: The hoedown library doesn't support that, you could try above mentioned script `Markdown-it markdown parser`

**Comment by DutchPete** [comment] 2018-11-13 12:03
> 
Thanks for your quick reply Patrizio. I am sorry, I am neither a coder nor a programmer. Filing a bug to a 3rd party will require technical explanations, which I am not capable of.

As for trying out a script, I have no idea what that means/involves/how to do/....

So, if I understand you well, the status of table formation as it now stands is as far as you can take it. Correct?

**Comment by pbek** [comment] 2018-11-13 12:10
> As for trying out a script, I have no idea what that means/involves/how to do/....

In QOwnNotes search for the menu item with the name `Script repository` in it, there you can install mentioned script to replace the current preview generator.

> So, if I understand you well, the status of table formation as it now stands is as far as you can take it. Correct?

possibly

**Comment by pbek** [comment] 2018-11-13 13:34
Did you really try the markdown-it script?

I tried

```markdown
| Name | Description | age         
| :- |-------------: | :-:
|Mary| She is a nice girl.  | 20
| Jackie Junior | He is a very naughty boy. | 5
```

The cells were aligned left, right and center.

**Comment by DutchPete** [comment] 2018-11-13 14:19
> Did you really try the markdown-it script?
> 
I assume you mean the script that is QON's default markdown renderer. I did try that, and is why I raised this issue.
Following your previous recommendation, I installed the `Markdown-it markdown parser script` hoping for improvement, but to no avail.
So in both cases it did not work.

FYI, this is not a big issue for me, I think/hope, because I would always try to get the pipes and dashes lined up in the editor. But sometimes that is not possible. In my opinion this issue should be fixed, but I personally can live with it.

I find the other issue of being able to leave a blank line between a table and the next line of text much more important because presentationally it looks crummy, whereas the pipes/dashes issue can be worked around if one is preparing a presentation.

**Comment by pbek** [comment] 2018-11-13 15:36
![screenshot_20181113_163641](https://user-images.githubusercontent.com/1798101/48424148-4e397600-e762-11e8-8bd2-31afbd761a8b.png)

**Comment by pbek** [comment] 2018-11-13 15:38
![screenshot_20181113_163802](https://user-images.githubusercontent.com/1798101/48424234-7e811480-e762-11e8-8af2-60cf3a704637.png)

**Comment by DutchPete** [comment] 2018-11-13 16:38
This is in reply to both your screenshots.

1st screenshot: yes, it seems to work for you - misaligned table in editor, aligned table in preview.
2nd screenshot: you seem to have `markdown-it markdown parser` installed, like me.
So I don't understand why it does not work at my end :-(

From you point of view my end is not important because it does seem to work so other users won't experience this issue.

**Comment by pbek** [comment] 2018-11-13 17:00
ok ;)

**Closed by pbek** 2018-11-13 17:00 UTC
Labels: enhancement

**Comment by DutchPete** [comment] 2018-11-13 17:08
Thanks for your help. At least tables have borders now.

**Comment by pbek** [comment] 2018-11-13 17:34
Thank you for your reports and your feedback!
