### ISSUE TITLE
Where is setting data store?

### ISSUE THREAD

**Issue by LiangWei88** [pbek/QOwnNotes#56] opened 2016-02-04 19:26 UTC
I think I can just remove the folder to uninstall.
and I also search and remove the related folder in AppData.
But the next time I Unzip a newest version,
I can see my setting include the ownCloud connection information are still there.
How can I uninstall it completely?

**Comment by pbek** [comment] 2016-02-04 21:29
It depends on what operating system are you using.
[QSettings](http://doc.qt.io/qt-5/qsettings.html) is used to store settings.

**Comment by LiangWei88** [comment] 2016-02-04 23:35
I found in the QSetting doc.
I am using windows and it store in Registry.

It would be better to provide some way to uninstall and remove all the personal data and setting.
because there is the server url, username, password ect. 

And after all,should not leave anything unexpected in system after uninstall.

What do you think?

**Comment by pbek** [comment] 2016-02-05 06:15
That's an excellent idea. I will put it on my todo list. Thank you!

**Comment by pbek** [comment] 2016-02-08 17:27
This is now implemented in the current version 0.95. Can you please be so kind and confirm if everything works as intended?

**Comment by LiangWei88** [comment] 2016-02-10 01:32
It works great!
just miss the translate.
I will add the new translation in new releases when I have time.

**Comment by pbek** [comment] 2016-02-10 05:49
great! Thank you, I will update the `.ts` files

**Comment by pbek** [comment] 2016-02-10 06:45
I now updated the translation files so you can translate the new text. Thanks a lot. I will close this issue now.

**Closed by pbek** 2016-02-10 06:45 UTC
Labels: enhancement, question
