### ISSUE TITLE
Scale doesn't automatically change after monitor switching on Windows

### ISSUE THREAD

**Issue by e1fueg0** [pbek/QOwnNotes#1956] opened 2020-11-18 21:26 UTC
I use a laptop and, when at home, I plug a monitor/keyboard/mouse to it. For the laptop own screen I use scale 250%, for the discreet one I use 225%. Thus, when I unplug the discreet monitor, fonts become too big, and vise versa. Only manual restart fixes the problem. Btw, similar thing occurs with the update window: it repaints, but the window size remains the same (and so it partially contains artifacts from the previous paint).

#### Expected behaviour
The program does properly repaint after screen scale change.
#### Actual behaviour
The program doesn't properly repaint after screen scale change.

**Comment by pbek** [comment] 2020-11-19 06:15
This sounds a problem with what Windows does to Qt applications (like #1119).
I wouldn't know how to get around that in QOwnNotes itself. 😬

**Comment by pbek** [comment] 2020-11-19 06:17
And so far I haven't seen that in any windows installation nor was I able to reproduce such a behavior.

**Comment by e1fueg0** [comment] 2020-11-19 12:24
Right now I use Win10 version 1909, but when I installed the program, it was probably 1708 or so.
This may also depend on screen resolution (though I doubt this). I have 4K on both monitors.

**Comment by e1fueg0** [comment] 2020-11-19 12:29
Anyway the problem occurs in runtime only. Once I restart the program, it paints everything good.

**Comment by pbek** [comment] 2020-11-19 12:32
Really strange...

**Comment by bcutter** [comment] 2020-12-07 21:06
Strange: after updating to v20.12.3 build 794 about an hour ago the scaling on the main screen is totally rubbish. Only on second screen it looks okay (only if flag "HIGHDPIAWARE" is NOT set for qownnotes.exe), so the update caused this issue... no idea how to fix it. Will need to figure out how to downgrade for the first time after years...

**Comment by pbek** [comment] 2020-12-07 21:39
> Strange: after updating to v20.12.3 build 794

Updating from which version?

**Comment by bcutter** [comment] 2020-12-07 21:57
> 
> 
> > Strange: after updating to v20.12.3 build 794
> 
> Updating from which version?

Latest before that one: v20.12.2. So I guess according to https://github.com/pbek/QOwnNotes/releases/tag/v20.12.3 the 
```
the Windows releases of QOwnNotes are now built with Qt 5.15.2
(for #1976)
```
might have broken it?

**Comment by pbek** [comment] 2020-12-08 06:40
Must be a "feature" of Qt 5.15.2 then.
I can't reproduce that easily, I've no Windows on my machine with multi-high-dpi screens...
Anything useful there?: https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

**Comment by bcutter** [comment] 2020-12-12 18:34
> 
> 
> Must be a "feature" of Qt 5.15.2 then.
> I can't reproduce that easily, I've no Windows on my machine with multi-high-dpi screens...
> Anything useful there?: https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

Unfortunately not. I don´t know how to test things. How can I downgrade QOwnNotes to a specific version? I wanna make sure it´s releated to the update mentioned and compare before / after.

**Comment by pbek** [comment] 2020-12-13 06:28
Do you have the same issue with other Qt 5.15 apps (in case you have some)?

> How can I downgrade QOwnNotes to a specific version? I wanna make 100 % sure it´s releated to the update mentioned and compare before / after to likely create a new issue for this.

Can you please test the lastest release 20.12.4 first, in case something changed there (new version of mingw).

If that didn't help, you can download the zip from https://github.com/pbek/QOwnNotes/releases/tag/v20.12.2 and replace your current QOwnNotes folder with its content.

**Comment by bcutter** [comment] 2020-12-13 21:25
> 
> 
> Do you have the same issue with other Qt 5.15 apps (in case you have some)?
> 
> > How can I downgrade QOwnNotes to a specific version? I wanna make 100 % sure it´s releated to the update mentioned and compare before / after to likely create a new issue for this.
> 
>     1. Can you please test the lastest release 20.12.4 first by normally updating to it, in case something changed there (new version of mingw).
> 
>     2. Edit - new step 2: Please remove your QOwnNotes folder and replace it with the content of the zip of https://github.com/pbek/QOwnNotes/releases/tag/v20.12.4 so there are no old files in it any more.
> 
>     3. If that didn't help, you can download the zip from https://github.com/pbek/QOwnNotes/releases/tag/v20.12.2 and replace your current QOwnNotes folder with its content.

Now I can confirm it is related to the v20.12.3 update. I
a) followed your instructions on 1) (already updated to 20.12.5): issue persists
b) followed your instructions on 2) and downgraded this way to v20.12.4: issue persists
c) followed your instructions on 3) and downgraded this way to v20.12.2: issue is gone, everything fine. As soon as the update to a version greater than v20.12.2 (e. g. v20.12.5) is done, the issue is back.

What to try next?

**Comment by pbek** [comment] 2020-12-14 11:31
So it looks like a Qt 5.15.2 issue under Windows.
The only thing that comes to mind is building QOwnNotes yourself:

https://www.qownnotes.org/installation/building.html

and playing around with Qt's high-dpi flags in:

https://github.com/pbek/QOwnNotes/blob/169d322357e52c57ab642b5a77b2488f1e841b1b/src/main.cpp#L380-L383

**Comment by e1fueg0** [comment] 2020-12-14 20:25
Well, guys, version 20.12.5 works good with scale, no need to restart anymore, thank you very much!

**Comment by pbek** [comment] 2020-12-14 20:47
It did for you, @e1fueg0? But not for @bcutter?

**Comment by e1fueg0** [comment] 2020-12-14 23:28
yes, for me it works good now @pbek.

**Comment by e1fueg0** [comment] 2020-12-17 19:02
Actually, it doesn't work completely accurate, especially, font size in the left side menu wasn't completely correct, but now at least it's possible to work w/o restart.

**Comment by bcutter** [comment] 2020-12-18 11:59
> So it looks like a Qt 5.15.2 issue under Windows.
> 
> The only thing that comes to mind is building QOwnNotes yourself:
> 
> 
> 
> https://www.qownnotes.org/installation/building.html
> 
> 
> 
> and playing around with Qt's high-dpi flags in:
> 
> 
> 
> https://github.com/pbek/QOwnNotes/blob/169d322357e52c57ab642b5a77b2488f1e841b1b/src/main.cpp#L380-L383
> 
> 
> 
> 

Unfortunately that's out of my comfort zone (user, not a dev/expert).
I tested the behavior on other Windows endpoints: same result.

It seems like
- before the update: the Windows scaling setting was used.
- after the update: the Windows scaling setting was multiplied, so now QOwnNotes looks TOO BIG.

For explanation: my main screen is a 4K screen with 3.840x2160 pixels. The scaling is set to recommended 150 %.

Compared to other applications QOwnNotes is simply displayed WAY too large. I'll provide a screenshot in a few minutes.

**Comment by bcutter** [comment] 2020-12-18 12:06
![image](https://user-images.githubusercontent.com/13799156/102612829-be7d0780-4131-11eb-935e-994b67b59943.png)

QOwnNotes compared to other applications (notepad). Same DPI-Settings, crazy behavior in QOwnNotes.

**Comment by pbek** [comment] 2020-12-18 12:12
You can change all those things in the interface settings.

![image](https://user-images.githubusercontent.com/1798101/102613404-b4a7d400-4132-11eb-8b49-b0436c24492a.png)

**Comment by bcutter** [comment] 2020-12-18 12:20
Found it right after I posted the screenshot. Played around with that and the text size and it looks almost good now. Will check that on my main Windows endpoint later.

So of those values have not been changed with the update, the way Qt handles that has changed.

Thanks so far!

**Comment by pbek** [comment] 2020-12-18 12:30
> (I did NOT touch them)

maybe just the Qt default values have changed. to what values do the sizes reset when you press the reset buttons?

**Comment by bcutter** [comment] 2020-12-18 13:11
Now on 20.12.6 it defaults to 24 / 15px.

**Comment by pbek** [comment] 2020-12-18 13:17
Does that look ok or is that too high with your zoom?

**Comment by bcutter** [comment] 2020-12-19 13:46
Here´s the history of settings according to the version:

20.12.2:
![grafik](https://user-images.githubusercontent.com/13799156/102690834-7e3c8880-4208-11eb-9b5c-5b3a39d87cfa.png)

20.12.7 (default / unchanged):
![grafik](https://user-images.githubusercontent.com/13799156/102690837-8694c380-4208-11eb-9cf5-bfce91b663da.png)

20.12.7 (changed to have a result similar as with 20.12.2 before):
![grafik](https://user-images.githubusercontent.com/13799156/102690844-8b597780-4208-11eb-8629-57d1dd3b05cc.png)

So to achieve about the same optical result as on 20.12.2 I need to tweak icon size setting and enforce UI size setting. Additionally the text size (normal setting e. g. using 
![grafik](https://user-images.githubusercontent.com/13799156/102690890-dd9a9880-4208-11eb-80a1-67f3ed8a491e.png)) needed to be adjusted.

The only (new) main issue now is not related to scaling at all; I´ll create a separate issue for that.

**Comment by bcutter** [comment] 2020-12-19 14:01
By the way: in the debug section I spotted the following information:

**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1680x1050, 1600x900`

The 1920x1080 is a former screen size. Now it should be 3840x2160 for the primary screen. Where are these information from? Can they be set? Maybe that´s the root cause... because when it adapts to 1920x1080 screen size where it´s actually 3840x2160... that may result in those scaling issues, don´t you think?

**Comment by pbek** [comment] 2020-12-19 16:06
Qt reports that information.
For my two 4k screens under Linux with a 150% scale this is reported:

**Primary screen resolution**: `2560x1440`
**Screen resolution(s)**: `2560x1440, 2560x1440`

**Comment by bcutter** [comment] 2020-12-19 21:40
> 
> 
> Qt reports that information.
> For my two 4k screens under Linux with a 150% scale this is reported:
> 
> **Primary screen resolution**: `2560x1440`
> **Screen resolution(s)**: `2560x1440, 2560x1440`

Alright, so I don´t know why but in my case Qt is reporting rubbish: instead of "1920x1080" it should be "3840x2160"...

**Comment by pbek** [comment] 2020-12-19 21:52
For me under windows (other pc) the windows display scaling isn't taken in account. Qt always shows the original display resolution. Do you have three screens?

**Comment by bcutter** [comment] 2020-12-19 21:57
Yes I do. One of them is the 4 K screen Qt reports a wrong resolution. Doesn't really matter in the end cause everything is looking good meanwhile in terms of dpi and scaling, I was just wondering if that might have been an indication for my special issue.

**Comment by pbek** [comment] 2020-12-19 21:59
Ok I will then close this issue until there is more information.

**Closed by pbek** 2020-12-19 21:59 UTC
Labels: Type: Support, Type: Upstream-problem
