### ISSUE TITLE
Bug: Delay after opening a note

### ISSUE THREAD

**Issue by ivanpirog** [pbek/QOwnNotes#1418] opened 2019-11-14 15:27 UTC
Video: https://youtu.be/SGVbFvq7vb4

**Comment by ivanpirog** [comment] 2019-11-14 15:29
Sometimes, when I open a note, the QON doesn't respond about 3-6 seconds.

**Comment by ivanpirog** [comment] 2019-11-14 15:31
Hardware: Core i7 3.6 GHz, 32 Gb ram, SSD

**Comment by pbek** [comment] 2019-11-14 16:04
Thank you for reporting, I can't reproduce that on any of my systems.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

@Waqar144, I can't see any spellchecking. Can that still be a thing?

**Comment by pbek** [comment] 2019-11-14 16:05
@ivanpirog and can you please upload an example note file that takes long to load.

**Comment by Waqar144** [comment] 2019-11-14 16:37
@ivanpirog 
- did you build yourself or using pre-built binary?
- Can you tell us about the file size of the note which takes long to load?
- Can you confirm whether *spell checking* is enabled or disabled in Main menu- Edit -> Check spelling?
- Can you tell us which version of QON you are using? 

@pbek 
Spellchecker can be enabled but if there's no highlighting it means that it wasn't able to load dictionaries and hence the function returns early. I will try with Russian dictionary to confirm. The delay is too much for a debug version even.

**Comment by pbek** [comment] 2019-11-14 16:38
> The delay is too much for a debug version even.

I've no delay for large notes in debug.

**Comment by Waqar144** [comment] 2019-11-14 16:44
> > The delay is too much for a debug version even.
> 
> I've no delay for large notes in debug.

I get a delay of about 1100ms with auto detect (using 2 dictionaries, German and English) with a note of about 160KB and almost 3000 blocks. It used to be 3000ms before for me.

With specific language, for eg en_US, it takes, 500ms. With German, 700 because dictionary size is bigger.

This is the startup performance.

Once the application has loaded the note and dictionary, switching notes is faster.

**Comment by ivanpirog** [comment] 2019-11-14 17:40
> Thank you for reporting, I can't reproduce that on any of my systems.

I have 2 different machines with different Win 10 version (64 & 32 bit). On the fast machine delay is slightly lower. 

> did you build yourself or using pre-built binary?

pre-build

> Can you tell us about the file size of the note which takes long to load?

Size is matter. The larger the size of the note, the longer the delay.

> Can you confirm whether spell checking is enabled or disabled in Main menu- Edit -> Check spelling?

Yes. When I disable spellchecking, notes opens super fast!

> Can you tell us which version of QON you are using?

19.11.12. 

[QON General Debug Info.txt](https://github.com/pbek/QOwnNotes/files/3847798/QON.General.Debug.Info.txt)

When I open long note I have long debug log about "[warning] Unable to find any suggestion for 'blahblah'".

[QON Open note debug info.txt](https://github.com/pbek/QOwnNotes/files/3847814/QON.Open.note.debug.info.txt)

Example note:

[123.txt](https://github.com/pbek/QOwnNotes/files/3847818/123.txt)

**Comment by ivanpirog** [comment] 2019-11-14 17:42
It’s strange thing that spellchecking is not looking for words, but whole sentences.

**Comment by ivanpirog** [comment] 2019-11-14 17:47
BTW, I have no spellchecker installed.

**Comment by Waqar144** [comment] 2019-11-14 17:49
> It’s strange thing that spellchecking is not looking for words, but whole sentences.

It's trying to guess the language so that's why these are sentences.

Can you check whether you have any dictionaries installed?
Dictionaries are visible in Edit->Languages

**Comment by Waqar144** [comment] 2019-11-14 17:51
> BTW, I have no spellchecker installed for russian lang.

Even so, the guessing should work for some sentences and not fail for everything. I will look investigate this more.

**Comment by ivanpirog** [comment] 2019-11-14 17:51
If you need more note examples, just go [here](https://habr.com/ru/) and copy/paste and long article.

**Comment by ivanpirog** [comment] 2019-11-14 17:53
> 
> 
> > It’s strange thing that spellchecking is not looking for words, but whole sentences.
> 
> It's trying to guess the language so that's why these are sentences.
> 
> Can you check whether you have any dictionaries installed?
> Dictionaries are visible in Edit->Languages

No languages installed:

![изображение](https://user-images.githubusercontent.com/8699212/68882689-5b43c900-0718-11ea-9a71-28114b0e07ea.png)

**Comment by Waqar144** [comment] 2019-11-14 17:54
> If you need more note examples, just go [here](https://habr.com/ru/) and copy/paste and long article.

Thank you for the link. I will be investigating this more.

Did you install a dictionary and try?

**Comment by ivanpirog** [comment] 2019-11-14 17:56
> Can you install a dictionary and then see if there is a delay?

I installed Russian lang and have no more delays!

**Comment by Waqar144** [comment] 2019-11-14 17:58
> > > It’s strange thing that spellchecking is not looking for words, but whole sentences.
> > 
> > 
> > It's trying to guess the language so that's why these are sentences.
> > Can you check whether you have any dictionaries installed?
> > Dictionaries are visible in Edit->Languages
> 
> No languages installed:
> 
> ![изображение](https://user-images.githubusercontent.com/8699212/68882689-5b43c900-0718-11ea-9a71-28114b0e07ea.png)

Ahh. So that's why.
The trigrams are failing so that's why it's taking so long.

**Comment by Waqar144** [comment] 2019-11-14 17:58
> > Can you install a dictionary and then see if there is a delay?
> 
> I installed Russian lang and have no more delays!
> Option: Automatic detect

Great!
If you are using only one language, you should switch to a specific language instead of auto detect. It will be even more faster.

**Comment by ivanpirog** [comment] 2019-11-14 17:59
According to my feelings, when automatically detecting a language, notes open a little slower than if I specify the language. But it’s difficult to determine by eye, I need to measure time. In any case, after installing the dictionary, notes open very quickly.

**Comment by ivanpirog** [comment] 2019-11-14 18:01
> Great!

So, the problem is detected. Congratulations! :)

**Comment by Waqar144** [comment] 2019-11-14 18:29
> According to my feelings, when automatically detecting a language, notes open a little slower than if I specify the language. But it’s difficult to determine by eye, I need to measure time. In any case, after installing the dictionary, notes open very quickly.

Yes, auto detection is slower because it tries to guess your language. If you don't have any dictionaries installed, it will fail completely but will still try to guess language for every sentence.

Auto detection is useful when you have two languages in the same note. It will detect both languages and provide spell checking for them. (You need dictionaries for both languages)

The problem was that spellchecker should be disabled in case no dictionaries found.

**Comment by ivanpirog** [comment] 2019-11-14 18:37
> Auto detection is useful when you have two languages in the same note. It will detect both languages and provide spell checking for them. (You need dictionaries for both languages)

I have an idea. If just one dictionary installed, you should automatically set to that language. In this case the Automatic detect option have no sense.

**Comment by Waqar144** [comment] 2019-11-14 18:41
> > Auto detection is useful when you have two languages in the same note. It will detect both languages and provide spell checking for them. (You need dictionaries for both languages)
> 
> I have an idea. If just one dictionary installed, you should automatically set to that language. In this case the Auto detect option have no sense.

Good point. 
What do you think @pbek?

**Comment by pbek** [comment] 2019-11-14 20:42
Great work! :grin:

**Comment by pbek** [comment] 2019-11-14 20:43
> I have an idea. If just one dictionary installed, you should automatically set to that language. In this case the Auto detect option have no sense.

good idea

**Comment by pbek** [comment] 2019-11-16 05:22
## 19.11.14
- the spellchecker is now disabled if no dictionaries are available and language
  auto-detection enabling is fixed for multiple languages
  (for [#1418](https://github.com/pbek/QOwnNotes/issues/1418), thank you @Waqar144)

**Comment by pbek** [comment] 2019-11-17 06:46
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2019-11-17 18:47
It seems that GitHub currently has troubles. I still get a unicorn on https://github.com/pbek/QOwnNotes/releases...

**Comment by ivanpirog** [comment] 2019-11-18 18:03
> It seems that GitHub currently has troubles. I still get a unicorn on https://github.com/pbek/QOwnNotes/releases...

Can't find windows release

**Comment by ivanpirog** [comment] 2019-11-18 18:05
> 
> 
> It seems that GitHub currently has troubles. I still get a unicorn on https://github.com/pbek/QOwnNotes/releases...

Waiting for 19.11.14...

**Comment by pbek** [comment] 2019-11-18 18:05
Yes, it seems that GitHub still has troubles. I still get a unicorn on https://github.com/pbek/QOwnNotes/releases... I got that confirmed by GitHub, but they don't know when it will be fixed.

**Comment by ivanpirog** [comment] 2019-11-18 18:09
I've checked last version for MacOS.

In the previous version (19.11.13 for Mac) there were the same delays when opening notes. In the latest version, notes open instantly. Dictionaries not installed. Build for MacOS works fine!

**Comment by pbek** [comment] 2019-11-19 19:02
You should get a new Windows version within one hour.

**Comment by ivanpirog** [comment] 2019-11-20 17:53
Checked. Everything works well!

**Comment by pbek** [comment] 2019-11-20 18:27
Great, thank you for testing!

**Closed by pbek** 2019-11-20 18:27 UTC
Labels: enhancement
