### ISSUE TITLE
Moving Panels is not save the new location

### ISSUE THREAD

**Issue by Servh37** [pbek/QOwnNotes#409] opened 2016-12-07 00:10 UTC
Hi,

when i uplock the Panels and try and move them to haave the Notes preview and the bottem and the note edit on top it does not allow me  to save it like that is there something that im missinig?

Debug 
[QOwnNotes Debug.txt](https://github.com/pbek/QOwnNotes/files/635356/QOwnNotes.Debug.txt)

**Comment by pbek** [comment] 2016-12-07 05:18
Can you please explain in more detail and step by step what you did, what happened and what you expected.

**Comment by Servh37** [comment] 2016-12-07 22:54
Hi @pbek ,

Please see the requested information below.

**step by step**

1. Click on Window -> Unlock Panels
2. Click and hold and move the Note preview panale to the bottem where it turns blue and let go.
3. Click on Window -> Unlock Panels to reloack the panels

**what happened**
The view panel goes back yto it's origenal place.

**what you expected**
when the the View panel or any of the panels are moved it will save its new location, not reverty back to the old location.

Regards

**Comment by pbek** [comment] 2016-12-08 06:28
Thank you for your description. So the panels move to their old place when you click the lock button again? I never heard of such a thing before...

What happens if you create a 2nd workspace?

**Comment by pbek** [comment] 2016-12-08 07:09
So far I couldn't reproduce that behavior under Windows. Even after a restart everything stays in place as it should be.

**Comment by Servh37** [comment] 2016-12-08 22:24
Hi @pbek,

I have check that it is not a permission issue and i have move the folder location just incase but it still want allow mw to have the 2 panel as landscape.

Regards

**Comment by pbek** [comment] 2016-12-09 05:45
Are other settings also not stored?

**Comment by Servh37** [comment] 2016-12-09 06:02
No All over setting save, just not the panels saving in there new locations.

**Comment by pbek** [comment] 2016-12-09 06:40
The panels move to their old place when you click the lock button again?
What happens if you create a 2nd workspace?

**Comment by pbek** [comment] 2016-12-09 19:39
I neither couldn't reproduce this under Windows 10 (my last test was under Windows 8.1).

**Comment by pbek** [comment] 2016-12-11 15:03
I will close this issue until there is more information.

**Closed by pbek** 2016-12-11 15:03 UTC
Labels: question

**Comment by Servh37** [comment] 2016-12-13 02:25
Hi @pbek,

Not sure what the casue was but its not fix not sure if it was the update you had sent out or just my PC.

thank you for tyhe for help.

Regards

**Comment by pbek** [comment] 2016-12-13 05:27
I haven't changed anything with the panels. ;) But I'm glad it works now.
