### ISSUE TITLE
Import from Joplin JEX

### ISSUE THREAD

**Issue by dbogdanov** [pbek/QOwnNotes#2189] opened 2021-07-18 01:49 UTC
Is there a way to bulk-import notes from Joplin maintaining tags and attachments (images, etc.)?  

Joplin provides its own JEX dump format ([no specs published, but it is a tar file with a bunch of md and media files](https://github.com/laurent22/joplin/issues/408)), [but not ENEX](https://discourse.joplinapp.org/t/feature-request-export-to-enex/4735/11). Also, it is possible to export Joplin notes to Markdown, but then the tags and attachments (images, etc.) are lost.

**Comment by pbek** [comment] 2021-07-18 05:50
How are tags managed in Joplin? Can please you provide such a JEX dump to have something to talk about?

**Comment by pbek** [comment] 2021-07-18 05:51
If the tags are inside the markdown you could try to work with them directly, since tagging is scriptable in QOwnNotes.

**Comment by pbek** [comment] 2021-07-18 07:13
I got Joplin myself to play around with the export. 
[18_07_2021.jex.tar.gz](https://github.com/pbek/QOwnNotes/files/6835788/18_07_2021.jex.tar.gz)

The way I see it if you have a note with one tag you'll get three "markdown" files (there is a lot of "non-markdown" stuff going on in them).

- One for the note
- One for the tag
- One for the note to tag assignment

So two tags on a note would result in five files.

**Comment by pbek** [comment] 2021-07-18 07:17
Images seem to have "markdown" files too and are linked like this in notes: `![](:/2c5d34af711e46fd9a257a3e3d9d4090)`

**Comment by pbek** [comment] 2021-07-18 08:46
## 21.7.8
- you now can **import notes** from a *RAW - Joplin Export Directory* of
  **[Joplin](https://joplinapp.org/)** with a new import dialog in the *Note menu*
  (for [#2189](https://github.com/pbek/QOwnNotes/issues/2189))
    - this first draft of the feature supports only importing all files that are
      marked as "note" in a rudimentary fashion
    - if you just have a *JEX - Joplin Export File* please extract the content
      of that file to a directory and select that directory in the import dialog
    - note that this import is done by reverse engineering, since there is no
      documentation for the Joplin export format
    - no tags, images or attachments are yet imported

**Comment by pbek** [comment] 2021-07-18 08:58
There now is a new release, could you please test it and report if it works for you?

**Comment by dbogdanov** [comment] 2021-07-18 11:33
Wow this was fast! 🌠 
I'll test it now with my dump.

**Comment by pbek** [comment] 2021-07-18 16:32
## 21.7.9
- the **[Joplin](https://joplinapp.org/) note import** was improved
  (for [#2189](https://github.com/pbek/QOwnNotes/issues/2189))
    - tags, images and attachments will now also be imported
    - the raw metadata part at the bottom of the note will now be not imported any more
    - numbers and points are now only removed from the beginning of the note
      name instead of the whole note name

**Comment by pbek** [comment] 2021-07-18 17:02
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2021-07-18 17:03
Maybe I will work some more on the headline detection...

**Comment by dbogdanov** [comment] 2021-07-19 00:12
Imported ~1400 notes with the latest release without issues!

- The images referred in the format `![4-766161.jpg](:/51c8701bcbc4406b8d5f37c3bd1b74d2)`are missing.
- Joplin organizes notes in notebooks and sub-notebooks. Could those be mapped to folders?
- I'm wondering if some of the metadata files are useful. For example, `source_url` is the source URL of original webpages for notes that were scraped with Joplin Web Clipper.

**Comment by pbek** [comment] 2021-07-19 06:49
> The images referred in the format ![4-766161.jpg](:/51c8701bcbc4406b8d5f37c3bd1b74d2)are missing.

Can you please export notes with such images. So far I didn't have any issues with images. 

> Joplin organizes notes in notebooks and sub-notebooks. Could those be mapped to folders?

Not sure yet. Takes quite some work.

> I'm wondering if some of the metadata files are useful. For example, source_url is the source URL of original webpages for notes that were scraped with Joplin Web Clipper.

What meta data files are we talking about? or are you talking about the metadata in the Joplin note files?

**Comment by dbogdanov** [comment] 2021-07-19 12:44
Yes, I referred to the metadata in the end of each Joplin note file. However different users can have different opinions on which metadata fields are useful to keep, if to keep them at all.

I'll prepare a test example of a Joplin note for which the images did not work.

**Comment by pbek** [comment] 2021-07-19 17:24
This was a lot of work... 😅 

## 21.7.10
- the **[Joplin](https://joplinapp.org/) note import** was improved
    - the whole notebook / folder structure can now now also be imported as note sub-folders

**Comment by pbek** [comment] 2021-07-19 17:28
There now is a new release, could you please test it and report if it works for you?

**Comment by dbogdanov** [comment] 2021-07-19 20:07
Folders work all fine.

Here is an example of a JEX file with a note for which the image is being lost: [test.jex.tar.gz](https://github.com/pbek/QOwnNotes/files/6843610/test.jex.tar.gz)

**Comment by pbek** [comment] 2021-07-20 06:29
The `file_extension` attribute is empty...

```
tossa1.jpg

id: 384d4f403c764f0fa7cf91488f625a1a
mime: image/jpeg
filename: tossa1.jpg
created_time: 2020-01-12T23:16:22.915Z
updated_time: 2020-01-12T23:16:22.915Z
user_created_time: 2020-01-12T23:16:22.915Z
user_updated_time: 2020-01-12T23:16:22.915Z
file_extension: 
encryption_cipher_text: 
encryption_applied: 0
encryption_blob_encrypted: 0
size: 85039
is_shared: 0
type_: 4
```

**Comment by pbek** [comment] 2021-07-20 06:37
I'll try to get around that.

**Comment by dbogdanov** [comment] 2021-07-20 07:59
I think this is a case of notes coming from the Joplin's web clipper.

**Comment by pbek** [comment] 2021-07-20 16:01
I think that should be all of it...

## 21.7.11
- the **[Joplin](https://joplinapp.org/) note import** was improved
  (for [#2189](https://github.com/pbek/QOwnNotes/issues/2189))
    - if Joplin didn't set the file extension of attachments or images in the export
      we now will try to get it from the original file name
    - importing of images from image html tags like `<img src=":/ID"/>` is now also supported
    - the metadata of notes can now optionally be imported as frontmatter

**Comment by pbek** [comment] 2021-07-20 16:09
There now is a new release, could you please test it and report if it works for you?

**Closed** 2021-07-23 08:02 UTC
Labels: Effort: High, Importance: Medium, Type: Feature

**Comment by dbogdanov** [comment] 2021-07-24 11:39
Confirmed. Seems to work perfectly with the latest release on my JEX dump.

**Comment by pbek** [comment] 2021-07-24 16:46
Great, thank you for testing!

**Comment by netguerrilla12** [comment] 2021-08-05 14:49
I seem to missing something. I just installed QOwnNotes. I did a small test import from Evernote using an ENEX file. That worked fine. Then, once I figured out how to extract the data, I did a test import of one of my own JEX. The QOwnNotes progress bar showed that was importing the notes. However, I have no idea where it put the notes. I tested with pbek's export TAR in this scenario. I've attached a couple of screen shots showing what I'm seeing.

Rick
![QOwn 2](https://user-images.githubusercontent.com/88498198/128370664-8379bba6-81b6-4e0a-a3d1-7f156d9f7b38.JPG)
![QOwn 1](https://user-images.githubusercontent.com/88498198/128370666-ffdfa36f-3067-4b5c-ae63-11b7fd53157b.JPG)

**Comment by pbek** [comment] 2021-08-05 16:42
Is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting Debug in Options).

**Comment by netguerrilla12** [comment] 2021-08-05 18:39
I ran the import again with logging enabled. I also selected the option to show the log panel (see 1st screen shot) but I don't anything that looks like a log panel. I noticed that it put the MD files into a folder under my Notes folder (see 2nd screen shot). And I see that it created some new tags but there are no notes in those tags. Well, one of the tags does have a note in it but that note was one of my existing notes. I also found out earlier that I can import those files as text files but that will be a slow process for me since I have a lot of notes. Lastly, I attached the log file.

![QOwn 3](https://user-images.githubusercontent.com/88498198/128403364-be337c16-6fe9-4268-99f4-4a0e8871c6cf.JPG)
![QOwn 4](https://user-images.githubusercontent.com/88498198/128403229-9b9e57cc-9ac7-4e8f-af26-29738313fc1e.JPG)
[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/6940967/QOwnNotes.log)

**Comment by pbek** [comment] 2021-08-06 05:21
I can't seen your whole screen, it looks like your log panel is shrunk somewhere. You can find it better with the menu *WIndow / Unlock panels*.

In your log I see a few notes imported. In your screenshot you have a tag selected, what happens if you click on "All notes" on the top left in the tags panel? I'd need to see that JEX to say more.

**Comment by pbek** [comment] 2021-08-06 05:24
Your JEX could contain a lot of tags (since those are in their own "markdown" files), but no notes or note-tag-assignments.

**Comment by netguerrilla12** [comment] 2021-08-06 13:46
To clarify, what I showed you yesterday was from your export02 test data. But I went ahead and ran the import again. The first screen shot shows All Notes at 9 and it shows the log panel.

![QOwn 5](https://user-images.githubusercontent.com/88498198/128518741-8378dd90-8bb0-46de-a03a-8f1759667d0a.JPG)

The second screen shot shows the folder where I put your export02 test data.

![QOwn 6](https://user-images.githubusercontent.com/88498198/128518847-533037f3-230f-476a-bbf1-2aefa9c82cc5.JPG)

The third screen shot shows where I selected the folder with your test data in it.

![QOwn 7](https://user-images.githubusercontent.com/88498198/128518977-d7f7d6f1-2876-4ca5-844f-ad1f6b9c4ef7.JPG)

The fourth screen shot shows that QOwnNotes imported 23 of 23 files. (By the way, it would be nice if it showed an OK button or gave same indication it was done.)

![QOwn 8](https://user-images.githubusercontent.com/88498198/128519154-7aba409d-57b8-4d00-b5a3-0a635c9c7a52.JPG)

The fifth screen shot shows the UI after the import. All Notes shows 9 notes just like it showed before the import. I do see the four new tags but notice that none of those tags are showing any notes. Also notice that the log panel is the same as it was before.

![QOwn 9](https://user-images.githubusercontent.com/88498198/128519401-94c64a5f-d06f-4b33-baca-25caa484403b.JPG)

The sixth screen shot shows where it put the MD files. (I'm assuming the Test folder is where the files are supposed to be.) So it's creating the MD files as it should. The notes just don't show up in the UI.

![QOwn 10](https://user-images.githubusercontent.com/88498198/128519653-9554dce0-b638-415b-9336-2100ae6ced83.JPG)

Lastly, I deleted the Aug. 05 entries from the log file so you'd have to look at only the Aug. 06 entries. I've attached the log file as well.

[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/6945913/QOwnNotes.log)

**Comment by pbek** [comment] 2021-08-06 14:58
> log panel

strange, that should show a lot of debug messages, is "debug" still turned on in the panel?

> 23 files imported

that looks about right, 9 notes, a couple of tags and a couple of tag assignments...
what was your issue again? 😁

**Comment by netguerrilla12** [comment] 2021-08-06 15:14
Turns out I didn't have debug enabled for the log panel. I'll re-run the import in a little while so we can see if anything shows up in the log panel.

You asked what my issue was. The issue is the fact that the imported notes don't show up anywhere in the UI. All Notes showed 9 notes both before and after the import. I would have expected it to show 11 notes after importing your two notes. The only thing that appeared were the four new tags. I've attached a new screen shot that shows all of the notes the UI sees. (I circled that panel in the screen shot.) All of those notes were notes I imported from Evernote. I would have expected to see your two notes in there after the import.

![QOwn 11](https://user-images.githubusercontent.com/88498198/128532443-2fc7612a-b749-42f6-9ba5-2ed825fe0614.JPG)

**Comment by netguerrilla12** [comment] 2021-08-06 15:26
I just re-ran the import. I've attached a screen shot that shows the results. Just like before, it shows the four new tags that it imported but it shows no new notes anywhere in the UI. This screen shot also shows the debug info in the log panel. I copied all of that data to a text file which I also attached. That file is called LogPanel.txt. Lastly, I attached the main log file again.

![QOwn 12](https://user-images.githubusercontent.com/88498198/128534018-1f5f5974-af91-4c2d-8f8b-60d86a86140c.JPG)

[LogPanel.txt](https://github.com/pbek/QOwnNotes/files/6946430/LogPanel.txt)

[QOwnNotes.log](https://github.com/pbek/QOwnNotes/files/6946432/QOwnNotes.log)

**Comment by netguerrilla12** [comment] 2021-08-06 15:44
I decided to try one more test. This time I imported your two test MD files as text files. The first screen shot shows where I selected them.

![QOwn 13](https://user-images.githubusercontent.com/88498198/128536083-1290ba51-5ee2-4c68-87be-05e0adabd2fd.JPG)

The second screen shot shows the results after it imported the MD text files. Notice that All Notes now shows 11 notes which is what I would expect. Notice also that the notes panel now shows your two test notes which is also what I'd expect.

![QOwn 14](https://user-images.githubusercontent.com/88498198/128536225-7995677f-4228-4e14-a782-654d52413224.JPG)

The Evernote import is a one step process once I select the ENEX file I want to import. I expected the Joplin import to work in a similar manner. However, if I have to run the Joplin import and then import the text files after the fact, I suppose that's fine. It's just an extra step that shouldn't be necessary. Also, if that's the case, that should be in the documentation.

**Comment by pbek** [comment] 2021-08-06 16:08
I really can't help you a lot without you providing the Joplin Export you are trying to import...

**Comment by netguerrilla12** [comment] 2021-08-06 17:05
For some reason, we're miscommunicating. I'm testing with **your** test data. I used your data from export02.tar.gz. You posted a link to that file 19 days ago. I downloaded that file and tested with that.

**Comment by pbek** [comment] 2021-08-06 17:15
Ah, now I see. The notes are of course also supposed to be imported automatically. In your log file I see the notes from my example. Can you try to reload your note folder manually (there is a shortcut for that).

**Comment by netguerrilla12** [comment] 2021-08-06 18:06
I deleted your test notes and tags. Then I imported them again. Then I selected the Reload Note Folder from the menu. The imported notes still don't show up. I did it twice just to make sure. Still nothing. Then I imported your test files as text notes. Again, it imported them just fine and once again they appear in the UI.

**Comment by pbek** [comment] 2021-08-07 08:05
Strange, what operating system are you using?

**Comment by pbek** [comment] 2021-08-07 08:15
According to your screenshots you were importing folders, but it seems you haven't turned note sub-folders on for your note folder. That could be the reason you can't see the notes. Just turn off folders in the Joplin dialog or turn of note sub-folders for your note folder.

**Comment by pbek** [comment] 2021-08-07 08:34
## 21.8.2
- if you don't have note subfolders enabled for the current note folder the
  import of folders is now automatically disabled in the
  **[Joplin](https://joplinapp.org/) note import**

**Comment by pbek** [comment] 2021-08-07 08:48
There now is a new release, could you please test it and report if it works for you?

**Comment by netguerrilla12** [comment] 2021-08-07 13:53
I'm using Windows 10. I'll download the new version and test it.

**Comment by netguerrilla12** [comment] 2021-08-07 14:14
**MUCH BETTER!!!** Thanks for fixing this. I've attached a new screen shot which shows that All Notes is now seeing 17 notes (it was at 10 before I did the test import). I've also highlighted the notes panel which shows the new notes. In addition, you can see one of the new notes in the center panel.

This leads me to another question. In the center panel you can see several lines with special characters in them. For example, the top line which says "Welcome to Joplin!" has special characters at the end of that line. Is there an easy way I can remove these characters? I noticed this the other day but I wanted to get the import issue resolved first. When I first saw the special characters I removed them manually but with thousands of notes to import, that will be a slow and painful process.

![QOwn 17](https://user-images.githubusercontent.com/88498198/128603119-aa3796ff-fc42-4903-9a18-385c34c7075e.JPG)

**Comment by laurent22** [comment] 2021-08-07 14:22
I think the extra characters are emojis. Perhaps it's a matter of importing the notes as UTF-8? (because normally all data in Joplin is UTF-8)

**Comment by netguerrilla12** [comment] 2021-08-07 14:29
I wondered about UTF-8. How do I tell QOwnNotes to import the notes as UTF-8?

**Comment by netguerrilla12** [comment] 2021-08-07 14:39
Interesting. It even shows the special characters in the files names.

![QOwn 18](https://user-images.githubusercontent.com/88498198/128603820-25912c27-393b-4b1d-aa53-0a1c4ac1d4ca.JPG)

**Comment by netguerrilla12** [comment] 2021-08-07 14:47
Even more interesting. I just exported one note from Joplin to a raw Joplin file. This note had no images or attachments. Then I imported this note into QOwnNotes. It imported fine and it's showing no special characters. See the screen shot below. I'll do some more testing over the next few days. I'm liking QOwnNotes so far and if I can get past these bumps, I'm going to move all my notes to QOwnNotes.

![QOwn 19](https://user-images.githubusercontent.com/88498198/128604050-e54afe23-d30e-4cba-8a9f-e250173e10bf.JPG)

**Comment by netguerrilla12** [comment] 2021-08-07 14:59
I did some more testing. Next, I imported a Joplin note with an MP3 attachment. (This is a big one for me because I have lots of notes with MP3 attachments.) The import worked fine. It deleted the '/' characters in the title but that's minor. I tested the MP3 attachment which played just like I'd expect.

Then I exported a Joplin note with several images in it. The import itself worked but it looks like several of the images didn't get imported. I'll do some more in depth testing of this scenario later. Right now, I've got to get on to other things. :)

**Comment by pbek** [comment] 2021-08-07 20:48
If the emojis work usually depend on the installed emojis in the operating system. They work pretty fine on my KDE Neon box. And yes, everything should be UTF-8.

**Comment by netguerrilla12** [comment] 2021-08-08 14:57
I just checked. I have a fairly good assortment of emojis on this machine. They're just the default emojis that Windows 10 comes with. Problem is, without seeing the original note on the author's machine, I have no way to know what emojis QON is having trouble rendering.

So I guess I'll have to leave that issue alone for the moment. I don't put emojis in most of my notes so hopefully that won't be a huge issue. I'll have to test it some more. A greater concern for me is notes that don't import pictures. I'll test that some more, too. Thanks for all your hard work on QON.

**Comment by netguerrilla12** [comment] 2021-08-08 15:24
BTW, I just took a look at a note I imported a few days ago. That note had the following text in it: "is the worldÃ¢â‚¬â„¢s #1 best-selling camera guide author."

I'm 100% sure that's not an emjoi. I'm sure that should say "is the world's #1 best-selling camera guide author." I was curious to see if the issue existed in Joplin so I reimported the JEX file into Joplin. Here's how it appears in Joplin.

![QOwn 20](https://user-images.githubusercontent.com/88498198/128636982-283443c5-cb24-4c62-9cae-177a1941b9f2.JPG)

Here's how that same section appears in QON.

![QOwn 23](https://user-images.githubusercontent.com/88498198/128637030-21301688-d609-424c-a7ae-e2ba3434de35.JPG)

I also realized that that note had an image in it. Here's how it appears in Joplin.

![QOwn 21](https://user-images.githubusercontent.com/88498198/128637056-1be37b44-6729-40af-8368-581d6ddee807.JPG)

And here's how that section appears in QOwn.

![QOwn 22](https://user-images.githubusercontent.com/88498198/128637069-9f92ec5c-5948-4795-80b8-11f162a286b4.JPG)

I've attached the JEX file so you can take a look. GitHub wouldn't let me upload the JEX file so I had to change the name to .ZIP. You can just unzip it to get the MD files.

[RPhotography.zip](https://github.com/pbek/QOwnNotes/files/6951008/RPhotography.zip)

**Comment by netguerrilla12** [comment] 2021-08-09 18:47
I thought of another just now which I just ran. I exported a note from Evernote as an ENEX file. That note has several images in it. Then I imported the note into QON. Here's how it appears in QON after the import.

![QOwn 24](https://user-images.githubusercontent.com/88498198/128757140-4bbba6c7-a1d9-49a2-a4c0-b573b48e3f1b.JPG)

So as you can see that worked fine. It appears that the issue with not importing images only occurs with Joplin notes. I've
attached the ENEX file in case you want to look at that. GitHub wouldn't let me upload an ENEX file so I had to upload it as a ZIP file.

[Evernote Test.zip](https://github.com/pbek/QOwnNotes/files/6956693/Evernote.Test.zip)

**Comment by pbek** [comment] 2021-08-10 07:02
It seems like GitHub really had some issue yesterday, I can't see your two comments you made where I got notifications for. I don't seem to have an issue with your JEX...

The text is fine for me:

![image](https://user-images.githubusercontent.com/1798101/128822622-f13246d8-f26a-46c1-ab77-98ed9a0ee260.png)

And I also see the image:

![image](https://user-images.githubusercontent.com/1798101/128822753-9904ae58-ec49-4eeb-8719-0f881c8a9645.png)

**Comment by pbek** [comment] 2021-08-10 07:03
That was your issue with the image?

**Comment by pbek** [comment] 2021-08-10 07:04
As for the Evernote import, please open a new image on that.
