### ISSUE TITLE
[I] Using some fonts causes ignoring boldness defined in scheme

### ISSUE THREAD

**Issue by FireFragment** [pbek/QOwnNotes#2185] opened 2021-07-12 17:47 UTC
#### Expected behaviour

Editor should follow scheme, including boldness.

#### Actual behaviour

When using some fonts, boldness of text defined in scheme is ignored:

 - ~~Strong text (with `**`s) is bold even when in scheme is defined that it shouldn't be~~ (resolved in 21.7.5).
 - Other texts are not bold, even when in scheme is defined, that they should.

![Markdown Cheatsheet - default - QOwnNotes - 21 7 4 - 1](https://user-images.githubusercontent.com/55660550/125331511-5e0d1c00-e348-11eb-8ee2-c7b2314e06eb.png)

Occurs when using [Fira Code](https://github.com/tonsky/FiraCode) and [Iosefka](https://github.com/be5invis/Iosevka).  
Preview of schema in settings previews theme correctly:

![Settings - 3](https://user-images.githubusercontent.com/55660550/125332432-539f5200-e349-11eb-9512-773d3006abc7.png)

Other fonts works fine for me.

#### Steps to reproduce

1. Download [Fira Code](https://github.com/tonsky/FiraCode) font.
2. In `Editor's fonts and colors` set Fira Code as the default font.
3. Select any scheme with bold headers (eg. `light` or `dark` scheme)
4. Restart the app.
6. See thin headings in the editor.
7. Go back to `Editor's fonts and colors` and copy theme.
8. Click `Strong` -> Uncheck `Bold`
9. Restart the app.
10. See, that strong text still renders bold.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `po čvc 12 19:44:59 2021`
**Version**: `21.7.4`
**Build date**: `Jul  8 2021`
**Build number**: `853`
**Platform**: `linux`
**Operating System**: `Debian GNU/Linux 11 (bullseye)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `/home/firefragment/.configkde/PBE/QOwnNotes.conf`
**Application database path**: `/home/firefragment/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/firefragment/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/firefragment/Notes/notes.sqlite`

## Enabled scripts
</details>

> **NOTE:** For security I removed some of informations.

**Comment by pbek** [comment] 2021-07-12 18:34
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment] 2021-07-12 19:07
Looks like there was a regression in https://github.com/pbek/qmarkdowntextedit/commit/5bb9d5ac7908297f926a8dcf515a740433a70a28, @Waqar144 😉

**Comment by pbek** [comment] 2021-07-12 19:13
## 21.7.5
- if you uncheck `Bold` for `Strong text` in the *Editor fonts & colors* settings
  the text is now really not bold anymore in the editor (for [#2182](https://github.com/pbek/QOwnNotes/issues/2182))
    - the preview now also allows tags like headings and strong to not be bold
      when the editor highlighting styles are used for the preview

**Comment by pbek** [comment] 2021-07-12 19:32
There now is a new release, could you please test it and report if it works for you?

**Comment by FireFragment** [comment] 2021-07-13 18:09
It partially works:  
Strong text is now fine (it isn't bold when it shouldn't be), but headers are still thin.

I think you misunderstood the problem with headers. Headers ***are not*** rendered bold, even when scheme says they ***should be***.  

Thanks for a quick reply! :)

**Comment by Waqar144** [comment] 2021-07-13 18:14
Indeed. Very odd case.

Also, Fira is a really modern font so it could be that Qt has issues with rendering it in bold. One could experiment with Qt creator to make sure.

**Comment by pbek** [comment] 2021-07-13 19:03
Strange I can't reproduce this with other fonts. So it seems to be an issue of the font with Qt.
Since this is a different issue you could open a different issue that will get the tag `Upstream issue` (and probably never fixed in Qt 😅).

**Closed by pbek** 2021-07-13 19:03 UTC
Labels: Severity: Low, Type: Bug - Regression

**Comment by pbek** [comment] 2021-07-13 19:04
I doubt QPlainTextEdit supports ligatures or ligatures fonts...

**Comment by FireFragment** [comment] 2021-07-13 20:12
Interesting is, that strong text is *rendered* bold properly (unless scheme states otherwise).

**Comment by pbek** [comment] 2021-07-13 20:21
For me bold and headline don't look bold with Iosefka...

![image](https://user-images.githubusercontent.com/1798101/125519322-48197fab-2e2c-42be-aecc-f36d75acebfa.png)

**Comment by FireFragment** [comment] 2021-07-13 20:24
Strange...
