### ISSUE TITLE
[I] Last opened note not remembered

### ISSUE THREAD

**Issue by geckolinux** [pbek/QOwnNotes#1924] opened 2020-10-27 20:11 UTC
#### Expected behaviour

Hi there, first of all, many thanks for QOwnNotes!

I'm experiencing an issue where it's not remembering the last opened note upon loading the application. My folder structure is like this:

Main1
	- Sub1
	- Sub2
	- Sub3
	- Sub4
	- Sub5
	- Sub6
	- Sub7
	- Sub8
Main2
Main3
	- Sub1
	- Sub2

#### Actual behaviour

It appears to be always default to opening the first note that exists in `Main1 > Sub2` (`Sub1` is currently empty.)

#### Steps to reproduce

Change to any other folder and open a note there, close the app, reopen, and it defaults to the the first note.

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```
[14:57:53] [warning] QTextCursor::setPosition: Position '157' out of range
```
</details>

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue Oct 27 14:58:16 2020`
**Version**: `20.10.10`
**Build date**: `Oct 27 2020`
**Build number**: `777`
**Platform**: `linux`
**Operating System**: `openSUSE Tumbleweed`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.1`
**Qt Version (runtime)**: `5.15.1`
**Portable mode**: `no`
**Settings path / key**: `/home/myself/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/myself/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `elementary-xfce-dark`
**Notes in current note folder**: `12`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `es_ANY`
**Language codes**: `en_US, es_ANY, es_ES`
**Language names**: `American English (United States), español de España (España), español de España (España)`
**Application dictionaries path**: `/home/myself/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `4`

### Note folder `Main1`

**id**: `1`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/myself/Documents/B/C/D/E/F/G/H`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/myself/Documents/B/C/D/E/F/G/H/notes.sqlite`

### Note folder `Main2`

**id**: `3`
**isCurrent**: `no`
**activeTagId**: `0`
**localPath**: `/home/myself/Documents/B/C/D/QOwnNotes/D`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/myself/Documents/B/C/D/QOwnNotes/D/notes.sqlite`

### Note folder `Main3`

**id**: `4`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/myself/Documents/B/C/D/E/QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/myself/Documents/B/C/D/E/QOwnNotes/notes.sqlite`
</details>

**Comment by pbek** [comment] 2020-10-28 05:26
Strange, I couldn't reproduce that. I selected the 2nd or 3rd note in a subfolder of any depth and QON always remembered the correct note.

Do you get this also when trying to start a new QON session (see https://www.qownnotes.org/getting-started/cli-parameters.html)?

**Comment by pbek** [comment] 2020-10-28 05:30
You didn't post your settings, did you maybe disable that the last open note should be opened in the Genera Settings?

**Comment by pbek** [comment] 2020-11-02 15:25
I will close this issue until there is more information.

**Closed by pbek** 2020-11-02 15:25 UTC
Labels: Type: Support
