### ISSUE TITLE
Encountering a 148 line limit in note editor.

### ISSUE THREAD

**Issue by ryliejamesthomas** [pbek/QOwnNotes#583] opened 2017-05-16 12:40 UTC
Hi. Just ran into this annoying little thing where I can't scroll the note editor pane past 148 lines of text.

I can add text past that limit (by pasting, for example), and can view it in the preview window; just can't get the editor window to scroll down. The editor with scroll down when I initially pass 148 lines, but once I switch to another note then switch back I get stuck.

I've tried restarting the program.

I'm on Arch Linux, version 17.05.3 - AUR - build 333

For now I've just made an extra file as a workaround, so no big emergency or nothin. But 150 lines aint much!

I can't share my file as it contains a lot of private information, I'm afraid.

**Comment by pbek** [comment] 2017-05-16 12:52
I have notes with far over 1000 lines under Manjaro Linux, so I can't reproduce your problem.
What do you mean by getting stuck?
Have you tried turning "Restore cursor position when opening notes" off in the General settings.

**Comment by ryliejamesthomas** [comment] 2017-05-16 12:59
Yep, 'Restore cursor position when opening notes' is checked.

By 'getting stuck' i just mean I get the reported problem, nothing extra (sorry that wasn't clear).

**Comment by pbek** [comment] 2017-05-16 13:02
> Have you tried turning "Restore cursor position when opening notes" off in the General settings?
have you?

What's the output from the debug section in the settings dialog?
Is there any relevant log output (you have to enable enable the log widget)?

**Comment by ryliejamesthomas** [comment] 2017-05-16 13:16
Nothing relevant in the log, just

```
[May 16 23:06:34] [scripting]: loading script file: /mnt/shared/ownCloud/Notes/scripts/style_loader.qml
[May 16 23:06:34] [scripting]: loading script file: /mnt/shared/ownCloud/Notes/scripts/new_note.qml
[May 16 23:06:34] [scripting]: loading script file: /mnt/shared/ownCloud/Notes/scripts/pin-note.qml
[May 16 23:06:34] [scripting]: loading script file: /mnt/shared/ownCloud/Notes/scripts/favorite-note.qml
[May 16 23:06:44] [status]: Stored 1 note(s) to disk
[May 16 23:07:04] [status]: Stored 1 note(s) to disk
[May 16 23:07:14] [status]: Stored 1 note(s) to disk
[May 16 23:07:54] [status]: Stored 1 note(s) to disk
```
I tried disabling the scripts and restartign and no difference.

Debug output is:

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Tue. May 16 23:12:13 2017`
**Version**: `17.05.3`
**Build date**: `May 10 2017`
**Build number**: `333`
**Platform**: `linux`
**Operating System**: `Antergos Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.8.0`
**Qt Version (runtime)**: `5.8.0`
**Portable mode**: `no`
**Settings path / key**: `/home/x/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/x/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_AU`
**Locale (interface)**: *empty*
**Icon theme**: `Numix-Square`
**Notes in current note folder**: `58`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `x`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `9.1.4.2`
**appVersion**: `16.09.0`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `shared`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/mnt/shared/ownCloud/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `Game ideas`
**database file**: `/mnt/shared/ownCloud/Notes/notes.sqlite`

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `true`
**DistractionFreeMode/editorWidthMode**: `3`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `20`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**FileDialog/LastPath**: `/mnt/shared/ownCloud/Notes/scripts`
**FileDialog/LastPath-NotePDFExport**: `/home/x/Desktop`
**FileDialog/LastPath-ScriptPath**: `/mnt/shared/ownCloud/Notes/scripts`
**LastUpdateCheck**: `2017-05-16T23:09:33`
**LinkDialog/geometry**: `<binary data>`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `19`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1**: `selectbutton/Wiki, Game ideas, Computer`
**MainWindow/noteTextEdit.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font**: `Open Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font**: `monospace,10,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font**: `Open Sans,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**NoteDialog/geometry**: `<binary data>`
**NoteDiffDialog/geometry**: `<binary data>`
**NoteSortOrder**: `0`
**PiwikClientId**: `<hidden>`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**ShowSystemTray**: `false`
**SortingModeAlphabetically**: `false`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `7a480995-328d-44cb-867b-77a8c43eca0a`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `13`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**noteSaveIntervalTime**: `10`
**notesPath**: `/mnt/shared/ownCloud/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `x`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: `x`
**ownCloud/userName**: `x`
**previousWorkspace**: `d04da1a7-2eb8-4484-ac71-7b3093510a5e`
**recentNoteFolders**: `/mnt/shared/ownCloud/notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `x`
**showMenuBar**: `true`
**showStatusBar**: `false`
**tagWasAddedToNote**: `true`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `main toolbar`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `formatting toolbar`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `inserting toolbar`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `encryption toolbar`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `window toolbar`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `quit toolbar`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**workspace-7a480995-328d-44cb-867b-77a8c43eca0a/name**: `full`
**workspace-7a480995-328d-44cb-867b-77a8c43eca0a/noteSubFolderDockWidgetVisible**: `true`
**workspace-7a480995-328d-44cb-867b-77a8c43eca0a/windowState**: `<binary data>`
**workspace-d04da1a7-2eb8-4484-ac71-7b3093510a5e/name**: `minimal`
**workspace-d04da1a7-2eb8-4484-ac71-7b3093510a5e/noteSubFolderDockWidgetVisible**: `true`
**workspace-d04da1a7-2eb8-4484-ac71-7b3093510a5e/windowState**: `<binary data>`
**workspaces**: `7a480995-328d-44cb-867b-77a8c43eca0a, d04da1a7-2eb8-4484-ac71-7b3093510a5e`

## System environment

**XDG_MENU_PREFIX**: `xfce-`
**LANG**: `en_AU.UTF-8`
**QT_STYLE_OVERRIDE**: `gtk`
**EDITOR**: `/usr/bin/nano`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_VTNR**: `7`
**GLADE_CATALOG_PATH**: `:`
**XDG_SESSION_ID**: `c2`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/x`
**USER**: `x`
**GLADE_MODULE_PATH**: `:`
**DESKTOP_SESSION**: `xfce`
**LC_COLLATE**: `en_AU.UTF-8`
**PWD**: `/home/x`
**HOME**: `/home/x`
**BROWSER**: `/usr/bin/chromium`
**XDG_SESSION_TYPE**: `x11`
**XDG_DATA_DIRS**: `/usr/local/share:/usr/share`
**XDG_SESSION_DESKTOP**: `xfce`
**GLADE_PIXMAP_PATH**: `:`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**MAIL**: `/var/spool/mail/x`
**SHELL**: `/bin/bash`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_CURRENT_DESKTOP**: `XFCE`
**SHLVL**: `1`
**XDG_SEAT**: `seat0`
**GDMSESSION**: `xfce`
**LOGNAME**: `x`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XAUTHORITY**: `/home/x/.Xauthority`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
**_**: `/usr/bin/xfce4-session`
**SESSION_MANAGER**: `local/thinkpad:@/tmp/.ICE-unix/764,unix/thinkpad:/tmp/.ICE-unix/764`
**SSH_AUTH_SOCK**: `/tmp/ssh-aMfVt9bgTHHo/agent.770`
**SSH_AGENT_PID**: `771`
**DISPLAY**: `:0.0`

**Comment by pbek** [comment] 2017-05-16 13:29
I've no idea what is causing this.
But you still haven't tried turning off `restoreCursorPosition`...

**Comment by pbek** [comment] 2017-05-16 13:31
Have you tried moving the app to your other screen?

**Comment by ryliejamesthomas** [comment] 2017-05-16 13:32
Oh whoops, I missread you. I've tried turnign that off now and no luck.

An yep, I've tried it on my main screen, and tried disconecting the second monitor too.

**Comment by pbek** [comment] 2017-05-16 13:34
The last thing that comes to mind is that you try using an other Qt / KDE app with a QTextEdit to see if you have the same problem...

**Comment by ryliejamesthomas** [comment] 2017-05-16 13:37
I'll give that a go tomorrow. Thanks for trying to help!

**Comment by pbek** [comment] 2017-05-17 07:41
I will close this issue until there is more information.

**Closed by pbek** 2017-05-17 07:41 UTC
