### ISSUE TITLE
windows-b5460 release fails; previous release windows-b5434 works properly

### ISSUE THREAD

**Issue by answerquest** [pbek/QOwnNotes#1656] opened 2020-03-11 11:18 UTC
#### Expected behaviour
QOwnNotes should work on Windows 10

#### Actual behaviour
Latest windows build errors out saying a Qt plugin could not be loaded, but the windows build before that succeeds

#### Steps to reproduce
- On Win 10 OS
- Download latest win release from the website or Releases section: **windows-b5460** : https://github.com/pbek/QOwnNotes/releases/tag/windows-b5460
- Unzip and double-click QOwnNotes.exe
- It fails. An error popup is seen, saying something about Qt plugin not available or something.
- Remove this and go back to Releases page, browse to previous Windows release: **windows-b5434** https://github.com/pbek/QOwnNotes/releases/tag/windows-b5434 
- Install this one. And it works.

**Comment by pbek** [comment] 2020-03-11 11:22
Thank you for reporting, I will try to reproduce your issue when I have access to a Windows box.

Can anyone else reproduce this issue?

**Comment by pbek** [comment] 2020-03-11 15:10
I cannot reproduce your issue. I just upgraded on Windows 10.

## General Info

**Version**: `20.3.3`
**Build date**: `Mar 10 2020`
**Build number**: `5460`
**Platform**: `windows`
**Operating System**: `Windows 10 (10.0)`
**Build architecture**: `i386`
**Current architecture**: `x86_64`
**Release**: `AppVeyor`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`

**Comment by pbek** [comment] 2020-03-11 15:12
How are you running QOwnNotes? Maybe your Windows doesn't use the correct working directory to run the EXE. It has to be the directory where the EXE is at.

**Comment by answerquest** [comment] 2020-03-12 10:23
Hi @pbek , I'm doing the typical thing: unzip to a folder, go into that folder and double-click the .exe .Both normal and as-admin giving same error.

I'm using one version lower now and that is working fine: QOwnNotes - version 20.3.2 - AppVeyor - build 5434

My windows laptop is a corporate one with tons of corporate interventions. Not standard. So something may be interfering. 

But older version is working fine so I'm inclined to think maybe one of the supporting files is improper. When I was searching online for the error message I found some mentions about "libEGL.dll".

**Comment by pbek** [comment] 2020-03-12 10:31
`libEGL.dll` is present in both released ZIP files, so I don't know what is interfering...

Can you please open your terminal (`cmd.exe`) and `cd` to the QOwnNotes directory and run `QOwnNotes.exe` from there.

**Comment by pbek** [comment] 2020-03-19 20:18
I will close this issue until there is more information.

**Closed by pbek** 2020-03-19 20:18 UTC
Labels: Type: Support
