### ISSUE TITLE
Email addresses in code blocks picked up as attachments.

### ISSUE THREAD

**Issue by aberfan** [pbek/QOwnNotes#2720] opened 2023-02-02 09:06 UTC
**Version**: `23.1.3`
**Build date**: `Jan 27 2023`
**Build number**: `1006`
**Platform**: `windows`
**Operating System**: `Windows 7 Version 6.1 (Build 7601: SP 1)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`

#### Expected behaviour
When I enter text in code blocks (``` these ```) it shouldn't be parsed.

#### Actual behaviour
QownNotes thinks that email addresses are attachments.  

#### Steps to reproduce

Doing this:

````
```
From: Some Person <person@emailaddress.com>
to: me@email.com
date: Jan 26, 2023, 4:25 AM
subject: Email subject here

This is an email body
```
````

Results, in QownNotes, of this:
````
```
From: Some Person [person@emailaddress.com](file:///c/path/to/qownnotes/../../node/person@emailaddress.com)
to: me@email.com
date: Jan 26, 2023, 4:25 AM
subject: Email subject here

This is an email body
```
````
It shouldn't be doing any rendering in a code fence, and obviously, there's no attachment in those places.

**Comment by pbek** [comment] 2023-02-02 09:12
Hah, funny. 😁  Thank you for reporting.

@Waqar144, do you think there could be anything done about this?

**Comment by Waqar144** [comment] 2023-02-02 09:48
I think this is an issue with the preprocessing where it tries to detect note links and changes them not with code block handler. 

It should be possible to fix this by using a proper solution for md to html conversion that allows us to plug in our own changes. But the way it is done now, I don't think it can be fixed in a reliable way i.e simple regex doesn't know about context and will fail in any non basic scenario.

**Comment by pbek** [comment] 2023-02-02 14:53
Hm, too bad...

**Comment by Waqar144** [comment] 2023-02-03 12:13
It might be possible by using md4c in a more level way to handle this in a better way.

we currently just call md_html() and that gives us the html we need. Instead if we use the lower level api `md_parse` and install our own callback functions and then do whatever we want when there is a link span, the output might be better.

**Comment by aberfan** [comment] 2023-02-03 14:08
This is probably a really dumb question, but is there any way to just say "Don't do anything with the text between here"?  As in, \`\`\`pre shouldn't parse for links or anything?  (Vs \`\`\`javascript or \`\`\`bash where there is and you'd expect syntax highlighting)

Thank you guys for actually looking into this; it's not a big deal, since it's not modifying the actual notes, only the rendering, but it's a pretty weird cosmetic output.

**Comment by aberfan** [comment] 2023-02-13 07:44
I want to add something I noticed, which I would think someone else reported, but having HTML in a code block removes it from being previewed.  Ex:
````
```javascript

class floatPanel extends HTMLElement {
  constructor() {
  const internalTemplate = `
   <div id="floatPanelCustom" class="noprint">
        <span class="labelText">Utility:</span>
        <BR>
        <BR>
        <button id="fixFormatBtn" type="button">Fix Formatting</button>
        <button id="saveDataBtn" type="button">Save Values</button>
        <BR>
        <BR>
        <span id="statusText">Status</span>
   </div>
  `;
```  
````
Renders as:
![image](https://user-images.githubusercontent.com/72705523/218398089-e1705a39-0627-4016-995c-85d65abddd0a.png)

Am I missing something in usage? What is the markdown method of saying "Don't touch this text or render it in any way, beyond making it pretty colors"?

Is this a regression? It seems like this used to work --- this is much more of an issue than just the email addresses being modified.

**Comment by pbek** [comment] 2023-02-13 10:11
Hm, I can't reproduce that...

![image](https://user-images.githubusercontent.com/1798101/218430161-04b38e2a-6e83-4210-b5e3-7a137149b53a.png)

**Comment by aberfan** [comment] 2023-02-13 16:59
I swear I'm not insane!  This is bizarre!  What can I do to try to figure out why it's insisting on rendering, instead of doing the correct behavior??  I don't think any of the scripts I have enabled are relevant, but including those... I haven't gone through and disabled to see.  There isn't some setting that would be relevant, is there? This absolutely should not be rendering...

![17b470429ac68dda8b1f322beb509695](https://user-images.githubusercontent.com/72705523/218521760-06279dd7-1e2d-4bdc-87db-b25dc38e28cf.png)
![267196fcde996e1ddb18c39627d312fa](https://user-images.githubusercontent.com/72705523/218521787-0f96b9a4-839e-466a-8dd5-9d61778488dd.png)
![924a6da20c84f8cfd2ec448dcce1ff17](https://user-images.githubusercontent.com/72705523/218521803-c033c0a0-3ee5-4ad5-b868-4424f62fd95c.png)

**Comment by pbek** [comment] 2023-02-13 20:55
Can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it.

**Comment by pbek** [comment] 2023-02-13 20:56
Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

**Comment by aberfan** [comment] 2023-02-13 22:45
> Do you have the same issue when running QOwnNotes in a new session (see [cli-parameters](https://www.qownnotes.org/getting-started/cli-parameters.html))?

I tried running with the --session test, and same exact issue.  For future reference, how do you make it so the edit window and preview window are _not_ synchronized? I wanted to take a screenshot, but the two would not line up, and I couldn't get them to stop moving. (I saw an "unsticky tab" option, but it didn't do it)

What's weird is the _editor_  (QOwnNotes's ) shows it properly ... or at least, the syntax highlighting is correct, and it sees it as a code block and doesn't try to render it.  (I should note, I use an external editor, and always just have the "Preview" tab in QOwnNotes, and that's what I've been doing screenshots of)

Debug, with private info redacted, also, I had disabled all scripts and issue was still present.
```

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mon Feb 13 16:25:19 2023`
**Version**: `23.1.3`
**Build date**: `Jan 27 2023`
**Build number**: `1006`
**Platform**: `windows`
**Operating System**: `Windows 7 Version 6.1 (Build 7601: SP 1)`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `yes`
**Application arguments**: `QOwnNotes.exe`, `--portable`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Primary screen resolution**: `1920x1080`
**Screen resolution(s)**: `1920x1080, 1920x1080, 1080x1920, 1080x1920`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `249`
**Calendar items**: `0`
**Enabled scripts**: `9`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: `auto`
**Language codes**: `en-medical, en_GB, en_US`
**Language names**: `American English (medical), British English (United Kingdom), American English (United States)`
**Application dictionaries path**: `C:\qnotes\Data\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `redact`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**remotePath**: *empty*
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `yes`
**activeNoteSubFolder name**: `redact`

## Cloud connections
### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActionDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**AttachmentDialog/geometry** (QByteArray): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DictionaryManagerDialog/geometry** (QByteArray): `<binary data>`
**DictionaryManagerDialog/mainSplitterState** (QByteArray): `<binary data>`
**DistractionFreeMode/editorWidthCustom** (QString): `80`
**DistractionFreeMode/editorWidthMode** (QString): `4`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `25`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-046e1c8d-9175-4272-81d8-203febd5bc8a`
**Editor/autoBracketClosing** (QString): `false`
**Editor/autoBracketRemoval** (QString): `false`
**Editor/centerCursor** (QString): `false`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `false`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `3`
**Editor/removeTrailingSpaces** (QString): `false`
**Editor/showLineNumbers** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**FileDialog/LastPath-ExternalEditor** (QString): `C:/Program Files (x86)/Notepad++`
**FileDialog/LastPath-GitExecutable** (QString): `C:/Program Files/Git/bin`
**FileDialog/LastPath-ScriptSettingsFile-external-note-open-executablePath** (QString): `C:/Program Files (x86)/Notepad++`
**ImageDialog/disableCopying** (QString): `false`
**ImageDialog/geometry** (QByteArray): `<binary data>`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2023-02-13T16:21:13.028`
**LocalTrashDialog/geometry** (QByteArray): `<binary data>`
**LogWidget/criticalLog** (QString): `true`
**LogWidget/debugLog** (QString): `true`
**LogWidget/fatalLog** (QString): `true`
**LogWidget/infoLog** (QString): `true`
**LogWidget/scriptingLog** (QString): `true`
**LogWidget/statusLog** (QString): `true`
**LogWidget/warningLog** (QString): `true`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-2** (QString): `deprecated`
**MainWindow/noteTextEdit.code.font** (QString): `Source Code Pro,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `Amazon Ember,11,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `Source Code Pro,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `Accord SF,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.refreshDebounceTime** (QString): `600`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/script-install-successful** (QString): `1024`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteDialog/tabWidgetIndex** (QString): `0`
**NoteFolder-1/NoteTabNameList** (QStringList): `Requester Mappings, Identity`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/allowDifferentNoteFileName** (bool): `true`
**NoteFolder-2/NoteTabSubFolderPathDataList** (QString): 
**NoteFolder-2/allowDifferentNoteFileName** (QString): `true`
**NoteHistory-1** (QVariantList): `<variant list with 200 item(s)>`
**NoteHistory-2** (QVariantList): `<variant list with 40 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `199`
**NoteHistoryCurrentIndex-2** (QString): `39`
**OrphanedImagesDialog/geometry** (QByteArray): `<binary data>`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/geometry** (QByteArray): `<binary data>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `0`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**SettingsExport/platform** (QString): `windows`
**ShareDialog/geometry** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**TableDialog/geometry** (QByteArray): `<binary data>`
**TagAddDialog/geometry** (QByteArray): `<binary data>`
**UpdateDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `true`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `true`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `true`
**checkSpelling** (QString): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**cursorWidth** (QString): `1`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `false`
**enableWebAppSupport** (QString): `false`
**externalEditorPath** (QString): `../../../Program Files (x86)/Notepad++/notepad++.exe`
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `86400`
**gitExecutablePath** (QString): `C:/Program Files/Git/bin/git.exe`
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**ignoredNoteFiles** (QString): *empty*
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): `yyyy.MM.dd hh:mm`
**interfaceFontSize** (QString): `15`
**interfaceLanguage** (QString): `en`
**interfaceStyle** (QString): `windowsvista`
**internalIconTheme** (QString): `true`
**itemHeight** (QString): `16`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `false`
**localTrashSplitterSizes** (QByteArray): `<binary data>`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelAutoSelect** (QString): `true`
**navigationPanelHideSearch** (QString): `true`
**networking/ignoreSSLErrors** (QString): `false`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `true`
**noteEditIsCentralWidget** (QString): `false`
**noteFileExtensionList** (QStringList): `md, txt`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `300`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `true`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `true`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `0`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `1`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `0`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `false`
**restoreLastNoteAtStartup** (QString): `false`
**restoreNoteTabs** (QString): `true`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**tagWasAddedToNote** (QString): `true`
**taggingShowNotesRecursively** (QString): `true`
**tagsPanelHideNoteCount** (QString): `true`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `1`
**todoCalendarSupport** (QString): `false`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, `
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useSoftWrapInNoteEditor** (QString): `true`
**useUNIXNewline** (QString): `false`
**webAppClientService/serverUrl** (QString): `wss://app.qownnotes.org`
**webAppClientService/token** (QString): `<hidden>`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/commandSnippetsNoteName** (QString): `Commands`
**webSocketServerService/commandSnippetsTag** (QString): `commands`
**webSocketServerService/port** (QString): `22222`
**webSocketServerService/token** (QString): `<hidden>`
**workspace-290152e5-8901-461d-81d3-22feb4900db6/name** (QString): `Slimdown`
**workspace-290152e5-8901-461d-81d3-22feb4900db6/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-290152e5-8901-461d-81d3-22feb4900db6/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
```

Are there any things I can try doing in the code fence itself, to see if it matters?  Since it's QT, you'd think the rendering should be consistent?   I know my system is ancient, but this shouldn't matter, since it's the same (presumably) libraries?

**Comment by pbek** [comment] 2023-02-14 07:54
>  how do you make it so the edit window and preview window are not synchronized?

you could open the note in another window (right click on it in the note list)

**Comment by aberfan** [comment] 2023-03-18 04:47
I wanted to check in and see if there was any progress with this. I'm hitting it quite frequently, and I'm surprised others aren't: if there's something particular to my setup (like running in portable mode) I'm happy to try something else. 

It's weird the editor in QOwnNotes can properly render in place, but the actual markdown preview can't. 

I want to add another rendering issue I ran into this evening.

Trying to ~~strike out~~ notes that have a url won't work if it's a proper url.
```
~~test  [http://test.com/]~~

~~[http://this is a test.com]~~
```
![e5b375a8ae55d48736e1bededf46624d](https://user-images.githubusercontent.com/72705523/226085050-2d6536e7-b14c-4827-8671-80afa7ede5fa.png)

Adding a backslash before the period in the first one _will_ allow it to be properly stuck out.   

I mean, if these issues are because I'm using Windows, I'll get a Linux system running to use QOwnNotes, since it's become a big part of my workflow.

**Comment by pbek** [comment] 2023-03-18 10:06
I'm sorry, no news on that front... But pull requests are welcome to be reviewed!

**Comment by pbek** [comment] 2023-03-19 10:54
> I think this is an issue with the preprocessing where it tries to detect note links and changes them not with code block handler.
> 
> It should be possible to fix this by using a proper solution for md to html conversion that allows us to plug in our own changes. But the way it is done now, I don't think it can be fixed in a reliable way i.e simple regex doesn't know about context and will fail in any non basic scenario.

Yup, hard to get around in...

https://github.com/pbek/QOwnNotes/blob/0f8871811fd0ba63f43d095a68ede6131ee5c7de/src/entities/note.cpp#L2399-L2409

**Comment by pbek** [comment] 2023-03-19 11:06
This particular issue with `<person@emailaddress.com>` I can prevent in https://github.com/pbek/QOwnNotes/commit/909de64ff2eaf6f7091f43a6ebbf887b1a21dffe, but this doesn't solve the general issue of text replacements in code blocks, so there should be another issue for that.

**Comment by aberfan** [comment] 2023-03-19 18:11
At the risk of asking a very naive question and being mocked, why are codeblocks being parsed for markdown at all? Even as just using three tildas, or three tildas and "pre", it's broken, but my understanding is that nothing inside should be treated as anything specially at all; especially if it's just 'pre' where there isn't any syntax highlighting desired.

And I wish I could contribute code-wise, but this is way above me.  Thank you again for sharing it with the world and your hard work.

**Comment by pbek** [comment] 2023-03-20 07:26
Good question. Above code has no concept about code blocks or where the are. The regular expression is run on the whole note.

@Waqar144, do you maybe know if there is a way in md4c to do some context aware parsing?

**Comment by pbek** [comment] 2023-03-20 14:12
## 23.3.7
- text parts with an `@` in it will now not be detected as note link
  (for [#2720](https://github.com/pbek/QOwnNotes/issues/2720))

**Comment by pbek** [comment] 2023-03-20 14:14
There now is a new release, could you please test it and report if it works for you?

**Comment by aberfan** [comment] 2023-03-20 15:11
> There now is a new release, could you please test it and report if it works for you?
Yes, verified, 23.3.7 no longer parses email within code blocks; thanks!

**Comment by pbek** [comment] 2023-03-20 15:16
Great, thank you for testing!
Then for all other issues please feel free to open new ones. (E.g. the general issue of things being replaced in code blocks, not only out of them)

**Closed** 2023-03-20 15:16 UTC
Labels: Type: Bug, Severity: Low
