### ISSUE TITLE
Feature request: Support CalDAV tasks from non-ownCloud servers

### ISSUE THREAD

**Issue by Letterus** [pbek/QOwnNotes#312] opened 2016-09-05 10:37 UTC
Even though I stopped using OwnCloud (we just could not become friends) I proceed using QOwnNotes because it just does nicely what I need. And it works well combined with the Seafile wiki function and the Seafile mobile app.

There's just one drawback: I can't use the tasks feature of QOwnNotes even though I often like to take notes in my tasks which I sync using CalDAV. Currently I'm managing all my tasks stuff in "2Do", but it would be nice if I could do task notes in QOwnNotes as well.

As ownCloud supports CalDAV as well: Would it be possible to use CalDAV as interface for the tasks feature? This standard interface would open this feature of QOwnNotes to a even wider range of users and backends.

**Comment by pbek** [comment] 2016-09-05 10:45
The tasks are using CalDAV, but the paths are hardcoded to ownCloud's need and the user credentials and host name are taken from the ownCloud settings.

**Comment by Letterus** [comment] 2016-09-05 10:47
Uh, that sounds great. So it would be easily possible to make this work with other platforms? ;-)

**Comment by pbek** [comment] 2016-09-05 10:55
Easily? No, not very. :)

**Comment by pbek** [comment] 2016-09-05 11:01
Providing an account on the CalDAV server to test certainly would help... I don't even know if every server works the same...

**Comment by pbek** [comment] 2016-09-05 11:03
If you want to PGP encrypt me something, here's my key: https://keybase.io/pbek ;)

**Comment by Letterus** [comment] 2016-09-05 12:02
If it's okay for you it's probably the easiest way to register an account at fruux. It's free and they are the maintainers of the sabre/dav library, aiming very high standards compatibility. If QOwnNotes works with fruux it's highly probable it works with all proper implementations of sabre/dav (including OwnCloud).

**Comment by pbek** [comment] 2016-09-08 15:33
I'm currently working on that. There are some bumps I have to smooth out...

**Comment by Letterus** [comment] 2016-09-08 15:43
Great to hear! Have a successful coding session! :)

**Comment by pbek** [comment] 2016-09-10 11:20
## 16.09.4
- you can now also manage todo lists from a **custom CalDAV server**
    - this should already work
        - listing of all calendars in the settings dialog
        - listing of all tasks of a calendar in the todo dialog
        - creating new tasks
        - removing tasks
        - setting tasks to completed / uncompleted
    - work in progress
        - showing the calendar names instead of the hashes from the server
        - not showing an error message when switching to CalDAV in the
          settings if no server url is entered
        - storing additional information to a task, such as description,
          priority and reminder date
        - showing a better warning dialog if CalDAV username / password
          are wrong, currently there only is a warning in the log dialog

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment] 2016-09-11 16:34
I've started to have some CalDAV error pop-up every time I open app settings, with CalDAV off.

**Comment by pbek** [comment] 2016-09-11 16:44
Oh, I "love" such regressions. Thanks a lot for reporting! Are you using ownCloud in QOwnNotes and if yes does the connection work?

**Comment by pbek** [comment] 2016-09-11 17:04
Will be fixed in 16.09.5.

**Comment by pbek** [comment] 2016-09-11 17:16
## 16.09.5
- more todo list features
    - storing of additional information to a task, such as description,
      priority and reminder date for custom CalDAV servers (this was
      tested with [Fruux](https://fruux.com))
    - the display name of the calendar will now be shown instead of the
      hash of the calendar
    - there now is a button to clear your calendar item cache in the
      todo settings, so that all todo list items will be reloaded from
      your server the next time you open your todo dialog
    - fixed a problem where an error message is shown every time you
      open your settings dialog when you don't have entered a ownCloud
      server name or when you switch to a the custom CalDAV server
      and have no server name entered yet in the todo settings

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Maboroshy** [comment] 2016-09-11 17:46
I don't use any in-app sync features.

**Comment by Letterus** [comment] 2016-09-11 17:47
Really nice! Works great so far. Absolutely a feature very nice to have! Tested 16.09.5 with Fruux.
I'll test it "in production" and report if I experience any issues.

Just two hints for improvement:
1. It took me some moments to get which address I have to enter in the settings form. So maybe the description of this field could be more precise like "Kalender Basis URL" (or what else would be accurate in German) instead of "Server URL"?
2. The list of calendars in the settings window shows event lists as well task lists. I know they are technically the same, but Fruux has an attribute or something to distinguish them (either "events" or "tasks" or "events & tasks"). For me it would be nice if only those calendars marked as "tasks" or "tasks & events" (at Fruux) would be listed in the window.

**Comment by pbek** [comment] 2016-09-11 17:54
@Maboroshy, does it work now (is the error message gone)?
@Letterus 1) yes, I was already searching for a better name, but I haven't found any so far, maybe ´Calendar base url` is a good choice
2) that's already on my todo list ;)

**Comment by Letterus** [comment] 2016-09-11 18:05
Great! :)

Now I found something like a bug: I added the task list "Eingang" which contains a lot of "done" tasks but only 6 or so which are not marked as done. QOwnNotes shows all of these tasks even if the check box for "done" tasks is unchecked. If I check it 6 additional tasks are displayed but I don't know why. They are by far not the only ones which are "done" (the tasks shown then are not those which are "not done". So it is not an inversion bug.).

**Comment by Maboroshy** [comment] 2016-09-11 18:05
No errors on 16.09.5

**Comment by pbek** [comment] 2016-09-11 19:02
@Letterus so Fruux outputs done tasks differently than ownCloud?
@Maboroshy, thank you!

**Comment by Letterus** [comment] 2016-09-11 19:08
Yep, basically that's it. :-)

**Comment by pbek** [comment] 2016-09-12 08:03
@Letterus, I can't reproduce your "done problem".

this is what I did:

- I created a new task in Fruux
- I set this task to done in Fruux
- I synced my tasks in QOwnNotes
- The task was shown as "done"

**Comment by Letterus** [comment] 2016-09-12 09:07
Thank you for investigating. This is correct, it works for me the same.

But: When I add a task in my tasks app "2Do" and mark it as done it is shown as "done" in the Fruux webinterface but not in QOwnNotes. Conclusion: There must be an additional attribute which should be checked to see if a task is marked as "done".

So I compared two tasks - one marked as done in Fruux, one in 2Do: Both show "STATUS:COMPLETED" and "COMPLETED:20160912T084618Z". But the Fruux task is also showing "PERCENT-COMPLETE:100". Maybe QOwnNotes is only checking PERCENT-COMPLETE?

I'm attaching both items for your own comparison.
[Eingang.ics.txt](https://github.com/pbek/QOwnNotes/files/466928/Eingang.ics.txt)

**Comment by pbek** [comment] 2016-09-12 09:24
Or with other words, 2Do only sets the completed status, but not the "percent-complete"...
Thank you for your sample file, I will take that into account in v16.09.6. Although I can't test it, because it already worked in all CalDAV clients I have at hand.

**Comment by pbek** [comment] 2016-09-12 16:56
## 16.09.6
- fixed a possible crash if the option to use a custom CalDAV server was
  selected in the todo settings, but no server url was entered
- only calendars that can hold todo items will now be shown in the
  calendar list in the todo settings
- the completed status of ical items will now also be taken into account
  then checking for completed todo items on your CalDAV server
- because of the changes made to the viewing of calendar names you now
  have to select them again in the todo settings
- now an error message is shown if the username or password to your
  CalDAV server is incorrect

There now is a new release, could you please test it and report if the new features work for you?

**Comment by Letterus** [comment] 2016-09-12 17:45
Works. Thank you very much for implementing and fixing this so quickly.

**Comment by pbek** [comment] 2016-09-13 04:53
Great to hear! It was even more work than I imagined and introduced a lot of side effects. ;)

**Closed by pbek** 2016-09-13 04:53 UTC
Labels: enhancement

**Comment by pbek** [comment] 2016-09-13 05:29
@Letterus, if you want to translate the new texts for it you can do so at: <https://crowdin.com/translate/qownnotes/1/en-de>
