### ISSUE TITLE
Copy & Paste copied with new line in front

### ISSUE THREAD

**Issue by 2Fake** [pbek/QOwnNotes#1171] opened 2019-04-03 12:13 UTC
Hi, 

i have a small problem with copy and paste some information from a note in preview view.
This is the text in edit mode:
Data Matrix Code 1409301750001652
If i switch to the preview mode and copy a string like this.
![image](https://user-images.githubusercontent.com/17730741/55477781-4481b380-561a-11e9-8bba-459c0390874c.png)
in my clipboard is the number but if i copy it into another editor, there is the number but with an new line before it
![image](https://user-images.githubusercontent.com/17730741/55477871-7e52ba00-561a-11e9-96dc-dc471602f12b.png)

**Comment by pbek** [comment] 2019-04-03 12:59
I'm sorry, I cannot reproduce this.

Could you please use the issue assistant in the `Help` menu to post this issue so you can provide needed information more easily?

The menu entry is named `Post questions, feature requests or issues`.

**Comment by 2Fake** [comment] 2019-04-03 13:07
#### Expected behaviour

Copy (ctrl + c) copies the actual marked string

#### Actual behaviour

CTRL + C copies the string with a new line in front

#### Steps to reproduce

Mark a string. Hit CTRL + C. Insert to another text editor

#### Relevant log output in the Log panel

```
[15:05:53] [status] Die Aufgaben werden von Ihrem Server geladen
```

#### Information about the application, settings and environment

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Mi. Apr. 3 15:06:13 2019`
**Version**: `18.09.4`
**Build date**: `Sep 26 2018`
**Build number**: `479`
**Platform**: `linux`
**Operating System**: `KDE neon User Edition 5.15`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Launchpad PPA`
**Qt Version (build)**: `5.5.1`
**Qt Version (runtime)**: `5.12.0`
**Portable mode**: `no`
**Settings path / key**: `/home/Markus.Bong/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/Markus.Bong/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`, `-session`, `1020a1b018619a000155265456900000074840031_1554218210_662331`
**Qt Debug**: `0`
**Locale (system)**: `de_DE`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-qownnotes`
**Notes in current note folder**: `36`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: `https://nc.famabo.de`
**appIsValid**: `yes`
**notesPathExists**: `yes`
**serverVersion**: `15.0.4.0`
**appVersion**: *empty*

## Note folders

**currentNoteFolderId**: `1`

### Note folder `Standard`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `-1`
**localPath**: `/media/data/nextcloud/Lokal/Notes`
**remotePath**: `Notes`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `devolo`
**database file**: `/media/data/nextcloud/Lokal/Notes/notes.sqlite`

## Enabled scripts

## Settings

**AboutDialog/geometry**: `<binary data>`
**ActionDialog/geometry**: `<binary data>`
**ActiveNoteHistoryItem**: *empty*
**Debug/fakeOldVersionNumber**: `false`
**Debug/fileLogging**: `false`
**DistractionFreeMode/isEnabled**: `false`
**DistractionFreeMode/menuBarGeometry**: `<binary data>`
**DistractionFreeMode/menuBarHeight**: `30`
**DistractionFreeMode/menuBarVisible**: `true`
**DistractionFreeMode/windowState**: `<binary data>`
**Editor/CurrentSchemaKey**: `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing**: `true`
**Editor/autoBracketRemoval**: `true`
**Editor/editorWidthInDFMOnly**: `true`
**Editor/highlightCurrentLine**: `true`
**Editor/vimMode**: `false`
**IssueAssistantDialog/geometry**: `<binary data>`
**LastUpdateCheck**: `2019-04-03T14:38:52.222`
**LinkDialog/geometry**: `<binary data>`
**LogWidget/criticalLog**: `true`
**LogWidget/debugLog**: `true`
**LogWidget/fatalLog**: `true`
**LogWidget/infoLog**: `true`
**LogWidget/scriptingLog**: `true`
**LogWidget/statusLog**: `true`
**LogWidget/warningLog**: `true`
**MainWindow/geometry**: `<binary data>`
**MainWindow/mainToolBar.iconSize**: `22`
**MainWindow/menuBarGeometry**: `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1**: `Informationsmanagement, Enki Insights`
**MainWindow/noteTextEdit.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font**: `Hack,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font**: `Noto Sans,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.rtl**: `false`
**MainWindow/showNotesFromAllNoteSubFolders**: `false`
**NoteDialog/geometry**: `<binary data>`
**PiwikClientId**: `<hidden>`
**SearchEngineId**: `2`
**SettingsDialog/geometry**: `<binary data>`
**SettingsDialog/mainSplitterState**: `<binary data>`
**Shortcuts/MainWindow-actionSwitch_to_previous_workspace**: `F3`
**ShowSystemTray**: `true`
**StartHidden**: `false`
**TableDialog/geometry**: `<binary data>`
**TodoDialog/geometry**: `<binary data>`
**TodoDialog/mainSplitterState**: `<binary data>`
**TodoDialog/showCompletedItems**: `0`
**TodoDialog/todoListSelectorSelectedItem**: `Arbeit`
**UpdateDialog/geometry**: `<binary data>`
**VersionDialog/geometry**: `<binary data>`
**WelcomeDialog/geometry**: `<binary data>`
**acceptAllExternalModifications**: `false`
**allowDifferentNoteFileName**: `false`
**allowNoteEditing**: `true`
**allowOnlyOneAppInstance**: `true`
**appMetrics/disableAppHeartbeat**: `false`
**appMetrics/disableTracking**: `false`
**appMetrics/notificationShown**: `true`
**automaticNoteFolderDatabaseClosing**: `false`
**closeTodoListAfterSave**: `false`
**cryptoKey**: `<hidden>`
**currentNoteFolderId**: `1`
**currentWorkspace**: `6bf73595-74bd-4457-87d9-a35cf9bca12d`
**cursorWidth**: `1`
**customNoteFileExtensionList**: *empty*
**darkMode**: `false`
**darkModeColors**: `false`
**darkModeTrayIcon**: `false`
**defaultNoteFileExtension**: `md`
**disableAutomaticUpdateDialog**: `true`
**dockWasInitializedOnce**: `true`
**externalEditorPath**: *empty*
**fullyHighlightedBlockquotes**: `false`
**gitCommitInterval**: `30`
**gitExecutablePath**: *empty*
**gitLogCommand**: *empty*
**ignoreAllExternalModifications**: `false`
**ignoreAllExternalNoteFolderChanges**: `false`
**imageScaleDown**: `false`
**imageScaleDownMaximumHeight**: `1024`
**imageScaleDownMaximumWidth**: `1024`
**insertTimeFormat**: *empty*
**interfaceLanguage**: *empty*
**internalIconTheme**: `false`
**itemHeight**: `24`
**localTrash/autoCleanupDays**: `30`
**localTrash/autoCleanupEnabled**: `true`
**localTrash/supportEnabled**: `true`
**markdownHighlightingEnabled**: `true`
**networking/ignoreSSLErrors**: `true`
**networking/proxyType**: `2`
**newNoteAskHeadline**: `false`
**noteEditIsCentralWidget**: `false`
**noteListPreview**: `false`
**noteSaveIntervalTime**: `10`
**noteSubfoldersPanelDisplayAsFullTree**: `true`
**noteSubfoldersPanelHideSearch**: `false`
**noteSubfoldersPanelOrder**: `0`
**noteSubfoldersPanelShowFullPath**: `false`
**noteSubfoldersPanelShowNotesRecursively**: `false`
**noteSubfoldersPanelShowRootFolderName**: `true`
**noteSubfoldersPanelSort**: `0`
**notesPanelOrder**: `0`
**notesPanelSort**: `1`
**notesPath**: `/media/data/nextcloud/Lokal/Notes`
**notifyAllExternalModifications**: `false`
**ownCloud/password**: `<hidden>`
**ownCloud/serverUrl**: `https://nc.famabo.de`
**ownCloud/supportEnabled**: `true`
**ownCloud/todoCalendarBackend**: `3`
**ownCloud/todoCalendarCalDAVPassword**: `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl**: *empty*
**ownCloud/todoCalendarCalDAVUsername**: *empty*
**ownCloud/todoCalendarDisplayNameList**: `Persönlich, Arbeit`
**ownCloud/todoCalendarEnabledList**: `Persönlich`
**ownCloud/todoCalendarEnabledUrlList**: `https://nc.famabo.de/remote.php/dav/calendars/markus/personal/`
**ownCloud/todoCalendarUrlList**: `https://nc.famabo.de/remote.php/dav/calendars/markus/personal/, https://nc.famabo.de/remote.php/dav/calendars/markus/arbeit/`
**ownCloud/userName**: `markus`
**ownCloudInfo/appIsValid**: `true`
**ownCloudInfo/connectionErrorMessage**: `Unbekannter Fehler`
**ownCloudInfo/notesPathExistsText**: `yes`
**ownCloudInfo/serverVersion**: `15.0.4.0`
**previousWorkspace**: `13a739ce-7300-418c-982e-80d14f5b6aeb`
**recentNoteFolders**: `/media/data/nextcloud/Notes, /home/markus/Nextcloud/Notes`
**restoreCursorPosition**: `true`
**savedSearches/noteFolder-1**: `Note 2019-03-19T09.57.55, Note 2019-03-19T09.54.26, Note 2019-03-01T07.18.44, Note 2019-02-25T07.51.56, Note 2019-02-25T07.50.40, Note 2019-02-25T07.49.43, Note 2019-02-25T07.47.11, Note 2019-02-25T07.42.56, Note 2019-02-21T10.47.07, Note 2018-12-13T10.14.45, Note 2018-12-07T15.31.04, Note 2018-11-28T10.41.16, Note 2018-11-27T09.36.34, Note 2018-10-17T14.53.02, Note 2018-09-07T10.28.06, Note 2018-09-03T15.44.41, Note 2018-08-27T14.49.27, Note 2018-08-21T12.44.15, Note 2018-07-19T08.36.14`
**showMenuBar**: `true`
**showStatusBar**: `true`
**tagWasAddedToNote**: `true`
**taggingShowNotesRecursively**: `false`
**tagsPanelHideSearch**: `false`
**tagsPanelOrder**: `0`
**tagsPanelSort**: `0`
**toolbar/1/items**: `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name**: `mainToolBar`
**toolbar/1/title**: `Hauptsymbolleiste`
**toolbar/2/items**: `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name**: `formattingToolbar`
**toolbar/2/title**: `Formatierungs-Werkzeugleiste`
**toolbar/3/items**: `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name**: `insertingToolbar`
**toolbar/3/title**: `Einfügen-Werkzeugleiste`
**toolbar/4/items**: `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name**: `encryptionToolbar`
**toolbar/4/title**: `Werkzeugleiste Verschlüsselung`
**toolbar/5/items**: `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name**: `windowToolbar`
**toolbar/5/title**: `Fenster-Werkzeugleiste`
**toolbar/6/items**: `action_Quit`
**toolbar/6/name**: `quitToolbar`
**toolbar/6/title**: `Beenden - Symbolleiste`
**toolbar/size**: `6`
**useUNIXNewline**: `false`
**versionSplitterSizes**: `<binary data>`
**workspace-13a739ce-7300-418c-982e-80d14f5b6aeb/name**: `Minimal`
**workspace-13a739ce-7300-418c-982e-80d14f5b6aeb/noteSubFolderDockWidgetVisible**: `true`
**workspace-13a739ce-7300-418c-982e-80d14f5b6aeb/windowState**: `<binary data>`
**workspace-6bf73595-74bd-4457-87d9-a35cf9bca12d/name**: `Preview`
**workspace-6bf73595-74bd-4457-87d9-a35cf9bca12d/noteSubFolderDockWidgetVisible**: `true`
**workspace-6bf73595-74bd-4457-87d9-a35cf9bca12d/windowState**: `<binary data>`
**workspace-b5df2976-e579-4605-bf87-9bc412c0abe1/name**: `Vollständig`
**workspace-b5df2976-e579-4605-bf87-9bc412c0abe1/noteSubFolderDockWidgetVisible**: `true`
**workspace-b5df2976-e579-4605-bf87-9bc412c0abe1/windowState**: `<binary data>`
**workspace-e44bb553-44db-47bc-b526-71fb1174ac00/name**: `Preview`
**workspace-e44bb553-44db-47bc-b526-71fb1174ac00/noteSubFolderDockWidgetVisible**: `true`
**workspace-e44bb553-44db-47bc-b526-71fb1174ac00/windowState**: `<binary data>`
**workspaces**: `b5df2976-e579-4605-bf87-9bc412c0abe1, 13a739ce-7300-418c-982e-80d14f5b6aeb, 6bf73595-74bd-4457-87d9-a35cf9bca12d, e44bb553-44db-47bc-b526-71fb1174ac00`

## System environment

**KDE_FULL_SESSION**: `true`
**GS_LIB**: `/home/Markus.Bong/.fonts`
**PAM_KWALLET5_LOGIN**: `/run/user/1000/kwallet5.socket`
**USER**: `Markus.Bong`
**XDG_SEAT**: `seat0`
**XDG_SESSION_TYPE**: `x11`
**SSH_AGENT_PID**: `5940`
**SHLVL**: `0`
**HOME**: `/home/Markus.Bong`
**DESKTOP_SESSION**: `/usr/share/xsessions/plasma`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**KDE_SESSION_VERSION**: `5`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MANDATORY_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.mandatory.path`
**LOGNAME**: `Markus.Bong`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**DEFAULTS_PATH**: `/usr/share/gconf//usr/share/xsessions/plasma.default.path`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_ID**: `3`
**PATH**: `/home/Markus.Bong/bin:/home/Markus.Bong/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/android-sdk//tools:/usr/lib/android-sdk//platforms-tools`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session1`
**XCURSOR_THEME**: `breeze_cursors`
**DISPLAY**: `:0`
**LANG**: `de_DE.UTF-8`
**XDG_CURRENT_DESKTOP**: `KDE`
**XDG_SESSION_DESKTOP**: `KDE`
**XAUTHORITY**: `/tmp/xauth-1000-_0`
**SSH_AUTH_SOCK**: `/tmp/ssh-2EojYFSbMRb7/agent.5891`
**SHELL**: `/bin/bash`
**QT_ACCESSIBILITY**: `1`
**GPG_AGENT_INFO**: `/run/user/1000/gnupg/S.gpg-agent:0:1`
**XDG_VTNR**: `1`
**PWD**: `/home/Markus.Bong`
**ANDROID_HOME**: `/usr/lib/android-sdk/`
**XDG_DATA_DIRS**: `/usr/share//usr/share/xsessions/plasma:/home/Markus.Bong/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-/usr/share/xsessions/plasma:/etc/xdg`
**KDE_SESSION_UID**: `1000`
**GTK_RC_FILES**: `/etc/gtk/gtkrc:/home/Markus.Bong/.gtkrc:/home/Markus.Bong/.config/gtkrc`
**GTK2_RC_FILES**: `/etc/gtk-2.0/gtkrc:/home/Markus.Bong/.gtkrc-2.0:/home/Markus.Bong/.config/gtkrc-2.0`
**SESSION_MANAGER**: `local/MarkusTestRechner:@/tmp/.ICE-unix/6004,unix/MarkusTestRechner:/tmp/.ICE-unix/6004`

**Comment by pbek** [comment] 2019-04-03 13:12
I'm sorry, I still cannot reproduce this on KDE Neon...

**Comment by 2Fake** [comment] 2019-04-03 13:17
Are you in Preview mode?

**Comment by 2Fake** [comment] 2019-04-03 13:19
Found the trigger. 
I have everything as a list with "-" in front. 
If the "-" is not in front, the copy is fine, with the "-" in front i got a new line if i copy it in preview mode.

**Comment by 2Fake** [comment] 2019-04-03 13:34
This one is copied correctly:
132456798
and this one will have a new line in front:
- 132456798
But only in preview mode. The attached file is a html file. Just change the ending ;)

[Note 2019-03-19T09.57.55.txt](https://github.com/pbek/QOwnNotes/files/3038894/Note.2019-03-19T09.57.55.txt)

**Comment by 2Fake** [comment] 2019-04-03 13:35
accidently closed it

**Comment by 2Fake** [comment] 2019-04-03 13:36
This is the markdown file

[Note 2019-03-19T09.57.55.txt](https://github.com/pbek/QOwnNotes/files/3038906/Note.2019-03-19T09.57.55.txt)

**Comment by pbek** [comment] 2019-04-03 19:37
> and this one will have a new line in front:

I guess that's the way it is copied from a `QTextBrowser` widget

I couldn't find anything on <https://bugreports.qt.io/browse/QTBUG-32084?jql=text%20~%20%22qtextbrowser%20list%22>, maybe you have more luck

**Comment by pbek** [comment] 2019-11-12 09:08
I will close this issue until there is more information.

**Closed by pbek** 2019-11-12 09:08 UTC
Labels: question, upstream-problem

**Comment by marcluer** [comment] 2024-02-08 17:05
I am having the exact same problem.
Did anyone find any workarounds for this?

OS: Win11
QON: 24.1.5
