### ISSUE TITLE
A menu for Folder Tree

### ISSUE THREAD

**Issue by LightTemplar** [pbek/QOwnNotes#246] opened 2016-07-15 16:05 UTC
I think, there should also a context menu, like for Notes. 

- New Note
- New Subfolder
- Remove Folder
- Show Folder in File Manager

**Comment by pbek** [comment] 2016-07-15 18:18
It's on my todo list. ;)

**Comment by pbek** [comment] 2016-07-16 11:16
There now is a new release, could you please test it and report if the new features work for you?

**Comment by DarkIrata** [comment] 2016-07-16 13:21
Fixed it for the Note list, now the folder list has the problem.  :D

**Comment by pbek** [comment] 2016-07-16 13:22
Are you really talking about this feature request, @DarkIrata?

**Comment by LightTemplar** [comment] 2016-07-16 13:33
1) after creating a subfolder it shows all notes from the root folder:
![image](https://cloud.githubusercontent.com/assets/453783/16895067/01c02a80-4b6a-11e6-898d-9a2937da6670.png)
2) "Show Folder in File Manager" opens just the root folder, instead of selected folder.

**Comment by DarkIrata** [comment] 2016-07-16 13:41
wubs. Misread by the amount of open tabs, sorry. =D

**Comment by pbek** [comment] 2016-07-16 13:51
@DarkIrata, so please add your comment to the right issue. ;)

**Comment by pbek** [comment] 2016-07-16 13:56
@LightTemplar 
1) I can't reproduce that. What happens if you select an other folder and then select your new folder again?
2) Usually it shows the parent of the folder with the subfolder selected. An appropriate file manager is started with the subfolder as parameter, whatever it does with that parameter...
3) don't be shy :)

**Comment by LightTemplar** [comment] 2016-07-16 14:31
1) I got it. It doesn't connected with new subfolder. It is the problem of all folders from a third level of nesting. 
Root -> folder 1 -> folder 1.1 -> folder 1.1.1 -> all notes from the root folder. 
And also a creating notes and subfolders there create them under the root.
2) I thought it also, but even folder from third level of nesting opens the root. And about showing a folder with subitem selected does it make sense? Isn't it better to just open a whole subfolder, so the user could see all items with notes under it?
3) Because of pointing of that test folder to the Root, I am afraid, it would remove all ))) 
Though removing ones a level higher did work well. With all subitems.

**Comment by pbek** [comment] 2016-07-16 20:46
1) I will take a look at that
2) that's nothing I can control, it is done differently by each file manager
3) YOU wished for that feature ;) it can potentially delete the whole hard drive! I guess I will output the folder in the dialog.

**Comment by LightTemplar** [comment] 2016-07-17 06:22
2) I understand. But I guess, you run it like "FileManager RootFolder SubFolder", where Subfolder could be "folder1/folder1.1/folder1.1.1", instead of "FileManager RootFolder/SubFolder". I think so because it opens always Root. No file manager would open /path/to/root if you'd give them /path/to/root/folder1/folder1.1/folder1.1.1

**Comment by pbek** [comment] 2016-07-17 06:43
@LightTemplar, now I see. 3rd note subfolder levels have general problems... the folder path will not be returned correctly. I will take a look at that, thanks!

**Comment by pbek** [comment] 2016-07-17 06:50
...will be fixed in version 16.07.8

**Comment by pbek** [comment] 2016-07-17 08:09
## 16.07.8
- you can now also create a note subfolder by typing it into the search field 
  and pressing <kbd>Return</kbd>
- note subfolders deeper than 2nd level can now be used
- note subfolders can now be renamed in the note subfolder tree
- now the root note folder cannot be removed in the note subfolder tree  
- the folders that are about to be delete when removing a note subfolder 
  will now be viewed in the confirmation dialog to make it more clear what 
  will happen

**Comment by pbek** [comment] 2016-07-17 09:47
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment] 2016-07-17 12:59
(my numbered points)
1) works well
2) I still unsure you run it properly. I just tried "dolphin /home/user/Documents" in console and saw actually this folder, /home/user/Documents, not the /home/user with selected "Documents"
3) works well. Very helpful message in the confirmation dialog about the path of removing folder! 

Other issues regarding new version I will create.

**Comment by pbek** [comment] 2016-07-19 13:30
2) it's started with the `--select` parameter

**Closed by pbek** 2016-07-19 13:30 UTC
Labels: enhancement

**Comment by pbek** [comment] 2016-07-19 15:38
## 16.07.10
- when opening a note subfolder in the file manager the folder will be opened
  instead of the parent folder with the subfolder selected

@LightTemplar, could you please test if that works for you

**Comment by pbek** [comment] 2016-07-19 17:31
There now is a new release, could you please test it and report if the new features work for you?

**Comment by LightTemplar** [comment] 2016-07-19 18:33
Works well!
