### ISSUE TITLE
QON not save note correctly in some condition

### ISSUE THREAD

**Issue by vanleo2001** [pbek/QOwnNotes#635] opened 2017-07-18 02:27 UTC
QON doesn't save note correctly when I restore with shortcut "ctrl-z" immediately after I delete some lines . 

Below is what I do:
(1) Open QON with an example note
![snap740](https://user-images.githubusercontent.com/12027772/28297966-3ffae844-6ba3-11e7-8ae6-d25c55d44fd6.jpg)

(2) delete the last line
![snap741](https://user-images.githubusercontent.com/12027772/28298006-79583dbc-6ba3-11e7-9a28-251f7d2acf51.jpg)

(3) restore with shortcut "ctrl-z", then "ctrl-s" to save it ( you can see the note is saved in log window)or just close the QON directly ( QON can autosave the note)
![snap743](https://user-images.githubusercontent.com/12027772/28298015-8788f098-6ba3-11e7-8fd5-be7dfb132f6b.jpg)

(4) restart QON, you can see the restore content does not be saved.
![snap744](https://user-images.githubusercontent.com/12027772/28298021-94b52fca-6ba3-11e7-8e41-d97d3be3f5b3.jpg)

**Comment by pbek** [comment] 2017-07-18 04:11
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment] 2017-07-18 04:21
I wasn't able to reproduce that, the note with the "undone" removed line was always saved for me.

**Comment by pbek** [comment] 2017-07-18 05:23
Same under Windows, it works for me. How did you delete the last line?

**Comment by vanleo2001** [comment] 2017-07-18 05:41
open a note
1. Select the last line with mouse, hit del key to delete it. 
2. Use "ctrl-z" to restore it 
3. "ctrl-s" to save it. 
4. Restart QON.

I will send you video via email

**Comment by vanleo2001** [comment] 2017-07-18 05:48
Please check you email :  office@bekerle.com

**Comment by pbek** [comment] 2017-07-18 05:53
Got it, thank you.
I did exactly what you did (and I also tried backspace) and it always worked for me... :/

**Comment by pbek** [comment] 2017-07-18 07:25
Do you have some sync-tools or other 3rd party apps that are accessing the notes who might interfere?

**Comment by vanleo2001** [comment] 2017-07-18 07:40
I have turned off the sync-tool, although the notes are kept in sync folder

**Comment by pbek** [comment] 2017-07-18 07:47
Hmmm, I still think some other app might interfere with the note. So far I haven't found a way to reproduce this under windows. :/

**Comment by vanleo2001** [comment] 2017-07-18 07:59
But I test in another PC with win 8.1 pro, which has no sync tools, the problem is same. Sadly!

**Comment by pbek** [comment] 2017-07-18 13:22
What happens if you don't restart QOwnNotes after saving the note, but open the note file in an other editor. Is the restored line present in the other editor or not?

**Comment by vanleo2001** [comment] 2017-07-18 13:40
Same as I said above, sadly. I'll try to debug it

**Comment by pbek** [comment] 2017-07-18 13:55
"Same" in what way?

**Comment by vanleo2001** [comment] 2017-07-18 14:36
1. prepare a markdown file with 3rd editor. The content is below: 
```
Note 2017-07-18
---

aaaaaaaaa
bbbbbbbb
ccccccccc
```

2. Close the 3rd editor. Open this md file with QON

3. select last line `ccccccccc` with mouse, del it, then "ctrl-z" to restore it.

4. "ctrl-s" to save it. That should be no change in this md file.

5. Don't close QON, open this md file with 3rd editor. You can see the older last line `ccccccccc` is missed

**Comment by pbek** [comment] 2017-07-18 20:29
Thank you for testing, I've no idea why I can't reproduce that behavior...

**Comment by pbek** [comment] 2017-07-18 20:31
It's done by `MainWindow::storeUpdatedNotesToDisk()` in <https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L2441>.

**Comment by vanleo2001** [comment] 2017-07-19 14:50
## Problem reproduce:

Step 1. Preapre the markdown file with content below, then save it.

```
Note 2017-07-18
---
aaaa
bbbb
```


Step 2. Open the md note with QON

Step 3. Select the last line `bbbb` with mouse, then hit del key to delete it at once. Now the note text is

```
Note 2017-07-18
---
aaaa
```

Step 4. **Don't save** note, just ctrl-z to restore text. Now the note text is:

```
Note 2017-07-18
---
aaaa
bbbb
```

Step 5. ctrl-s to save note, open it with 3rd editor, but the md file is

```
Note 2017-07-18
---
aaaa
```


# Find in Debugger ollydbg and QON source

### When current note text is modified in STEP 3,
[void MainWindow::on_noteTextEdit_textChanged()](https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L4350) will trigger first( ).
...
 (text != noteTextFromDisk) {
    [this->currentNote.storeNewText(text);](https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L4362)

Trace step into:
[bool Note::store()](https://github.com/pbek/QOwnNotes/blob/develop/src/entities/note.cpp#L742)
QON uses a memory databse to store the modified note with modified sign "has_dirty_data" , so the text is changed and stored in this db in **STEP 3**, also "has_dirty_data" is set as 1 which means text modified.

### When I restore the note with shortcut ctrl-z in STEP 4, 
The current note text is  same as the md file on harddisc, when code runs:
(text = noteTextFromDisk) https://github.com/pbek/QOwnNotes/blob/develop/src/mainwindow.cpp#L4361
then the restore text doesn't fill in memory database. The memory database keeps the note text modified sign "has_dirty_data" as 1 and text in STEP 3

### When I save the note in STEP 5,
QON will query the note text modified sign "has_dirty_data" in memory database. Because "has_dirty_data"=1 , QON stores the text  (the text of STEP 3, but not text of STEP 4)  from memory database onto harddisk. So the bug happens.

**Comment by pbek** [comment] 2017-07-19 16:02
Good debugging, thank you! But I still have no idea why it doesn't happen for me and so I'm not sure what I should do for your issue. :( Or do you see an obvious problem that can be fixed in the source code?

**Comment by vanleo2001** [comment] 2017-07-20 02:35
I send you email attached videos about the action of QON in my host win7 and MAC OS in VMWare virtual machine. Both in these 2 OS platform , QON ver 17.07.4 can't save note correctly.

Every step I do in video is:
1. clear all settting in QON.
2. run QON in default setting, except set language as english.
3. run QON, create a new note, type in some random text, exit.
4. restart QON, delete last line, restore it, exit. They are all done by mouse right menu  clicking.
5. restart QON, you can see note is saved uncorrectly.
6. repeat step 4 and 5 several times.

BTW, sometimes after I do STEP 4, an alert windows will jump out. It ask me if I accept the external modifition or not. Then QON maybe save note correctly. But in most time this alert will not show even if I set "Notify about all external modifications of the current note" checked.

**Comment by pbek** [comment] 2017-07-20 04:19
Thank you for your videos, so you also did it on macOS... I tried the same and the last line was always stored. I really want to know what the difference between our systems is.

**Comment by vanleo2001** [comment] 2017-07-20 06:30
What is your operation system? with onwcloud or nextcloud on it?

**Comment by pbek** [comment] 2017-07-20 07:19
- Windows 7, KDE Neon, Manjaro Linux, mac OS
- ownCloud or Nextcloud client

**Comment by vanleo2001** [comment] 2017-07-20 08:05
I don't deploy the wnCloud or Nextcloud client. 
I test in windows 7, windows 8.1 on real pc, MAC os on VM. QON save notes uncorrectly.

**Comment by pbek** [comment] 2017-07-20 08:14
I will do more testing.

**Comment by pbek** [comment] 2017-07-20 08:36
Do you care to build QOwnNotes yourself to test a change I made?
<http://www.qownnotes.org/installation#building>

```diff
diff --git a/src/mainwindow.cpp b/src/mainwindow.cpp
index 9a022aa..66008f0 100644
--- a/src/mainwindow.cpp
+++ b/src/mainwindow.cpp
@@ -4358,7 +4358,10 @@ void MainWindow::on_noteTextEdit_textChanged() {
     QString text = Utils::Misc::transformLineFeeds(
             ui->noteTextEdit->toPlainText());
 
-    if (text != noteTextFromDisk) {
+    // store the note to the database if the note text differs from the one
+    // on the disk or the note was already modified but not stored to disk
+    if ((text != noteTextFromDisk || currentNote.getHasDirtyData())) {
+        qDebug() << __func__ << " - 'note stored'";
         this->currentNote.storeNewText(text);
         this->currentNote.refetch();
         this->currentNoteLastEdited = QDateTime::currentDateTime();
```

**Comment by vanleo2001** [comment] 2017-07-20 09:54
Great! It works correctly in windows 7.

**Comment by pbek** [comment] 2017-07-20 10:03
Really? That's awesome! Thanks a lot for all the research and testing!

## 17.07.5
- fixed a problem with correctly storing the note text when special note text
  changes were made between the note save intervals

**Comment by vanleo2001** [comment] 2017-07-20 10:06
You flush the memory database. In a strict sense, the restored note is not the real original note. But it works correctly. Thanks a lot!

**Comment by pbek** [comment] 2017-07-20 10:11
I compared the note on the disk with the current note text but past changes within the interval were not stored to disk yet so it could happen that the note on the disk wasn't updated with the latest modifications. Although you did a much better job at triggering that behaviour than me... :)

**Comment by vanleo2001** [comment] 2017-07-20 10:21
I know. The dafault setting of "note save interval time " is 10 sec. If  deleting and restoring  action is less than this interval time, QON will save uncorrectly because it need compare the current note and note on disk before it saves.

**Comment by pbek** [comment] 2017-07-20 10:28
Exactly.

**Comment by pbek** [comment] 2017-07-20 16:04
There now is a new release, could you please test it and report if it works for you?

**Closed** 2017-07-23 06:12 UTC
