### ISSUE TITLE
Enabling the "Enable logging to file" option causes a Segmentation fault when QOwnNotes application is closed

### ISSUE THREAD

**Issue by onelittlehope** [pbek/QOwnNotes#468] opened 2017-01-07 14:12 UTC
To reproduce:
- Replicate a clean start by ensuring no previous configs exist: `rm -rf ~/ownCloud/ .config/PBE/ .local/share/PBE/`
- Start: `QOwnNotes`
- Select the Note >> Settings menu item and go to the Debug >> Debug Options tab
- Ensure the "Enable logging to file" option is checked. Press "Ok" and then quit QOwnNotes.
- You should see a 'Segmentation fault' message logged to stdout and no log file created in the ~/.local/share/PBE/QOwnNotes folder called QOwnNotes.log. I can confirm that there are no permission/ownership issues with trying to write to that folder.

[QOwnNotes Debug Information.txt](https://github.com/pbek/QOwnNotes/files/691525/QOwnNotes.Debug.Information.txt)

**Comment by pbek** [comment] 2017-01-07 22:08
Thank you for reporting, I will try to reproduce your issue.

**Comment by pbek** [comment] 2017-01-09 17:30
I'm sorry, I cannot reproduce that under `KDE neon User Edition 5.8`. No crash, just a normal quit and the corresponding log messages in the log file...

**Comment by philiptruax** [comment] 2017-01-12 16:04
I'm unable to reproduce a crash running an up to date version of Arch with Gnome. I installed via the AUR.

**Comment by pbek** [comment] 2017-01-12 20:49
Thank you, @philiptruax! I will close this issue until there is more information.

**Comment by stavpup** [comment] 2017-01-17 07:20
Believe it or not, I can reproduce this bug (windows vista !)
QOwnNotes.log has the following

`[Jan 17 09:13:57] [warning]: libpng warning: iCCP: known incorrect sRGB profile
[Jan 17 09:13:57] [warning]: libpng warning: iCCP: known incorrect sRGB profile
[Jan 17 09:13:57] [warning]: libpng warning: iCCP: known incorrect sRGB profile
[Jan 17 09:13:57] [warning]: libpng warning: iCCP: known incorrect sRGB profile
[Jan 17 09:13:57] [warning]: libpng warning: iCCP: known incorrect sRGB profile`


etc..

**Comment by pbek** [comment] 2017-01-17 07:23
I don't think these warnings have anything to do with the issue.
http://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#22747902

**Comment by stavpup** [comment] 2017-01-17 08:20
Also produces three files

WERDB13.tmp.version.txt
WEREEE2.tmp.appcompat.txt
WEREF21.tmp.mdmp

first two are text and the third is about 2 Mb

**Comment by pbek** [comment] 2017-01-21 08:30
I will close this issue until there is more information.

**Closed by pbek** 2017-01-21 08:30 UTC
