### ISSUE TITLE
DBCS and Auto format table problem

### ISSUE THREAD

**Issue by Anongh** [pbek/QOwnNotes#1494] opened 2019-12-09 07:18 UTC
#### Expected behaviour

![QOwnNotes_2019-12-09_15-57-12](https://user-images.githubusercontent.com/22952514/70414280-fb350e00-1a9c-11ea-8d5f-81e2ca1d672f.png)

#### Actual behaviour

![QOwnNotes_2019-12-09_15-55-36](https://user-images.githubusercontent.com/22952514/70414299-06883980-1a9d-11ea-9003-d64b46da5848.png)

As shown in the above picture, if I enter Asian characters in the table and use the 'Auto format table' function, it does not get the desired result.

Perhaps the algorithm of the format only calculates the width of single-byte character sets such as English.

**Comment by pbek** [comment] 2019-12-09 08:13
> use the 'Auto format table' function

Are you referring to pressing `Ctrl + Space`?

**Comment by pbek** [comment] 2019-12-09 08:14
I don't know if it is even possible to do that with characters that doesn't have a fixed width.

**Comment by Anongh** [comment] 2019-12-09 13:54
I have no experience with Qt programming. :disappointed: 

I tested the letters from different countries around the world on the site below: https://www.rocketlanguages.com/blog/how-to-say-hello-in-the-worlds-most-spoken-languages

If a character in each language goes over 3 bytes, the format of the table does not work well; 1 byte characters in Western countries such as English do not cause problems.
https://mothereff.in/byte-counter

It is only a guess that comes from my past experience to connect the byte of the letter and this problem with each other.

**Comment by pbek** [comment] 2019-12-10 09:09
> It is only a guess that comes from my past experience to connect the byte of the letter and this problem with each other.

We don't have a problem with counting characters here, don't we? Because the actual count of inserted spaces is correct, isn't it? The problem is that e.g. Japanese Kanji take up more space than the other characters in a mono-space font and this way the optical illusion of "everything aligns" is destroyed.

**Comment by pbek** [comment] 2020-01-13 16:04
I will close this issue until there is more information.

**Closed by pbek** 2020-01-13 16:04 UTC
Labels: Importance: Low, Type: Improvement
