### ISSUE TITLE
Image files are invisible on file browser window using insert image function

### ISSUE THREAD

**Issue by Manu-sh** [pbek/QOwnNotes#391] opened 2016-11-17 11:48 UTC
Image files are invisible on file browser window using insert image function https://anonm.gr?14a5.png

**Comment by pbek** [comment] 2016-11-17 11:54
Thank you for reporting.
I just tested on Windows 8.1 and they were visible for me in the file-open dialog.
Can you please post the output from the debug settings.

**Comment by Manu-sh** [comment] 2016-11-17 12:25
md: https://arin.ga/UR3KJo
strace (splitted): https://arin.ga/UQyL3u
the information provided by log doesn't report any error, only line like this
[nov 17 13:23:25] [warning]: libpng warning: iCCP: known incorrect sRGB profile

**Comment by Manu-sh** [comment] 2016-11-17 12:30
md: https://arin.ga/UR3KJo
strace (splitted): https://arin.ga/UQyL3u

the path is /home/user/Immagini/vaporwawe_wall
i suggest to start from line 1126
the information provided by log doesn't report any error, only line like this:
[nov 17 13:23:25] [warning]: libpng warning: iCCP: known incorrect sRGB profile

**Comment by pbek** [comment] 2016-11-17 13:16
Oh, I thought you were using Windows...
It also works for me in KDE Neon.

**Comment by pbek** [comment] 2016-11-17 13:24
What Desktop Environment are you using?

**Comment by Manu-sh** [comment] 2016-11-17 13:26
I use xfce on my notebook, but after i can test on another pc with gnome

**Comment by pbek** [comment] 2016-11-17 13:30
QOwnNotes tries to use the native file open dialog (via Qt). I'm not sure which dialog you are using under xfce. You can also drag and drop images to QOwnNotes.

**Comment by Manu-sh** [comment] 2016-11-17 13:52
I don't think that this is the problem because qtcreator show those file, however maybe after i can try to make more test

**Comment by Manu-sh** [comment] 2016-11-17 16:52
@pbek i have also try on another pc with gnome and same issue, i use arch linux on both my pc, the current version of Qt is 5.7.0

**Comment by pbek** [comment] 2016-11-17 17:20
Strange, I can see them under Manjaro (Arch with KDE) under Qt 5.7. Can you please post a screenshot of the dialog under Gnome.

**Comment by Manu-sh** [comment] 2016-11-17 17:30
On gnome i have previous version 16.11.11 https://anonm.gr?65c0.png

**Comment by Manu-sh** [comment] 2016-11-17 18:01
Ok, i have make following test:
On gnome and kde with version 16.11.11:
* https://anonm.gr?65c0.png
* https://anonm.gr?d2e0.png

then i have also clone and build from branch master, previously i have used develop branch:
but same issue, then i have try to build without using parallel jobs but doesn't solve anything
for build i have used following commands:
```
git clone https://github.com/pbek/QOwnNotes -b master
cd QOwnNotes
git submodule update --init
cd src
qmake
make
sudo make install
```

**Comment by pbek** [comment] 2016-11-17 20:12
Can you please create a `.enex` file and try if you see it in the Evernote importer?
Do you have similar problems with other KDE Applications if file extensions are filtered?

**Comment by Manu-sh** [comment] 2016-11-17 20:37
.enex file are correctly shown

**Comment by pbek** [comment] 2016-11-17 21:23
interesting, and you you have any Qt application that opens files with multiple formats in one filter (like the QOwnNotes image open dialog)?

**Comment by Manu-sh** [comment] 2016-11-17 21:34
yes, QtCreator: https://anonm.gr?0ed5.png

**Comment by pbek** [comment] 2016-11-18 05:34
I hope I can reproduce that somewhere.

**Comment by pbek** [comment] 2016-11-18 07:24
It also worked under Unity in a Ubuntu 14.04 and in openSUSE Leap.
I used the syntax from the documentation for setting up the filter.

- <https://github.com/pbek/QOwnNotes/blob/windows-b2512/src/mainwindow.cpp#L4884>
- <http://doc.qt.io/qt-5/qfiledialog.html#setNameFilter>

I'm not sure what I can do. Since you seem to build QOwnNotes yourself you could try to modify the filter string.

**Comment by pbek** [comment] 2016-11-18 07:29
I also tried to use `dialog.setOption(QFileDialog::DontUseNativeDialog, true);` to get the non-native dialog. It worked there too...

**Comment by Manu-sh** [comment] 2016-11-18 11:30
I don't have experience with C++ or Qt framework but i have try to replace this line:
`dialog.setNameFilter(tr("Image files (*.jpg *.png *.gif)"));`

with this (just for test):
`dialog.setNameFilter(tr("Images (*.jpg *.png *.gif)"));`
copied from http://doc.qt.io/qt-5/qfiledialog.html
and now work properly (i have also insert an image without any problem)
https://anonm.gr?8b9c.png

then i suspect that you have install more Qt version on your pc and for this reason work, but i don't know...

**Comment by pbek** [comment] 2016-11-18 12:36
Oh, I now think I saw spaces in the `*.jpg *.png *.gif` expressions in your first screenshot. You are using the Italian translation. So that's the problem. Can you please test to use the original code and switch the language to any other language than Italian.

**Comment by pbek** [comment] 2016-11-18 12:44
I tried it myself too. The Italian translation for that string is "broken". I think I will exclude the file extensions.

**Comment by Manu-sh** [comment] 2016-11-18 13:35
Yes @pbek i have change language from it to en and now work properly

**Comment by pbek** [comment] 2016-11-18 17:42
Thank you for testing.

**Comment by Manu-sh** [comment] 2016-11-18 17:52
Thank you for this program is really useful for me

**Comment by pbek** [comment] 2016-11-18 18:58
Thank you for your kind words and your effort on the Italian translation!

**Comment by pbek** [comment] 2016-11-19 08:40
## 16.11.13
- Fixed a problem with inserting images when application language is Italian
    - potential file open dialog filter problems in other languages were
      also fixed in the process

**Comment by pbek** [comment] 2016-11-19 10:54
There now is a new release, could you please test it and report if the dialog works for you?

**Comment by Manu-sh** [comment] 2016-11-19 11:15
Yes i can confirm, now image files are correctly shown

**Comment by pbek** [comment] 2016-11-19 12:07
Great, thank you!

**Closed by pbek** 2016-11-19 12:07 UTC
