### ISSUE TITLE
[BUG] crashes consistently upon copy-pasting 3 lines of code into the markdown 

### ISSUE THREAD

**Issue by Haiderahandali** [pbek/QOwnNotes#2959] opened 2024-02-16 11:09 UTC
#### Expected behaviour
to copy from my clip board to the note
#### Actual behaviour
crashes/hangs
#### Steps to reproduce
I am not sure if it will happen for anyone else, I have a markdown keeping notes about javascript code (taken from [here](https://javascript.info/array)). 
the program crashes when I copy pasted a few lines into app as shown in the attached video. I have copy-pasted a few times with no issues, but this happens consistently. 
#### Output from the debug section in the settings dialog
The program hangs I don't get anything. 

#### Relevant log output in the Log panel
Again the program hangs and I don't see anything being logged. if there is a log file to check I will provide it.

Finally here are my system information 
[DxDiag.txt](https://github.com/pbek/QOwnNotes/files/14310108/DxDiag.txt)

https://github.com/pbek/QOwnNotes/assets/53301143/e1a7db21-be11-45a4-a78d-d1f551f37c74

Please note during the video I don't press anything, and just moving my mouse, the program closes on its own (in some cases it shows on the title bar, something like the program is not responding).

I installed the program today, so I have the latest updates.

**Comment by pbek** [comment] 2024-02-16 11:42
I wasn't able to produce this with the lines you used. Can you please add the markdown file you pasted it into?

And can you please post the output from the debug settings that you can copy when you get into the settings dialog in QOwnNotes and head over to the *Debug* section of it?

**Comment by Haiderahandali** [comment] 2024-02-16 11:53
here is the entire file I am editing
[JavaScript Test.md](https://github.com/pbek/QOwnNotes/files/14310531/JavaScript.Test.md)

and here are the exact lines I am copying:
let arr = [1, 2, 3, 4, 5];

arr.length = 2; // truncate to 2 elements
alert( arr ); // [1, 2]

arr.length = 5; // return length back
alert( arr[3] ); // undefined: the values do not return

here is the copy-paste debug output:
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Fri Feb 16 14:52:24 2024`
**Version**: `24.2.3`
**Build date**: `Feb 15 2024`
**Build number**: `1080`
**Platform**: `windows`
**Operating System**: `Windows 10 Version 2009`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `GitHub Actions`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Settings path / key**: `\HKEY_CURRENT_USER\Software\PBE\QOwnNotes`
**Application database path**: `C:\Users\Ali\AppData\Roaming\PBE\QOwnNotes\QOwnNotes.sqlite`
**Application arguments**: `C:\Users\Ali\BinApp\QOwnNotes\QOwnNotes.exe`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1920x1080`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `yes`
**notesPathExists**: *empty*
**serverVersion**: *empty*
**appVersion**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `C:\Users\Ali\AppData\Roaming\PBE\QOwnNotes\dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `C:\Users\Ali\Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `C:\Users\Ali\Notes\notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/removeTrailingSpaces** (QString): `false`
**LastUpdateCheck** (QDateTime): `2024-02-16T14:02:32.047`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (int): `30`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `Courier New,12,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `MS Shell Dlg 2,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Courier New,9,-1,2,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `MS Shell Dlg 2,7.8,-1,5,50,0,0,0,0,0`
**NoteFolder-1/NoteTabNameList** (QStringList): `JavaScript Test`
**NoteFolder-1/NoteTabStickinessList** (QStringList): *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QStringList): *empty*
**NoteHistory-1** (QVariantList): `<variant list with 4 item(s)>`
**NoteHistoryCurrentIndex-1** (int): `3`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (QString): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**checkSpelling** (QString): `false`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**dockWasInitializedOnce** (QString): `true`
**guiFirstRunInit** (QString): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (int): `18`
**markdownHighlightingEnabled** (QString): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**notesPath** (QString): `C:/Users/Ali/Notes`
**ownCloud/supportEnabled** (QString): `false`
**ownCloudInfo/appIsValid** (QString): `true`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**savedSearches/noteFolder-1** (QStringList): `Note 2024-02-16T08.13.37`
**showMenuBar** (QString): `true`
**showStatusBar** (QString): `true`
**webAppClientService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**ALLUSERSPROFILE**: `C:\ProgramData`
**APPDATA**: `C:\Users\Ali\AppData\Roaming`
**CommonProgramFiles**: `C:\Program Files\Common Files`
**CommonProgramFiles(x86)**: `C:\Program Files (x86)\Common Files`
**CommonProgramW6432**: `C:\Program Files\Common Files`
**COMPUTERNAME**: `DESKTOP-3J3HJBO`
**ComSpec**: `C:\Windows\system32\cmd.exe`
**DriverData**: `C:\Windows\System32\Drivers\DriverData`
**EMSDK**: `C:/Users/Ali/BinApp/emsdk-main`
**EMSDK_NODE**: `C:\Users\Ali\BinApp\emsdk-main\node\16.20.0_64bit\bin\node.exe`
**EMSDK_PYTHON**: `C:\Users\Ali\BinApp\emsdk-main\python\3.9.2-nuget_64bit\python.exe`
**FPS_BROWSER_APP_PROFILE_STRING**: `Internet Explorer`
**FPS_BROWSER_USER_PROFILE_STRING**: `Default`
**HOMEDRIVE**: `C:`
**HOMEPATH**: `\Users\Ali`
**IGCCSVC_DB**: `AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAALcKI5Ln/lEiLVN42FZDf5wQAAAACAAAAAAAQZgAAAAEAACAAAAD6n2Kk+rOTvaIVIGxNdco4vCzkmcnRx5fNNABSmg1GjwAAAAAOgAAAAAIAACAAAAC7/MwweiOF70RjuFrgnI41xI3+7OQ2AAJ9DlwG5YoQcmAAAACKN3GPyOaRICgL8A135FRj53axeIxNZnrFCYWEON/r33YLtZZfMnjtmTTfXVBugWbUC6I89blTFmwZiEvaKkoEpMaaM7X59/XHAgXcXSkjzDKdYxQwsbhDanRtTyuD6JNAAAAAh4b4BJPQNn2POE2lzQXb4nAeDm9o3edBcYBwFRfZZYytoeexuwrrLBscjNVA72XuKrIXkrmZZgz1LbJshdcufg==`
**JAVA_HOME**: `C:\Users\Ali\BinApp\emsdk-main\java\8.152_64bit`
**LOCALAPPDATA**: `C:\Users\Ali\AppData\Local`
**LOGONSERVER**: `\\DESKTOP-3J3HJBO`
**NUMBER_OF_PROCESSORS**: `20`
**OneDrive**: `C:\Users\Ali\OneDrive`
**OS**: `Windows_NT`
**Path**: `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Ali\Work\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Ali\BinApp;C:\Users\Ali\BinApp\Cmake\bin;C:\Program Files\Sublime Text;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\Ali\Work\;C:\Program Files\nodejs\;C:\Users\Ali\BinApp\ripgrep\;C:\Users\Ali\BinApp\emsdk-main\;C:\Users\Ali\BinApp\emsdk-main\upstream\emscripten\;C:\Users\Ali\Documents\emsdk-main\emsdk-main;C:\Users\Ali\Documents\emsdk-main\emsdk-main\upstream\emscripten;C:\Users\Ali\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\Ali\AppData\Local\Programs\Python\Python312\;C:\Users\Ali\AppData\Local\Programs\Python\Launcher\;C:\Users\Ali\AppData\Local\Microsoft\WindowsApps;C:\Users\Ali\.dotnet\tools;C:\Users\Ali\AppData\Roaming\npm`
**PATHEXT**: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`
**PROCESSOR_ARCHITECTURE**: `AMD64`
**PROCESSOR_IDENTIFIER**: `Intel64 Family 6 Model 154 Stepping 3, GenuineIntel`
**PROCESSOR_LEVEL**: `6`
**PROCESSOR_REVISION**: `9a03`
**ProgramData**: `C:\ProgramData`
**ProgramFiles**: `C:\Program Files`
**ProgramFiles(x86)**: `C:\Program Files (x86)`
**ProgramW6432**: `C:\Program Files`
**PSModulePath**: `%ProgramFiles%\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`
**PUBLIC**: `C:\Users\Public`
**RlsSvcPort**: `22112`
**SystemDrive**: `C:`
**SystemRoot**: `C:\Windows`
**TEMP**: `C:\Users\Ali\AppData\Local\Temp`
**TMP**: `C:\Users\Ali\AppData\Local\Temp`
**USERDOMAIN**: `DESKTOP-3J3HJBO`
**USERDOMAIN_ROAMINGPROFILE**: `DESKTOP-3J3HJBO`
**USERNAME**: `Ali`
**USERPROFILE**: `C:\Users\Ali`
**VS110COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\`
**VS120COMNTOOLS**: `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\`
**windir**: `C:\Windows`
**ZES_ENABLE_SYSMAN**: `1`

**Comment by pbek** [comment] 2024-02-16 12:05
I tried to paste the code into your note for 10 times in a JS code block, but no crash for me.

The only thing that comes to mind that you can do is to build the application yourself, for example with QtCreator. See https://www.qownnotes.org/installation/building.html. And then test in Debug mode where the crash happens. ️🤷🏻

**Comment by Haiderahandali** [comment] 2024-02-16 12:07
@pbek  
I don't mind building the application to be honest, but I would really prefer to avoid installing Qt and its giant framework, if that is the only way, I might do later tonight.

**Comment by Haiderahandali** [comment] 2024-02-16 12:09
@pbek  
I am ready to hob into IRC if that helps.

**Comment by pbek** [comment] 2024-02-16 12:16
IRC will not help, you can't get a stack-trace in a debugger when the app is not built in Debug Mode... ️🤷🏻

**Comment by pbek** [comment] 2024-02-16 12:21
I tried several ways to enter the code, no crash.

What happens when you turn off the preview panel.
What happens when you turn off Markdown highlighting in the Editor settings?

**Comment by Haiderahandali** [comment] 2024-02-16 12:35
Okay we are getting somewhere, the problem is in the preview panel, because it only crashes when I paste it while I am showing the preview panel.

**Comment by Haiderahandali** [comment] 2024-02-16 12:35
I am sorry but I will need to go for now, I will be back in 9 hours.

**Comment by pbek** [comment] 2024-02-16 13:05
> Okay we are getting somewhere, the problem is in the preview panel, because it only crashes when I paste it while I am showing the preview panel.

I had it on too...

**Comment by mk-fhg** [comment] 2024-02-16 16:41
I was able to recreate the problem.
It only crashed if I pasted in the lines excactly as shown in the video, that is:

The code block looks like

```js
```

Then the cursor is positioned at the beginning of the line with the code block ending back ticks.
Then I paste in the code using Ctrl+V.

Then I noticed something:
At the moment QOwnNotes crashed, the threeending backticks were on the same line as the last line of pasted in code, so it looked like this:

alert( arr[3] ); // undefined: the values do not return```


When I opened QOwnNotes after the crash this then looked like this:

alert( arr[3] ); // undefined: the values do not return
```


When I positioned the cursor behind the word return and pressed the delete key, therefore moving the three back ticks back up into the line, QOwnNotes crashed again.

The error might not be able to be reproduced when the the copied code in the clipboard contains a new line at the end, preventing the backticks to appear on the same line as the JS code.

**Comment by mk-fhg** [comment] 2024-02-16 16:45
I was able to reduce it down.

The file only needs to caontain the JS code block, i.e.

```js
```

Then paste in the comment delimiter (//) before the ending back ticks.

Pasting in other things were no problem. Only the comment delimiter.

**Comment by mk-fhg** [comment] 2024-02-16 16:50
Github automatically formats the code sections that I wanted to be visible as raw characters. Can I edit them somehow that it stays visible? Or do you get my point?

**Comment by Haiderahandali** [comment] 2024-02-16 17:27
@mk-fhg you can use paste bin to paste the code exactly without any formatting, or use some escape codes. 
But it is easier with just sharing it via a permanent link.

**Comment by mk-fhg** [comment] 2024-02-16 17:46
https://pastebin.com/ZunczZMV

It's not limited to JavaScript and back slashes.
When using Python for the code blocks, it crashes when inserting #.
So it probably happens with evry supported programming language and inline comment.
It also doesn't have to be copy and paste. Typing it in is enough.

**Comment by pbek** [comment] 2024-02-16 18:32
Just for reference, there are tilde-codeblocks and 4-space-fences: https://www.qownnotes.org/getting-started/markdown.html#_4-spaces-fence

**Comment by pbek** [comment] 2024-02-16 18:35
It took a while to reproduce that (because you used wrong backticks in your pastbin example), but now I can reproduce it. Thank you!

**Comment by pbek** [comment] 2024-02-16 19:11
@Waqar144, I found the position of the crash:

https://github.com/pbek/QOwnNotes/blob/02124b74a3f2583a47a03740e467593c3871b24e/src/helpers/codetohtmlconverter.cpp#L482

I'm currently taking a look at it.

**Comment by Haiderahandali** [comment] 2024-02-16 19:53
Glad you found it.

**Comment by pbek** [comment] 2024-02-16 19:55
## 24.2.4
- fixed a crash, when someone enters a misplaced comment marker directly before
  the closing mark of the code block (for [#2959](https://github.com/pbek/QOwnNotes/issues/2959))

**Comment by Haiderahandali** [comment] 2024-02-16 20:07
@spoelstraethan am I missing something or is there no zip in the releases for windows.
previous releases had 14 assets, this one has 10. or are they still in testing?

**Comment by pbek** [comment] 2024-02-16 20:11
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2024-02-16 20:13
> am I missing something or is there no zip in the releases for windows.
previous releases had 14 assets, this one has 10. or are they still in testing?

https://github.com/pbek/QOwnNotes/actions/runs/7935593181 was still building, it's done now.

**Comment by pbek** [comment] 2024-02-16 20:14
But just use the updater, no need to download the ZIP manually...

**Comment by Haiderahandali** [comment] 2024-02-16 20:20
@pbek  I just tested it and it works, I think you can close the issue if you want. (It is a habit developed with Visual studio, in which every update breaks the entire installation, so I am used to remove something entirely and download a new release, completely forgot there was an updater).

Btw, I am not sure if you have time, but maybe lib fuzz is worth checking out, I heard it finds crashes in almost every program that accepts a string of text as an input (I tried to look into your ci, I did not see it there).

**Comment by pbek** [comment] 2024-02-16 20:23
> Btw, I am not sure if you have time, but maybe lib fuzz is worth checking out, I heard it finds crashes in almost every program that accepts a string of text as an input (I tried to look into your ci, I did not see it there).

I hardly believe (but I could be wrong) that it can fuzzy a QPlainTextEdit, but if you want to try I'm open for pull requests for a CI workflow.

**Closed** 2024-02-16 20:23 UTC
Labels: Type: Bug - Regression, Severity: Low
