### ISSUE TITLE
New Note invoked from (new experimental) global hot key exits QOwnNotes if cancelled

### ISSUE THREAD

**Issue by uffejakobsen** [pbek/QOwnNotes#1668] opened 2020-03-30 11:33 UTC
New Note (note headline) popup-dialog invoked from (new experimental) global hot key exits QOwnNotes if cancel button or ESC-key is pressed

QN v20.3.8 @ ArchLinux (LXQt desktop environment)

**Comment by Waqar144** [comment] 2020-03-30 12:09
Reproducable.

Only happens if QON was in the background and global shortucut was activated

**Comment by pbek** [comment] 2020-03-30 12:12
I tried minimizing and closing via tray. And both times QON didn't quit or crash for me.

@uffejakobsen, are you talking about the dialog you get when you use the *The shortcut to create a new note asks for headline* Checkbox? I have no issue with that dialog. Do you get the same issue when you use the in-application shortcut `Ctrl + N`?

Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging.

**Comment by pbek** [comment] 2020-03-30 12:15
And @uffejakobsen can you please explain in more detail and step by step what you did and what happened.

**Comment by uffejakobsen** [comment] 2020-03-30 12:43
I just startup QOwnNotes and have it running with only a system tray icon - no main windows open.
Then I try to use the new experimantal global hotkey feature to create a new note pressing Meta+Shift+N.
When the dialog titled "New note" (subtitle "Note headline") appears I just press the ESC-key and QOwnNotes quits

**Comment by Waqar144** [comment] 2020-03-30 12:46
steps from me:

1. Open QON.
2. Minimize to tray.
3. Meta + Shift + N
4. New note dialog appears
5. Press cancel.
6. Watch QON quit from systray.

**Comment by pbek** [comment] 2020-03-30 16:29
## 20.3.9
- you can now also manage **global keyboard shortcuts** in the *Shortcuts settings*
  (for [#44](https://github.com/pbek/QOwnNotes/issues/44))
    - there you can set a global shortcut to every action of the main menu,
      including custom scripting actions
    - you can also search for global shortcuts in the `Search for shortcut` line edit
    - by default there are no global shortcuts activated

**Comment by pbek** [comment] 2020-03-30 17:03
I still can't reproduce it but 20.3.9 could possibly fix it.
There now is a new release, could you please test it and report if it works for you?

**Comment by uffejakobsen** [comment] 2020-03-30 22:07
Well it works better now - that mean that the app does not shutdown once i hit escape.

The problem now is that i cannot use the meta in the global hotkeys.

**Comment by pbek** [comment] 2020-03-31 04:54
Thank you for testing.

> The problem now is that i cannot use the meta in the global hotkeys.

That's explained in #44

**Closed by pbek** 2020-03-31 04:54 UTC
Labels: Type: Support
