### ISSUE TITLE
Is there a way to defeat the "control" key changing font size?

### ISSUE THREAD

**Issue by jml9904** [pbek/QOwnNotes#2060] opened 2021-02-22 11:53 UTC

**Comment by pbek** [comment] 2021-02-22 12:02
I can't reproduce that.

Can you please explain in more detail and step by step what you did, what happened and what you expected.
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).

**Comment by jml9904** [comment] 2021-02-22 12:13
As luck would have it, it's not reproducing _now_ (although it did just before I opened this). The only thing in the log panel is this:

[07:10:32] [warning] Failed to register hotkey. Error: The operation completed successfully. 
[07:10:32] [warning] Failed to register hotkey. Error: The operation completed successfully. 
[07:10:32] [warning] Failed to register hotkey. Error: The operation completed successfully.

Not sure if that's related to the remediation or not. The debug log itself shows nothing useful. I'll leave the logging on and if the issue does happen again, will post it here.

Thanks for the fast response!!!!

**Comment by pbek** [comment] 2021-02-22 13:10
> I'll leave the logging on and if the issue does happen again, will post it here.

Ok, I will close this issue until there is more information. 😉

**Closed by pbek** 2021-02-22 13:10 UTC
Labels: Type: Support
