### ISSUE TITLE
qfilesystemwatcher will only trigger once if the file update method was deleted and created

### ISSUE THREAD

**Issue by clevertension** [pbek/QOwnNotes#2389] opened 2022-01-19 02:49 UTC
[issues] see this link https://stackoverflow.com/questions/18300376/qt-qfilesystemwatcher-signal-filechanged-gets-emited-only-once
some external editor will first delete file and create a new one, so QOwnNotes can't detect the file update

#### Steps to reproduce
i can use MegaSync to reproduce it when the note sync from one computer to another

#### Solution
so i can give a solution, and test it is ok now:
while(note.fileExists()==false) {
   sleep 1 seconds and retry max 30 times
}
if(note.fileExists()) {
   we can reload the current note
}

**Comment by pbek** [comment] 2022-01-19 05:49
> i can use MegaSync to reproduce it when the note sync from one computer to another

Can you please describe step by step what you did to reproduce this issue (best without any other tool that would be needed to be installed)?

> sleep 1 seconds and retry max 30 times

you can't really "sleep", it would freeze the application... and to do that in the background would cause a lot of side-effects

**Comment by clevertension** [comment] 2022-01-19 05:52
just like  QCoreApplication.processEvents(QEventLoop:AllEvents, 100); process all events every 100ms, this can avoid freeze application

**Comment by pbek** [comment] 2022-01-19 06:33
> just like QCoreApplication.processEvents(QEventLoop:AllEvents, 100); process all events every 100ms, this can avoid freeze application

Let's discuss that in a Pull Requests...

So far I cannot reproduce your issue... I removed a note externally and the note folder was reloaded, than I created the same file again externally and the note folder was reloaded...

**Comment by clevertension** [comment] 2022-01-19 12:04
you can simulator with following code, it delete file and create it immediatelly


`
#include <QCoreApplication>
#include <QDebug>
#include <QFile>
#include <QTextStream>
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    //read file content
    QString filename = "/Users/dan/Documents/MEGA/QOwnNotes/database/Postgresql.md";
    QFile file(filename);
    file.open(QIODevice::ReadOnly);
    QString s;
    QTextStream in(&file);
    s.append(in.readAll());
    file.close();
    //delete file
    QFile ff(filename);
    ff.remove();
    //create a new one
    QFile file1(filename);
    if (file1.open(QIODevice::ReadWrite)) {
        QTextStream stream(&file1);
        stream <<s<<"---->add something" << endl;
    }
    return a.exec();
}
`

**Comment by pbek** [comment] 2022-01-19 13:29
I used your example in a new application. It just added `---->add something` to an existing file. The external change was detected by QOwnNotes.

**Comment by clevertension** [comment] 2022-01-19 13:55
i use this software https://mega.nz/, it can sync file, so put QOwnNotes root directory to mega directory, and test it again,
my OS is 10.15.7 macOS Catalina, same issue exist in macOS Bigsur

**Comment by pbek** [comment] 2022-01-20 16:00
I'm not very keen in creating a Mega account and installing their sync client. 😅

**Comment by Waqar144** [comment] 2022-02-15 18:03
Should be fixed with https://github.com/pbek/QOwnNotes/pull/2460

**Comment by pbek** [comment] 2022-02-15 19:11
## 22.2.6
- issues with the directory watcher for the note folder were fixed
  (for [#2389](https://github.com/pbek/QOwnNotes/issues/2389), thank you, @Waqar144)

**Comment by pbek** [comment] 2022-02-15 19:13
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2022-02-22 06:40
I will close this issue until there is more information.

**Closed by pbek** 2022-02-22 06:40 UTC
Labels: Type: Support
