### ISSUE TITLE
QOwnNotes (ownCloud) often hang and showing folder externaly change (if activated) on a windows network drive

### ISSUE THREAD

**Issue by Qixuga** [pbek/QOwnNotes#956] opened 2018-07-02 06:48 UTC
If you activate the possiblity to do "external changes" and store ownCloud respective QOwnNotes on a network drive the App offen hangs and is showing "external changes" in their bottom line.

So it might be a problem with the file changes-detection because ownCloud themself work very well without any problems like "syncing all the time".

There will be no log available with that problem.

I used the actualy version and nearly every version before - 18.07.0

**Comment by dragotin** [comment] 2018-07-30 16:41
I can confirm this problem. I am running QOwnNotes on Linux (openSUSE, but not relevant) and the notes are stored in a directory that is synced via ownCloud client to an ownCloud server. Whenever QOwnNotes saves a note, ownCloud is syncing that file to the server. After that, QOwnNotes reloads the folder (I believe), and the reason could be that ownCloud modifies a few dot-files in the directory when it syncs files (the sync journal database and logfiles).

A solution might be to not reload the notes folder if only dot-files are modified.  QOwnNotes monitors them as well (that seems to be the default of QFileSystemWatcher).

**Comment by pbek** [comment] 2018-07-30 17:52
> A solution might be to not reload the notes folder if only dot-files are modified. QOwnNotes monitors them as well (that seems to be the default of QFileSystemWatcher).

that doesn't work that way, you can only monitor specific files (and if they really are monitors depends on the operating system and what else is monitored on it) or specific folders (you'll get an event if anything changes)

**Comment by dragotin** [comment] 2018-07-30 19:41
IIRC QOwnNotes does both, monitoring specific files and folders. So this can only be caused by the watcher that monitors the folder. How about ignoring dot files in the slot that is hit when the folder monitor fires?

**Comment by pbek** [comment] 2018-07-30 20:02
You cannot ignore files.

**Comment by pbek** [comment] 2018-07-31 04:06
...because the folder watcher doesn't get the information which file was modified.

**Comment by dragotin** [comment] 2018-08-01 08:41
After some more debugging I think there is a bug in the detection of external changes. In `MainWindow::notesWereModified` the code checks if the text in the editor is different from the text in the note file. If so, the code says, the file is modified externally.

That does not seem to be accurate, as (in my cases) always the text in the text editor had changed, which is fair, because I type fast ;-)

I think a more accurate sign of an external change would be to check if the file modification time of the note file has changed. It is on all platforms a valid measurement of change. For that, the code should store the mod time of all note files when it reads it, I am not sure if it already does or not.

**Comment by pbek** [comment] 2018-08-01 08:55
> I think a more accurate sign of an external change would be to check if the file modification time of the note file has changed.

Notes are not stored instantly on the disk, you may lose the changes between the last note storing and the event.

**Comment by dragotin** [comment] 2018-08-01 12:57
Ok, but that happens every relatively often, especially if the notes folder is synced via the sync client to ownCloud. Do you have any idea why that is? And also, do you have any objections on checking the file modification time?

**Comment by pbek** [comment] 2018-08-01 13:28
> Ok, but that happens every relatively often, especially if the notes folder is synced via the sync client to ownCloud.

I wasn't able to find that out, it also seems to depend on the operating system.

> And also, do you have any objections on checking the file modification time?

I'm not sure why you want to check that. `notesWereModified` (https://github.com/pbek/QOwnNotes/blob/5c2effbfc6e376b2628b75d3548d769b7c872429/src/mainwindow.cpp#L2367) is about if the current note (that you are possibly also currently editing) and the note file of the current note that was possibly overwritten on the disk.

**Comment by mpodshivalin** [comment] 2018-08-04 20:08
I may have found the core reason for this as well as a workaround.
I've had the same problem as @dragotin 
> I can confirm this problem. I am running QOwnNotes on Linux (openSUSE, but not relevant) and the notes are stored in a directory that is synced via ownCloud client to an ownCloud server. Whenever QOwnNotes saves a note, ownCloud is syncing that file to the server. After that, QOwnNotes reloads the folder (I believe), and the reason could be that ownCloud modifies a few dot-files in the directory when it syncs files (the sync journal database and logfiles).

This is the behaviour I've gotten on macOS, and on Fedora 28 it has gotten even worse - I've constantly had popups saying that my note was modified externally.

I think the core reason why me and @dragotin have this problem (and others don't) is because we have non-standard folder structure with folder sync connections.

Usual folder structure is "Sync everything". So you have a "Nextcloud" folder in your home folder which has everything synced with your Nextcloud. There is a folder called "Notes", and Nextcloud saves sync logs in "Nextcloud" folder, not in the "Nextcloud/Notes" folder, so the problem never occurs because nothing in "Notes" folder changes when QOwnNotes saves notes:
```
Home
|- Nextcloud
|-- Notes
|--- Note 1.md
|--- Note 2.md
|-- Documents
|-- Etc.
|-- .owncloudsync.log <- These files do not cause problems
|-- .owncloudsync.log.1 <- These files do not cause problems
```

My folder structure is different - I use sync folder connections
So I've created Notes folder in my Home folder, and created folder sync connection with Nextcloud.
This is where the problem occurs. There is no longer a parent directory which can contain hidden log files, so they are stored in Notes folder directly:
```
Home
|- Notes
|-- Note 1.md
|-- Note 2.md
|-- .owncloudsync.log <- These files cause problems
|-- .owncloudsync.log.1 <- These files cause problems
```

The solution is to use "Sync everything" folder structure, or at least have a Notes folder inside another folder while using sync connections.

**Comment by pbek** [comment] 2018-08-05 03:52
So there are some hidden log files if you are using selective sync? That's an interesting find! I wonder how these files are named on other operating systems and how many there can be. And if the Nextcloud sync client uses other files...

**Comment by dragotin** [comment] 2018-08-05 15:16
Yes, I also do use a "syncfolder-setup", and I tried to say (https://github.com/pbek/QOwnNotes/issues/956#issuecomment-408929853) that the dot-files of ownCloud sync client that get modified at every sync are the source of the problem. The modification of these files triggers the slot `notesWereModified()` which hicks up as described.
To be accurate, the problem is not the "syncfolder-setup", but the fact, that the note files of QOwnNotes are in the same directory that is used as the root of the sync.

To your question:
- The log-files for the ownCloud sync are always named `.owncloudsync.log*`
- There are also the sync journal database file with the name pattern `._sync_*`

They are named similar on all platforms IIRC.

**Comment by Qixuga** [comment] 2018-08-21 14:56
Sorry i forgot to reply.
I'm on windows 10 x64 plattform, the files are store in user profile directly on our server (network share !)
If i deactivate external change detection as i said, everything seems to work fine.

may be the external change detection an a network-drive in combination seems not to work?

**Comment by pbek** [comment] 2018-08-21 15:01
like I said, if other files are changed in the folder by Windows I can't do anything about them...

**Comment by Qixuga** [comment] 2018-08-21 19:34
No there aren't any file-changes, the software might detect them but there aren't.
so it consumes much cpu-power with synching changes that aren't there.

it seems that the machanism detects other access as changes within network drives.

**Comment by pbek** [comment] 2018-08-21 20:11
> the software might detect them but there aren't.

there are a lot of system files that a normal user can't even see
actually the operating system tells QOwnNotes about those file changes...

I will close this issue until there is more information or I can actually fix somethig.

**Closed by pbek** 2018-08-21 20:11 UTC
Labels: question
