### ISSUE TITLE
Reopening QON after closing in maximized distraction-free mode results in mixed state

### ISSUE THREAD

**Issue by sanderboom** [pbek/QOwnNotes#1448] opened 2019-11-24 13:11 UTC
#### Expected behaviour
- enable 'Distraction free' mode
- close QON
- reopen QON
- enter 'Distraction free' mode

#### Actual behaviour
- enable 'Distraction free' mode
- close QON
- reopen QON
- QON is in a mixed state: 
  - panels are shows as if QON is in 'normal' mode
  - 'Editor width' is active as if QON is in 'Distraction free' mode

Version: `19.11.20`

**Comment by pbek** [comment] 2019-11-24 15:37
How often have I already fixed that Zombie-bug... :laughing:

**Comment by pbek** [comment] 2019-11-24 15:41
But I just tried your steps and it worked fine for me on KDE Neon.
Can you please post the output from the debug settings (see issue template).
And can you please explain in step by step what you exactly you did (which buttons you clicked, which shortcuts you used, especially how exactly you did close the application).

**Comment by pbek** [comment] 2019-11-24 15:42
And maybe a screenshot how it looked before entering DFM, one how it looked in DFM and one how it looked after open QOwnNotes again.

**Comment by sanderboom** [comment] 2019-11-24 16:12
Hmm I tried to reproduce with a fresh session, but everything works like it should - I can't get it to break when mixing shortcuts/ways of closing QON. Maybe something in my profile, and not worth your time in this case..

**Comment by pbek** [comment] 2019-11-24 16:39
I was hoping to get every possible combination of states and settings working. :grin:

**Comment by sanderboom** [comment] 2019-11-24 17:48
It seems to be related to QON being maximized...

Here are 2 screenrecordings (sorry about the flickering - wtf is that anyway). 

[vokoscreen-2019-11-24_18-30-50.tar.gz](https://github.com/pbek/QOwnNotes/files/3883931/vokoscreen-2019-11-24_18-30-50.tar.gz)

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `zo nov. 24 18:44:41 2019`
**Version**: `19.11.20`
**Build date**: `Nov 24 2019`
**Build number**: `625`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.13.2`
**Qt Version (runtime)**: `5.13.2`
**Portable mode**: `no`
**Application arguments**: `QOwnNotes`, `--session`, `test`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `4`
**Calendar items**: `0`
**Enabled scripts**: `1`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `auto`
**Language codes**: `en_PH, en_US, en_US-large, nl_AW, nl_BE, nl_NL`
**Language names**: `English (Philippines), American English (United States), American English (United States) [large], Nederlands (Aruba), Nederlands (België), Nederlands (Nederland)`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: *empty*

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Enabled scripts

### Script `journal-entry`

**id**: `1`
**variablesJson**:
```
{
    "defaultTags": "journal",
    "noteBodyTemplate": "tewrewrew",
    "singleJournalPerDay": true
}
```

## Settings

**AboutDialog/geometry** (QByteArray): `<binary data>`
**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (bool): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (int): `0`
**DistractionFreeMode/menuBarVisible** (bool): `false`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-cdbf28fc-1ddc-4d13-bb21-6a4043316a2f`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2019-11-24T18:42:30.161`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `22`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteTextEdit.code.font** (QString): `IBM Plex Mono,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextEdit.font** (QString): `IBM Plex Sans Condensed,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.code.font** (QString): `IBM Plex Mono,9,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.font** (QString): `IBM Plex Sans Condensed,10,-1,5,50,0,0,0,0,0,Regular`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (QString): `false`
**NoteHistory-1** (QVariantList): `<variant list with 2 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `1`
**PiwikClientId** (QString): `<hidden>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `false`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowDifferentNoteFileName** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `false`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `true`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `b34ad9e0-b075-4e78-8709-60bbe753e08a`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `true`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `false`
**defaultNoteFileExtension** (QString): `md`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `false`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `minimal`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `33`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**previousWorkspace** (QString): `initial`
**restoreCursorPosition** (QString): `true`
**savedSearches/noteFolder-1** (QString): `Note 2019-03-17T10.21.37`
**showMatches** (QString): `true`
**showMenuBar** (bool): `false`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `auto`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-b34ad9e0-b075-4e78-8709-60bbe753e08a/name** (QString): `just right`
**workspace-b34ad9e0-b075-4e78-8709-60bbe753e08a/noteSubFolderDockWidgetVisible** (bool): `true`
**workspace-b34ad9e0-b075-4e78-8709-60bbe753e08a/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, b34ad9e0-b075-4e78-8709-60bbe753e08a`

**Comment by Waqar144** [comment] 2019-11-24 18:12
Meanwhile I am able to reproduce it every time.

The main menu disappears, the text edit has huge padding. Looks like this:

![image](https://user-images.githubusercontent.com/7696024/69498906-cc506100-0f0e-11ea-8438-fd921fc761da.png)

Happens regardless of whether I use shortcut or menu to switch to the 'Distraction free mode`

**Comment by sanderboom** [comment] 2019-11-24 20:39
> It can happen if you don't use KDE 

You mean if you DO use KDE...?

**Comment by Waqar144** [comment] 2019-11-25 04:47
> > It can happen if you don't use KDE
> 
> You mean if you DO use KDE...?

I said that about the flickering (as a joke). Apologies if it caused any offense :(

**Comment by sanderboom** [comment] 2019-11-25 07:34
> Apologies if it caused any offense :(

Haha no offense at all - I just thought you made a typo (and meant 'happen if you do use KDE') as I am using KDE in the screencast :yum:

**Comment by pbek** [comment] 2019-11-25 10:07
I don't get any padding if I leave the DFM after a restart of the application.

**Comment by Waqar144** [comment] 2019-11-25 10:12
Steps to reproduce:
- Open QON
- Press Ctrl+Shift+D (DFM)
- Close QON while it is in DFM
- reopen
DFM mode isn't restored properly.

**Comment by pbek** [comment] 2019-11-25 10:49
> Close QON while it is in DFM

which way to close the app did you use?

**Comment by Waqar144** [comment] 2019-11-25 13:30
> which way to close the app did you use?

Just clicking the close button(x) of the window on "top right corner". (Since that's the only button available to close QON in DFM)

**Comment by pbek** [comment] 2019-11-26 10:24
I managed to reproduce it.
Key was that the window must be maximized before closing it.

- maximize application window
- enter DFM
- quit (regardless of how)
- open app again

seems like a side-effect because of the safety measures in conjunction with full-screen mode...

**Comment by Waqar144** [comment] 2019-11-26 11:02
> seems like a side-effect because of the safety measures in conjunction with full-screen mode...

https://github.com/pbek/QOwnNotes/blob/8d3074346ff9d5000e0d07a966e4295e574cf122/src/mainwindow.cpp#L391-L393

Yep, 
if you increase the delay to 1000, you see the distraction mode get restored for a split second and then all the panels appear

What if we do this instead:
```cpp
    if (isMaximized() || isFullScreen()) {
        if (isInDistractionFreeMode()) {
             restoreCurrentWorkspace();
        } else {
            QTimer::singleShot(500, this, SLOT(restoreCurrentWorkspace()));
       }
    }
```

**Comment by pbek** [comment] 2019-11-26 12:00
Nice, let's go for it if it works :)

**Comment by pbek** [comment] 2019-11-26 13:24
@Waqar144, do you want to make a PR?

**Comment by Waqar144** [comment] 2019-11-26 13:27
> @Waqar144, do you want to make a PR?

Yes, i am on it.

And I will revert the previous change from #1458 and ammend it as discussed (if you haven't already)

**Comment by pbek** [comment] 2019-11-26 13:43
> And I will revert the previous change from #1458 and ammend it as discussed (if you haven't already)

I've done that already, my changes will be committed in the next hours. You only need to change above code.

**Comment by Waqar144** [comment] 2019-11-26 13:44
> > And I will revert the previous change from #1458 and ammend it as discussed (if you haven't already)
> 
> I've done that already, my changes will be committed in the next hours. You only need to change above code.

You were a minute too late :grimacing: 

I will revert it again. And do this one only

**Comment by pbek** [comment] 2019-11-26 16:06
## 19.11.22
- fixed distraction free mode not restored properly on app restart if the app
  previously was maximized (for [#1448](https://github.com/pbek/QOwnNotes/issues/1448), thank you @Waqar144)

**Comment by pbek** [comment] 2019-11-26 16:07
There now is a new release, could you please test it and report if it works for you?

**Comment by Waqar144** [comment] 2019-11-26 20:40
Working great!👍

**Comment by pbek** [comment] 2019-11-26 20:43
Great, thank you for testing!

**Closed by pbek** 2019-11-26 20:43 UTC
Labels: bug, importance-low

**Comment by sanderboom** [comment] 2019-11-26 22:58
NICE GUYS :+1: :rocket:
