### ISSUE TITLE
Code highlighting doesn't work on the "Note Preview" panel, it only colors the code at the "Edit" panel. It doesn't change its font either.

### ISSUE THREAD

**Issue by LeperAffinity666** [pbek/QOwnNotes#1851] opened 2020-08-10 19:57 UTC
#### Expected behaviour
While writing code in C, I expect the "Note Preview" panel to show said code in a highlighted way (colored functions, loops, etc) and with a different font, similar to Monospace or the like.

#### Actual behaviour
The code is accurately highlighted in the "Note Editor" panel, but it appears plain green and with no font change in the "Note Preview" panel.

#### Debug Settings Output

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `lun. ago. 10 15:56:21 2020`
**Version**: `20.8.3`
**Build date**: `Aug  9 2020`
**Build number**: `747`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `OBS`
**Qt Version (build)**: `5.15.0`
**Qt Version (runtime)**: `5.15.0`
**Portable mode**: `no`
**Settings path / key**: `/home/usr/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/usr/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1366x768`
**Icon theme**: `Papirus-Maia`
**Notes in current note folder**: `7`
**Calendar items**: `0`
**Enabled scripts**: `0`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `false`
**Selected language**: *empty*
**Language codes**: *empty*
**Language names**: *empty*
**Application dictionaries path**: `/home/usr/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/usr/Documents/QOwnNotes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `yes`
**isUseGit**: `no`
**activeNoteSubFolder name**: `W2 - Functions & Arrays`
**database file**: `/home/usr/Documents/QOwnNotes/notes.sqlite`

### Cloud connection ``

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*

## Settings

**ActiveNoteHistoryItem** (NoteHistoryItem): `<binary data>`
**Debug/fakeOldVersionNumber** (QString): `false`
**Debug/fileLogging** (QString): `false`
**DistractionFreeMode/isEnabled** (QString): `false`
**DistractionFreeMode/menuBarGeometry** (QByteArray): `<binary data>`
**DistractionFreeMode/menuBarHeight** (QString): `25`
**DistractionFreeMode/menuBarVisible** (QString): `true`
**DistractionFreeMode/windowState** (QByteArray): `<binary data>`
**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/autoBracketClosing** (QString): `true`
**Editor/autoBracketRemoval** (QString): `true`
**Editor/disableCursorBlinking** (QString): `false`
**Editor/editorWidthInDFMOnly** (QString): `true`
**Editor/highlightCurrentLine** (QString): `true`
**Editor/indentSize** (QString): `4`
**Editor/removeTrainingSpaces** (QString): `false`
**Editor/useTabIndent** (QString): `false`
**Editor/vimMode** (QString): `false`
**IssueAssistantDialog/geometry** (QByteArray): `<binary data>`
**LastUpdateCheck** (QDateTime): `2020-08-10T15:07:24.809`
**MainWindow/geometry** (QByteArray): `<binary data>`
**MainWindow/mainToolBar.iconSize** (QString): `21`
**MainWindow/menuBarGeometry** (QByteArray): `<binary data>`
**MainWindow/noteSubFolderTreeWidgetExpandState-1** (QStringList): `CS50`
**MainWindow/noteTextEdit.code.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextEdit.font** (QString): `Cantarell,11,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.code.font** (QString): `Cantarell,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.font** (QString): `Cantarell,10,-1,5,50,0,0,0,0,0`
**MainWindow/noteTextView.ignoreCodeFontSize** (QString): `true`
**MainWindow/noteTextView.rtl** (QString): `false`
**MainWindow/noteTextView.underline** (QString): `true`
**MainWindow/noteTextView.useEditorStyles** (QString): `true`
**MainWindow/noteTextView.useInternalExportStyling** (QString): `true`
**MainWindow/showNotesFromAllNoteSubFolders** (bool): `false`
**MessageBoxOverride/layoutwidget-use-layout** (QString): `16384`
**MessageBoxOverride/move-notes** (QString): `16384`
**NoteDialog/geometry** (QByteArray): `<binary data>`
**NoteFolder-1/NoteTabNameList** (QString): `Algorithms`
**NoteFolder-1/NoteTabStickinessList**: *empty*
**NoteFolder-1/NoteTabSubFolderPathDataList** (QString): 
```
CS50
W3 - Algorithms
```
**NoteHistory-1** (QVariantList): `<variant list with 19 item(s)>`
**NoteHistoryCurrentIndex-1** (QString): `18`
**PiwikClientId** (QString): `<hidden>`
**ScriptRepositoryDialog/mainSplitterState** (QByteArray): `<binary data>`
**SearchEngineId** (QString): `2`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**SettingsDialog/mainSplitterState** (QByteArray): `<binary data>`
**ShowSystemTray** (QString): `true`
**StartHidden** (QString): `false`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**acceptAllExternalModifications** (QString): `false`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (QString): `true`
**appMetrics/disableAppHeartbeat** (QString): `false`
**appMetrics/disableTracking** (QString): `true`
**appMetrics/notificationShown** (QString): `true`
**automaticNoteFolderDatabaseClosing** (QString): `false`
**checkSpelling** (bool): `false`
**closeTodoListAfterSave** (QString): `false`
**cryptoKey** (QString): `<hidden>`
**currentNoteFolderId** (QString): `1`
**currentWorkspace** (QString): `nV3N4YVPp5AL`
**cursorWidth** (QString): `1`
**customNoteFileExtensionList**: *empty*
**darkMode** (QString): `false`
**darkModeColors** (QString): `true`
**darkModeIconTheme** (QString): `true`
**darkModeTrayIcon** (QString): `true`
**defaultNoteFileExtension** (QString): `md`
**demoNotesCreated** (QString): `true`
**disableAutomaticUpdateDialog** (QString): `true`
**disableSavedSearchesAutoCompletion** (QString): `false`
**dockWasInitializedOnce** (QString): `true`
**enableNoteTree** (QString): `false`
**enableSocketServer** (QString): `true`
**externalEditorPath** (QString): *empty*
**fullyHighlightedBlockquotes** (QString): `true`
**gitCommitInterval** (QString): `30`
**gitExecutablePath** (QString): *empty*
**gitLogCommand** (QString): *empty*
**guiFirstRunInit** (bool): `true`
**ignoreAllExternalModifications** (QString): `false`
**ignoreAllExternalNoteFolderChanges** (QString): `false`
**ignoreNoteSubFolders** (QString): `^\.`
**imageScaleDown** (QString): `false`
**imageScaleDownMaximumHeight** (QString): `1024`
**imageScaleDownMaximumWidth** (QString): `1024`
**initialLayoutIdentifier** (QString): `full`
**insertTimeFormat** (QString): *empty*
**interfaceFontSize** (QString): `11`
**interfaceLanguage** (QString): *empty*
**internalIconTheme** (QString): `false`
**itemHeight** (QString): `24`
**legacyLinking** (QString): `false`
**localTrash/autoCleanupDays** (QString): `30`
**localTrash/autoCleanupEnabled** (QString): `true`
**localTrash/supportEnabled** (QString): `true`
**markdownHighlightingEnabled** (QString): `true`
**navigationPanelHideSearch** (QString): `false`
**networking/ignoreSSLErrors** (QString): `true`
**networking/proxyType** (QString): `2`
**newNoteAskHeadline** (QString): `false`
**noteEditIsCentralWidget** (QString): `true`
**noteListPreview** (QString): `false`
**noteSaveIntervalTime** (QString): `10`
**noteSubfoldersPanelDisplayAsFullTree** (QString): `true`
**noteSubfoldersPanelHideSearch** (QString): `false`
**noteSubfoldersPanelOrder** (QString): `0`
**noteSubfoldersPanelShowFullPath** (QString): `false`
**noteSubfoldersPanelShowNotesRecursively** (QString): `false`
**noteSubfoldersPanelShowRootFolderName** (QString): `true`
**noteSubfoldersPanelSort** (QString): `0`
**notesPanelOrder** (QString): `0`
**notesPanelSort** (QString): `1`
**notesPath** (QString): `/home/usr/Documents/QOwnNotes`
**notifyAllExternalModifications** (QString): `false`
**overrideInterfaceFontSize** (QString): `false`
**ownCloud/supportEnabled** (QString): `false`
**ownCloud/todoCalendarBackend** (QString): `3`
**ownCloud/todoCalendarCalDAVPassword** (QString): `<hidden>`
**ownCloud/todoCalendarCalDAVServerUrl** (QString): *empty*
**ownCloud/todoCalendarCalDAVUsername** (QString): *empty*
**ownCloud/todoCalendarCloudConnectionId** (QString): `1`
**ownCloud/todoCalendarDisplayNameList**: *empty*
**ownCloud/todoCalendarEnabledList**: *empty*
**ownCloud/todoCalendarEnabledUrlList**: *empty*
**ownCloud/todoCalendarUrlList**: *empty*
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**restoreCursorPosition** (QString): `true`
**restoreLastNoteAtStartup** (QString): `true`
**restoreNoteTabs** (QString): `true`
**savedSearches/noteFolder-1** (QStringList): `Note 2020-08-10T12.59.05, Note 2020-06-30T10.38.42, Note 2020-06-30T10.36.58`
**showMatches** (QString): `true`
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**systemIconTheme** (QString): `false`
**taggingShowNotesRecursively** (QString): `false`
**tagsPanelHideSearch** (QString): `false`
**tagsPanelOrder** (QString): `0`
**tagsPanelSort** (QString): `0`
**todoCalendarSupport** (QString): `true`
**toolbar/1/items** (QStringList): `action_New_note, action_Find_note, action_Remove_note, action_Open_note_in_external_editor, actionShow_local_trash, actionAllow_note_editing, , action_Back_in_note_history, action_Forward_in_note_history, , action_Find_text_in_note, actionReplace_in_current_note, , actionShow_versions, actionShow_trash, actionShare_note, , actionOpen_List`
**toolbar/1/name** (QString): `mainToolBar`
**toolbar/1/title** (QString): `main toolbar`
**toolbar/2/items** (QStringList): `actionFormat_text_bold, actionFormat_text_italic, actionStrike_out_text, actionInsert_code_block, actionInsert_block_quote`
**toolbar/2/name** (QString): `formattingToolbar`
**toolbar/2/title** (QString): `formatting toolbar`
**toolbar/3/items** (QStringList): `actionInsert_Link_to_note, actionInsert_image, actionInsert_current_time`
**toolbar/3/name** (QString): `insertingToolbar`
**toolbar/3/title** (QString): `inserting toolbar`
**toolbar/4/items** (QStringList): `action_Encrypt_note, actionEdit_encrypted_note, actionDecrypt_note`
**toolbar/4/name** (QString): `encryptionToolbar`
**toolbar/4/title** (QString): `encryption toolbar`
**toolbar/5/items** (QStringList): `actionWorkspaceComboBox, actionStore_as_new_workspace, actionRemove_current_workspace, actionRename_current_workspace, actionSwitch_to_previous_workspace, actionUnlock_panels, , actionToggle_distraction_free_mode, action_Increase_note_text_size, action_Decrease_note_text_size, action_Reset_note_text_size`
**toolbar/5/name** (QString): `windowToolbar`
**toolbar/5/title** (QString): `window toolbar`
**toolbar/6/items** (QString): `action_Quit`
**toolbar/6/name** (QString): `quitToolbar`
**toolbar/6/title** (QString): `quit toolbar`
**toolbar/size** (QString): `6`
**useNoteFolderButtons** (QString): `false`
**useUNIXNewline** (QString): `false`
**webSocketServerService/bookmarksNoteName** (QString): `Bookmarks`
**webSocketServerService/bookmarksTag** (QString): `bookmarks`
**webSocketServerService/port** (QString): `22222`
**workspace-ALbrCANsc6vy/name** (QString): `Minimal`
**workspace-ALbrCANsc6vy/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-ALbrCANsc6vy/windowState** (QByteArray): `<binary data>`
**workspace-BgQQk4Qsnkvt/name** (QString): `Full vertical`
**workspace-BgQQk4Qsnkvt/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-BgQQk4Qsnkvt/windowState** (QByteArray): `<binary data>`
**workspace-initial/name** (QString): `Full`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspace-nV3N4YVPp5AL/name** (QString): `Full`
**workspace-nV3N4YVPp5AL/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-nV3N4YVPp5AL/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial, ALbrCANsc6vy, BgQQk4Qsnkvt, nV3N4YVPp5AL`

## System environment

**SHELL**: `/bin/bash`
**XDG_CONFIG_DIRS**: `/etc/xdg`
**XDG_SESSION_PATH**: `/org/freedesktop/DisplayManager/Session0`
**XDG_MENU_PREFIX**: `xfce-`
**LC_ADDRESS**: `es_CO.UTF-8`
**LC_NAME**: `es_CO.UTF-8`
**DESKTOP_SESSION**: `xfce`
**LC_MONETARY**: `es_CO.UTF-8`
**EDITOR**: `/usr/bin/nano`
**GTK_MODULES**: `canberra-gtk-module:canberra-gtk-module`
**XDG_SEAT**: `seat0`
**PWD**: `/home/usr`
**XDG_SESSION_DESKTOP**: `xfce`
**LOGNAME**: `usr`
**QT_QPA_PLATFORMTHEME**: `qt5ct`
**XDG_SESSION_TYPE**: `x11`
**XAUTHORITY**: `/home/usr/.Xauthority`
**XDG_GREETER_DATA_DIR**: `/var/lib/lightdm-data/usr`
**GTK2_RC_FILES**: `/home/usr/.gtkrc-2.0`
**HOME**: `/home/usr`
**LANG**: `en_US.utf8`
**LC_PAPER**: `es_CO.UTF-8`
**XDG_CURRENT_DESKTOP**: `XFCE`
**XDG_SEAT_PATH**: `/org/freedesktop/DisplayManager/Seat0`
**XDG_SESSION_CLASS**: `user`
**LC_IDENTIFICATION**: `es_CO.UTF-8`
**USER**: `usr`
**SHLVL**: `0`
**LC_TELEPHONE**: `es_CO.UTF-8`
**LC_MEASUREMENT**: `es_CO.UTF-8`
**XDG_VTNR**: `7`
**XDG_SESSION_ID**: `2`
**MOZ_PLUGIN_PATH**: `/usr/lib/mozilla/plugins`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**LC_TIME**: `es_CO.UTF-8`
**QT_AUTO_SCREEN_SCALE_FACTOR**: `0`
**XDG_DATA_DIRS**: `/home/usr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share`
**PATH**: `/home/usr/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin`
**GDMSESSION**: `xfce`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**MAIL**: `/var/spool/mail/usr`
**LC_NUMERIC**: `es_CO.UTF-8`
**SESSION_MANAGER**: `local/usr-cx627ql:@/tmp/.ICE-unix/1076,unix/usr-cx627ql:/tmp/.ICE-unix/1076`
**SSH_AUTH_SOCK**: `/tmp/ssh-TwKoz2V77HNk/agent.1148`
**SSH_AGENT_PID**: `1149`
**PANEL_GDK_CORE_DEVICE_EVENTS**: `0`
**DISPLAY**: `:0.0`

**Comment by pbek** [comment] 2020-08-10 20:21
Can you please post the output from the debug settings (see issue template).
And is there any useful log output if you enable the log panel (see Window / Panels)? Please make sure you also enable debug logging in the log panel (by right-clicking on the panel and and selecting `Debug` in `Options`).
And please add an example markdown and a screenshot, I can't reproduce your issue...


![image](https://user-images.githubusercontent.com/1798101/89827404-d62afa80-db57-11ea-8edf-5bd968034cb4.png)

**Comment by LeperAffinity666** [comment] 2020-08-10 21:05
Thank you for your answer, and sorry for missing the debug information. It has been added as an edit to the original post. As for the screenshot, this is what I get:

![image](https://user-images.githubusercontent.com/65421290/89831030-ccd36b00-db22-11ea-8db4-e8eb17de40de.png)

As for the log panel, this is what it shows when creating another code block:

![image](https://user-images.githubusercontent.com/65421290/89831319-423f3b80-db23-11ea-97d6-8885bcab579e.png)

**Comment by pbek** [comment] 2020-08-11 07:03
Please try a lower case `c` in the code block.

**Comment by pbek** [comment] 2020-09-08 06:26
I will close this issue until there is more information.

**Closed by pbek** 2020-09-08 06:26 UTC
Labels: Type: Support
