### ISSUE TITLE
[I] Black placeholder color in dark theme

### ISSUE THREAD

**Issue by Katarn** [pbek/QOwnNotes#2490] opened 2022-03-04 18:37 UTC
![изображение](https://user-images.githubusercontent.com/6339978/156821698-e90d41f6-18fb-4f1d-89e0-878959d66130.png)

The screenshot was taken in Linux, but I also got this problem in Windows. But it's somehow different there. If in Linux the text looks black all the time, then in Windows I have not figured out how to reproduce this problem. Sometimes it looks normal, sometimes black.

Also pay attention to the magnifying glass icons - they are of different colors in the upper and lower fields.

#### Information about the application, settings and environment

<details><summary>Expand</summary>

QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `пт мар. 4 21:31:09 2022`
**Version**: `22.3.1`
**Build date**: `Mar  4 2022`
**Build number**: `956`
**Platform**: `linux`
**Operating System**: `Gentoo/Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `Gentoo`
**Qt Version (build)**: `5.15.2`
**Qt Version (runtime)**: `5.15.2`
**Portable mode**: `no`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `ru_RU`
**Locale (interface)**: *empty*
**Primary screen resolution**: `1280x1024`
**Icon theme**: `breeze-dark-qownnotes`
**Notes in current note folder**: `253`
**Calendar items**: `0`
**Enabled scripts**: `1`
</details>

If any information is missing - ask, I will clarify.

**Comment by pbek** [comment] 2022-03-05 09:39
> Black placeholder color in dark theme

Can you please describe in more detail what the issue is and what is amiss in your screenshot. Which placeholder?

> they are of different colors in the upper and lower fields.

Hm, seems like they are styled differently in dark mode.

**Comment by Katarn** [comment] 2022-03-05 09:44
> Can you please describe in more detail what the issue is and what is amiss in your screenshot. Which placeholder?

The black text of placeholders is not readable. In the top input displays "Find or create note sub folder" and in the bottom input displays "Search or create note".

**Comment by pbek** [comment] 2022-03-05 12:17
I cannot reproduce that.

<img width="194" alt="image" src="https://user-images.githubusercontent.com/1798101/156882550-4302a673-6d77-4e5e-b7ef-5b6f419da6f8.png">

**Comment by pbek** [comment] 2022-03-05 12:34
## 22.3.2
- the search icons for sub-folders, tags and the navigation panel in the main-window
  are now all better visible in dark mode (for [#2490](https://github.com/pbek/QOwnNotes/issues/2490))

**Comment by Katarn** [comment] 2022-03-05 20:37
> I cannot reproduce that.

I assume that the dark theme of the application does not have a rule for placeholders and the color is taken from the system theme. And our system themes are different. Therefore, my placeholder color is black, and yours is gray.

**Comment by Katarn** [comment] 2022-03-05 21:07
Something similar to https://github.com/UN-GCPDS/qt-material/issues/12

**Comment by pbek** [comment] 2022-03-06 16:25
I cannot reproduce this under Windows 10 neither...
Under Linux my System Theme is a light theme which would set the placeholder text to black, but no issue there neither.

**Comment by Katarn** [comment] 2022-03-06 19:44
Can you tell me where I can look in my system? In general, are there any theories?

**Comment by pbek** [comment] 2022-03-06 20:16
I'm not sure, if you cannot style it with CSS it doesn't even seem to come with your desktop environment theme...

**Comment by pbek** [comment] 2022-03-09 06:29
> the search icons for sub-folders, tags and the navigation panel in the main-window
    are now all better visible in dark mode (for https://github.com/pbek/QOwnNotes/issues/2490)

There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment] 2022-04-07 08:44
I will close this issue until there is more information.

**Closed by pbek** 2022-04-07 08:44 UTC
Labels: Type: Support

**Comment by Katarn** [comment] 2022-04-07 15:52
Sorry, I missed the new version notification. I'm still seeing this bug myself.

**Comment by pbek** [comment] 2022-04-07 17:36
Hard to tell, I was never able to reproduce that...
