### ISSUE TITLE
Lost Toolbar Settings after Restart

### ISSUE THREAD

**Issue by toxpal** [pbek/QOwnNotes#1182] opened 2019-04-14 14:53 UTC
```
QOwnNotes Debug Information
===========================

## General Info

**Version**: `19.4.2`
**Build date**: `Apr 12 2019`
**Build number**: `530`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `no`
**Settings path / key**: `/home/toxpal/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/toxpal/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/usr/bin/QOwnNotes`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Icon theme**: *empty*
**Notes in current note folder**: `53`
**Enabled scripts**: `0`
```

In short, the issue is very similar to https://github.com/pbek/QOwnNotes/issues/1140 except that it's much smaller.

After every OS restart, QOwnNotes loses its toolbar configuration. That is to say, if I configure window layout (by removing some toolbars I don't need in main window) and restart OS, all default toolbars are displayed again.

It does NOT happen if I close app and do NOT restart OS. I can start/quit app many times, and my toolbars configuration is "respected". However, restarting OS means lost toolbar configuration immediately.

I don't really know if it's OS or app problem because I never had this issue on Antergos KDE, and I only experience this issue after installing Manjaro KDE a few days ago. However, QOwnNotes is the only app which loses settings after OS restart, so I guess the issue is app-based.

**Comment by pbek** [comment] 2019-04-14 20:37
I'm sorry, I couldn't reproduce that on my Manjaro Laptop.

**Comment by pbek** [comment] 2019-04-14 20:49
I restarted the laptop and still my QOwnNotes toolbars are still the same.

## General Info

**Current Date**: `So. Apr. 14 22:48:45 2019`
**Version**: `19.4.2`
**Build date**: `Apr 10 2019`
**Build number**: `530`
**Platform**: `linux`
**Operating System**: `Manjaro Linux`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AUR`
**Qt Version (build)**: `5.12.2`
**Qt Version (runtime)**: `5.12.2`
**Portable mode**: `no`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: `en`
**Icon theme**: `breeze`
**Notes in current note folder**: `601`
**Enabled scripts**: `5`

**Comment by toxpal** [comment] 2019-04-15 06:55
For some reason, it still happens there. I forgot to mention that window loses its size/position as well. If other people don't experience this issue, I guess a fresh re-install is worth trying for me now.

**Comment by pbek** [comment] 2019-04-15 07:07
There is a command line paramter `--session` you could try to just use an other settings-session. see: http://docs.qownnotes.org/en/develop/cli-parameters.html

**Comment by zezyx** [comment] 2019-04-30 02:18
Same issue here. Every time open it go maximize. The Interface/Layout setting not working on Windows 10.
![Capture](https://user-images.githubusercontent.com/40623401/56937778-2b90f300-6b31-11e9-96e6-b0f75422475f.PNG)

**Comment by pbek** [comment] 2019-04-30 03:55
> Same issue here. Every time open it go maximize. The Interface/Layout setting not working on Windows 10.

Can you please explain in more detail and step by step what you did, what happened and what you expected. Can you please post the output from the debug settings.
And is there any useful log output if you enable the log widget?

**Comment by toxpal** [comment] 2019-04-30 10:30
Sadly, I wasn't able to fix this issue, even with multiple re-installations. Actually, it only got worse after re-install - now window size/position and toolbar configuration is lost every time I quit the app.

**Comment by pbek** [comment] 2019-04-30 10:56
How did you re-install?

**Comment by toxpal** [comment] 2019-04-30 11:02
I install/update/uninstall all the tools using Manjaro package manager (Pamac).

**Comment by pbek** [comment] 2019-04-30 11:04
That doesn't remove your settings, so please check...

> There is a command line parameter --session you could try to just use an other settings-session. see: http://docs.qownnotes.org/en/develop/cli-parameters.html

**Comment by toxpal** [comment] 2019-04-30 11:13
> That doesn't remove your settings

But how it comes that all my settings are reset after re-installation? I mean, I need to re-configure everything - from notes location to themes, individual checkboxes in each Options section, etc.

I tried session too, just not sure if I did it right (because all settings are still lost). I launched:
QOwnNotes -session my_session_name

and changed window size/position/toolbars. Then closed the app and launched it again using:
QOwnNotes -session my_session_name

Result is the same - window size/position lost.

**Comment by pbek** [comment] 2019-04-30 12:15
> But how it comes that all my settings are reset after re-installation? I mean, I need to re-configure everything - from notes location to themes, individual checkboxes in each Options section, etc.

strange, I've no idea how your package manager detects the settings file

> Result is the same - window size/position lost.

I've no idea why I can't reproduce that on Manjaro KDE, do you use some special version of Qt or something else?

**Comment by toxpal** [comment] 2019-04-30 13:29
It's a pretty default Manjaro KDE installation. Like I mentioned before, I used antergos KDE for almost a year, and never had such problem with QOwnNotes, so the issue might be related to my Manjaro installation. In other hand, I did a fresh re-install of Manjaro too, and the issue still exists (and QOwnNotes is the only app which loses its position).

There's QT stuff on my PC, but I guess it won't help much :) https://i.postimg.cc/5N1WtMBr/qt.png

I could actually apply some type of fix using KDE itself (where you can force specific settings for each window in KDE), but that only works for current version. Once QOwnNotes gets updated (which happens often, and I like it), special settings for app window are lost too, and I need to re-force them again. I guess I'll need to live with it...

**Comment by pbek** [comment] 2019-04-30 13:44
Your settings should never be touched when QOwnNotes is updated. I don't understand how that happens to you. In the debug settings you can see where the settings are stored.

**Comment by toxpal** [comment] 2019-04-30 14:30
No, I mean that only KDE window settings are lost during update. QOwnNotes settings are in place :)

**Comment by pbek** [comment] 2019-11-12 09:13
Do you still have that issue?

**Comment by pbek** [comment] 2019-11-12 09:13
I will close this issue until there is more information.

**Closed by pbek** 2019-11-12 09:13 UTC
Labels: question

**Comment by toxpal** [comment] 2019-11-12 12:24
No, the issue is long time gone ...

**Comment by pbek** [comment] 2019-11-12 12:33
Perfect! Thank you.
